open62541++: opcua::TypeWrapper< T, typeIndex > Class Template Reference
opcua::TypeWrapper< T, typeIndex > Class Template Reference
Wrapper classes of UA_* types
Template base class to wrap UA_* type objects.
#include <TypeWrapper.h>
Public Types
using TypeWrapperBase = TypeWrapper< T, typeIndex >
using NativeType = T
Public Member Functions
TypeWrapper ()=default
TypeWrapper (const T &data)
Constructor with native object (deep copy).
constexpr TypeWrapper (T &&data) noexcept
Constructor with native object (move rvalue).
~TypeWrapper ()
TypeWrapper (const TypeWrapper &other)
Copy constructor (deep copy).
TypeWrapper (TypeWrapper &&other) noexcept
Move constructor.
TypeWrapper & operator= (const TypeWrapper &other)
Copy assignment (deep copy).
TypeWrapper & operator= (const T &other)
Copy assignment with native object (deep copy).
TypeWrapper & operator= (TypeWrapper &&other) noexcept
Move assignment.
TypeWrapper & operator= (T &&other) noexcept
Move assignment with native object.
constexpr operator T& () noexcept
Implicit conversion to native object.
constexpr operator const T & () const noexcept
Implicit conversion to native object.
constexpr T * operator-> () noexcept
Member access to native object.
constexpr const T * operator-> () const noexcept
Member access to native object.
void swap (TypeWrapper &other) noexcept
Swap with wrapper object.
void swap (T &other) noexcept
Swap with native object.
constexpr T * handle () noexcept
Return pointer to native object.
constexpr const T * handle () const noexcept
Return const pointer to native object.
Static Public Member Functions
static constexpr TypeIndex getTypeIndex ()
Get type as type index of the UA_TYPES array.
static const UA_DataType * getDataType ()
Get type as UA_DataType object.
Protected Member Functions
void clear () noexcept
void copy (const T &data)
Static Protected Member Functions
static void checkMemSize ()
Detailed Description
template<typename T, TypeIndex typeIndex>
class opcua::TypeWrapper< T, typeIndex >
Template base class to wrap UA_* type objects.
Zero cost abstraction to wrap the C API objects and delete them on destruction. The derived classes should implement specific constructors to convert from other data types.
TypeWrapper<T, typeIndex> is pointer-interconvertible to T. Use asWrapper(NativeType&) or asWrapper(constNativeType&) to cast native object references to wrapper object references.
Warning
No virtual constructor defined, don't implement a destructor in the derived classes.
Definition at line 38 of file TypeWrapper.h.
Member Typedef Documentation
NativeType
template<typename T , TypeIndex typeIndex> using opcua::TypeWrapper< T, typeIndex >::NativeType = T
Definition at line 43 of file TypeWrapper.h.
TypeWrapperBase
template<typename T , TypeIndex typeIndex> using opcua::TypeWrapper< T, typeIndex >::TypeWrapperBase = TypeWrapper<T, typeIndex>
Definition at line 42 of file TypeWrapper.h.
Constructor & Destructor Documentation
TypeWrapper() [1/5]
template<typename T , TypeIndex typeIndex> opcua::TypeWrapper< T, typeIndex >::TypeWrapper () default
TypeWrapper() [2/5]
template<typename T , TypeIndex typeIndex> opcua::TypeWrapper< T, typeIndex >::TypeWrapper (const T & data) inline explicit
Constructor with native object (deep copy).
Definition at line 48 of file TypeWrapper.h.
References opcua::TypeWrapper< T, typeIndex >::copy().
TypeWrapper() [3/5]
template<typename T , TypeIndex typeIndex> constexpr opcua::TypeWrapper< T, typeIndex >::TypeWrapper (T && data) inline constexpr noexcept
Constructor with native object (move rvalue).
Definition at line 53 of file TypeWrapper.h.
~TypeWrapper()
template<typename T , TypeIndex typeIndex> opcua::TypeWrapper< T, typeIndex >::~TypeWrapper () inline
Definition at line 56 of file TypeWrapper.h.
References opcua::TypeWrapper< T, typeIndex >::clear().
TypeWrapper() [4/5]
template<typename T , TypeIndex typeIndex> opcua::TypeWrapper< T, typeIndex >::TypeWrapper (const TypeWrapper< T, typeIndex > & other) inline
Copy constructor (deep copy).
Definition at line 61 of file TypeWrapper.h.
References opcua::TypeWrapper< T, typeIndex >::copy().
TypeWrapper() [5/5]
template<typename T , TypeIndex typeIndex> opcua::TypeWrapper< T, typeIndex >::TypeWrapper (TypeWrapper< T, typeIndex > && other) inline noexcept
Move constructor.
Definition at line 66 of file TypeWrapper.h.
References opcua::TypeWrapper< T, typeIndex >::swap().
Member Function Documentation
checkMemSize()
template<typename T , TypeIndex typeIndex> static void opcua::TypeWrapper< T, typeIndex >::checkMemSize () inline static protected
Definition at line 154 of file TypeWrapper.h.
References opcua::TypeWrapper< T, typeIndex >::getDataType().
Referenced by opcua::TypeWrapper< T, typeIndex >::clear(), and opcua::TypeWrapper< T, typeIndex >::copy().
clear()
template<typename T , TypeIndex typeIndex> void opcua::TypeWrapper< T, typeIndex >::clear () inline protected noexcept
Definition at line 158 of file TypeWrapper.h.
References opcua::TypeWrapper< T, typeIndex >::checkMemSize(), opcua::TypeWrapper< T, typeIndex >::getDataType(), and UA_clear().
Referenced by opcua::TypeWrapper< T, typeIndex >::copy(), opcua::TypeWrapper< T, typeIndex >::operator=(), and opcua::TypeWrapper< T, typeIndex >::~TypeWrapper().
copy()
template<typename T , TypeIndex typeIndex> void opcua::TypeWrapper< T, typeIndex >::copy (const T & data) inline protected
Definition at line 163 of file TypeWrapper.h.
References opcua::TypeWrapper< T, typeIndex >::checkMemSize(), opcua::TypeWrapper< T, typeIndex >::clear(), opcua::TypeWrapper< T, typeIndex >::getDataType(), opcua::detail::throwOnBadStatus(), and UA_copy().
Referenced by opcua::TypeWrapper< T, typeIndex >::operator=(), opcua::TypeWrapper< T, typeIndex >::operator=(), opcua::TypeWrapper< T, typeIndex >::TypeWrapper(), and opcua::TypeWrapper< T, typeIndex >::TypeWrapper().
getDataType()
template<typename T , TypeIndex typeIndex> static const UA_DataType * opcua::TypeWrapper< T, typeIndex >::getDataType () inline static
Get type as UA_DataType object.
Definition at line 139 of file TypeWrapper.h.
Referenced by opcua::TypeWrapper< T, typeIndex >::checkMemSize(), opcua::TypeWrapper< T, typeIndex >::clear(), and opcua::TypeWrapper< T, typeIndex >::copy().
getTypeIndex()
template<typename T , TypeIndex typeIndex> static constexpr TypeIndex opcua::TypeWrapper< T, typeIndex >::getTypeIndex () inline static constexpr
Get type as type index of the UA_TYPES array.
Definition at line 134 of file TypeWrapper.h.
handle() [1/2]
template<typename T , TypeIndex typeIndex> constexpr const T * opcua::TypeWrapper< T, typeIndex >::handle () const inline constexpr noexcept
Return const pointer to native object.
Definition at line 149 of file TypeWrapper.h.
handle() [2/2]
template<typename T , TypeIndex typeIndex> constexpr T * opcua::TypeWrapper< T, typeIndex >::handle () inline constexpr noexcept
Return pointer to native object.
Definition at line 144 of file TypeWrapper.h.
Referenced by opcua::services::writeValue().
operator const T &()
template<typename T , TypeIndex typeIndex> constexpr opcua::TypeWrapper< T, typeIndex >::operator const T & () const inline constexpr noexcept
Implicit conversion to native object.
Definition at line 107 of file TypeWrapper.h.
operator T&()
template<typename T , TypeIndex typeIndex> constexpr opcua::TypeWrapper< T, typeIndex >::operator T& () inline constexpr noexcept
Implicit conversion to native object.
Definition at line 102 of file TypeWrapper.h.
operator->() [1/2]
template<typename T , TypeIndex typeIndex> constexpr const T * opcua::TypeWrapper< T, typeIndex >::operator-> () const inline constexpr noexcept
Member access to native object.
Definition at line 117 of file TypeWrapper.h.
operator->() [2/2]
template<typename T , TypeIndex typeIndex> constexpr T * opcua::TypeWrapper< T, typeIndex >::operator-> () inline constexpr noexcept
Member access to native object.
Definition at line 112 of file TypeWrapper.h.
operator=() [1/4]
template<typename T , TypeIndex typeIndex> TypeWrapper & opcua::TypeWrapper< T, typeIndex >::operator= (const T & other) inline
Copy assignment with native object (deep copy).
Definition at line 80 of file TypeWrapper.h.
References opcua::TypeWrapper< T, typeIndex >::copy().
operator=() [2/4]
template<typename T , TypeIndex typeIndex> TypeWrapper & opcua::TypeWrapper< T, typeIndex >::operator= (const TypeWrapper< T, typeIndex > & other) inline
Copy assignment (deep copy).
Definition at line 71 of file TypeWrapper.h.
References opcua::TypeWrapper< T, typeIndex >::copy().
operator=() [3/4]
template<typename T , TypeIndex typeIndex> TypeWrapper & opcua::TypeWrapper< T, typeIndex >::operator= (T && other) inline noexcept
Move assignment with native object.
Definition at line 95 of file TypeWrapper.h.
References opcua::TypeWrapper< T, typeIndex >::clear().
operator=() [4/4]
template<typename T , TypeIndex typeIndex> TypeWrapper & opcua::TypeWrapper< T, typeIndex >::operator= (TypeWrapper< T, typeIndex > && other) inline noexcept
Move assignment.
Definition at line 86 of file TypeWrapper.h.
References opcua::TypeWrapper< T, typeIndex >::swap().
swap() [1/2]
template<typename T , TypeIndex typeIndex> void opcua::TypeWrapper< T, typeIndex >::swap (T & other) inline noexcept
Swap with native object.
Definition at line 128 of file TypeWrapper.h.
swap() [2/2]
template<typename T , TypeIndex typeIndex> void opcua::TypeWrapper< T, typeIndex >::swap (TypeWrapper< T, typeIndex > & other) inline noexcept
Swap with wrapper object.
Definition at line 122 of file TypeWrapper.h.
Referenced by opcua::TypeWrapper< T, typeIndex >::operator=(), opcua::services::readValue(), and opcua::TypeWrapper< T, typeIndex >::TypeWrapper().