open62541pp: opcua::StatusCode Class Reference
opcua::StatusCode Class Reference
Wrapper classes
#include <types.hpp>
Detailed Description
UA_StatusCode wrapper class.
StatusCode can be used interchangeably with UA_StatusCode due to implicit conversions (without any overhead) but provides some methods to simplify the handling with status codes.
See also
statuscodes.h
https://reference.opcfoundation.org/Core/Part4/v105/docs/7.39
Examples
server_accesscontrol.cpp, and server_datasource.cpp.
Definition at line 41 of file types.hpp.
Public Member Functions
constexpr StatusCode () noexcept=default
constexpr StatusCode (UA_StatusCode code) noexcept
constexpr UA_StatusCode get () const noexcept
std::string_view name () const noexcept
constexpr bool isGood () const noexcept
constexpr bool isUncertain () const noexcept
constexpr bool isBad () const noexcept
constexpr void throwIfBad () const
Public Member Functions inherited from opcua::Wrapper< UA_StatusCode >
constexpr Wrapper () noexcept=default
constexpr Wrapper (const Wrapper &other)
constexpr Wrapper (const UA_StatusCode &native)
constexpr Wrapper (Wrapper &&other) noexcept
constexpr Wrapper (UA_StatusCode &&native) noexcept
~Wrapper () noexcept=default
constexpr Wrapper & operator= (const Wrapper &other)
constexpr Wrapper & operator= (const UA_StatusCode &native)
constexpr Wrapper & operator= (Wrapper &&other) noexcept
constexpr Wrapper & operator= (UA_StatusCode &&native) noexcept
constexpr operator UA_StatusCode & () noexcept
constexpr operator const UA_StatusCode & () const noexcept
constexpr UA_StatusCode * operator-> () noexcept
constexpr const UA_StatusCode * operator-> () const noexcept
constexpr UA_StatusCode * handle () noexcept
constexpr const UA_StatusCode * handle () const noexcept
constexpr void swap (Wrapper &other) noexcept
constexpr void swap (UA_StatusCode &native) noexcept
Additional Inherited Members
Public Types inherited from opcua::Wrapper< UA_StatusCode >
using NativeType = UA_StatusCode
using HandlerType = TypeHandler< UA_StatusCode >
Protected Member Functions inherited from opcua::Wrapper< UA_StatusCode >
constexpr const UA_StatusCode & native () const noexcept
constexpr UA_StatusCode & native () noexcept
constexpr void clear () noexcept
Related Symbols inherited from opcua::Wrapper< UA_StatusCode >
constexpr UA_StatusCode * asWrapper (typename T::NativeType *native) noexcept
constexpr const UA_StatusCode * asWrapper (const typename T::NativeType *native) noexcept
constexpr UA_StatusCode & asWrapper (typename T::NativeType &native) noexcept
constexpr const UA_StatusCode & asWrapper (const typename T::NativeType &native) noexcept
constexpr T::NativeType * asNative (UA_StatusCode *wrapper) noexcept
constexpr const T::NativeType * asNative (const UA_StatusCode *wrapper) noexcept
constexpr T::NativeType & asNative (UA_StatusCode &wrapper) noexcept
constexpr const T::NativeType & asNative (const UA_StatusCode &wrapper) noexcept
Constructor & Destructor Documentation
StatusCode() [1/2]
constexpr opcua::StatusCode::StatusCode () constexpr default noexcept
Create StatusCode with the default code UA_STATUSCODE_GOOD.
StatusCode() [2/2]
constexpr opcua::StatusCode::StatusCode (UA_StatusCode code) inline constexpr noexcept
Definition at line 46 of file types.hpp.
Member Function Documentation
get()
constexpr UA_StatusCode opcua::StatusCode::get () const inline constexpr noexcept
Explicitly get underlying UA_StatusCode.
Definition at line 50 of file types.hpp.
isBad()
constexpr bool opcua::StatusCode::isBad () const inline constexpr noexcept
Check if the status code is bad.
Definition at line 73 of file types.hpp.
isGood()
constexpr bool opcua::StatusCode::isGood () const inline constexpr noexcept
Check if the status code is good.
Definition at line 63 of file types.hpp.
isUncertain()
constexpr bool opcua::StatusCode::isUncertain () const inline constexpr noexcept
Check if the status code is uncertain.
Definition at line 68 of file types.hpp.
name()
std::string_view opcua::StatusCode::name () const inline noexcept
Get human-readable name of the StatusCode.
This feature might be disabled to create a smaller binary with the UA_ENABLE_STATUSCODE_DESCRIPTIONS build-flag. Then the function returns an empty string for every StatusCode.
Definition at line 58 of file types.hpp.
throwIfBad()
constexpr void opcua::StatusCode::throwIfBad () const inline constexpr
Throw a BadStatus exception if the status code is bad.
Exceptions
BadStatus
Definition at line 79 of file types.hpp.
Referenced by opcua::Node< Connection >::addModellingRule(), opcua::Node< Connection >::addReference(), opcua::MonitoredItem< Connection >::deleteMonitoredItem(), opcua::Node< Connection >::deleteNode(), opcua::Node< Connection >::deleteReference(), opcua::Subscription< Connection >::deleteSubscription(), opcua::MonitoredItem< Connection >::setMonitoringParameters(), opcua::Subscription< Connection >::subscribeDataChange(), opcua::Subscription< Connection >::subscribeEvent(), opcua::Node< Connection >::writeAccessLevel(), opcua::Node< Connection >::writeArrayDimensions(), opcua::Node< Connection >::writeContainsNoLoops(), opcua::Node< Connection >::writeDataType(), opcua::Node< Connection >::writeDataValue(), opcua::Node< Connection >::writeDescription(), opcua::Node< Connection >::writeDisplayName(), opcua::Node< Connection >::writeEventNotifier(), opcua::Node< Connection >::writeExecutable(), opcua::Node< Connection >::writeHistorizing(), opcua::Node< Connection >::writeInverseName(), opcua::Node< Connection >::writeIsAbstract(), opcua::Node< Connection >::writeMinimumSamplingInterval(), opcua::Node< Connection >::writeSymmetric(), opcua::Node< Connection >::writeUserAccessLevel(), opcua::Node< Connection >::writeUserExecutable(), opcua::Node< Connection >::writeUserWriteMask(), opcua::Node< Connection >::writeValue(), opcua::Node< Connection >::writeValueRank(), and opcua::Node< Connection >::writeWriteMask().