open62541pp: opcua::ua::ModifyMonitoredItemsResponse Class Reference
opcua::ua::ModifyMonitoredItemsResponse Class Reference
Wrapper classes
#include <types.hpp>
Detailed Description
UA_CreateMonitoredItemsResponse wrapper class.
See also
https://reference.opcfoundation.org/Core/Part4/v105/docs/5.12.3
Definition at line 2194 of file types.hpp.
Public Member Functions
const ResponseHeader & responseHeader () const noexcept
const ResponseHeader & getResponseHeader () const noexcept
ResponseHeader & responseHeader () noexcept
ResponseHeader & getResponseHeader () noexcept
Span< const MonitoredItemModifyResult > results () const noexcept
Span< MonitoredItemModifyResult > results () noexcept
Span< const MonitoredItemModifyResult > getResults () const noexcept
Span< MonitoredItemModifyResult > getResults () noexcept
Span< const DiagnosticInfo > diagnosticInfos () const noexcept
Span< DiagnosticInfo > diagnosticInfos () noexcept
Span< const DiagnosticInfo > getDiagnosticInfos () const noexcept
Span< DiagnosticInfo > getDiagnosticInfos () noexcept
constexpr TypeWrapper () noexcept=default
constexpr TypeWrapper (const T &native)
constexpr TypeWrapper (T &&native) noexcept
constexpr TypeWrapper (const TypeWrapper &other)
constexpr TypeWrapper (TypeWrapper &&other) noexcept
Public Member Functions inherited from opcua::TypeWrapper< UA_ModifyMonitoredItemsResponse, UA_TYPES_MODIFYMONITOREDITEMSRESPONSE >
constexpr TypeWrapper () noexcept=default
constexpr TypeWrapper (const UA_ModifyMonitoredItemsResponse &native)
constexpr TypeWrapper (UA_ModifyMonitoredItemsResponse &&native) noexcept
constexpr TypeWrapper (const TypeWrapper &other)
constexpr TypeWrapper (TypeWrapper &&other) noexcept
~TypeWrapper ()
constexpr TypeWrapper & operator= (const TypeWrapper &other)
constexpr TypeWrapper & operator= (const UA_ModifyMonitoredItemsResponse &native)
constexpr TypeWrapper & operator= (TypeWrapper &&other) noexcept
constexpr TypeWrapper & operator= (UA_ModifyMonitoredItemsResponse &&native) noexcept
Public Member Functions inherited from opcua::Wrapper< UA_ModifyMonitoredItemsResponse >
constexpr Wrapper () noexcept=default
constexpr Wrapper (const UA_ModifyMonitoredItemsResponse &native) noexcept
constexpr Wrapper (UA_ModifyMonitoredItemsResponse &&native) noexcept
constexpr Wrapper & operator= (const UA_ModifyMonitoredItemsResponse &native) noexcept
constexpr Wrapper & operator= (UA_ModifyMonitoredItemsResponse &&native) noexcept
constexpr operator UA_ModifyMonitoredItemsResponse & () noexcept
constexpr operator const UA_ModifyMonitoredItemsResponse & () const noexcept
constexpr UA_ModifyMonitoredItemsResponse * operator-> () noexcept
constexpr const UA_ModifyMonitoredItemsResponse * operator-> () const noexcept
constexpr UA_ModifyMonitoredItemsResponse * handle () noexcept
constexpr const UA_ModifyMonitoredItemsResponse * handle () const noexcept
constexpr void swap (Wrapper &other) noexcept
constexpr void swap (UA_ModifyMonitoredItemsResponse &native) noexcept
Additional Inherited Members
Public Types inherited from opcua::Wrapper< UA_ModifyMonitoredItemsResponse >
using NativeType
Static Public Member Functions inherited from opcua::TypeWrapper< UA_ModifyMonitoredItemsResponse, UA_TYPES_MODIFYMONITOREDITEMSRESPONSE >
static constexpr TypeIndex typeIndex ()
Protected Member Functions inherited from opcua::TypeWrapper< UA_ModifyMonitoredItemsResponse, UA_TYPES_MODIFYMONITOREDITEMSRESPONSE >
constexpr void clear () noexcept
Protected Member Functions inherited from opcua::Wrapper< UA_ModifyMonitoredItemsResponse >
constexpr const UA_ModifyMonitoredItemsResponse & native () const noexcept
constexpr UA_ModifyMonitoredItemsResponse & native () noexcept
Related Symbols inherited from opcua::TypeWrapper< UA_ModifyMonitoredItemsResponse, UA_TYPES_MODIFYMONITOREDITEMSRESPONSE >
String toString (const UA_ModifyMonitoredItemsResponse &object, const UA_DataType &type)
String toString (const UA_ModifyMonitoredItemsResponse &object)
String toString (const UA_ModifyMonitoredItemsResponse &object, const UA_DataType &type)
String toString (const UA_ModifyMonitoredItemsResponse &object)
Related Symbols inherited from opcua::Wrapper< UA_ModifyMonitoredItemsResponse >
constexpr WrapperType * asWrapper (NativeType *native) noexcept
constexpr const WrapperType * asWrapper (const NativeType *native) noexcept
constexpr WrapperType & asWrapper (NativeType &native) noexcept
constexpr const WrapperType & asWrapper (const NativeType &native) noexcept
constexpr NativeType * asNative (WrapperType *wrapper) noexcept
constexpr const NativeType * asNative (const WrapperType *wrapper) noexcept
constexpr NativeType & asNative (WrapperType &wrapper) noexcept
constexpr const NativeType & asNative (const WrapperType &wrapper) noexcept
constexpr WrapperType * asWrapper (NativeType *native) noexcept
constexpr const WrapperType * asWrapper (const NativeType *native) noexcept
constexpr WrapperType & asWrapper (NativeType &native) noexcept
constexpr const WrapperType & asWrapper (const NativeType &native) noexcept
constexpr NativeType * asNative (WrapperType *wrapper) noexcept
constexpr const NativeType * asNative (const WrapperType *wrapper) noexcept
constexpr NativeType & asNative (WrapperType &wrapper) noexcept
constexpr const NativeType & asNative (const WrapperType &wrapper) noexcept
Member Function Documentation
responseHeader() [1/2]
const ResponseHeader & opcua::ua::ModifyMonitoredItemsResponse::responseHeader () const inline noexcept
Definition at line 2199 of file types.hpp.
Referenced by getResponseHeader().
getResponseHeader() [1/2]
const ResponseHeader & opcua::ua::ModifyMonitoredItemsResponse::getResponseHeader () const inline noexcept
Deprecated
Use responseHeader instead
Definition at line 2199 of file types.hpp.
Referenced by getResponseHeader().
responseHeader() [2/2]
ResponseHeader & opcua::ua::ModifyMonitoredItemsResponse::responseHeader () inline noexcept
Definition at line 2199 of file types.hpp.
getResponseHeader() [2/2]
ResponseHeader & opcua::ua::ModifyMonitoredItemsResponse::getResponseHeader () inline noexcept
Deprecated
Use responseHeader instead
Definition at line 2199 of file types.hpp.
results() [1/2]
Span< const MonitoredItemModifyResult > opcua::ua::ModifyMonitoredItemsResponse::results () const inline noexcept
Definition at line 2200 of file types.hpp.
Referenced by getResults().
results() [2/2]
Span< MonitoredItemModifyResult > opcua::ua::ModifyMonitoredItemsResponse::results () inline noexcept
Definition at line 2200 of file types.hpp.
getResults() [1/2]
Span< const MonitoredItemModifyResult > opcua::ua::ModifyMonitoredItemsResponse::getResults () const inline noexcept
Deprecated
Use results instead
Definition at line 2200 of file types.hpp.
Referenced by getResults().
getResults() [2/2]
Span< MonitoredItemModifyResult > opcua::ua::ModifyMonitoredItemsResponse::getResults () inline noexcept
Deprecated
Use results instead
Definition at line 2200 of file types.hpp.
diagnosticInfos() [1/2]
Span< const DiagnosticInfo > opcua::ua::ModifyMonitoredItemsResponse::diagnosticInfos () const inline noexcept
Definition at line 2203 of file types.hpp.
Referenced by getResults().
diagnosticInfos() [2/2]
Span< DiagnosticInfo > opcua::ua::ModifyMonitoredItemsResponse::diagnosticInfos () inline noexcept
Definition at line 2203 of file types.hpp.
getDiagnosticInfos() [1/2]
Span< const DiagnosticInfo > opcua::ua::ModifyMonitoredItemsResponse::getDiagnosticInfos () const inline noexcept
Deprecated
Use diagnosticInfos instead
Definition at line 2203 of file types.hpp.
Referenced by getResults().
getDiagnosticInfos() [2/2]
Span< DiagnosticInfo > opcua::ua::ModifyMonitoredItemsResponse::getDiagnosticInfos () inline noexcept
Deprecated
Use diagnosticInfos instead
Definition at line 2203 of file types.hpp.
TypeWrapper() [1/5]
opcua::TypeWrapper< T, Index >::TypeWrapper () constexpr default noexcept
TypeWrapper() [2/5]
opcua::TypeWrapper< T, Index >::TypeWrapper (const T & native) inline explicit constexpr
Constructor with native object (deep copy).
Definition at line 31 of file typewrapper.hpp.
TypeWrapper() [3/5]
opcua::TypeWrapper< T, Index >::TypeWrapper (T && native) inline constexpr noexcept
Constructor with native object (move rvalue).
Definition at line 35 of file typewrapper.hpp.
TypeWrapper() [4/5]
opcua::TypeWrapper< T, Index >::TypeWrapper (const TypeWrapper & other) inline constexpr
Copy constructor (deep copy).
Definition at line 43 of file typewrapper.hpp.
TypeWrapper() [5/5]
opcua::TypeWrapper< T, Index >::TypeWrapper (TypeWrapper && other) inline constexpr noexcept
Move constructor.
Definition at line 47 of file typewrapper.hpp.