open62541pp: opcua::ua::BrowseNextResponse Class Reference
opcua::ua::BrowseNextResponse Class Reference
Wrapper classes
#include <types.hpp>
Detailed Description
UA_BrowseNextResponse wrapper class.
Definition at line 1218 of file types.hpp.
Public Member Functions
const ResponseHeader & responseHeader () const noexcept
const ResponseHeader & getResponseHeader () const noexcept
ResponseHeader & responseHeader () noexcept
ResponseHeader & getResponseHeader () noexcept
Span< const BrowseResult > results () const noexcept
Span< BrowseResult > results () noexcept
Span< const BrowseResult > getResults () const noexcept
Span< BrowseResult > getResults () noexcept
Span< const DiagnosticInfo > diagnosticInfos () const noexcept
Span< DiagnosticInfo > diagnosticInfos () noexcept
Span< const DiagnosticInfo > getDiagnosticInfos () const noexcept
Span< DiagnosticInfo > getDiagnosticInfos () noexcept
constexpr TypeWrapper () noexcept=default
constexpr TypeWrapper (const T &native)
constexpr TypeWrapper (T &&native) noexcept
constexpr TypeWrapper (const TypeWrapper &other)
constexpr TypeWrapper (TypeWrapper &&other) noexcept
Public Member Functions inherited from opcua::TypeWrapper< UA_BrowseNextResponse, UA_TYPES_BROWSENEXTRESPONSE >
constexpr TypeWrapper () noexcept=default
constexpr TypeWrapper (const UA_BrowseNextResponse &native)
constexpr TypeWrapper (UA_BrowseNextResponse &&native) noexcept
constexpr TypeWrapper (const TypeWrapper &other)
constexpr TypeWrapper (TypeWrapper &&other) noexcept
~TypeWrapper ()
constexpr TypeWrapper & operator= (const TypeWrapper &other)
constexpr TypeWrapper & operator= (const UA_BrowseNextResponse &native)
constexpr TypeWrapper & operator= (TypeWrapper &&other) noexcept
constexpr TypeWrapper & operator= (UA_BrowseNextResponse &&native) noexcept
Public Member Functions inherited from opcua::Wrapper< UA_BrowseNextResponse >
constexpr Wrapper () noexcept=default
constexpr Wrapper (const UA_BrowseNextResponse &native) noexcept
constexpr Wrapper (UA_BrowseNextResponse &&native) noexcept
constexpr Wrapper & operator= (const UA_BrowseNextResponse &native) noexcept
constexpr Wrapper & operator= (UA_BrowseNextResponse &&native) noexcept
constexpr operator UA_BrowseNextResponse & () noexcept
constexpr operator const UA_BrowseNextResponse & () const noexcept
constexpr UA_BrowseNextResponse * operator-> () noexcept
constexpr const UA_BrowseNextResponse * operator-> () const noexcept
constexpr UA_BrowseNextResponse * handle () noexcept
constexpr const UA_BrowseNextResponse * handle () const noexcept
constexpr void swap (Wrapper &other) noexcept
constexpr void swap (UA_BrowseNextResponse &native) noexcept
Additional Inherited Members
Public Types inherited from opcua::Wrapper< UA_BrowseNextResponse >
using NativeType
Static Public Member Functions inherited from opcua::TypeWrapper< UA_BrowseNextResponse, UA_TYPES_BROWSENEXTRESPONSE >
static constexpr TypeIndex typeIndex ()
Protected Member Functions inherited from opcua::TypeWrapper< UA_BrowseNextResponse, UA_TYPES_BROWSENEXTRESPONSE >
constexpr void clear () noexcept
Protected Member Functions inherited from opcua::Wrapper< UA_BrowseNextResponse >
constexpr const UA_BrowseNextResponse & native () const noexcept
constexpr UA_BrowseNextResponse & native () noexcept
Related Symbols inherited from opcua::TypeWrapper< UA_BrowseNextResponse, UA_TYPES_BROWSENEXTRESPONSE >
String toString (const UA_BrowseNextResponse &object, const UA_DataType &type)
String toString (const UA_BrowseNextResponse &object)
String toString (const UA_BrowseNextResponse &object, const UA_DataType &type)
String toString (const UA_BrowseNextResponse &object)
Related Symbols inherited from opcua::Wrapper< UA_BrowseNextResponse >
constexpr WrapperType * asWrapper (NativeType *native) noexcept
constexpr const WrapperType * asWrapper (const NativeType *native) noexcept
constexpr WrapperType & asWrapper (NativeType &native) noexcept
constexpr const WrapperType & asWrapper (const NativeType &native) noexcept
constexpr NativeType * asNative (WrapperType *wrapper) noexcept
constexpr const NativeType * asNative (const WrapperType *wrapper) noexcept
constexpr NativeType & asNative (WrapperType &wrapper) noexcept
constexpr const NativeType & asNative (const WrapperType &wrapper) noexcept
constexpr WrapperType * asWrapper (NativeType *native) noexcept
constexpr const WrapperType * asWrapper (const NativeType *native) noexcept
constexpr WrapperType & asWrapper (NativeType &native) noexcept
constexpr const WrapperType & asWrapper (const NativeType &native) noexcept
constexpr NativeType * asNative (WrapperType *wrapper) noexcept
constexpr const NativeType * asNative (const WrapperType *wrapper) noexcept
constexpr NativeType & asNative (WrapperType &wrapper) noexcept
constexpr const NativeType & asNative (const WrapperType &wrapper) noexcept
Member Function Documentation
responseHeader() [1/2]
const ResponseHeader & opcua::ua::BrowseNextResponse::responseHeader () const inline noexcept
Definition at line 1222 of file types.hpp.
Referenced by getResponseHeader().
getResponseHeader() [1/2]
const ResponseHeader & opcua::ua::BrowseNextResponse::getResponseHeader () const inline noexcept
Deprecated
Use responseHeader instead
Definition at line 1222 of file types.hpp.
Referenced by getResponseHeader().
responseHeader() [2/2]
ResponseHeader & opcua::ua::BrowseNextResponse::responseHeader () inline noexcept
Definition at line 1222 of file types.hpp.
getResponseHeader() [2/2]
ResponseHeader & opcua::ua::BrowseNextResponse::getResponseHeader () inline noexcept
Deprecated
Use responseHeader instead
Definition at line 1222 of file types.hpp.
results() [1/2]
Span< const BrowseResult > opcua::ua::BrowseNextResponse::results () const inline noexcept
Definition at line 1223 of file types.hpp.
Referenced by getResults().
results() [2/2]
Span< BrowseResult > opcua::ua::BrowseNextResponse::results () inline noexcept
Definition at line 1223 of file types.hpp.
getResults() [1/2]
Span< const BrowseResult > opcua::ua::BrowseNextResponse::getResults () const inline noexcept
Deprecated
Use results instead
Definition at line 1223 of file types.hpp.
Referenced by getResults().
getResults() [2/2]
Span< BrowseResult > opcua::ua::BrowseNextResponse::getResults () inline noexcept
Deprecated
Use results instead
Definition at line 1223 of file types.hpp.
diagnosticInfos() [1/2]
Span< const DiagnosticInfo > opcua::ua::BrowseNextResponse::diagnosticInfos () const inline noexcept
Definition at line 1226 of file types.hpp.
Referenced by getResults().
diagnosticInfos() [2/2]
Span< DiagnosticInfo > opcua::ua::BrowseNextResponse::diagnosticInfos () inline noexcept
Definition at line 1226 of file types.hpp.
getDiagnosticInfos() [1/2]
Span< const DiagnosticInfo > opcua::ua::BrowseNextResponse::getDiagnosticInfos () const inline noexcept
Deprecated
Use diagnosticInfos instead
Definition at line 1226 of file types.hpp.
Referenced by getResults().
getDiagnosticInfos() [2/2]
Span< DiagnosticInfo > opcua::ua::BrowseNextResponse::getDiagnosticInfos () inline noexcept
Deprecated
Use diagnosticInfos instead
Definition at line 1226 of file types.hpp.
TypeWrapper() [1/5]
opcua::TypeWrapper< T, Index >::TypeWrapper () constexpr default noexcept
TypeWrapper() [2/5]
opcua::TypeWrapper< T, Index >::TypeWrapper (const T & native) inline explicit constexpr
Constructor with native object (deep copy).
Definition at line 31 of file typewrapper.hpp.
TypeWrapper() [3/5]
opcua::TypeWrapper< T, Index >::TypeWrapper (T && native) inline constexpr noexcept
Constructor with native object (move rvalue).
Definition at line 35 of file typewrapper.hpp.
TypeWrapper() [4/5]
opcua::TypeWrapper< T, Index >::TypeWrapper (const TypeWrapper & other) inline constexpr
Copy constructor (deep copy).
Definition at line 43 of file typewrapper.hpp.
TypeWrapper() [5/5]
opcua::TypeWrapper< T, Index >::TypeWrapper (TypeWrapper && other) inline constexpr noexcept
Move constructor.
Definition at line 47 of file typewrapper.hpp.