open62541++: opcua::ByteString Class Reference
opcua::ByteString Class Reference
UA_ByteString wrapper class.
#include <TypeWrapper.h>
Public Member Functions
ByteString (std::string_view str)
bool operator== (const ByteString &other) const
bool operator!= (const ByteString &other) const
std::string get () const
std::string_view getView () const
Public Member Functions inherited from opcua::TypeWrapper< UA_ByteString, Type::ByteString >
TypeWrapper ()
TypeWrapper (const UA_ByteString &data)
Constructor with native UA_* type (deep copy)
TypeWrapper (UA_ByteString &&data) noexcept
Constructor with native UA_* type (move rvalue)
TypeWrapper (const TypeWrapper &other)
Copy constructor (deep copy)
TypeWrapper (TypeWrapper &&other) noexcept
Move constructor.
virtual ~TypeWrapper ()
TypeWrapper & operator= (const TypeWrapper &other)
Copy assignment (deep copy)
TypeWrapper & operator= (TypeWrapper &&other) noexcept
Move assignment.
UA_ByteString * handle ()
Return pointer to wrapped UA data type.
const UA_ByteString * handle () const
Return const pointer to wrapped UA data type.
Additional Inherited Members
Public Types inherited from opcua::TypeWrapper< UA_ByteString, Type::ByteString >
using BaseClass = TypeWrapper< UA_ByteString, type >
using UaType = UA_ByteString
Static Public Member Functions inherited from opcua::TypeWrapper< UA_ByteString, Type::ByteString >
constexpr static Type getType ()
Return type enum.
constexpr static const UA_DataType * getDataType ()
Return UA_DataType object.
Protected Member Functions inherited from opcua::TypeWrapper< UA_ByteString, Type::ByteString >
void init () noexcept
void clear () noexcept
void set (const UA_ByteString &data)
void set (UA_ByteString &&data)
Detailed Description
UA_ByteString wrapper class.
UA_ByteString is a typedef of UA_String. Therefore the type can not be deduced from UA_ByteString itself. Second template argument (Type::ByteString) necessary to map to the right type.
Definition at line 162 of file TypeWrapper.h.
Constructor & Destructor Documentation
ByteString()
opcua::ByteString::ByteString (std::string_view str) inline explicit
Definition at line 166 of file TypeWrapper.h.
References opcua::allocUaString().
Member Function Documentation
get()
std::string opcua::ByteString::get () const inline
Definition at line 174 of file TypeWrapper.h.
References opcua::TypeWrapper< UA_ByteString, Type::ByteString >::handle(), and opcua::uaStringToString().
getView()
std::string_view opcua::ByteString::getView () const inline
Definition at line 176 of file TypeWrapper.h.
References opcua::TypeWrapper< UA_ByteString, Type::ByteString >::handle(), and opcua::uaStringToStringView().
operator!=()
bool opcua::ByteString::operator!= (const ByteString & other) const inline
Definition at line 172 of file TypeWrapper.h.
References operator==().
operator==()
bool opcua::ByteString::operator== (const ByteString & other) const inline
Definition at line 168 of file TypeWrapper.h.
References opcua::TypeWrapper< UA_ByteString, Type::ByteString >::handle(), and opcua::TypeWrapper< T, type >::handle().
Referenced by operator!=().
The documentation for this class was generated from the following file:
/home/runner/work/open62541pp/open62541pp/include/open62541pp/TypeWrapper.h