open62541++: opcua::String Class Reference
opcua::String Class Reference
Wrapper classes of UA_* types
UA_String wrapper class.
#include <TypeWrapper.h>
Public Member Functions
String (std::string_view str)
std::string get () const
std::string_view getView () const
Public Member Functions inherited from opcua::TypeWrapper< UA_String, UA_TYPES_STRING >
TypeWrapper ()
TypeWrapper (const UA_String &data)
Constructor with native UA_* type (deep copy).
TypeWrapper (UA_String &&data) noexcept
Constructor with native UA_* type (move rvalue).
TypeWrapper (const TypeWrapper &other)
Copy constructor (deep copy).
TypeWrapper (TypeWrapper &&other) noexcept
Move constructor.
virtual ~TypeWrapper ()
TypeWrapper & operator= (const TypeWrapper &other)
Copy assignment (deep copy).
TypeWrapper & operator= (TypeWrapper &&other) noexcept
Move assignment.
operator UA_String & () noexcept
Implicit conversion to wrapped object.
operator const UA_String & () const noexcept
Implicit conversion to wrapped object.
UA_String * operator-> () noexcept
Member access to wrapped object.
const UA_String * operator-> () const noexcept
Member access to wrapped object.
void swap (TypeWrapper &other) noexcept
Swap wrapped objects.
UA_String * handle () noexcept
Return pointer to wrapped object.
const UA_String * handle () const noexcept
Return const pointer to wrapped object.
Additional Inherited Members
Public Types inherited from opcua::TypeWrapper< UA_String, UA_TYPES_STRING >
using TypeWrapperBase = TypeWrapper< UA_String, typeIndex >
using UaType = UA_String
Static Public Member Functions inherited from opcua::TypeWrapper< UA_String, UA_TYPES_STRING >
static constexpr uint16_t getTypeIndex ()
Get type as type index.
static constexpr Type getType ()
Get type as Type enum (only for builtin types).
static const UA_DataType * getDataType ()
Get type as UA_DataType object.
Protected Member Functions inherited from opcua::TypeWrapper< UA_String, UA_TYPES_STRING >
void init () noexcept
void clear () noexcept
void copy (const UA_String &data)
Static Protected Member Functions inherited from opcua::TypeWrapper< UA_String, UA_TYPES_STRING >
static void checkMemSize ()
Detailed Description
UA_String wrapper class.
Definition at line 220 of file TypeWrapper.h.
Constructor & Destructor Documentation
String()
opcua::String::String (std::string_view str) explicit
Definition at line 10 of file TypeWrapper.cpp.
References opcua::detail::allocUaString().
Member Function Documentation
get()
std::string opcua::String::get () const
Definition at line 13 of file TypeWrapper.cpp.
References opcua::TypeWrapper< UA_String, UA_TYPES_STRING >::handle(), and opcua::detail::toString().
getView()
std::string_view opcua::String::getView () const
Definition at line 17 of file TypeWrapper.cpp.
References opcua::TypeWrapper< UA_String, UA_TYPES_STRING >::handle(), and opcua::detail::toStringView().