open62541pp: opcua::DiagnosticInfo Class Reference
opcua::DiagnosticInfo Class Reference
Wrapper classes
#include <types.hpp>
Detailed Description
UA_DiagnosticInfo wrapper class.
See also
https://reference.opcfoundation.org/Core/Part4/v105/docs/7.12
Definition at line 2327 of file types.hpp.
Public Member Functions
bool hasSymbolicId () const noexcept
bool hasNamespaceUri () const noexcept
bool hasLocalizedText () const noexcept
bool hasLocale () const noexcept
bool hasAdditionalInfo () const noexcept
bool hasInnerStatusCode () const noexcept
bool hasInnerDiagnosticInfo () const noexcept
int32_t symbolicId () const noexcept
int32_t getSymbolicId () const noexcept
int32_t namespaceUri () const noexcept
int32_t getNamespaceUri () const noexcept
int32_t localizedText () const noexcept
int32_t getLocalizedText () const noexcept
int32_t locale () const noexcept
int32_t getLocale () const noexcept
const String & additionalInfo () const noexcept
const String & getAdditionalInfo () const noexcept
StatusCode innerStatusCode () const noexcept
StatusCode getInnerStatusCode () const noexcept
const DiagnosticInfo * innerDiagnosticInfo () const noexcept
const DiagnosticInfo * getInnerDiagnosticInfo () const noexcept
constexpr TypeWrapper () noexcept=default
constexpr TypeWrapper (const T &native)
constexpr TypeWrapper (T &&native) noexcept
constexpr TypeWrapper (const TypeWrapper &other)
constexpr TypeWrapper (TypeWrapper &&other) noexcept
Public Member Functions inherited from opcua::TypeWrapper< UA_DiagnosticInfo, UA_TYPES_DIAGNOSTICINFO >
constexpr TypeWrapper () noexcept=default
constexpr TypeWrapper (const UA_DiagnosticInfo &native)
constexpr TypeWrapper (UA_DiagnosticInfo &&native) noexcept
constexpr TypeWrapper (const TypeWrapper &other)
constexpr TypeWrapper (TypeWrapper &&other) noexcept
~TypeWrapper ()
constexpr TypeWrapper & operator= (const TypeWrapper &other)
constexpr TypeWrapper & operator= (const UA_DiagnosticInfo &native)
constexpr TypeWrapper & operator= (TypeWrapper &&other) noexcept
constexpr TypeWrapper & operator= (UA_DiagnosticInfo &&native) noexcept
Public Member Functions inherited from opcua::Wrapper< T >
constexpr Wrapper () noexcept=default
constexpr Wrapper (const T &native) noexcept
constexpr Wrapper (T &&native) noexcept
constexpr Wrapper & operator= (const T &native) noexcept
constexpr Wrapper & operator= (T &&native) noexcept
constexpr operator T& () noexcept
constexpr operator const T & () const noexcept
constexpr T * operator-> () noexcept
constexpr const T * operator-> () const noexcept
constexpr T * handle () noexcept
constexpr const T * handle () const noexcept
constexpr void swap (Wrapper &other) noexcept
constexpr void swap (T &native) noexcept
Additional Inherited Members
Public Types inherited from opcua::Wrapper< T >
using NativeType = T
Static Public Member Functions inherited from opcua::TypeWrapper< UA_DiagnosticInfo, UA_TYPES_DIAGNOSTICINFO >
static constexpr TypeIndex typeIndex ()
Protected Member Functions inherited from opcua::TypeWrapper< UA_DiagnosticInfo, UA_TYPES_DIAGNOSTICINFO >
constexpr void clear () noexcept
Protected Member Functions inherited from opcua::Wrapper< T >
constexpr const T & native () const noexcept
constexpr T & native () noexcept
Related Symbols inherited from opcua::TypeWrapper< UA_DiagnosticInfo, UA_TYPES_DIAGNOSTICINFO >
String toString (const UA_DiagnosticInfo &object, const UA_DataType &type)
String toString (const UA_DiagnosticInfo &object)
Related Symbols inherited from opcua::Wrapper< T >
template<typename WrapperType , typename NativeType = typename WrapperType::NativeType>
constexpr WrapperType * asWrapper (NativeType *native) noexcept
template<typename WrapperType , typename NativeType = typename WrapperType::NativeType>
constexpr const WrapperType * asWrapper (const NativeType *native) noexcept
template<typename WrapperType , typename NativeType = typename WrapperType::NativeType>
constexpr WrapperType & asWrapper (NativeType &native) noexcept
template<typename WrapperType , typename NativeType = typename WrapperType::NativeType>
constexpr const WrapperType & asWrapper (const NativeType &native) noexcept
template<typename WrapperType , typename NativeType = typename WrapperType::NativeType>
constexpr NativeType * asNative (WrapperType *wrapper) noexcept
template<typename WrapperType , typename NativeType = typename WrapperType::NativeType>
constexpr const NativeType * asNative (const WrapperType *wrapper) noexcept
template<typename WrapperType , typename NativeType = typename WrapperType::NativeType>
constexpr NativeType & asNative (WrapperType &wrapper) noexcept
template<typename WrapperType , typename NativeType = typename WrapperType::NativeType>
constexpr const NativeType & asNative (const WrapperType &wrapper) noexcept
Member Function Documentation
hasSymbolicId()
bool opcua::DiagnosticInfo::hasSymbolicId () const inline noexcept
Definition at line 2331 of file types.hpp.
hasNamespaceUri()
bool opcua::DiagnosticInfo::hasNamespaceUri () const inline noexcept
Definition at line 2335 of file types.hpp.
hasLocalizedText()
bool opcua::DiagnosticInfo::hasLocalizedText () const inline noexcept
Definition at line 2339 of file types.hpp.
hasLocale()
bool opcua::DiagnosticInfo::hasLocale () const inline noexcept
Definition at line 2343 of file types.hpp.
hasAdditionalInfo()
bool opcua::DiagnosticInfo::hasAdditionalInfo () const inline noexcept
Definition at line 2347 of file types.hpp.
hasInnerStatusCode()
bool opcua::DiagnosticInfo::hasInnerStatusCode () const inline noexcept
Definition at line 2351 of file types.hpp.
hasInnerDiagnosticInfo()
bool opcua::DiagnosticInfo::hasInnerDiagnosticInfo () const inline noexcept
Definition at line 2355 of file types.hpp.
symbolicId()
int32_t opcua::DiagnosticInfo::symbolicId () const inline noexcept
Definition at line 2359 of file types.hpp.
Referenced by getSymbolicId().
getSymbolicId()
int32_t opcua::DiagnosticInfo::getSymbolicId () const inline noexcept
Deprecated:
Use symbolicId() instead
Definition at line 2365 of file types.hpp.
namespaceUri()
int32_t opcua::DiagnosticInfo::namespaceUri () const inline noexcept
Definition at line 2369 of file types.hpp.
Referenced by getNamespaceUri().
getNamespaceUri()
int32_t opcua::DiagnosticInfo::getNamespaceUri () const inline noexcept
Deprecated:
Use namespaceUri() instead
Definition at line 2375 of file types.hpp.
localizedText()
int32_t opcua::DiagnosticInfo::localizedText () const inline noexcept
Definition at line 2379 of file types.hpp.
Referenced by getLocalizedText().
getLocalizedText()
int32_t opcua::DiagnosticInfo::getLocalizedText () const inline noexcept
Deprecated:
Use localizedText() instead
Definition at line 2385 of file types.hpp.
locale()
int32_t opcua::DiagnosticInfo::locale () const inline noexcept
Definition at line 2389 of file types.hpp.
Referenced by getLocale().
getLocale()
int32_t opcua::DiagnosticInfo::getLocale () const inline noexcept
Deprecated:
Use locale() instead
Definition at line 2395 of file types.hpp.
additionalInfo()
const String & opcua::DiagnosticInfo::additionalInfo () const inline noexcept
Definition at line 2399 of file types.hpp.
Referenced by additionalInfo(), and getAdditionalInfo().
getAdditionalInfo()
const String & opcua::DiagnosticInfo::getAdditionalInfo () const inline noexcept
Deprecated:
Use additionalInfo() instead
Definition at line 2405 of file types.hpp.
innerStatusCode()
StatusCode opcua::DiagnosticInfo::innerStatusCode () const inline noexcept
Definition at line 2409 of file types.hpp.
Referenced by getInnerStatusCode().
getInnerStatusCode()
StatusCode opcua::DiagnosticInfo::getInnerStatusCode () const inline noexcept
Deprecated:
Use innerStatusCode() instead
Definition at line 2415 of file types.hpp.
innerDiagnosticInfo()
const DiagnosticInfo * opcua::DiagnosticInfo::innerDiagnosticInfo () const inline noexcept
Definition at line 2419 of file types.hpp.
Referenced by getInnerDiagnosticInfo(), and innerDiagnosticInfo().
getInnerDiagnosticInfo()
const DiagnosticInfo * opcua::DiagnosticInfo::getInnerDiagnosticInfo () const inline noexcept
Deprecated:
Use innerDiagnosticInfo() instead
Definition at line 2425 of file types.hpp.
TypeWrapper() [1/5]
constexpr opcua::TypeWrapper< T, Index >::TypeWrapper () constexpr default noexcept
TypeWrapper() [2/5]
constexpr opcua::TypeWrapper< T, Index >::TypeWrapper (const T & native) inline explicit constexpr
Constructor with native object (deep copy).
Definition at line 31 of file typewrapper.hpp.
TypeWrapper() [3/5]
constexpr opcua::TypeWrapper< T, Index >::TypeWrapper (T && native) inline constexpr noexcept
Constructor with native object (move rvalue).
Definition at line 35 of file typewrapper.hpp.
TypeWrapper() [4/5]
constexpr opcua::TypeWrapper< T, Index >::TypeWrapper (const TypeWrapper & other) inline constexpr
Copy constructor (deep copy).
Definition at line 43 of file typewrapper.hpp.
TypeWrapper() [5/5]
constexpr opcua::TypeWrapper< T, Index >::TypeWrapper (TypeWrapper && other) inline constexpr noexcept
Move constructor.
Definition at line 47 of file typewrapper.hpp.