open62541pp: opcua::ua::EndpointDescription Class Reference
opcua::ua::EndpointDescription Class Reference
Wrapper classes
#include <types.hpp>
Detailed Description
UA_EndpointDescription wrapper class.
See also
https://reference.opcfoundation.org/Core/Part4/v105/docs/7.14
Definition at line 310 of file types.hpp.
Public Member Functions
const String & endpointUrl () const noexcept
const String & getEndpointUrl () const noexcept
String & endpointUrl () noexcept
String & getEndpointUrl () noexcept
const ApplicationDescription & server () const noexcept
const ApplicationDescription & getServer () const noexcept
ApplicationDescription & server () noexcept
ApplicationDescription & getServer () noexcept
const ByteString & serverCertificate () const noexcept
const ByteString & getServerCertificate () const noexcept
ByteString & serverCertificate () noexcept
ByteString & getServerCertificate () noexcept
MessageSecurityMode securityMode () const noexcept
MessageSecurityMode getSecurityMode () const noexcept
const String & securityPolicyUri () const noexcept
const String & getSecurityPolicyUri () const noexcept
String & securityPolicyUri () noexcept
String & getSecurityPolicyUri () noexcept
Span< const UserTokenPolicy > userIdentityTokens () const noexcept
Span< UserTokenPolicy > userIdentityTokens () noexcept
Span< const UserTokenPolicy > getUserIdentityTokens () const noexcept
Span< UserTokenPolicy > getUserIdentityTokens () noexcept
const String & transportProfileUri () const noexcept
const String & getTransportProfileUri () const noexcept
String & transportProfileUri () noexcept
String & getTransportProfileUri () noexcept
UA_Byte securityLevel () const noexcept
UA_Byte getSecurityLevel () const noexcept
constexpr TypeWrapper () noexcept=default
constexpr TypeWrapper (const T &native)
constexpr TypeWrapper (T &&native) noexcept
constexpr TypeWrapper (const TypeWrapper &other)
constexpr TypeWrapper (TypeWrapper &&other) noexcept
Public Member Functions inherited from opcua::TypeWrapper< UA_EndpointDescription, UA_TYPES_ENDPOINTDESCRIPTION >
constexpr TypeWrapper () noexcept=default
constexpr TypeWrapper (const UA_EndpointDescription &native)
constexpr TypeWrapper (UA_EndpointDescription &&native) noexcept
constexpr TypeWrapper (const TypeWrapper &other)
constexpr TypeWrapper (TypeWrapper &&other) noexcept
~TypeWrapper ()
constexpr TypeWrapper & operator= (const TypeWrapper &other)
constexpr TypeWrapper & operator= (const UA_EndpointDescription &native)
constexpr TypeWrapper & operator= (TypeWrapper &&other) noexcept
constexpr TypeWrapper & operator= (UA_EndpointDescription &&native) noexcept
Public Member Functions inherited from opcua::Wrapper< UA_EndpointDescription >
constexpr Wrapper () noexcept=default
constexpr Wrapper (const UA_EndpointDescription &native) noexcept
constexpr Wrapper (UA_EndpointDescription &&native) noexcept
constexpr Wrapper & operator= (const UA_EndpointDescription &native) noexcept
constexpr Wrapper & operator= (UA_EndpointDescription &&native) noexcept
constexpr operator UA_EndpointDescription & () noexcept
constexpr operator const UA_EndpointDescription & () const noexcept
constexpr UA_EndpointDescription * operator-> () noexcept
constexpr const UA_EndpointDescription * operator-> () const noexcept
constexpr UA_EndpointDescription * handle () noexcept
constexpr const UA_EndpointDescription * handle () const noexcept
constexpr void swap (Wrapper &other) noexcept
constexpr void swap (UA_EndpointDescription &native) noexcept
Additional Inherited Members
Public Types inherited from opcua::Wrapper< UA_EndpointDescription >
using NativeType
Static Public Member Functions inherited from opcua::TypeWrapper< UA_EndpointDescription, UA_TYPES_ENDPOINTDESCRIPTION >
static constexpr TypeIndex typeIndex ()
Protected Member Functions inherited from opcua::TypeWrapper< UA_EndpointDescription, UA_TYPES_ENDPOINTDESCRIPTION >
constexpr void clear () noexcept
Protected Member Functions inherited from opcua::Wrapper< UA_EndpointDescription >
constexpr const UA_EndpointDescription & native () const noexcept
constexpr UA_EndpointDescription & native () noexcept
Related Symbols inherited from opcua::TypeWrapper< UA_EndpointDescription, UA_TYPES_ENDPOINTDESCRIPTION >
String toString (const UA_EndpointDescription &object, const UA_DataType &type)
String toString (const UA_EndpointDescription &object)
String toString (const UA_EndpointDescription &object, const UA_DataType &type)
String toString (const UA_EndpointDescription &object)
Related Symbols inherited from opcua::Wrapper< UA_EndpointDescription >
constexpr WrapperType * asWrapper (NativeType *native) noexcept
constexpr const WrapperType * asWrapper (const NativeType *native) noexcept
constexpr WrapperType & asWrapper (NativeType &native) noexcept
constexpr const WrapperType & asWrapper (const NativeType &native) noexcept
constexpr NativeType * asNative (WrapperType *wrapper) noexcept
constexpr const NativeType * asNative (const WrapperType *wrapper) noexcept
constexpr NativeType & asNative (WrapperType &wrapper) noexcept
constexpr const NativeType & asNative (const WrapperType &wrapper) noexcept
constexpr WrapperType * asWrapper (NativeType *native) noexcept
constexpr const WrapperType * asWrapper (const NativeType *native) noexcept
constexpr WrapperType & asWrapper (NativeType &native) noexcept
constexpr const WrapperType & asWrapper (const NativeType &native) noexcept
constexpr NativeType * asNative (WrapperType *wrapper) noexcept
constexpr const NativeType * asNative (const WrapperType *wrapper) noexcept
constexpr NativeType & asNative (WrapperType &wrapper) noexcept
constexpr const NativeType & asNative (const WrapperType &wrapper) noexcept
Member Function Documentation
endpointUrl() [1/2]
const String & opcua::ua::EndpointDescription::endpointUrl () const inline noexcept
Definition at line 315 of file types.hpp.
Referenced by endpointUrl().
getEndpointUrl() [1/2]
const String & opcua::ua::EndpointDescription::getEndpointUrl () const inline noexcept
Deprecated
Use endpointUrl instead
Definition at line 315 of file types.hpp.
Referenced by endpointUrl().
endpointUrl() [2/2]
String & opcua::ua::EndpointDescription::endpointUrl () inline noexcept
Definition at line 315 of file types.hpp.
getEndpointUrl() [2/2]
String & opcua::ua::EndpointDescription::getEndpointUrl () inline noexcept
Deprecated
Use endpointUrl instead
Definition at line 315 of file types.hpp.
server() [1/2]
const ApplicationDescription & opcua::ua::EndpointDescription::server () const inline noexcept
Definition at line 316 of file types.hpp.
Referenced by getServer().
getServer() [1/2]
const ApplicationDescription & opcua::ua::EndpointDescription::getServer () const inline noexcept
Deprecated
Use server instead
Definition at line 316 of file types.hpp.
Referenced by getServer().
server() [2/2]
ApplicationDescription & opcua::ua::EndpointDescription::server () inline noexcept
Definition at line 316 of file types.hpp.
getServer() [2/2]
ApplicationDescription & opcua::ua::EndpointDescription::getServer () inline noexcept
Deprecated
Use server instead
Definition at line 316 of file types.hpp.
serverCertificate() [1/2]
const ByteString & opcua::ua::EndpointDescription::serverCertificate () const inline noexcept
Definition at line 317 of file types.hpp.
Referenced by getServerCertificate().
getServerCertificate() [1/2]
const ByteString & opcua::ua::EndpointDescription::getServerCertificate () const inline noexcept
Deprecated
Use serverCertificate instead
Definition at line 317 of file types.hpp.
Referenced by getServerCertificate().
serverCertificate() [2/2]
ByteString & opcua::ua::EndpointDescription::serverCertificate () inline noexcept
Definition at line 317 of file types.hpp.
getServerCertificate() [2/2]
ByteString & opcua::ua::EndpointDescription::getServerCertificate () inline noexcept
Deprecated
Use serverCertificate instead
Definition at line 317 of file types.hpp.
securityMode()
MessageSecurityMode opcua::ua::EndpointDescription::securityMode () const inline noexcept
Definition at line 318 of file types.hpp.
Referenced by getSecurityMode().
getSecurityMode()
MessageSecurityMode opcua::ua::EndpointDescription::getSecurityMode () const inline noexcept
Deprecated
Use securityMode instead
Definition at line 318 of file types.hpp.
Referenced by getSecurityMode().
securityPolicyUri() [1/2]
const String & opcua::ua::EndpointDescription::securityPolicyUri () const inline noexcept
Definition at line 319 of file types.hpp.
Referenced by getSecurityPolicyUri().
getSecurityPolicyUri() [1/2]
const String & opcua::ua::EndpointDescription::getSecurityPolicyUri () const inline noexcept
Deprecated
Use securityPolicyUri instead
Definition at line 319 of file types.hpp.
Referenced by getSecurityPolicyUri().
securityPolicyUri() [2/2]
String & opcua::ua::EndpointDescription::securityPolicyUri () inline noexcept
Definition at line 319 of file types.hpp.
getSecurityPolicyUri() [2/2]
String & opcua::ua::EndpointDescription::getSecurityPolicyUri () inline noexcept
Deprecated
Use securityPolicyUri instead
Definition at line 319 of file types.hpp.
userIdentityTokens() [1/2]
Span< const UserTokenPolicy > opcua::ua::EndpointDescription::userIdentityTokens () const inline noexcept
Definition at line 322 of file types.hpp.
Referenced by getSecurityPolicyUri().
userIdentityTokens() [2/2]
Span< UserTokenPolicy > opcua::ua::EndpointDescription::userIdentityTokens () inline noexcept
Definition at line 322 of file types.hpp.
getUserIdentityTokens() [1/2]
Span< const UserTokenPolicy > opcua::ua::EndpointDescription::getUserIdentityTokens () const inline noexcept
Deprecated
Use userIdentityTokens instead
Definition at line 322 of file types.hpp.
Referenced by getSecurityPolicyUri().
getUserIdentityTokens() [2/2]
Span< UserTokenPolicy > opcua::ua::EndpointDescription::getUserIdentityTokens () inline noexcept
Deprecated
Use userIdentityTokens instead
Definition at line 322 of file types.hpp.
transportProfileUri() [1/2]
const String & opcua::ua::EndpointDescription::transportProfileUri () const inline noexcept
Definition at line 323 of file types.hpp.
Referenced by getTransportProfileUri().
getTransportProfileUri() [1/2]
const String & opcua::ua::EndpointDescription::getTransportProfileUri () const inline noexcept
Deprecated
Use transportProfileUri instead
Definition at line 323 of file types.hpp.
Referenced by getTransportProfileUri().
transportProfileUri() [2/2]
String & opcua::ua::EndpointDescription::transportProfileUri () inline noexcept
Definition at line 323 of file types.hpp.
getTransportProfileUri() [2/2]
String & opcua::ua::EndpointDescription::getTransportProfileUri () inline noexcept
Deprecated
Use transportProfileUri instead
Definition at line 323 of file types.hpp.
securityLevel()
UA_Byte opcua::ua::EndpointDescription::securityLevel () const inline noexcept
Definition at line 324 of file types.hpp.
Referenced by getSecurityLevel().
getSecurityLevel()
UA_Byte opcua::ua::EndpointDescription::getSecurityLevel () const inline noexcept
Deprecated
Use securityLevel instead
Definition at line 324 of file types.hpp.
Referenced by getSecurityLevel().
TypeWrapper() [1/5]
opcua::TypeWrapper< T, Index >::TypeWrapper () constexpr default noexcept
TypeWrapper() [2/5]
opcua::TypeWrapper< T, Index >::TypeWrapper (const T & native) inline explicit constexpr
Constructor with native object (deep copy).
Definition at line 31 of file typewrapper.hpp.
TypeWrapper() [3/5]
opcua::TypeWrapper< T, Index >::TypeWrapper (T && native) inline constexpr noexcept
Constructor with native object (move rvalue).
Definition at line 35 of file typewrapper.hpp.
TypeWrapper() [4/5]
opcua::TypeWrapper< T, Index >::TypeWrapper (const TypeWrapper & other) inline constexpr
Copy constructor (deep copy).
Definition at line 43 of file typewrapper.hpp.
TypeWrapper() [5/5]
opcua::TypeWrapper< T, Index >::TypeWrapper (TypeWrapper && other) inline constexpr noexcept
Move constructor.
Definition at line 47 of file typewrapper.hpp.