open62541++: opcua::Result< T > Class Template Reference
opcua::Result< T > Class Template Reference
#include <Result.h>
Detailed Description
template<typename T>
class opcua::Result< T >
The template class Result encapsulates a StatusCode and optionally a value.
A result may have one of the following contents:
a value and a good or uncertain StatusCode
no value and a bad StatusCode
Result<void> is a template specialization containing only a StatusCode.
The design is inspired by:
C++ 23's std::expected type
Rust's Result type
Swift's Result enumeration
Examples
method/client_method_async.cpp.
Definition at line 53 of file Result.h.
Public Types
using ValueType = T
Public Member Functions
constexpr Result () noexcept(std::is_nothrow_default_constructible_v< T >)
constexpr Result (const T &value, StatusCode code=UA_STATUSCODE_GOOD) noexcept(std::is_nothrow_copy_constructible_v< T >)
constexpr Result (T &&value, StatusCode code=UA_STATUSCODE_GOOD) noexcept(std::is_nothrow_move_constructible_v< T >)
constexpr Result (BadResult error) noexcept
constexpr T * operator-> () noexcept
constexpr const T * operator-> () const noexcept
constexpr T & operator* () &noexcept
constexpr const T & operator* () const &noexcept
constexpr T && operator* () &&noexcept
constexpr const T && operator* () const &&noexcept
constexpr StatusCode code () const noexcept
constexpr operator bool () const noexcept
constexpr bool hasValue () const noexcept
constexpr T & value () &
constexpr const T & value () const &
constexpr T && value () &&
constexpr const T && value () const &&
template<typename U >
constexpr T valueOr (U &&defaultValue) const &
template<typename U >
constexpr T valueOr (U &&defaultValue) &&
template<typename F >
constexpr auto transform (F &&func) &
template<typename F >
constexpr auto transform (F &&func) const &
template<typename F >
constexpr auto transform (F &&func) &&
template<typename F >
constexpr auto transform (F &&func) const &&
template<typename F >
constexpr auto andThen (F &&func) &
template<typename F >
constexpr auto andThen (F &&func) const &
template<typename F >
constexpr auto andThen (F &&func) &&
template<typename F >
constexpr auto andThen (F &&func) const &&
template<typename F >
constexpr auto orElse (F &&func) &
template<typename F >
constexpr auto orElse (F &&func) const &
template<typename F >
constexpr auto orElse (F &&func) &&
template<typename F >
constexpr auto orElse (F &&func) const &&
Member Typedef Documentation
ValueType
template<typename T > using opcua::Result< T >::ValueType = T
Definition at line 55 of file Result.h.
Constructor & Destructor Documentation
Result() [1/4]
template<typename T > constexpr opcua::Result< T >::Result () inline constexpr noexcept
Default constructor (default-initialized value and good StatusCode).
Definition at line 60 of file Result.h.
Result() [2/4]
template<typename T > constexpr opcua::Result< T >::Result (const T & value, StatusCode code = UA_STATUSCODE_GOOD) inline constexpr noexcept
Construct a Result with a value and a StatusCode (good or uncertain).
Definition at line 69 of file Result.h.
Result() [3/4]
template<typename T > constexpr opcua::Result< T >::Result (T && value, StatusCode code = UA_STATUSCODE_GOOD) inline constexpr noexcept
Construct a Result with a value and a StatusCode (good or uncertain).
Definition at line 80 of file Result.h.
Result() [4/4]
template<typename T > constexpr opcua::Result< T >::Result (BadResult< T > error) inline constexpr noexcept
Create a Result with the given error.
Definition at line 91 of file Result.h.
Member Function Documentation
operator->() [1/2]
template<typename T > constexpr T * opcua::Result< T >::operator-> () inline constexpr noexcept
Get the value of the Result.
Accessing a Result without a value leads to undefined behavior.
Definition at line 101 of file Result.h.
operator->() [2/2]
template<typename T > constexpr const T * opcua::Result< T >::operator-> () const inline constexpr noexcept
Get the value of the Result.
Accessing a Result without a value leads to undefined behavior.
Definition at line 106 of file Result.h.
operator*() [1/4]
template<typename T > constexpr T & opcua::Result< T >::operator* () & inline constexpr noexcept
Get the value of the Result.
Accessing a Result without a value leads to undefined behavior.
Definition at line 114 of file Result.h.
operator*() [2/4]
template<typename T > constexpr const T & opcua::Result< T >::operator* () const & inline constexpr noexcept
Get the value of the Result.
Accessing a Result without a value leads to undefined behavior.
Definition at line 119 of file Result.h.
operator*() [3/4]
template<typename T > constexpr T && opcua::Result< T >::operator* () && inline constexpr noexcept
Get the value of the Result.
Accessing a Result without a value leads to undefined behavior.
Definition at line 124 of file Result.h.
operator*() [4/4]
template<typename T > constexpr const T && opcua::Result< T >::operator* () const && inline constexpr noexcept
Get the value of the Result.
Accessing a Result without a value leads to undefined behavior.
Definition at line 129 of file Result.h.
code()
template<typename T > constexpr StatusCode opcua::Result< T >::code () const inline constexpr noexcept
Get the StatusCode of the Result.
Definition at line 136 of file Result.h.
Referenced by opcua::services::browseAll(), and opcua::Result< void >::value().
operator bool()
template<typename T > constexpr opcua::Result< T >::operator bool () const inline explicit constexpr noexcept
Check if the Result has a value.
Definition at line 143 of file Result.h.
hasValue()
template<typename T > constexpr bool opcua::Result< T >::hasValue () const inline constexpr noexcept
Check if the Result has a value.
Definition at line 150 of file Result.h.
Referenced by opcua::Result< T >::operator bool(), and opcua::Result< void >::operator bool().
value() [1/4]
template<typename T > constexpr T & opcua::Result< T >::value () & inline constexpr
Get the value of the Result.
Exceptions
BadStatus If the Result does not have a value (bad StatusCode).
Definition at line 158 of file Result.h.
Referenced by opcua::services::browseAll().
value() [2/4]
template<typename T > constexpr const T & opcua::Result< T >::value () const & inline constexpr
Get the value of the Result.
Exceptions
BadStatus If the Result does not have a value (bad StatusCode).
Definition at line 164 of file Result.h.
value() [3/4]
template<typename T > constexpr T && opcua::Result< T >::value () && inline constexpr
Get the value of the Result.
Exceptions
BadStatus If the Result does not have a value (bad StatusCode).
Definition at line 170 of file Result.h.
value() [4/4]
template<typename T > constexpr const T && opcua::Result< T >::value () const && inline constexpr
Get the value of the Result.
Exceptions
BadStatus If the Result does not have a value (bad StatusCode).
Definition at line 176 of file Result.h.
valueOr() [1/2]
template<typename T > template<typename U > constexpr T opcua::Result< T >::valueOr (U && defaultValue) const & inline constexpr
Get the value of the Result or a default value.
The default value is returned in case of an bad StatusCode.
Definition at line 186 of file Result.h.
valueOr() [2/2]
template<typename T > template<typename U > constexpr T opcua::Result< T >::valueOr (U && defaultValue) && inline constexpr
Get the value of the Result or a default value.
The default value is returned in case of an bad StatusCode.
Definition at line 192 of file Result.h.
transform() [1/4]
template<typename T > template<typename F > constexpr auto opcua::Result< T >::transform (F && func) & inline constexpr
Transforms Result<T> to Result<U> using the given value transformation function.
The function is only applied if the Result has a value. Otherwise Result<U> with the same bad StatusCode is returned.
Parameters
func Callable with the signature U(T&&)
Definition at line 203 of file Result.h.
transform() [2/4]
template<typename T > template<typename F > constexpr auto opcua::Result< T >::transform (F && func) const & inline constexpr
Transforms Result<T> to Result<U> using the given value transformation function.
The function is only applied if the Result has a value. Otherwise Result<U> with the same bad StatusCode is returned.
Parameters
func Callable with the signature U(T&&)
Definition at line 209 of file Result.h.
transform() [3/4]
template<typename T > template<typename F > constexpr auto opcua::Result< T >::transform (F && func) && inline constexpr
Transforms Result<T> to Result<U> using the given value transformation function.
The function is only applied if the Result has a value. Otherwise Result<U> with the same bad StatusCode is returned.
Parameters
func Callable with the signature U(T&&)
Definition at line 215 of file Result.h.
transform() [4/4]
template<typename T > template<typename F > constexpr auto opcua::Result< T >::transform (F && func) const && inline constexpr
Transforms Result<T> to Result<U> using the given value transformation function.
The function is only applied if the Result has a value. Otherwise Result<U> with the same bad StatusCode is returned.
Parameters
func Callable with the signature U(T&&)
Definition at line 221 of file Result.h.
andThen() [1/4]
template<typename T > template<typename F > constexpr auto opcua::Result< T >::andThen (F && func) & inline constexpr
Transforms Result<T> to Result<U> using the given function.
The function is only applied if the Result has a value. Otherwise Result<U> with the same bad StatusCode is returned.
Parameters
func Callable with the signature Result<U>(T&&) or Result<U>(T&&, StatusCode)
Definition at line 232 of file Result.h.
andThen() [2/4]
template<typename T > template<typename F > constexpr auto opcua::Result< T >::andThen (F && func) const & inline constexpr
Transforms Result<T> to Result<U> using the given function.
The function is only applied if the Result has a value. Otherwise Result<U> with the same bad StatusCode is returned.
Parameters
func Callable with the signature Result<U>(T&&) or Result<U>(T&&, StatusCode)
Definition at line 238 of file Result.h.
andThen() [3/4]
template<typename T > template<typename F > constexpr auto opcua::Result< T >::andThen (F && func) && inline constexpr
Transforms Result<T> to Result<U> using the given function.
The function is only applied if the Result has a value. Otherwise Result<U> with the same bad StatusCode is returned.
Parameters
func Callable with the signature Result<U>(T&&) or Result<U>(T&&, StatusCode)
Definition at line 244 of file Result.h.
andThen() [4/4]
template<typename T > template<typename F > constexpr auto opcua::Result< T >::andThen (F && func) const && inline constexpr
Transforms Result<T> to Result<U> using the given function.
The function is only applied if the Result has a value. Otherwise Result<U> with the same bad StatusCode is returned.
Parameters
func Callable with the signature Result<U>(T&&) or Result<U>(T&&, StatusCode)
Definition at line 250 of file Result.h.
orElse() [1/4]
template<typename T > template<typename F > constexpr auto opcua::Result< T >::orElse (F && func) & inline constexpr
Transforms Result<T> with a bad StatusCode to Result<T> using the given function.
The function is only applied if the Result has no value. Otherwise the same Result<T> is returned.
Parameters
func Callable with the signature Result<T>(StatusCode)
Definition at line 261 of file Result.h.
orElse() [2/4]
template<typename T > template<typename F > constexpr auto opcua::Result< T >::orElse (F && func) const & inline constexpr
Transforms Result<T> with a bad StatusCode to Result<T> using the given function.
The function is only applied if the Result has no value. Otherwise the same Result<T> is returned.
Parameters
func Callable with the signature Result<T>(StatusCode)
Definition at line 267 of file Result.h.
orElse() [3/4]
template<typename T > template<typename F > constexpr auto opcua::Result< T >::orElse (F && func) && inline constexpr
Transforms Result<T> with a bad StatusCode to Result<T> using the given function.
The function is only applied if the Result has no value. Otherwise the same Result<T> is returned.
Parameters
func Callable with the signature Result<T>(StatusCode)
Definition at line 273 of file Result.h.
orElse() [4/4]
template<typename T > template<typename F > constexpr auto opcua::Result< T >::orElse (F && func) const && inline constexpr
Transforms Result<T> with a bad StatusCode to Result<T> using the given function.
The function is only applied if the Result has no value. Otherwise the same Result<T> is returned.
Parameters
func Callable with the signature Result<T>(StatusCode)
Definition at line 279 of file Result.h.