open62541++: opcua::LocalizedText Class Reference
opcua::LocalizedText Class Reference
Wrapper classes of UA_* types
UA_LocalizedText wrapper class.
#include <TypeWrapper.h>
Public Member Functions
LocalizedText (std::string_view text, std::string_view locale)
std::string getText () const
std::string_view getTextView () const
std::string getLocale () const
std::string_view getLocaleView () const
Public Member Functions inherited from opcua::TypeWrapper< UA_LocalizedText, UA_TYPES_LOCALIZEDTEXT >
TypeWrapper ()
TypeWrapper (const UA_LocalizedText &data)
Constructor with native UA_* type (deep copy).
TypeWrapper (UA_LocalizedText &&data) noexcept
Constructor with native UA_* type (move rvalue).
TypeWrapper (const TypeWrapper &other)
Copy constructor (deep copy).
TypeWrapper (TypeWrapper &&other) noexcept
Move constructor.
virtual ~TypeWrapper ()
TypeWrapper & operator= (const TypeWrapper &other)
Copy assignment (deep copy).
TypeWrapper & operator= (TypeWrapper &&other) noexcept
Move assignment.
operator UA_LocalizedText & () noexcept
Implicit conversion to wrapped object.
operator const UA_LocalizedText & () const noexcept
Implicit conversion to wrapped object.
UA_LocalizedText * operator-> () noexcept
Member access to wrapped object.
const UA_LocalizedText * operator-> () const noexcept
Member access to wrapped object.
void swap (TypeWrapper &other) noexcept
Swap wrapped objects.
UA_LocalizedText * handle () noexcept
Return pointer to wrapped object.
const UA_LocalizedText * handle () const noexcept
Return const pointer to wrapped object.
Additional Inherited Members
Public Types inherited from opcua::TypeWrapper< UA_LocalizedText, UA_TYPES_LOCALIZEDTEXT >
using TypeWrapperBase = TypeWrapper< UA_LocalizedText, typeIndex >
using UaType = UA_LocalizedText
Static Public Member Functions inherited from opcua::TypeWrapper< UA_LocalizedText, UA_TYPES_LOCALIZEDTEXT >
static constexpr uint16_t getTypeIndex ()
Get type as type index.
static constexpr Type getType ()
Get type as Type enum (only for builtin types).
static const UA_DataType * getDataType ()
Get type as UA_DataType object.
Protected Member Functions inherited from opcua::TypeWrapper< UA_LocalizedText, UA_TYPES_LOCALIZEDTEXT >
void init () noexcept
void clear () noexcept
void copy (const UA_LocalizedText &data)
Static Protected Member Functions inherited from opcua::TypeWrapper< UA_LocalizedText, UA_TYPES_LOCALIZEDTEXT >
static void checkMemSize ()
Detailed Description
UA_LocalizedText wrapper class.
Definition at line 291 of file TypeWrapper.h.
Constructor & Destructor Documentation
LocalizedText()
opcua::LocalizedText::LocalizedText (std::string_view text, std::string_view locale)
Definition at line 76 of file TypeWrapper.cpp.
References opcua::detail::allocUaString().
Member Function Documentation
getLocale()
std::string opcua::LocalizedText::getLocale () const
Definition at line 87 of file TypeWrapper.cpp.
References opcua::TypeWrapper< UA_LocalizedText, UA_TYPES_LOCALIZEDTEXT >::handle(), and opcua::detail::toString().
getLocaleView()
std::string_view opcua::LocalizedText::getLocaleView () const
Definition at line 91 of file TypeWrapper.cpp.
References opcua::TypeWrapper< UA_LocalizedText, UA_TYPES_LOCALIZEDTEXT >::handle(), and opcua::detail::toStringView().
getText()
std::string opcua::LocalizedText::getText () const
Definition at line 79 of file TypeWrapper.cpp.
References opcua::TypeWrapper< UA_LocalizedText, UA_TYPES_LOCALIZEDTEXT >::handle(), and opcua::detail::toString().
getTextView()
std::string_view opcua::LocalizedText::getTextView () const
Definition at line 83 of file TypeWrapper.cpp.
References opcua::TypeWrapper< UA_LocalizedText, UA_TYPES_LOCALIZEDTEXT >::handle(), and opcua::detail::toStringView().