open62541++: opcua::Guid Class Reference
opcua::Guid Class Reference
UA_Guid wrapper class.
#include <TypeWrapper.h>
Public Member Functions
Guid (UA_UInt32 data1, UA_UInt16 data2, UA_UInt16 data3, std::array< UA_Byte, 8 > data4)
bool operator== (const Guid &other) const noexcept
bool operator!= (const Guid &other) const noexcept
Public Member Functions inherited from opcua::TypeWrapper< UA_Guid >
TypeWrapper ()
TypeWrapper (const UA_Guid &data)
Constructor with native UA_* type (deep copy)
TypeWrapper (UA_Guid &&data) noexcept
Constructor with native UA_* type (move rvalue)
TypeWrapper (const TypeWrapper &other)
Copy constructor (deep copy)
TypeWrapper (TypeWrapper &&other) noexcept
Move constructor.
virtual ~TypeWrapper ()
TypeWrapper & operator= (const TypeWrapper &other)
Copy assignment (deep copy)
TypeWrapper & operator= (TypeWrapper &&other) noexcept
Move assignment.
UA_Guid * handle () noexcept
Return pointer to wrapped UA data type.
const UA_Guid * handle () const noexcept
Return const pointer to wrapped UA data type.
Additional Inherited Members
Public Types inherited from opcua::TypeWrapper< UA_Guid >
using BaseClass = TypeWrapper< UA_Guid, getType< UA_Guid >() >
using UaType = UA_Guid
Static Public Member Functions inherited from opcua::TypeWrapper< UA_Guid >
constexpr static Type getType ()
Return type enum.
constexpr static const UA_DataType * getDataType ()
Return UA_DataType object.
Protected Member Functions inherited from opcua::TypeWrapper< UA_Guid >
void init () noexcept
void clear () noexcept
void set (const UA_Guid &data)
void set (UA_Guid &&data)
Detailed Description
UA_Guid wrapper class.
Definition at line 141 of file TypeWrapper.h.
Constructor & Destructor Documentation
Guid()
opcua::Guid::Guid (UA_UInt32 data1, UA_UInt16 data2, UA_UInt16 data3, std::array< UA_Byte, 8 > data4) inline
Definition at line 145 of file TypeWrapper.h.
Member Function Documentation
operator!=()
bool opcua::Guid::operator!= (const Guid & other) const inline noexcept
Definition at line 157 of file TypeWrapper.h.
References operator==().
operator==()
bool opcua::Guid::operator== (const Guid & other) const inline noexcept
Definition at line 153 of file TypeWrapper.h.
References opcua::TypeWrapper< UA_Guid >::handle(), and UA_Guid_equal().
Referenced by operator!=().
The documentation for this class was generated from the following file:
/home/runner/work/open62541pp/open62541pp/include/open62541pp/TypeWrapper.h