open62541++: opcua::XmlElement Class Reference
opcua::XmlElement Class Reference
Wrapper classes of UA_* types
UA_XmlElement wrapper class.
#include <TypeWrapper.h>
Public Member Functions
XmlElement (std::string_view str)
std::string get () const
std::string_view getView () const
Public Member Functions inherited from opcua::TypeWrapper< UA_XmlElement, UA_TYPES_XMLELEMENT >
TypeWrapper ()
TypeWrapper (const UA_XmlElement &data)
Constructor with native UA_* type (deep copy).
TypeWrapper (UA_XmlElement &&data) noexcept
Constructor with native UA_* type (move rvalue).
TypeWrapper (const TypeWrapper &other)
Copy constructor (deep copy).
TypeWrapper (TypeWrapper &&other) noexcept
Move constructor.
virtual ~TypeWrapper ()
TypeWrapper & operator= (const TypeWrapper &other)
Copy assignment (deep copy).
TypeWrapper & operator= (TypeWrapper &&other) noexcept
Move assignment.
operator UA_XmlElement & () noexcept
Implicit conversion to wrapped UA data type.
operator const UA_XmlElement & () const noexcept
Implicit conversion to wrapped UA data type.
void swap (TypeWrapper &other) noexcept
Swap wrapper objects.
UA_XmlElement * handle () noexcept
Return pointer to wrapped UA data type.
const UA_XmlElement * handle () const noexcept
Return const pointer to wrapped UA data type.
Additional Inherited Members
Public Types inherited from opcua::TypeWrapper< UA_XmlElement, UA_TYPES_XMLELEMENT >
using TypeWrapperBase = TypeWrapper< UA_XmlElement, typeIndex >
using UaType = UA_XmlElement
Static Public Member Functions inherited from opcua::TypeWrapper< UA_XmlElement, UA_TYPES_XMLELEMENT >
static constexpr uint16_t getTypeIndex ()
Get type as type index.
static constexpr Type getType ()
Get type as Type enum (only for builtin types).
static const UA_DataType * getDataType ()
Get type as UA_DataType object.
Protected Member Functions inherited from opcua::TypeWrapper< UA_XmlElement, UA_TYPES_XMLELEMENT >
void init () noexcept
void clear () noexcept
void copy (const UA_XmlElement &data)
Static Protected Member Functions inherited from opcua::TypeWrapper< UA_XmlElement, UA_TYPES_XMLELEMENT >
static void checkMemSize ()
Detailed Description
UA_XmlElement wrapper class.
Definition at line 250 of file TypeWrapper.h.
Constructor & Destructor Documentation
XmlElement()
opcua::XmlElement::XmlElement (std::string_view str) explicit
Definition at line 46 of file TypeWrapper.cpp.
References opcua::detail::allocUaString().
Member Function Documentation
get()
std::string opcua::XmlElement::get () const
Definition at line 49 of file TypeWrapper.cpp.
References opcua::TypeWrapper< UA_XmlElement, UA_TYPES_XMLELEMENT >::handle(), and opcua::detail::toString().
getView()
std::string_view opcua::XmlElement::getView () const
Definition at line 53 of file TypeWrapper.cpp.
References opcua::TypeWrapper< UA_XmlElement, UA_TYPES_XMLELEMENT >::handle(), and opcua::detail::toStringView().