open62541pp: opcua::Node< Connection > Class Template Reference
opcua::Node< Connection > Class Template Reference
#include <node.hpp>
Detailed Description
template<typename Connection>
class opcua::Node< Connection >
High-level node class to access node attribute, browse and populate address space.
The Node API is just a more convenient way of using the free functions in the opcua::services namespace.
Node objects are useful as-is but they do not expose the entire OPC UA protocol. You can get access to the associated NodeId instance with the Node::id() method and apply the native open62541 functions or the free functions in the opcua::services namespace.
Note
The async functions are available for Client only.
Template Parameters
Connection Server or Client
See also
Services
Examples
client_browse.cpp, client_connect.cpp, client_minimal.cpp, custom_datatypes/client_custom_datatypes.cpp, custom_datatypes/server_custom_datatypes.cpp, events/server_events.cpp, method/client_method.cpp, method/client_method_async.cpp, method/server_method.cpp, server.cpp, server_accesscontrol.cpp, server_instantiation.cpp, server_minimal.cpp, and server_valuecallback.cpp.
Definition at line 45 of file node.hpp.
Public Member Functions
Node (Connection &connection, const NodeId &id)
Node (Connection &connection, NodeId &&id)
Connection & connection () noexcept
const Connection & connection () const noexcept
const NodeId & id () const noexcept
bool exists () noexcept
NodeManagement
Node addFolder (const NodeId &id, std::string_view browseName, const ObjectAttributes &attributes={}, const NodeId &referenceType=ReferenceTypeId::HasComponent)
template<typename CompletionToken = DefaultCompletionToken>
auto addFolderAsync (const NodeId &id, std::string_view browseName, const ObjectAttributes &attributes={}, const NodeId &referenceType=ReferenceTypeId::HasComponent, CompletionToken &&token=DefaultCompletionToken())
Node addObject (const NodeId &id, std::string_view browseName, const ObjectAttributes &attributes={}, const NodeId &objectType=ObjectTypeId::BaseObjectType, const NodeId &referenceType=ReferenceTypeId::HasComponent)
template<typename CompletionToken = DefaultCompletionToken>
auto addObjectAsync (const NodeId &id, std::string_view browseName, const ObjectAttributes &attributes={}, const NodeId &objectType=ObjectTypeId::BaseObjectType, const NodeId &referenceType=ReferenceTypeId::HasComponent, CompletionToken &&token=DefaultCompletionToken())
Node addVariable (const NodeId &id, std::string_view browseName, const VariableAttributes &attributes={}, const NodeId &variableType=VariableTypeId::BaseDataVariableType, const NodeId &referenceType=ReferenceTypeId::HasComponent)
template<typename CompletionToken = DefaultCompletionToken>
auto addVariableAsync (const NodeId &id, std::string_view browseName, const VariableAttributes &attributes={}, const NodeId &variableType=VariableTypeId::BaseDataVariableType, const NodeId &referenceType=ReferenceTypeId::HasComponent, CompletionToken &&token=DefaultCompletionToken())
Node addProperty (const NodeId &id, std::string_view browseName, const VariableAttributes &attributes={})
template<typename CompletionToken = DefaultCompletionToken>
auto addPropertyAsync (const NodeId &id, std::string_view browseName, const VariableAttributes &attributes={}, CompletionToken &&token=DefaultCompletionToken())
Node addMethod (const NodeId &id, std::string_view browseName, services::MethodCallback callback, Span< const Argument > inputArguments, Span< const Argument > outputArguments, const MethodAttributes &attributes={}, const NodeId &referenceType=ReferenceTypeId::HasComponent)
template<typename CompletionToken = DefaultCompletionToken>
auto addMethodAsync (const NodeId &id, std::string_view browseName, services::MethodCallback callback, Span< const Argument > inputArguments, Span< const Argument > outputArguments, const MethodAttributes &attributes={}, const NodeId &referenceType=ReferenceTypeId::HasComponent, CompletionToken &&token=DefaultCompletionToken())
Node addObjectType (const NodeId &id, std::string_view browseName, const ObjectTypeAttributes &attributes={}, const NodeId &referenceType=ReferenceTypeId::HasSubtype)
template<typename CompletionToken = DefaultCompletionToken>
auto addObjectTypeAsync (const NodeId &id, std::string_view browseName, const ObjectTypeAttributes &attributes={}, const NodeId &referenceType=ReferenceTypeId::HasSubtype, CompletionToken &&token=DefaultCompletionToken())
Node addVariableType (const NodeId &id, std::string_view browseName, const VariableTypeAttributes &attributes={}, const NodeId &variableType=VariableTypeId::BaseDataVariableType, const NodeId &referenceType=ReferenceTypeId::HasSubtype)
template<typename CompletionToken = DefaultCompletionToken>
auto addVariableTypeAsync (const NodeId &id, std::string_view browseName, const VariableTypeAttributes &attributes={}, const NodeId &variableType=VariableTypeId::BaseDataVariableType, const NodeId &referenceType=ReferenceTypeId::HasSubtype, CompletionToken &&token=DefaultCompletionToken())
Node addReferenceType (const NodeId &id, std::string_view browseName, const ReferenceTypeAttributes &attributes={}, const NodeId &referenceType=ReferenceTypeId::HasSubtype)
template<typename CompletionToken = DefaultCompletionToken>
auto addReferenceTypeAsync (const NodeId &id, std::string_view browseName, const ReferenceTypeAttributes &attributes={}, const NodeId &referenceType=ReferenceTypeId::HasSubtype, CompletionToken &&token=DefaultCompletionToken())
Node addDataType (const NodeId &id, std::string_view browseName, const DataTypeAttributes &attributes={}, const NodeId &referenceType=ReferenceTypeId::HasSubtype)
template<typename CompletionToken = DefaultCompletionToken>
auto addDataTypeAsync (const NodeId &id, std::string_view browseName, const DataTypeAttributes &attributes={}, const NodeId &referenceType=ReferenceTypeId::HasSubtype, CompletionToken &&token=DefaultCompletionToken())
Node addView (const NodeId &id, std::string_view browseName, const ViewAttributes &attributes={}, const NodeId &referenceType=ReferenceTypeId::Organizes)
template<typename CompletionToken = DefaultCompletionToken>
auto addViewAsync (const NodeId &id, std::string_view browseName, const ViewAttributes &attributes={}, const NodeId &referenceType=ReferenceTypeId::Organizes, CompletionToken &&token=DefaultCompletionToken())
Node & addReference (const NodeId &targetId, const NodeId &referenceType, bool forward=true)
template<typename CompletionToken = DefaultCompletionToken>
auto addReferenceAsync (const NodeId &targetId, const NodeId &referenceType, bool forward=true, CompletionToken &&token=DefaultCompletionToken())
Node & addModellingRule (ModellingRule rule)
template<typename CompletionToken = DefaultCompletionToken>
auto addModellingRuleAsync (ModellingRule rule, CompletionToken &&token=DefaultCompletionToken())
void deleteNode (bool deleteReferences=true)
template<typename CompletionToken = DefaultCompletionToken>
auto deleteNodeAsync (bool deleteReferences=true, CompletionToken &&token=DefaultCompletionToken())
Node & deleteReference (const NodeId &targetId, const NodeId &referenceType, bool isForward=true, bool deleteBidirectional=true)
template<typename CompletionToken = DefaultCompletionToken>
auto deleteReferenceAsync (const NodeId &targetId, const NodeId &referenceType, bool isForward=true, bool deleteBidirectional=true, CompletionToken &&token=DefaultCompletionToken())
View
std::vector< ReferenceDescription > browseReferences (BrowseDirection browseDirection=BrowseDirection::Both, const NodeId &referenceType=ReferenceTypeId::References, bool includeSubtypes=true, Bitmask< NodeClass > nodeClassMask=NodeClass::Unspecified)
std::vector< Node > browseReferencedNodes (BrowseDirection browseDirection=BrowseDirection::Both, const NodeId &referenceType=ReferenceTypeId::References, bool includeSubtypes=true, Bitmask< NodeClass > nodeClassMask=NodeClass::Unspecified)
std::vector< Node > browseChildren (const NodeId &referenceType=ReferenceTypeId::HierarchicalReferences, Bitmask< NodeClass > nodeClassMask=NodeClass::Unspecified)
Node browseChild (Span< const QualifiedName > path)
Node browseParent ()
Method
CallMethodResult callMethod (const NodeId &methodId, Span< const Variant > inputArguments)
template<typename CompletionToken = DefaultCompletionToken>
auto callMethodAsync (const NodeId &methodId, Span< const Variant > inputArguments, CompletionToken &&token=DefaultCompletionToken())
Attribute
NodeClass readNodeClass ()
template<typename CompletionToken = DefaultCompletionToken>
auto readNodeClassAsync (CompletionToken &&token=DefaultCompletionToken())
QualifiedName readBrowseName ()
template<typename CompletionToken = DefaultCompletionToken>
auto readBrowseNameAsync (CompletionToken &&token=DefaultCompletionToken())
LocalizedText readDisplayName ()
template<typename CompletionToken = DefaultCompletionToken>
auto readDisplayNameAsync (CompletionToken &&token=DefaultCompletionToken())
LocalizedText readDescription ()
template<typename CompletionToken = DefaultCompletionToken>
auto readDescriptionAsync (CompletionToken &&token=DefaultCompletionToken())
Bitmask< WriteMask > readWriteMask ()
template<typename CompletionToken = DefaultCompletionToken>
auto readWriteMaskAsync (CompletionToken &&token=DefaultCompletionToken())
Bitmask< WriteMask > readUserWriteMask ()
template<typename CompletionToken = DefaultCompletionToken>
auto readUserWriteMaskAsync (CompletionToken &&token=DefaultCompletionToken())
bool readIsAbstract ()
template<typename CompletionToken = DefaultCompletionToken>
auto readIsAbstractAsync (CompletionToken &&token=DefaultCompletionToken())
bool readSymmetric ()
template<typename CompletionToken = DefaultCompletionToken>
auto readSymmetricAsync (CompletionToken &&token=DefaultCompletionToken())
LocalizedText readInverseName ()
template<typename CompletionToken = DefaultCompletionToken>
auto readInverseNameAsync (CompletionToken &&token=DefaultCompletionToken())
bool readContainsNoLoops ()
template<typename CompletionToken = DefaultCompletionToken>
auto readContainsNoLoopsAsync (CompletionToken &&token=DefaultCompletionToken())
Bitmask< EventNotifier > readEventNotifier ()
template<typename CompletionToken = DefaultCompletionToken>
auto readEventNotifierAsync (CompletionToken &&token=DefaultCompletionToken())
DataValue readDataValue ()
template<typename CompletionToken = DefaultCompletionToken>
auto readDataValueAsync (CompletionToken &&token=DefaultCompletionToken())
Variant readValue ()
template<typename CompletionToken = DefaultCompletionToken>
auto readValueAsync (CompletionToken &&token=DefaultCompletionToken())
template<typename T >
T readValueScalar ()
template<typename T >
std::vector< T > readValueArray ()
NodeId readDataType ()
template<typename CompletionToken = DefaultCompletionToken>
auto readDataTypeAsync (CompletionToken &&token=DefaultCompletionToken())
ValueRank readValueRank ()
template<typename CompletionToken = DefaultCompletionToken>
auto readValueRankAsync (CompletionToken &&token=DefaultCompletionToken())
std::vector< uint32_t > readArrayDimensions ()
template<typename CompletionToken = DefaultCompletionToken>
auto readArrayDimensionsAsync (CompletionToken &&token=DefaultCompletionToken())
Bitmask< AccessLevel > readAccessLevel ()
template<typename CompletionToken = DefaultCompletionToken>
auto readAccessLevelAsync (CompletionToken &&token=DefaultCompletionToken())
Bitmask< AccessLevel > readUserAccessLevel ()
template<typename CompletionToken = DefaultCompletionToken>
auto readUserAccessLevelAsync (CompletionToken &&token=DefaultCompletionToken())
double readMinimumSamplingInterval ()
template<typename CompletionToken = DefaultCompletionToken>
auto readMinimumSamplingIntervalAsync (CompletionToken &&token=DefaultCompletionToken())
bool readHistorizing ()
template<typename CompletionToken = DefaultCompletionToken>
auto readHistorizingAsync (CompletionToken &&token=DefaultCompletionToken())
bool readExecutable ()
template<typename CompletionToken = DefaultCompletionToken>
auto readExecutableAsync (CompletionToken &&token=DefaultCompletionToken())
bool readUserExecutable ()
template<typename CompletionToken = DefaultCompletionToken>
auto readUserExecutableAsync (CompletionToken &&token=DefaultCompletionToken())
Variant readDataTypeDefinition ()
template<typename CompletionToken = DefaultCompletionToken>
auto readDataTypeDefinitionAsync (CompletionToken &&token=DefaultCompletionToken())
Variant readObjectProperty (const QualifiedName &propertyName)
Node & writeDisplayName (const LocalizedText &displayName)
template<typename CompletionToken = DefaultCompletionToken>
auto writeDisplayNameAsync (const LocalizedText &displayName, CompletionToken &&token=DefaultCompletionToken())
Node & writeDescription (const LocalizedText &description)
template<typename CompletionToken = DefaultCompletionToken>
auto writeDescriptionAsync (const LocalizedText &description, CompletionToken &&token=DefaultCompletionToken())
Node & writeWriteMask (Bitmask< WriteMask > writeMask)
template<typename CompletionToken = DefaultCompletionToken>
auto writeWriteMaskAsync (Bitmask< WriteMask > writeMask, CompletionToken &&token=DefaultCompletionToken())
Node & writeUserWriteMask (Bitmask< WriteMask > userWriteMask)
template<typename CompletionToken = DefaultCompletionToken>
auto writeUserWriteMaskAsync (Bitmask< WriteMask > userWriteMask, CompletionToken &&token=DefaultCompletionToken())
Node & writeIsAbstract (bool isAbstract)
template<typename CompletionToken = DefaultCompletionToken>
auto writeIsAbstractAsync (bool isAbstract, CompletionToken &&token=DefaultCompletionToken())
Node & writeSymmetric (bool symmetric)
template<typename CompletionToken = DefaultCompletionToken>
auto writeSymmetricAsync (bool symmetric, CompletionToken &&token=DefaultCompletionToken())
Node & writeInverseName (const LocalizedText &inverseName)
template<typename CompletionToken = DefaultCompletionToken>
auto writeInverseNameAsync (const LocalizedText &inverseName, CompletionToken &&token=DefaultCompletionToken())
Node & writeContainsNoLoops (bool containsNoLoops)
template<typename CompletionToken = DefaultCompletionToken>
auto writeContainsNoLoopsAsync (bool containsNoLoops, CompletionToken &&token=DefaultCompletionToken())
Node & writeEventNotifier (Bitmask< EventNotifier > eventNotifier)
template<typename CompletionToken = DefaultCompletionToken>
auto writeEventNotifierAsync (Bitmask< EventNotifier > eventNotifier, CompletionToken &&token=DefaultCompletionToken())
Node & writeDataValue (const DataValue &value)
template<typename CompletionToken = DefaultCompletionToken>
auto writeDataValueAsync (const DataValue &value, CompletionToken &&token=DefaultCompletionToken())
Node & writeValue (const Variant &value)
template<typename CompletionToken = DefaultCompletionToken>
auto writeValueAsync (const Variant &value, CompletionToken &&token=DefaultCompletionToken())
template<typename T >
Node & writeValueScalar (const T &value)
template<typename ArrayLike >
Node & writeValueArray (const ArrayLike &array)
template<typename InputIt >
Node & writeValueArray (InputIt first, InputIt last)
Node & writeDataType (const NodeId &dataType)
template<typename T >
Node & writeDataType ()
template<typename CompletionToken = DefaultCompletionToken>
auto writeDataTypeAsync (const NodeId &dataType, CompletionToken &&token=DefaultCompletionToken())
Node & writeValueRank (ValueRank valueRank)
template<typename CompletionToken = DefaultCompletionToken>
auto writeValueRankAsync (ValueRank valueRank, CompletionToken &&token=DefaultCompletionToken())
Node & writeArrayDimensions (Span< const uint32_t > dimensions)
template<typename CompletionToken = DefaultCompletionToken>
auto writeArrayDimensionsAsync (Span< const uint32_t > dimensions, CompletionToken &&token=DefaultCompletionToken())
Node & writeAccessLevel (Bitmask< AccessLevel > accessLevel)
template<typename CompletionToken = DefaultCompletionToken>
auto writeAccessLevelAsync (Bitmask< AccessLevel > accessLevel, CompletionToken &&token=DefaultCompletionToken())
Node & writeUserAccessLevel (Bitmask< AccessLevel > userAccessLevel)
template<typename CompletionToken = DefaultCompletionToken>
auto writeUserAccessLevelAsync (Bitmask< AccessLevel > userAccessLevel, CompletionToken &&token=DefaultCompletionToken())
Node & writeMinimumSamplingInterval (double milliseconds)
template<typename CompletionToken = DefaultCompletionToken>
auto writeMinimumSamplingIntervalAsync (double milliseconds, CompletionToken &&token=DefaultCompletionToken())
Node & writeHistorizing (bool historizing)
template<typename CompletionToken = DefaultCompletionToken>
auto writeHistorizingAsync (bool historizing, CompletionToken &&token=DefaultCompletionToken())
Node & writeExecutable (bool executable)
template<typename CompletionToken = DefaultCompletionToken>
auto writeExecutableAsync (bool executable, CompletionToken &&token=DefaultCompletionToken())
Node & writeUserExecutable (bool userExecutable)
template<typename CompletionToken = DefaultCompletionToken>
auto writeUserExecutableAsync (bool userExecutable, CompletionToken &&token=DefaultCompletionToken())
Node & writeObjectProperty (const QualifiedName &propertyName, const Variant &value)
Related Symbols
(Note that these are not member symbols.)
template<typename Connection >
bool operator== (const Node< Connection > &lhs, const Node< Connection > &rhs) noexcept
template<typename Connection >
bool operator!= (const Node< Connection > &lhs, const Node< Connection > &rhs) noexcept
Constructor & Destructor Documentation
Node() [1/2]
template<typename Connection > opcua::Node< Connection >::Node (Connection & connection, const NodeId & id) inline
Create a Node object.
Definition at line 48 of file node.hpp.
Node() [2/2]
template<typename Connection > opcua::Node< Connection >::Node (Connection & connection, NodeId && id) inline
Create a Node object.
Definition at line 53 of file node.hpp.
Member Function Documentation
connection() [1/2]
template<typename Connection > Connection & opcua::Node< Connection >::connection () inline noexcept
Get the server/client instance.
Definition at line 58 of file node.hpp.
Referenced by opcua::Node< Connection >::addModellingRule(), opcua::Node< Connection >::addModellingRuleAsync(), opcua::Node< Connection >::addReference(), opcua::Node< Connection >::addReferenceAsync(), opcua::Node< Connection >::browseChild(), opcua::Node< Connection >::browseParent(), opcua::Node< Connection >::browseReferencedNodes(), opcua::Node< Connection >::browseReferences(), opcua::Node< Connection >::callMethod(), opcua::Node< Connection >::callMethodAsync(), opcua::Node< Connection >::deleteNode(), opcua::Node< Connection >::deleteNodeAsync(), opcua::Node< Connection >::deleteReference(), opcua::Node< Connection >::deleteReferenceAsync(), opcua::Node< Connection >::readAccessLevel(), opcua::Node< Connection >::readAccessLevelAsync(), opcua::Node< Connection >::readArrayDimensions(), opcua::Node< Connection >::readArrayDimensionsAsync(), opcua::Node< Connection >::readBrowseName(), opcua::Node< Connection >::readBrowseNameAsync(), opcua::Node< Connection >::readContainsNoLoops(), opcua::Node< Connection >::readContainsNoLoopsAsync(), opcua::Node< Connection >::readDataType(), opcua::Node< Connection >::readDataTypeAsync(), opcua::Node< Connection >::readDataTypeDefinition(), opcua::Node< Connection >::readDataTypeDefinitionAsync(), opcua::Node< Connection >::readDataValue(), opcua::Node< Connection >::readDataValueAsync(), opcua::Node< Connection >::readDescription(), opcua::Node< Connection >::readDescriptionAsync(), opcua::Node< Connection >::readDisplayName(), opcua::Node< Connection >::readDisplayNameAsync(), opcua::Node< Connection >::readEventNotifier(), opcua::Node< Connection >::readEventNotifierAsync(), opcua::Node< Connection >::readExecutable(), opcua::Node< Connection >::readExecutableAsync(), opcua::Node< Connection >::readHistorizing(), opcua::Node< Connection >::readHistorizingAsync(), opcua::Node< Connection >::readInverseName(), opcua::Node< Connection >::readInverseNameAsync(), opcua::Node< Connection >::readIsAbstract(), opcua::Node< Connection >::readIsAbstractAsync(), opcua::Node< Connection >::readMinimumSamplingInterval(), opcua::Node< Connection >::readMinimumSamplingIntervalAsync(), opcua::Node< Connection >::readNodeClass(), opcua::Node< Connection >::readNodeClassAsync(), opcua::Node< Connection >::readSymmetric(), opcua::Node< Connection >::readSymmetricAsync(), opcua::Node< Connection >::readUserAccessLevel(), opcua::Node< Connection >::readUserAccessLevelAsync(), opcua::Node< Connection >::readUserExecutable(), opcua::Node< Connection >::readUserExecutableAsync(), opcua::Node< Connection >::readUserWriteMask(), opcua::Node< Connection >::readUserWriteMaskAsync(), opcua::Node< Connection >::readValue(), opcua::Node< Connection >::readValueAsync(), opcua::Node< Connection >::readValueRank(), opcua::Node< Connection >::readValueRankAsync(), opcua::Node< Connection >::readWriteMask(), opcua::Node< Connection >::readWriteMaskAsync(), opcua::Node< Connection >::writeAccessLevel(), opcua::Node< Connection >::writeAccessLevelAsync(), opcua::Node< Connection >::writeArrayDimensions(), opcua::Node< Connection >::writeArrayDimensionsAsync(), opcua::Node< Connection >::writeContainsNoLoops(), opcua::Node< Connection >::writeContainsNoLoopsAsync(), opcua::Node< Connection >::writeDataType(), opcua::Node< Connection >::writeDataTypeAsync(), opcua::Node< Connection >::writeDataValue(), opcua::Node< Connection >::writeDataValueAsync(), opcua::Node< Connection >::writeDescription(), opcua::Node< Connection >::writeDescriptionAsync(), opcua::Node< Connection >::writeDisplayName(), opcua::Node< Connection >::writeDisplayNameAsync(), opcua::Node< Connection >::writeEventNotifier(), opcua::Node< Connection >::writeEventNotifierAsync(), opcua::Node< Connection >::writeExecutable(), opcua::Node< Connection >::writeExecutableAsync(), opcua::Node< Connection >::writeHistorizing(), opcua::Node< Connection >::writeHistorizingAsync(), opcua::Node< Connection >::writeInverseName(), opcua::Node< Connection >::writeInverseNameAsync(), opcua::Node< Connection >::writeIsAbstract(), opcua::Node< Connection >::writeIsAbstractAsync(), opcua::Node< Connection >::writeMinimumSamplingInterval(), opcua::Node< Connection >::writeMinimumSamplingIntervalAsync(), opcua::Node< Connection >::writeSymmetric(), opcua::Node< Connection >::writeSymmetricAsync(), opcua::Node< Connection >::writeUserAccessLevel(), opcua::Node< Connection >::writeUserAccessLevelAsync(), opcua::Node< Connection >::writeUserExecutable(), opcua::Node< Connection >::writeUserExecutableAsync(), opcua::Node< Connection >::writeUserWriteMask(), opcua::Node< Connection >::writeUserWriteMaskAsync(), opcua::Node< Connection >::writeValue(), opcua::Node< Connection >::writeValueAsync(), opcua::Node< Connection >::writeValueRank(), opcua::Node< Connection >::writeValueRankAsync(), opcua::Node< Connection >::writeWriteMask(), and opcua::Node< Connection >::writeWriteMaskAsync().
connection() [2/2]
template<typename Connection > const Connection & opcua::Node< Connection >::connection () const inline noexcept
Get the server/client instance.
Definition at line 63 of file node.hpp.
id()
template<typename Connection > const NodeId & opcua::Node< Connection >::id () const inline noexcept
Get the node id.
Examples
method/client_method.cpp, and method/client_method_async.cpp.
Definition at line 68 of file node.hpp.
exists()
template<typename Connection > bool opcua::Node< Connection >::exists () noexcept
Check if the Node exists in the most efficient manner.
If the instance is of type Node<Server>, the internal node store is searched. If the instance is of type Node<Client>, an actual read request to the server is made.
addFolder()
template<typename Connection > Node opcua::Node< Connection >::addFolder (const NodeId & id, std::string_view browseName, const ObjectAttributes & attributes = {}, const NodeId & referenceType = ReferenceTypeId::HasComponent) inline
Add folder.
See also
services::addFolder
Definition at line 81 of file node.hpp.
addFolderAsync()
template<typename Connection > template<typename CompletionToken = DefaultCompletionToken> auto opcua::Node< Connection >::addFolderAsync (const NodeId & id, std::string_view browseName, const ObjectAttributes & attributes = {}, const NodeId & referenceType = ReferenceTypeId::HasComponent, CompletionToken && token = DefaultCompletionToken()) inline
Add folder.
See also
services::addFolder
Parameters
token The completion token that will be used to produce a completion handler, which will be called when the operation completes. Potential completion tokens include useFuture, useDeferred, useDetached, or a function (object) with the correct completion signature. The function signature of the completion handler must be:
void(Result<Node>&)
Returns
void if token is a callback function (object)
std::future<Result<Node>> if token is of type UseFutureToken
auto(auto&& token) callable for deferred execution if token is of type UseDeferredToken
void if token is of type UseDetachedToken
Definition at line 97 of file node.hpp.
addObject()
template<typename Connection > Node opcua::Node< Connection >::addObject (const NodeId & id, std::string_view browseName, const ObjectAttributes & attributes = {}, const NodeId & objectType = ObjectTypeId::BaseObjectType, const NodeId & referenceType = ReferenceTypeId::HasComponent) inline
Add object.
See also
services::addObject
Examples
server_instantiation.cpp.
Definition at line 116 of file node.hpp.
addObjectAsync()
template<typename Connection > template<typename CompletionToken = DefaultCompletionToken> auto opcua::Node< Connection >::addObjectAsync (const NodeId & id, std::string_view browseName, const ObjectAttributes & attributes = {}, const NodeId & objectType = ObjectTypeId::BaseObjectType, const NodeId & referenceType = ReferenceTypeId::HasComponent, CompletionToken && token = DefaultCompletionToken()) inline
Add object.
See also
services::addObjectAsync
Parameters
token The completion token that will be used to produce a completion handler, which will be called when the operation completes. Potential completion tokens include useFuture, useDeferred, useDetached, or a function (object) with the correct completion signature. The function signature of the completion handler must be:
void(Result<Node>&)
Returns
void if token is a callback function (object)
std::future<Result<Node>> if token is of type UseFutureToken
auto(auto&& token) callable for deferred execution if token is of type UseDeferredToken
void if token is of type UseDetachedToken
Definition at line 135 of file node.hpp.
addVariable()
template<typename Connection > Node opcua::Node< Connection >::addVariable (const NodeId & id, std::string_view browseName, const VariableAttributes & attributes = {}, const NodeId & variableType = VariableTypeId::BaseDataVariableType, const NodeId & referenceType = ReferenceTypeId::HasComponent) inline
Add variable.
See also
services::addVariable
Examples
custom_datatypes/server_custom_datatypes.cpp, server.cpp, server_accesscontrol.cpp, server_instantiation.cpp, server_minimal.cpp, and server_valuecallback.cpp.
Definition at line 156 of file node.hpp.
addVariableAsync()
template<typename Connection > template<typename CompletionToken = DefaultCompletionToken> auto opcua::Node< Connection >::addVariableAsync (const NodeId & id, std::string_view browseName, const VariableAttributes & attributes = {}, const NodeId & variableType = VariableTypeId::BaseDataVariableType, const NodeId & referenceType = ReferenceTypeId::HasComponent, CompletionToken && token = DefaultCompletionToken()) inline
Add variable.
See also
services::addVariableAsync
Parameters
token The completion token that will be used to produce a completion handler, which will be called when the operation completes. Potential completion tokens include useFuture, useDeferred, useDetached, or a function (object) with the correct completion signature. The function signature of the completion handler must be:
void(Result<Node>&)
Returns
void if token is a callback function (object)
std::future<Result<Node>> if token is of type UseFutureToken
auto(auto&& token) callable for deferred execution if token is of type UseDeferredToken
void if token is of type UseDetachedToken
Definition at line 175 of file node.hpp.
addProperty()
template<typename Connection > Node opcua::Node< Connection >::addProperty (const NodeId & id, std::string_view browseName, const VariableAttributes & attributes = {}) inline
Add property.
See also
services::addProperty
Examples
custom_datatypes/server_custom_datatypes.cpp.
Definition at line 196 of file node.hpp.
addPropertyAsync()
template<typename Connection > template<typename CompletionToken = DefaultCompletionToken> auto opcua::Node< Connection >::addPropertyAsync (const NodeId & id, std::string_view browseName, const VariableAttributes & attributes = {}, CompletionToken && token = DefaultCompletionToken()) inline
Add property.
See also
services::addPropertyAsync
Parameters
token The completion token that will be used to produce a completion handler, which will be called when the operation completes. Potential completion tokens include useFuture, useDeferred, useDetached, or a function (object) with the correct completion signature. The function signature of the completion handler must be:
void(Result<Node>&)
Returns
void if token is a callback function (object)
std::future<Result<Node>> if token is of type UseFutureToken
auto(auto&& token) callable for deferred execution if token is of type UseDeferredToken
void if token is of type UseDetachedToken
Definition at line 209 of file node.hpp.
addMethod()
template<typename Connection > Node opcua::Node< Connection >::addMethod (const NodeId & id, std::string_view browseName, services::MethodCallback callback, Span< const Argument > inputArguments, Span< const Argument > outputArguments, const MethodAttributes & attributes = {}, const NodeId & referenceType = ReferenceTypeId::HasComponent) inline
Add method.
See also
services::addMethod
Examples
events/server_events.cpp, and method/server_method.cpp.
Definition at line 227 of file node.hpp.
addMethodAsync()
template<typename Connection > template<typename CompletionToken = DefaultCompletionToken> auto opcua::Node< Connection >::addMethodAsync (const NodeId & id, std::string_view browseName, services::MethodCallback callback, Span< const Argument > inputArguments, Span< const Argument > outputArguments, const MethodAttributes & attributes = {}, const NodeId & referenceType = ReferenceTypeId::HasComponent, CompletionToken && token = DefaultCompletionToken()) inline
Add method.
See also
services::addMethodAsync
Parameters
token The completion token that will be used to produce a completion handler, which will be called when the operation completes. Potential completion tokens include useFuture, useDeferred, useDetached, or a function (object) with the correct completion signature. The function signature of the completion handler must be:
void(Result<Node>&)
Returns
void if token is a callback function (object)
std::future<Result<Node>> if token is of type UseFutureToken
auto(auto&& token) callable for deferred execution if token is of type UseDeferredToken
void if token is of type UseDetachedToken
Definition at line 256 of file node.hpp.
addObjectType()
template<typename Connection > Node opcua::Node< Connection >::addObjectType (const NodeId & id, std::string_view browseName, const ObjectTypeAttributes & attributes = {}, const NodeId & referenceType = ReferenceTypeId::HasSubtype) inline
Add object type.
See also
services::addObjectType
Examples
server_instantiation.cpp.
Definition at line 282 of file node.hpp.
addObjectTypeAsync()
template<typename Connection > template<typename CompletionToken = DefaultCompletionToken> auto opcua::Node< Connection >::addObjectTypeAsync (const NodeId & id, std::string_view browseName, const ObjectTypeAttributes & attributes = {}, const NodeId & referenceType = ReferenceTypeId::HasSubtype, CompletionToken && token = DefaultCompletionToken()) inline
Add object type.
See also
services::addObjectTypeAsync
Parameters
token The completion token that will be used to produce a completion handler, which will be called when the operation completes. Potential completion tokens include useFuture, useDeferred, useDetached, or a function (object) with the correct completion signature. The function signature of the completion handler must be:
void(Result<Node>&)
Returns
void if token is a callback function (object)
std::future<Result<Node>> if token is of type UseFutureToken
auto(auto&& token) callable for deferred execution if token is of type UseDeferredToken
void if token is of type UseDetachedToken
Definition at line 300 of file node.hpp.
addVariableType()
template<typename Connection > Node opcua::Node< Connection >::addVariableType (const NodeId & id, std::string_view browseName, const VariableTypeAttributes & attributes = {}, const NodeId & variableType = VariableTypeId::BaseDataVariableType, const NodeId & referenceType = ReferenceTypeId::HasSubtype) inline
Add variable type.
See also
services::addVariableType
Examples
custom_datatypes/server_custom_datatypes.cpp.
Definition at line 319 of file node.hpp.
addVariableTypeAsync()
template<typename Connection > template<typename CompletionToken = DefaultCompletionToken> auto opcua::Node< Connection >::addVariableTypeAsync (const NodeId & id, std::string_view browseName, const VariableTypeAttributes & attributes = {}, const NodeId & variableType = VariableTypeId::BaseDataVariableType, const NodeId & referenceType = ReferenceTypeId::HasSubtype, CompletionToken && token = DefaultCompletionToken()) inline
Add variable type.
See also
services::addVariableTypeAsync
Parameters
token The completion token that will be used to produce a completion handler, which will be called when the operation completes. Potential completion tokens include useFuture, useDeferred, useDetached, or a function (object) with the correct completion signature. The function signature of the completion handler must be:
void(Result<Node>&)
Returns
void if token is a callback function (object)
std::future<Result<Node>> if token is of type UseFutureToken
auto(auto&& token) callable for deferred execution if token is of type UseDeferredToken
void if token is of type UseDetachedToken
Definition at line 338 of file node.hpp.
addReferenceType()
template<typename Connection > Node opcua::Node< Connection >::addReferenceType (const NodeId & id, std::string_view browseName, const ReferenceTypeAttributes & attributes = {}, const NodeId & referenceType = ReferenceTypeId::HasSubtype) inline
Add reference type.
See also
services::addReferenceType
Definition at line 359 of file node.hpp.
addReferenceTypeAsync()
template<typename Connection > template<typename CompletionToken = DefaultCompletionToken> auto opcua::Node< Connection >::addReferenceTypeAsync (const NodeId & id, std::string_view browseName, const ReferenceTypeAttributes & attributes = {}, const NodeId & referenceType = ReferenceTypeId::HasSubtype, CompletionToken && token = DefaultCompletionToken()) inline
Add reference type.
See also
services::addReferenceTypeAsync
Parameters
token The completion token that will be used to produce a completion handler, which will be called when the operation completes. Potential completion tokens include useFuture, useDeferred, useDetached, or a function (object) with the correct completion signature. The function signature of the completion handler must be:
void(Result<Node>&)
Returns
void if token is a callback function (object)
std::future<Result<Node>> if token is of type UseFutureToken
auto(auto&& token) callable for deferred execution if token is of type UseDeferredToken
void if token is of type UseDetachedToken
Definition at line 377 of file node.hpp.
addDataType()
template<typename Connection > Node opcua::Node< Connection >::addDataType (const NodeId & id, std::string_view browseName, const DataTypeAttributes & attributes = {}, const NodeId & referenceType = ReferenceTypeId::HasSubtype) inline
Add data type.
See also
services::addDataType
Examples
custom_datatypes/server_custom_datatypes.cpp.
Definition at line 396 of file node.hpp.
addDataTypeAsync()
template<typename Connection > template<typename CompletionToken = DefaultCompletionToken> auto opcua::Node< Connection >::addDataTypeAsync (const NodeId & id, std::string_view browseName, const DataTypeAttributes & attributes = {}, const NodeId & referenceType = ReferenceTypeId::HasSubtype, CompletionToken && token = DefaultCompletionToken()) inline
Add data type.
See also
services::addDataTypeAsync
Parameters
token The completion token that will be used to produce a completion handler, which will be called when the operation completes. Potential completion tokens include useFuture, useDeferred, useDetached, or a function (object) with the correct completion signature. The function signature of the completion handler must be:
void(Result<Node>&)
Returns
void if token is a callback function (object)
std::future<Result<Node>> if token is of type UseFutureToken
auto(auto&& token) callable for deferred execution if token is of type UseDeferredToken
void if token is of type UseDetachedToken
Definition at line 414 of file node.hpp.
addView()
template<typename Connection > Node opcua::Node< Connection >::addView (const NodeId & id, std::string_view browseName, const ViewAttributes & attributes = {}, const NodeId & referenceType = ReferenceTypeId::Organizes) inline
Add view.
See also
services::addView
Definition at line 433 of file node.hpp.
addViewAsync()
template<typename Connection > template<typename CompletionToken = DefaultCompletionToken> auto opcua::Node< Connection >::addViewAsync (const NodeId & id, std::string_view browseName, const ViewAttributes & attributes = {}, const NodeId & referenceType = ReferenceTypeId::Organizes, CompletionToken && token = DefaultCompletionToken()) inline
Add view.
See also
services::addViewAsync
Parameters
token The completion token that will be used to produce a completion handler, which will be called when the operation completes. Potential completion tokens include useFuture, useDeferred, useDetached, or a function (object) with the correct completion signature. The function signature of the completion handler must be:
void(Result<Node>&)
Returns
void if token is a callback function (object)
std::future<Result<Node>> if token is of type UseFutureToken
auto(auto&& token) callable for deferred execution if token is of type UseDeferredToken
void if token is of type UseDetachedToken
Definition at line 449 of file node.hpp.
addReference()
template<typename Connection > Node & opcua::Node< Connection >::addReference (const NodeId & targetId, const NodeId & referenceType, bool forward = true) inline
Add reference.
See also
services::addReference
Definition at line 468 of file node.hpp.
addReferenceAsync()
template<typename Connection > template<typename CompletionToken = DefaultCompletionToken> auto opcua::Node< Connection >::addReferenceAsync (const NodeId & targetId, const NodeId & referenceType, bool forward = true, CompletionToken && token = DefaultCompletionToken()) inline
Add reference.
See also
services::addReferenceAsync
Parameters
token The completion token that will be used to produce a completion handler, which will be called when the operation completes. Potential completion tokens include useFuture, useDeferred, useDetached, or a function (object) with the correct completion signature. The function signature of the completion handler must be:
void(StatusCode)
Returns
void if token is a callback function (object)
std::future<StatusCode> if token is of type UseFutureToken
auto(auto&& token) callable for deferred execution if token is of type UseDeferredToken
void if token is of type UseDetachedToken
Definition at line 477 of file node.hpp.
addModellingRule()
template<typename Connection > Node & opcua::Node< Connection >::addModellingRule (ModellingRule rule) inline
Add modelling rule.
See also
services::addModellingRule
Examples
custom_datatypes/server_custom_datatypes.cpp, and server_instantiation.cpp.
Definition at line 494 of file node.hpp.
addModellingRuleAsync()
template<typename Connection > template<typename CompletionToken = DefaultCompletionToken> auto opcua::Node< Connection >::addModellingRuleAsync (ModellingRule rule, CompletionToken && token = DefaultCompletionToken()) inline
Add modelling rule.
See also
services::addModellingRuleAsync
Parameters
token The completion token that will be used to produce a completion handler, which will be called when the operation completes. Potential completion tokens include useFuture, useDeferred, useDetached, or a function (object) with the correct completion signature. The function signature of the completion handler must be:
void(StatusCode)
Returns
void if token is a callback function (object)
std::future<StatusCode> if token is of type UseFutureToken
auto(auto&& token) callable for deferred execution if token is of type UseDeferredToken
void if token is of type UseDetachedToken
Definition at line 503 of file node.hpp.
deleteNode()
template<typename Connection > void opcua::Node< Connection >::deleteNode (bool deleteReferences = true) inline
Delete node.
See also
services::deleteNode
Definition at line 512 of file node.hpp.
deleteNodeAsync()
template<typename Connection > template<typename CompletionToken = DefaultCompletionToken> auto opcua::Node< Connection >::deleteNodeAsync (bool deleteReferences = true, CompletionToken && token = DefaultCompletionToken()) inline
Delete node.
See also
services::deleteNodeAsync
Parameters
token The completion token that will be used to produce a completion handler, which will be called when the operation completes. Potential completion tokens include useFuture, useDeferred, useDetached, or a function (object) with the correct completion signature. The function signature of the completion handler must be:
void(StatusCode)
Returns
void if token is a callback function (object)
std::future<StatusCode> if token is of type UseFutureToken
auto(auto&& token) callable for deferred execution if token is of type UseDeferredToken
void if token is of type UseDetachedToken
Definition at line 520 of file node.hpp.
deleteReference()
template<typename Connection > Node & opcua::Node< Connection >::deleteReference (const NodeId & targetId, const NodeId & referenceType, bool isForward = true, bool deleteBidirectional = true) inline
Delete reference.
See also
services::deleteReference
Definition at line 529 of file node.hpp.
deleteReferenceAsync()
template<typename Connection > template<typename CompletionToken = DefaultCompletionToken> auto opcua::Node< Connection >::deleteReferenceAsync (const NodeId & targetId, const NodeId & referenceType, bool isForward = true, bool deleteBidirectional = true, CompletionToken && token = DefaultCompletionToken()) inline
Delete reference.
See also
services::deleteReferenceAsync
Parameters
token The completion token that will be used to produce a completion handler, which will be called when the operation completes. Potential completion tokens include useFuture, useDeferred, useDetached, or a function (object) with the correct completion signature. The function signature of the completion handler must be:
void(StatusCode)
Returns
void if token is a callback function (object)
std::future<StatusCode> if token is of type UseFutureToken
auto(auto&& token) callable for deferred execution if token is of type UseDeferredToken
void if token is of type UseDetachedToken
Definition at line 546 of file node.hpp.
browseReferences()
template<typename Connection > std::vector< ReferenceDescription > opcua::Node< Connection >::browseReferences (BrowseDirection browseDirection = BrowseDirection::Both, const NodeId & referenceType = ReferenceTypeId::References, bool includeSubtypes = true, Bitmask< NodeClass > nodeClassMask = NodeClass::Unspecified) inline
Browse references.
Definition at line 569 of file node.hpp.
browseReferencedNodes()
template<typename Connection > std::vector< Node > opcua::Node< Connection >::browseReferencedNodes (BrowseDirection browseDirection = BrowseDirection::Both, const NodeId & referenceType = ReferenceTypeId::References, bool includeSubtypes = true, Bitmask< NodeClass > nodeClassMask = NodeClass::Unspecified) inline
Browse referenced nodes (only local nodes).
Definition at line 587 of file node.hpp.
Referenced by opcua::Node< Connection >::browseChildren().
browseChildren()
template<typename Connection > std::vector< Node > opcua::Node< Connection >::browseChildren (const NodeId & referenceType = ReferenceTypeId::HierarchicalReferences, Bitmask< NodeClass > nodeClassMask = NodeClass::Unspecified) inline
Browse child nodes (only local nodes).
Definition at line 613 of file node.hpp.
browseChild()
template<typename Connection > Node opcua::Node< Connection >::browseChild (Span< const QualifiedName > path) inline
Browse child node specified by its relative path from this node (only local nodes).
The relative path is specified using browse names.
Exceptions
BadStatus (BadNoMatch) If path not found
Examples
method/client_method.cpp, method/client_method_async.cpp, and server_instantiation.cpp.
Definition at line 623 of file node.hpp.
browseParent()
template<typename Connection > Node opcua::Node< Connection >::browseParent () inline
Browse parent node.
A Node may have several parents, the first found is returned.
Exceptions
BadStatus (BadNotFound) If no parent node found
Definition at line 637 of file node.hpp.
callMethod()
template<typename Connection > CallMethodResult opcua::Node< Connection >::callMethod (const NodeId & methodId, Span< const Variant > inputArguments) inline
Call server methods.
See also
services::call
Examples
method/client_method.cpp.
Definition at line 660 of file node.hpp.
callMethodAsync()
template<typename Connection > template<typename CompletionToken = DefaultCompletionToken> auto opcua::Node< Connection >::callMethodAsync (const NodeId & methodId, Span< const Variant > inputArguments, CompletionToken && token = DefaultCompletionToken()) inline
See also
services::callAsync
Examples
method/client_method_async.cpp.
Definition at line 666 of file node.hpp.
readNodeClass()
template<typename Connection > NodeClass opcua::Node< Connection >::readNodeClass () inline
Read the AttributeId::NodeClass attribute of a node.
See also
services::readNodeClass
Definition at line 682 of file node.hpp.
readNodeClassAsync()
template<typename Connection > template<typename CompletionToken = DefaultCompletionToken> auto opcua::Node< Connection >::readNodeClassAsync (CompletionToken && token = DefaultCompletionToken()) inline
Read the AttributeId::NodeClass attribute of a node.
See also
services::readNodeClassAsync
Definition at line 688 of file node.hpp.
readBrowseName()
template<typename Connection > QualifiedName opcua::Node< Connection >::readBrowseName () inline
Read the AttributeId::BrowseName attribute of a node.
See also
services::readBrowseName
Definition at line 695 of file node.hpp.
readBrowseNameAsync()
template<typename Connection > template<typename CompletionToken = DefaultCompletionToken> auto opcua::Node< Connection >::readBrowseNameAsync (CompletionToken && token = DefaultCompletionToken()) inline
Read the AttributeId::BrowseName attribute of a node.
See also
services::readBrowseNameAsync
Definition at line 701 of file node.hpp.
readDisplayName()
template<typename Connection > LocalizedText opcua::Node< Connection >::readDisplayName () inline
Read the AttributeId::DisplayName attribute of a node.
See also
services::readDisplayName
Definition at line 708 of file node.hpp.
readDisplayNameAsync()
template<typename Connection > template<typename CompletionToken = DefaultCompletionToken> auto opcua::Node< Connection >::readDisplayNameAsync (CompletionToken && token = DefaultCompletionToken()) inline
Read the AttributeId::DisplayName attribute of a node.
See also
services::readDisplayNameAsync
Definition at line 714 of file node.hpp.
readDescription()
template<typename Connection > LocalizedText opcua::Node< Connection >::readDescription () inline
Read the AttributeId::Description attribute of a node.
See also
services::readDescription
Definition at line 721 of file node.hpp.
readDescriptionAsync()
template<typename Connection > template<typename CompletionToken = DefaultCompletionToken> auto opcua::Node< Connection >::readDescriptionAsync (CompletionToken && token = DefaultCompletionToken()) inline
Read the AttributeId::Description attribute of a node.
See also
services::readDescriptionAsync
Definition at line 727 of file node.hpp.
readWriteMask()
template<typename Connection > Bitmask< WriteMask > opcua::Node< Connection >::readWriteMask () inline
Read the AttributeId::WriteMask attribute of a node.
See also
services::readWriteMask
Definition at line 734 of file node.hpp.
readWriteMaskAsync()
template<typename Connection > template<typename CompletionToken = DefaultCompletionToken> auto opcua::Node< Connection >::readWriteMaskAsync (CompletionToken && token = DefaultCompletionToken()) inline
Read the AttributeId::WriteMask attribute of a node.
See also
services::readWriteMaskAsync
Definition at line 740 of file node.hpp.
readUserWriteMask()
template<typename Connection > Bitmask< WriteMask > opcua::Node< Connection >::readUserWriteMask () inline
Read the AttributeId::UserWriteMask attribute of a node.
See also
services::readUserWriteMask
Definition at line 747 of file node.hpp.
readUserWriteMaskAsync()
template<typename Connection > template<typename CompletionToken = DefaultCompletionToken> auto opcua::Node< Connection >::readUserWriteMaskAsync (CompletionToken && token = DefaultCompletionToken()) inline
Read the AttributeId::UserWriteMask attribute of a node.
See also
services::readUserWriteMaskAsync
Definition at line 753 of file node.hpp.
readIsAbstract()
template<typename Connection > bool opcua::Node< Connection >::readIsAbstract () inline
Read the AttributeId::IsAbstract attribute of a node.
See also
services::readIsAbstract
Definition at line 760 of file node.hpp.
readIsAbstractAsync()
template<typename Connection > template<typename CompletionToken = DefaultCompletionToken> auto opcua::Node< Connection >::readIsAbstractAsync (CompletionToken && token = DefaultCompletionToken()) inline
Read the AttributeId::IsAbstract attribute of a node.
See also
services::readIsAbstractAsync
Definition at line 766 of file node.hpp.
readSymmetric()
template<typename Connection > bool opcua::Node< Connection >::readSymmetric () inline
Read the AttributeId::Symmetric attribute of a node.
See also
services::readSymmetric
Definition at line 773 of file node.hpp.
readSymmetricAsync()
template<typename Connection > template<typename CompletionToken = DefaultCompletionToken> auto opcua::Node< Connection >::readSymmetricAsync (CompletionToken && token = DefaultCompletionToken()) inline
Read the AttributeId::Symmetric attribute of a node.
See also
services::readSymmetricAsync
Definition at line 779 of file node.hpp.
readInverseName()
template<typename Connection > LocalizedText opcua::Node< Connection >::readInverseName () inline
Read the AttributeId::InverseName attribute of a node.
See also
services::readInverseName
Definition at line 786 of file node.hpp.
readInverseNameAsync()
template<typename Connection > template<typename CompletionToken = DefaultCompletionToken> auto opcua::Node< Connection >::readInverseNameAsync (CompletionToken && token = DefaultCompletionToken()) inline
Read the AttributeId::InverseName attribute of a node.
See also
services::readInverseNameAsync
Definition at line 792 of file node.hpp.
readContainsNoLoops()
template<typename Connection > bool opcua::Node< Connection >::readContainsNoLoops () inline
Read the AttributeId::ContainsNoLoops attribute of a node.
See also
services::readContainsNoLoops
Definition at line 799 of file node.hpp.
readContainsNoLoopsAsync()
template<typename Connection > template<typename CompletionToken = DefaultCompletionToken> auto opcua::Node< Connection >::readContainsNoLoopsAsync (CompletionToken && token = DefaultCompletionToken()) inline
Read the AttributeId::ContainsNoLoops attribute of a node.
See also
services::readContainsNoLoopsAsync
Definition at line 805 of file node.hpp.
readEventNotifier()
template<typename Connection > Bitmask< EventNotifier > opcua::Node< Connection >::readEventNotifier () inline
Read the AttributeId::EventNotifier attribute of a node.
See also
services::readEventNotifier
Definition at line 812 of file node.hpp.
readEventNotifierAsync()
template<typename Connection > template<typename CompletionToken = DefaultCompletionToken> auto opcua::Node< Connection >::readEventNotifierAsync (CompletionToken && token = DefaultCompletionToken()) inline
Read the AttributeId::EventNotifier attribute of a node.
See also
services::readEventNotifierAsync
Definition at line 818 of file node.hpp.
readDataValue()
template<typename Connection > DataValue opcua::Node< Connection >::readDataValue () inline
Read the AttributeId::Value attribute of a node as a DataValue object.
See also
services::readDataValue
Definition at line 825 of file node.hpp.
readDataValueAsync()
template<typename Connection > template<typename CompletionToken = DefaultCompletionToken> auto opcua::Node< Connection >::readDataValueAsync (CompletionToken && token = DefaultCompletionToken()) inline
Read the AttributeId::Value attribute of a node as a DataValue object.
See also
services::readDataValueAsync
Definition at line 831 of file node.hpp.
readValue()
template<typename Connection > Variant opcua::Node< Connection >::readValue () inline
Read the AttributeId::Value attribute of a node.
See also
services::readValue
Definition at line 838 of file node.hpp.
Referenced by opcua::Node< Connection >::readObjectProperty(), opcua::Node< Connection >::readValueArray(), and opcua::Node< Connection >::readValueScalar().
readValueAsync()
template<typename Connection > template<typename CompletionToken = DefaultCompletionToken> auto opcua::Node< Connection >::readValueAsync (CompletionToken && token = DefaultCompletionToken()) inline
Read the AttributeId::Value attribute of a node.
See also
services::readValueAsync
Definition at line 844 of file node.hpp.
readValueScalar()
template<typename Connection > template<typename T > T opcua::Node< Connection >::readValueScalar () inline
Read scalar value from variable node.
Examples
client_connect.cpp, client_minimal.cpp, and server.cpp.
Definition at line 850 of file node.hpp.
readValueArray()
template<typename Connection > template<typename T > std::vector< T > opcua::Node< Connection >::readValueArray () inline
Read array value from variable node.
Definition at line 856 of file node.hpp.
readDataType()
template<typename Connection > NodeId opcua::Node< Connection >::readDataType () inline
Read the AttributeId::DataType attribute of a node.
See also
services::readDataType
Definition at line 861 of file node.hpp.
readDataTypeAsync()
template<typename Connection > template<typename CompletionToken = DefaultCompletionToken> auto opcua::Node< Connection >::readDataTypeAsync (CompletionToken && token = DefaultCompletionToken()) inline
Read the AttributeId::DataType attribute of a node.
See also
services::readDataTypeAsync
Definition at line 867 of file node.hpp.
readValueRank()
template<typename Connection > ValueRank opcua::Node< Connection >::readValueRank () inline
Read the AttributeId::ValueRank attribute of a node.
See also
services::readValueRank
Definition at line 874 of file node.hpp.
readValueRankAsync()
template<typename Connection > template<typename CompletionToken = DefaultCompletionToken> auto opcua::Node< Connection >::readValueRankAsync (CompletionToken && token = DefaultCompletionToken()) inline
Read the AttributeId::ValueRank attribute of a node.
See also
services::readValueRankAsync
Definition at line 880 of file node.hpp.
readArrayDimensions()
template<typename Connection > std::vector< uint32_t > opcua::Node< Connection >::readArrayDimensions () inline
Read the AttributeId::ArrayDimensions attribute of a node.
See also
services::readArrayDimensions
Definition at line 887 of file node.hpp.
readArrayDimensionsAsync()
template<typename Connection > template<typename CompletionToken = DefaultCompletionToken> auto opcua::Node< Connection >::readArrayDimensionsAsync (CompletionToken && token = DefaultCompletionToken()) inline
Read the AttributeId::ArrayDimensions attribute of a node.
See also
services::readArrayDimensionsAsync
Definition at line 893 of file node.hpp.
readAccessLevel()
template<typename Connection > Bitmask< AccessLevel > opcua::Node< Connection >::readAccessLevel () inline
Read the AttributeId::AccessLevel attribute of a node.
See also
services::readAccessLevel
Definition at line 900 of file node.hpp.
readAccessLevelAsync()
template<typename Connection > template<typename CompletionToken = DefaultCompletionToken> auto opcua::Node< Connection >::readAccessLevelAsync (CompletionToken && token = DefaultCompletionToken()) inline
Read the AttributeId::AccessLevel attribute of a node.
See also
services::readAccessLevelAsync
Definition at line 906 of file node.hpp.
readUserAccessLevel()
template<typename Connection > Bitmask< AccessLevel > opcua::Node< Connection >::readUserAccessLevel () inline
Read the AttributeId::UserAccessLevel attribute of a node.
See also
services::readUserAccessLevel
Definition at line 913 of file node.hpp.
readUserAccessLevelAsync()
template<typename Connection > template<typename CompletionToken = DefaultCompletionToken> auto opcua::Node< Connection >::readUserAccessLevelAsync (CompletionToken && token = DefaultCompletionToken()) inline
Read the AttributeId::UserAccessLevel attribute of a node.
See also
services::readUserAccessLevelAsync
Definition at line 919 of file node.hpp.
readMinimumSamplingInterval()
template<typename Connection > double opcua::Node< Connection >::readMinimumSamplingInterval () inline
Read the AttributeId::MinimumSamplingInterval attribute of a node.
See also
services::readMinimumSamplingInterval
Definition at line 926 of file node.hpp.
readMinimumSamplingIntervalAsync()
template<typename Connection > template<typename CompletionToken = DefaultCompletionToken> auto opcua::Node< Connection >::readMinimumSamplingIntervalAsync (CompletionToken && token = DefaultCompletionToken()) inline
Read the AttributeId::MinimumSamplingInterval attribute of a node.
See also
services::readMinimumSamplingIntervalAsync
Definition at line 932 of file node.hpp.
readHistorizing()
template<typename Connection > bool opcua::Node< Connection >::readHistorizing () inline
Read the AttributeId::Historizing attribute of a node.
See also
services::readHistorizing
Definition at line 939 of file node.hpp.
readHistorizingAsync()
template<typename Connection > template<typename CompletionToken = DefaultCompletionToken> auto opcua::Node< Connection >::readHistorizingAsync (CompletionToken && token = DefaultCompletionToken()) inline
Read the AttributeId::Historizing attribute of a node.
See also
services::readHistorizingAsync
Definition at line 945 of file node.hpp.
readExecutable()
template<typename Connection > bool opcua::Node< Connection >::readExecutable () inline
Read the AttributeId::Executable attribute of a node.
See also
services::readExecutable
Definition at line 952 of file node.hpp.
readExecutableAsync()
template<typename Connection > template<typename CompletionToken = DefaultCompletionToken> auto opcua::Node< Connection >::readExecutableAsync (CompletionToken && token = DefaultCompletionToken()) inline
Read the AttributeId::Executable attribute of a node.
See also
services::readExecutableAsync
Definition at line 958 of file node.hpp.
readUserExecutable()
template<typename Connection > bool opcua::Node< Connection >::readUserExecutable () inline
Read the AttributeId::UserExecutable attribute of a node.
See also
services::readUserExecutable
Definition at line 965 of file node.hpp.
readUserExecutableAsync()
template<typename Connection > template<typename CompletionToken = DefaultCompletionToken> auto opcua::Node< Connection >::readUserExecutableAsync (CompletionToken && token = DefaultCompletionToken()) inline
Read the AttributeId::UserExecutable attribute of a node.
See also
services::readUserExecutableAsync
Definition at line 971 of file node.hpp.
readDataTypeDefinition()
template<typename Connection > Variant opcua::Node< Connection >::readDataTypeDefinition () inline
Read the AttributeId::DataTypeDefinition attribute of a node.
See also
services::readDataTypeDefinition
Definition at line 978 of file node.hpp.
readDataTypeDefinitionAsync()
template<typename Connection > template<typename CompletionToken = DefaultCompletionToken> auto opcua::Node< Connection >::readDataTypeDefinitionAsync (CompletionToken && token = DefaultCompletionToken()) inline
Read the AttributeId::DataTypeDefinition attribute of a node.
See also
services::readDataTypeDefinitionAsync
Definition at line 984 of file node.hpp.
readObjectProperty()
template<typename Connection > Variant opcua::Node< Connection >::readObjectProperty (const QualifiedName & propertyName) inline
Read the value of an object property.
Parameters
propertyName Browse name of the property (variable node)
Definition at line 992 of file node.hpp.
writeDisplayName()
template<typename Connection > Node & opcua::Node< Connection >::writeDisplayName (const LocalizedText & displayName) inline
Write the AttributeId::DisplayName attribute of a node.
See also
services::writeDisplayName
Examples
server_valuecallback.cpp.
Definition at line 997 of file node.hpp.
writeDisplayNameAsync()
template<typename Connection > template<typename CompletionToken = DefaultCompletionToken> auto opcua::Node< Connection >::writeDisplayNameAsync (const LocalizedText & displayName, CompletionToken && token = DefaultCompletionToken()) inline
Write the AttributeId::DisplayName attribute of a node.
See also
services::writeDisplayNameAsync
Definition at line 1004 of file node.hpp.
writeDescription()
template<typename Connection > Node & opcua::Node< Connection >::writeDescription (const LocalizedText & description) inline
Write the AttributeId::Description attribute of a node.
See also
services::writeDescription
Definition at line 1013 of file node.hpp.
writeDescriptionAsync()
template<typename Connection > template<typename CompletionToken = DefaultCompletionToken> auto opcua::Node< Connection >::writeDescriptionAsync (const LocalizedText & description, CompletionToken && token = DefaultCompletionToken()) inline
Write the AttributeId::Description attribute of a node.
See also
services::writeDescriptionAsync
Definition at line 1020 of file node.hpp.
writeWriteMask()
template<typename Connection > Node & opcua::Node< Connection >::writeWriteMask (Bitmask< WriteMask > writeMask) inline
Write the AttributeId::WriteMask attribute of a node.
See also
services::writeWriteMask
Definition at line 1029 of file node.hpp.
writeWriteMaskAsync()
template<typename Connection > template<typename CompletionToken = DefaultCompletionToken> auto opcua::Node< Connection >::writeWriteMaskAsync (Bitmask< WriteMask > writeMask, CompletionToken && token = DefaultCompletionToken()) inline
Write the AttributeId::WriteMask attribute of a node.
See also
services::writeWriteMaskAsync
Definition at line 1036 of file node.hpp.
writeUserWriteMask()
template<typename Connection > Node & opcua::Node< Connection >::writeUserWriteMask (Bitmask< WriteMask > userWriteMask) inline
Write the AttributeId::UserWriteMask attribute of a node.
See also
services::writeUserWriteMask
Definition at line 1045 of file node.hpp.
writeUserWriteMaskAsync()
template<typename Connection > template<typename CompletionToken = DefaultCompletionToken> auto opcua::Node< Connection >::writeUserWriteMaskAsync (Bitmask< WriteMask > userWriteMask, CompletionToken && token = DefaultCompletionToken()) inline
Write the AttributeId::UserWriteMask attribute of a node.
See also
services::writeUserWriteMaskAsync
Definition at line 1052 of file node.hpp.
writeIsAbstract()
template<typename Connection > Node & opcua::Node< Connection >::writeIsAbstract (bool isAbstract) inline
Write the AttributeId::IsAbstract attribute of a node.
See also
services::writeIsAbstract
Definition at line 1061 of file node.hpp.
writeIsAbstractAsync()
template<typename Connection > template<typename CompletionToken = DefaultCompletionToken> auto opcua::Node< Connection >::writeIsAbstractAsync (bool isAbstract, CompletionToken && token = DefaultCompletionToken()) inline
Write the AttributeId::IsAbstract attribute of a node.
See also
services::writeIsAbstractAsync
Definition at line 1068 of file node.hpp.
writeSymmetric()
template<typename Connection > Node & opcua::Node< Connection >::writeSymmetric (bool symmetric) inline
Write the AttributeId::Symmetric attribute of a node.
See also
services::writeSymmetric
Definition at line 1075 of file node.hpp.
writeSymmetricAsync()
template<typename Connection > template<typename CompletionToken = DefaultCompletionToken> auto opcua::Node< Connection >::writeSymmetricAsync (bool symmetric, CompletionToken && token = DefaultCompletionToken()) inline
Write the AttributeId::Symmetric attribute of a node.
See also
services::writeSymmetricAsync
Definition at line 1082 of file node.hpp.
writeInverseName()
template<typename Connection > Node & opcua::Node< Connection >::writeInverseName (const LocalizedText & inverseName) inline
Write the AttributeId::InverseName attribute of a node.
See also
services::writeInverseName
Definition at line 1089 of file node.hpp.
writeInverseNameAsync()
template<typename Connection > template<typename CompletionToken = DefaultCompletionToken> auto opcua::Node< Connection >::writeInverseNameAsync (const LocalizedText & inverseName, CompletionToken && token = DefaultCompletionToken()) inline
Write the AttributeId::InverseName attribute of a node.
See also
services::writeInverseNameAsync
Definition at line 1096 of file node.hpp.
writeContainsNoLoops()
template<typename Connection > Node & opcua::Node< Connection >::writeContainsNoLoops (bool containsNoLoops) inline
Write the AttributeId::ContainsNoLoops attribute of a node.
See also
services::writeContainsNoLoops
Definition at line 1105 of file node.hpp.
writeContainsNoLoopsAsync()
template<typename Connection > template<typename CompletionToken = DefaultCompletionToken> auto opcua::Node< Connection >::writeContainsNoLoopsAsync (bool containsNoLoops, CompletionToken && token = DefaultCompletionToken()) inline
Write the AttributeId::ContainsNoLoops attribute of a node.
See also
services::writeContainsNoLoopsAsync
Definition at line 1112 of file node.hpp.
writeEventNotifier()
template<typename Connection > Node & opcua::Node< Connection >::writeEventNotifier (Bitmask< EventNotifier > eventNotifier) inline
Write the AttributeId::EventNotifier attribute of a node.
See also
services::writeEventNotifier
Examples
events/server_events.cpp.
Definition at line 1121 of file node.hpp.
writeEventNotifierAsync()
template<typename Connection > template<typename CompletionToken = DefaultCompletionToken> auto opcua::Node< Connection >::writeEventNotifierAsync (Bitmask< EventNotifier > eventNotifier, CompletionToken && token = DefaultCompletionToken()) inline
Write the AttributeId::EventNotifier attribute of a node.
See also
services::writeEventNotifierAsync
Definition at line 1128 of file node.hpp.
writeDataValue()
template<typename Connection > Node & opcua::Node< Connection >::writeDataValue (const DataValue & value) inline
Write the AttributeId::Value attribute of a node as a DataValue object.
See also
services::writeDataValue
Definition at line 1137 of file node.hpp.
writeDataValueAsync()
template<typename Connection > template<typename CompletionToken = DefaultCompletionToken> auto opcua::Node< Connection >::writeDataValueAsync (const DataValue & value, CompletionToken && token = DefaultCompletionToken()) inline
Write the AttributeId::Value attribute of a node as a DataValue object.
See also
services::writeDataValueAsync
Definition at line 1144 of file node.hpp.
writeValue()
template<typename Connection > Node & opcua::Node< Connection >::writeValue (const Variant & value) inline
Write the AttributeId::Value attribute of a node.
See also
services::writeValue
Definition at line 1153 of file node.hpp.
Referenced by opcua::Node< Connection >::writeObjectProperty(), opcua::Node< Connection >::writeValueArray(), opcua::Node< Connection >::writeValueArray(), and opcua::Node< Connection >::writeValueScalar().
writeValueAsync()
template<typename Connection > template<typename CompletionToken = DefaultCompletionToken> auto opcua::Node< Connection >::writeValueAsync (const Variant & value, CompletionToken && token = DefaultCompletionToken()) inline
Write the AttributeId::Value attribute of a node.
See also
services::writeValueAsync
Definition at line 1160 of file node.hpp.
writeValueScalar()
template<typename Connection > template<typename T > Node & opcua::Node< Connection >::writeValueScalar (const T & value) inline
Write scalar to variable node.
Examples
server.cpp, server_minimal.cpp, and server_valuecallback.cpp.
Definition at line 1168 of file node.hpp.
writeValueArray() [1/2]
template<typename Connection > template<typename ArrayLike > Node & opcua::Node< Connection >::writeValueArray (const ArrayLike & array) inline
Write array value to variable node.
Definition at line 1181 of file node.hpp.
writeValueArray() [2/2]
template<typename Connection > template<typename InputIt > Node & opcua::Node< Connection >::writeValueArray (InputIt first, InputIt last) inline
Write range of elements as array value to variable node.
Definition at line 1194 of file node.hpp.
writeDataType() [1/2]
template<typename Connection > Node & opcua::Node< Connection >::writeDataType (const NodeId & dataType) inline
Write the AttributeId::DataType attribute of a node.
See also
services::writeDataType
Definition at line 1200 of file node.hpp.
writeDataType() [2/2]
template<typename Connection > template<typename T > Node & opcua::Node< Connection >::writeDataType () inline
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Deduce the typeId from the template type.
Definition at line 1208 of file node.hpp.
Referenced by opcua::Node< Connection >::writeDataType().
writeDataTypeAsync()
template<typename Connection > template<typename CompletionToken = DefaultCompletionToken> auto opcua::Node< Connection >::writeDataTypeAsync (const NodeId & dataType, CompletionToken && token = DefaultCompletionToken()) inline
Write the AttributeId::DataType attribute of a node.
See also
services::writeDataTypeAsync
Definition at line 1214 of file node.hpp.
writeValueRank()
template<typename Connection > Node & opcua::Node< Connection >::writeValueRank (ValueRank valueRank) inline
Write the AttributeId::ValueRank attribute of a node.
See also
services::writeValueRank
Definition at line 1223 of file node.hpp.
writeValueRankAsync()
template<typename Connection > template<typename CompletionToken = DefaultCompletionToken> auto opcua::Node< Connection >::writeValueRankAsync (ValueRank valueRank, CompletionToken && token = DefaultCompletionToken()) inline
Write the AttributeId::ValueRank attribute of a node.
See also
services::writeValueRankAsync
Definition at line 1230 of file node.hpp.
writeArrayDimensions()
template<typename Connection > Node & opcua::Node< Connection >::writeArrayDimensions (Span< const uint32_t > dimensions) inline
Write the AttributeId::ArrayDimensions attribute of a node.
See also
services::writeArrayDimensions
Definition at line 1239 of file node.hpp.
writeArrayDimensionsAsync()
template<typename Connection > template<typename CompletionToken = DefaultCompletionToken> auto opcua::Node< Connection >::writeArrayDimensionsAsync (Span< const uint32_t > dimensions, CompletionToken && token = DefaultCompletionToken()) inline
Write the AttributeId::ArrayDimensions attribute of a node.
See also
services::writeArrayDimensionsAsync
Definition at line 1246 of file node.hpp.
writeAccessLevel()
template<typename Connection > Node & opcua::Node< Connection >::writeAccessLevel (Bitmask< AccessLevel > accessLevel) inline
Write the AttributeId::AccessLevel attribute of a node.
See also
services::writeAccessLevel
Definition at line 1255 of file node.hpp.
writeAccessLevelAsync()
template<typename Connection > template<typename CompletionToken = DefaultCompletionToken> auto opcua::Node< Connection >::writeAccessLevelAsync (Bitmask< AccessLevel > accessLevel, CompletionToken && token = DefaultCompletionToken()) inline
Write the AttributeId::AccessLevel attribute of a node.
See also
services::writeAccessLevelAsync
Definition at line 1262 of file node.hpp.
writeUserAccessLevel()
template<typename Connection > Node & opcua::Node< Connection >::writeUserAccessLevel (Bitmask< AccessLevel > userAccessLevel) inline
Write the AttributeId::UserAccessLevel attribute of a node.
See also
services::writeUserAccessLevel
Definition at line 1271 of file node.hpp.
writeUserAccessLevelAsync()
template<typename Connection > template<typename CompletionToken = DefaultCompletionToken> auto opcua::Node< Connection >::writeUserAccessLevelAsync (Bitmask< AccessLevel > userAccessLevel, CompletionToken && token = DefaultCompletionToken()) inline
Write the AttributeId::UserAccessLevel attribute of a node.
See also
services::writeUserAccessLevelAsync
Definition at line 1278 of file node.hpp.
writeMinimumSamplingInterval()
template<typename Connection > Node & opcua::Node< Connection >::writeMinimumSamplingInterval (double milliseconds) inline
Write the AttributeId::MinimumSamplingInterval attribute of a node.
See also
services::writeMinimumSamplingInterval
Definition at line 1287 of file node.hpp.
writeMinimumSamplingIntervalAsync()
template<typename Connection > template<typename CompletionToken = DefaultCompletionToken> auto opcua::Node< Connection >::writeMinimumSamplingIntervalAsync (double milliseconds, CompletionToken && token = DefaultCompletionToken()) inline
Write the AttributeId::MinimumSamplingInterval attribute of a node.
See also
services::writeMinimumSamplingIntervalAsync
Definition at line 1294 of file node.hpp.
writeHistorizing()
template<typename Connection > Node & opcua::Node< Connection >::writeHistorizing (bool historizing) inline
Write the AttributeId::Historizing attribute of a node.
See also
services::writeHistorizing
Definition at line 1303 of file node.hpp.
writeHistorizingAsync()
template<typename Connection > template<typename CompletionToken = DefaultCompletionToken> auto opcua::Node< Connection >::writeHistorizingAsync (bool historizing, CompletionToken && token = DefaultCompletionToken()) inline
Write the AttributeId::Historizing attribute of a node.
See also
services::writeHistorizingAsync
Definition at line 1310 of file node.hpp.
writeExecutable()
template<typename Connection > Node & opcua::Node< Connection >::writeExecutable (bool executable) inline
Write the AttributeId::Executable attribute of a node.
See also
services::writeExecutable
Definition at line 1319 of file node.hpp.
writeExecutableAsync()
template<typename Connection > template<typename CompletionToken = DefaultCompletionToken> auto opcua::Node< Connection >::writeExecutableAsync (bool executable, CompletionToken && token = DefaultCompletionToken()) inline
Write the AttributeId::Executable attribute of a node.
See also
services::writeExecutableAsync
Definition at line 1326 of file node.hpp.
writeUserExecutable()
template<typename Connection > Node & opcua::Node< Connection >::writeUserExecutable (bool userExecutable) inline
Write the AttributeId::UserExecutable attribute of a node.
See also
services::writeUserExecutable
Definition at line 1333 of file node.hpp.
writeUserExecutableAsync()
template<typename Connection > template<typename CompletionToken = DefaultCompletionToken> auto opcua::Node< Connection >::writeUserExecutableAsync (bool userExecutable, CompletionToken && token = DefaultCompletionToken()) inline
Write the AttributeId::UserExecutable attribute of a node.
See also
services::writeUserExecutableAsync
Definition at line 1340 of file node.hpp.
writeObjectProperty()
template<typename Connection > Node & opcua::Node< Connection >::writeObjectProperty (const QualifiedName & propertyName, const Variant & value) inline
Write the value of an object property.
Parameters
propertyName Browse name of the property (variable node)
value New value
Definition at line 1351 of file node.hpp.
Friends And Related Symbol Documentation
operator==()
template<typename Connection > bool operator== (const Node< Connection > & lhs, const Node< Connection > & rhs) related
Definition at line 1404 of file node.hpp.
operator!=()
template<typename Connection > bool operator!= (const Node< Connection > & lhs, const Node< Connection > & rhs) related
Definition at line 1410 of file node.hpp.