open62541pp: opcua::DataTypeMember Class Reference
opcua::DataTypeMember Class Reference
#include <datatype.hpp>
Detailed Description
Definition at line 38 of file datatype.hpp.
Public Member Functions
std::string_view memberName () const noexcept
void setMemberName (std::string_view memberName)
const UA_DataType * memberType () const noexcept
void setMemberType (const UA_DataType *memberType)
uint8_t padding () const noexcept
void setPadding (uint8_t padding)
bool isArray () const noexcept
void setIsArray (bool isArray)
bool isOptional () const noexcept
void setIsOptional (bool isOptional)
constexpr Wrapper () noexcept=default
constexpr Wrapper (const Wrapper &other)
constexpr Wrapper (const T &native)
constexpr Wrapper (Wrapper &&other) noexcept
constexpr Wrapper (T &&native) noexcept
Public Member Functions inherited from opcua::Wrapper< UA_DataTypeMember >
constexpr Wrapper () noexcept=default
constexpr Wrapper (const Wrapper &other)
constexpr Wrapper (const UA_DataTypeMember &native)
constexpr Wrapper (Wrapper &&other) noexcept
constexpr Wrapper (UA_DataTypeMember &&native) noexcept
~Wrapper () noexcept=default
constexpr Wrapper & operator= (const Wrapper &other)
constexpr Wrapper & operator= (const UA_DataTypeMember &native)
constexpr Wrapper & operator= (Wrapper &&other) noexcept
constexpr Wrapper & operator= (UA_DataTypeMember &&native) noexcept
constexpr operator UA_DataTypeMember & () noexcept
constexpr operator const UA_DataTypeMember & () const noexcept
constexpr UA_DataTypeMember * operator-> () noexcept
constexpr const UA_DataTypeMember * operator-> () const noexcept
constexpr UA_DataTypeMember * handle () noexcept
constexpr const UA_DataTypeMember * handle () const noexcept
constexpr void swap (Wrapper &other) noexcept
constexpr void swap (UA_DataTypeMember &native) noexcept
Additional Inherited Members
Public Types inherited from opcua::Wrapper< UA_DataTypeMember >
using NativeType = UA_DataTypeMember
using HandlerType = TypeHandler< UA_DataTypeMember >
Protected Member Functions inherited from opcua::Wrapper< UA_DataTypeMember >
constexpr const UA_DataTypeMember & native () const noexcept
constexpr UA_DataTypeMember & native () noexcept
constexpr void clear () noexcept
Related Symbols inherited from opcua::Wrapper< UA_DataTypeMember >
constexpr UA_DataTypeMember * asWrapper (typename T::NativeType *native) noexcept
constexpr const UA_DataTypeMember * asWrapper (const typename T::NativeType *native) noexcept
constexpr UA_DataTypeMember & asWrapper (typename T::NativeType &native) noexcept
constexpr const UA_DataTypeMember & asWrapper (const typename T::NativeType &native) noexcept
constexpr T::NativeType * asNative (UA_DataTypeMember *wrapper) noexcept
constexpr const T::NativeType * asNative (const UA_DataTypeMember *wrapper) noexcept
constexpr T::NativeType & asNative (UA_DataTypeMember &wrapper) noexcept
constexpr const T::NativeType & asNative (const UA_DataTypeMember &wrapper) noexcept
Member Function Documentation
isArray()
bool opcua::DataTypeMember::isArray () const inline noexcept
Definition at line 84 of file datatype.hpp.
Referenced by setIsArray().
isOptional()
bool opcua::DataTypeMember::isOptional () const inline noexcept
Definition at line 92 of file datatype.hpp.
Referenced by setIsOptional().
memberName()
std::string_view opcua::DataTypeMember::memberName () const inline noexcept
Definition at line 42 of file datatype.hpp.
Referenced by setMemberName().
memberType()
const UA_DataType * opcua::DataTypeMember::memberType () const inline noexcept
Definition at line 57 of file datatype.hpp.
Referenced by setMemberType().
padding()
uint8_t opcua::DataTypeMember::padding () const inline noexcept
Definition at line 76 of file datatype.hpp.
Referenced by setPadding().
setIsArray()
void opcua::DataTypeMember::setIsArray (bool isArray) inline
Definition at line 88 of file datatype.hpp.
Referenced by opcua::DataTypeBuilder< T, Tag, U >::addField(), opcua::DataTypeBuilder< T, Tag, U >::addField(), and opcua::DataTypeBuilder< T, Tag, U >::addUnionField().
setIsOptional()
void opcua::DataTypeMember::setIsOptional (bool isOptional) inline
Definition at line 100 of file datatype.hpp.
Referenced by opcua::DataTypeBuilder< T, Tag, U >::addField(), opcua::DataTypeBuilder< T, Tag, U >::addField(), and opcua::DataTypeBuilder< T, Tag, U >::addUnionField().
setMemberName()
void opcua::DataTypeMember::setMemberName (std::string_view memberName) inline
Definition at line 50 of file datatype.hpp.
Referenced by opcua::DataTypeBuilder< T, Tag, U >::addField(), opcua::DataTypeBuilder< T, Tag, U >::addField(), and opcua::DataTypeBuilder< T, Tag, U >::addUnionField().
setMemberType()
void opcua::DataTypeMember::setMemberType (const UA_DataType * memberType) inline
Definition at line 65 of file datatype.hpp.
Referenced by opcua::DataTypeBuilder< T, Tag, U >::addField(), opcua::DataTypeBuilder< T, Tag, U >::addField(), and opcua::DataTypeBuilder< T, Tag, U >::addUnionField().
setPadding()
void opcua::DataTypeMember::setPadding (uint8_t padding) inline
Definition at line 80 of file datatype.hpp.
Referenced by opcua::DataTypeBuilder< T, Tag, U >::addField(), opcua::DataTypeBuilder< T, Tag, U >::addField(), and opcua::DataTypeBuilder< T, Tag, U >::addUnionField().
Wrapper() [1/5]
constexpr opcua::Wrapper< T, Handler >::Wrapper () constexpr default noexcept
Wrapper() [2/5]
constexpr opcua::Wrapper< T, Handler >::Wrapper (const T & native) inline explicit constexpr
Copy constructor with native object.
Definition at line 151 of file wrapper.hpp.
Wrapper() [3/5]
constexpr opcua::Wrapper< T, Handler >::Wrapper (const Wrapper & other) inline constexpr
Copy constructor.
Definition at line 147 of file wrapper.hpp.
Wrapper() [4/5]
constexpr opcua::Wrapper< T, Handler >::Wrapper (T && native) inline constexpr noexcept
Move constructor with native object.
Definition at line 159 of file wrapper.hpp.
Wrapper() [5/5]
constexpr opcua::Wrapper< T, Handler >::Wrapper (Wrapper && other) inline constexpr noexcept
Move constructor.
Definition at line 155 of file wrapper.hpp.