open62541++: opcua::Subscription< Connection > Class Template Reference
opcua::Subscription< Connection > Class Template Reference
#include <Subscription.h>
Detailed Description
template<typename Connection>
class opcua::Subscription< Connection >
High-level subscription class.
The API is symmetric for both Server and Client, although servers don't use the subscription mechanism of OPC UA to transport notifications of data changes and events. Instead MonitoredItems are registered locally. Notifications are then forwarded to user-defined callbacks instead of a remote client. The subscriptionId for servers is always 0U.
Template Parameters
Connection Server or Client
Note
Not all methods are available and implemented for servers.
Use the free functions in the opcua::services namespace for more advanced usage:
Subscription service set
MonitoredItem service set
Definition at line 63 of file Subscription.h.
Public Member Functions
Subscription (Connection &connection, uint32_t subscriptionId) noexcept
Connection & connection () noexcept
const Connection & connection () const noexcept
Connection & getConnection () noexcept
const Connection & getConnection () const noexcept
uint32_t subscriptionId () const noexcept
uint32_t getSubscriptionId () const noexcept
std::vector< MonitoredItem< Connection > > getMonitoredItems ()
void setSubscriptionParameters (SubscriptionParameters &parameters)
void setPublishingMode (bool publishing)
MonitoredItem< Connection > subscribeDataChange (const NodeId &id, AttributeId attribute, MonitoringMode monitoringMode, MonitoringParametersEx &parameters, DataChangeNotificationCallback onDataChange)
MonitoredItem< Connection > subscribeDataChange (const NodeId &id, AttributeId attribute, MonitoringMode monitoringMode, MonitoringParametersEx &parameters, DataChangeCallback< Connection > onDataChange)
MonitoredItem< Connection > subscribeDataChange (const NodeId &id, AttributeId attribute, DataChangeNotificationCallback onDataChange)
MonitoredItem< Connection > subscribeDataChange (const NodeId &id, AttributeId attribute, DataChangeCallback< Connection > onDataChange)
MonitoredItem< Connection > subscribeEvent (const NodeId &id, MonitoringMode monitoringMode, MonitoringParametersEx &parameters, EventNotificationCallback onEvent)
MonitoredItem< Connection > subscribeEvent (const NodeId &id, MonitoringMode monitoringMode, MonitoringParametersEx &parameters, EventCallback< Connection > onEvent)
MonitoredItem< Connection > subscribeEvent (const NodeId &id, const EventFilter &eventFilter, EventNotificationCallback onEvent)
MonitoredItem< Connection > subscribeEvent (const NodeId &id, const EventFilter &eventFilter, EventCallback< Connection > onEvent)
void deleteSubscription ()
Constructor & Destructor Documentation
Subscription()
template<typename Connection > opcua::Subscription< Connection >::Subscription (Connection & connection, uint32_t subscriptionId) inline noexcept
Wrap an existing subscription.
The subscriptionId is ignored and set to 0U for servers.
Definition at line 67 of file Subscription.h.
Member Function Documentation
connection() [1/2]
template<typename Connection > Connection & opcua::Subscription< Connection >::connection () inline noexcept
Get the server/client instance.
Definition at line 72 of file Subscription.h.
connection() [2/2]
template<typename Connection > const Connection & opcua::Subscription< Connection >::connection () const inline noexcept
Get the server/client instance.
Definition at line 77 of file Subscription.h.
getConnection() [1/2]
template<typename Connection > Connection & opcua::Subscription< Connection >::getConnection () inline noexcept
Deprecated
Use connection() instead
Definition at line 83 of file Subscription.h.
getConnection() [2/2]
template<typename Connection > const Connection & opcua::Subscription< Connection >::getConnection () const inline noexcept
Deprecated
Use connection() instead
Definition at line 89 of file Subscription.h.
subscriptionId()
template<typename Connection > uint32_t opcua::Subscription< Connection >::subscriptionId () const inline noexcept
Get the server-assigned identifier of this subscription.
Definition at line 94 of file Subscription.h.
getSubscriptionId()
template<typename Connection > uint32_t opcua::Subscription< Connection >::getSubscriptionId () const inline noexcept
Deprecated
Use subscriptionId() instead
Definition at line 100 of file Subscription.h.
getMonitoredItems()
template<typename Connection > std::vector< MonitoredItem< Connection > > opcua::Subscription< Connection >::getMonitoredItems ()
Get all local monitored items.
setSubscriptionParameters()
template<typename Connection > void opcua::Subscription< Connection >::setSubscriptionParameters (SubscriptionParameters & parameters) inline
Modify this subscription.
Note
Not implemented for Server.
See also
services::modifySubscription
Definition at line 110 of file Subscription.h.
setPublishingMode()
template<typename Connection > void opcua::Subscription< Connection >::setPublishingMode (bool publishing) inline
Enable/disable publishing of notification messages.
Note
Not implemented for Server.
See also
services::setPublishingMode
Definition at line 117 of file Subscription.h.
subscribeDataChange() [1/4]
template<typename Connection > MonitoredItem< Connection > opcua::Subscription< Connection >::subscribeDataChange (const NodeId & id, AttributeId attribute, MonitoringMode monitoringMode, MonitoringParametersEx & parameters, DataChangeNotificationCallback onDataChange) inline
Create a monitored item for data change notifications.
This is an extended version of UA_MonitoringParameters with the timestamps parameter. Parameters are passed by reference because illegal parameters can be revised by the server. The updated parameters reflect the actual values that the server will use.
See also
https://reference.opcfoundation.org/Core/Part4/v105/docs/7.21
Definition at line 123 of file Subscription.h.
Referenced by opcua::Subscription< Connection >::subscribeDataChange(), opcua::Subscription< Connection >::subscribeDataChange(), and opcua::Subscription< Connection >::subscribeDataChange().
subscribeDataChange() [2/4]
template<typename Connection > MonitoredItem< Connection > opcua::Subscription< Connection >::subscribeDataChange (const NodeId & id, AttributeId attribute, MonitoringMode monitoringMode, MonitoringParametersEx & parameters, DataChangeCallback< Connection > onDataChange) inline
Deprecated
Use overload with DataChangeNotificationCallback instead
Definition at line 143 of file Subscription.h.
subscribeDataChange() [3/4]
template<typename Connection > MonitoredItem< Connection > opcua::Subscription< Connection >::subscribeDataChange (const NodeId & id, AttributeId attribute, DataChangeNotificationCallback onDataChange) inline
Create a monitored item for data change notifications (default settings).
The monitoring mode is set to MonitoringMode::Reporting and the default open62541 MonitoringParametersEx are used.
See also
services::MonitoringParametersEx
Definition at line 159 of file Subscription.h.
subscribeDataChange() [4/4]
template<typename Connection > MonitoredItem< Connection > opcua::Subscription< Connection >::subscribeDataChange (const NodeId & id, AttributeId attribute, DataChangeCallback< Connection > onDataChange) inline
Deprecated
Use overload with DataChangeNotificationCallback instead
Definition at line 170 of file Subscription.h.
subscribeEvent() [1/4]
template<typename Connection > MonitoredItem< Connection > opcua::Subscription< Connection >::subscribeEvent (const NodeId & id, MonitoringMode monitoringMode, MonitoringParametersEx & parameters, EventNotificationCallback onEvent) inline
Create a monitored item for event notifications.
This is an extended version of UA_MonitoringParameters with the timestamps parameter. Parameters are passed by reference because illegal parameters can be revised by the server. The updated parameters reflect the actual values that the server will use.
See also
https://reference.opcfoundation.org/Core/Part4/v105/docs/7.21
Note
Not implemented for Server.
Definition at line 179 of file Subscription.h.
Referenced by opcua::Subscription< Connection >::subscribeEvent(), opcua::Subscription< Connection >::subscribeEvent(), and opcua::Subscription< Connection >::subscribeEvent().
subscribeEvent() [2/4]
template<typename Connection > MonitoredItem< Connection > opcua::Subscription< Connection >::subscribeEvent (const NodeId & id, MonitoringMode monitoringMode, MonitoringParametersEx & parameters, EventCallback< Connection > onEvent) inline
Deprecated
Use overload with EventNotificationCallback instead
Definition at line 198 of file Subscription.h.
subscribeEvent() [3/4]
template<typename Connection > MonitoredItem< Connection > opcua::Subscription< Connection >::subscribeEvent (const NodeId & id, const EventFilter & eventFilter, EventNotificationCallback onEvent) inline
Create a monitored item for event notifications (default settings).
The monitoring mode is set to MonitoringMode::Reporting and the default open62541 MonitoringParametersEx are used.
Note
Not implemented for Server.
Definition at line 211 of file Subscription.h.
subscribeEvent() [4/4]
template<typename Connection > MonitoredItem< Connection > opcua::Subscription< Connection >::subscribeEvent (const NodeId & id, const EventFilter & eventFilter, EventCallback< Connection > onEvent) inline
Deprecated
Use overload with EventNotificationCallback instead
Definition at line 221 of file Subscription.h.
deleteSubscription()
template<typename Connection > void opcua::Subscription< Connection >::deleteSubscription () inline
Delete this subscription.
Note
Not implemented for Server.
Definition at line 229 of file Subscription.h.