open62541pp: opcua::ua::EnumValueType Class Reference
opcua::ua::EnumValueType Class Reference
Wrapper classes
#include <types.hpp>
Detailed Description
UA_EnumValueType wrapper class.
See also
https://reference.opcfoundation.org/Core/Part3/v105/docs/8.39
Definition at line 135 of file types.hpp.
Public Member Functions
EnumValueType (int64_t value, LocalizedText displayName, LocalizedText description)
int64_t value () const noexcept
int64_t getValue () const noexcept
const LocalizedText & displayName () const noexcept
const LocalizedText & getDisplayName () const noexcept
LocalizedText & displayName () noexcept
LocalizedText & getDisplayName () noexcept
const LocalizedText & description () const noexcept
const LocalizedText & getDescription () const noexcept
LocalizedText & description () noexcept
LocalizedText & getDescription () noexcept
constexpr TypeWrapper () noexcept=default
constexpr TypeWrapper (const T &native)
constexpr TypeWrapper (T &&native) noexcept
constexpr TypeWrapper (const TypeWrapper &other)
constexpr TypeWrapper (TypeWrapper &&other) noexcept
Public Member Functions inherited from opcua::TypeWrapper< UA_EnumValueType, UA_TYPES_ENUMVALUETYPE >
constexpr TypeWrapper () noexcept=default
constexpr TypeWrapper (const UA_EnumValueType &native)
constexpr TypeWrapper (UA_EnumValueType &&native) noexcept
constexpr TypeWrapper (const TypeWrapper &other)
constexpr TypeWrapper (TypeWrapper &&other) noexcept
~TypeWrapper ()
constexpr TypeWrapper & operator= (const TypeWrapper &other)
constexpr TypeWrapper & operator= (const UA_EnumValueType &native)
constexpr TypeWrapper & operator= (TypeWrapper &&other) noexcept
constexpr TypeWrapper & operator= (UA_EnumValueType &&native) noexcept
Public Member Functions inherited from opcua::Wrapper< T >
constexpr Wrapper () noexcept=default
constexpr Wrapper (const T &native) noexcept
constexpr Wrapper (T &&native) noexcept
constexpr Wrapper & operator= (const T &native) noexcept
constexpr Wrapper & operator= (T &&native) noexcept
constexpr operator T& () noexcept
constexpr operator const T & () const noexcept
constexpr T * operator-> () noexcept
constexpr const T * operator-> () const noexcept
constexpr T * handle () noexcept
constexpr const T * handle () const noexcept
constexpr void swap (Wrapper &other) noexcept
constexpr void swap (T &native) noexcept
Additional Inherited Members
Public Types inherited from opcua::Wrapper< T >
using NativeType = T
Static Public Member Functions inherited from opcua::TypeWrapper< UA_EnumValueType, UA_TYPES_ENUMVALUETYPE >
static constexpr TypeIndex typeIndex ()
Protected Member Functions inherited from opcua::TypeWrapper< UA_EnumValueType, UA_TYPES_ENUMVALUETYPE >
constexpr void clear () noexcept
Protected Member Functions inherited from opcua::Wrapper< T >
constexpr const T & native () const noexcept
constexpr T & native () noexcept
Related Symbols inherited from opcua::TypeWrapper< UA_EnumValueType, UA_TYPES_ENUMVALUETYPE >
String toString (const UA_EnumValueType &object, const UA_DataType &type)
String toString (const UA_EnumValueType &object)
Related Symbols inherited from opcua::Wrapper< T >
template<typename WrapperType , typename NativeType = typename WrapperType::NativeType>
constexpr WrapperType * asWrapper (NativeType *native) noexcept
template<typename WrapperType , typename NativeType = typename WrapperType::NativeType>
constexpr const WrapperType * asWrapper (const NativeType *native) noexcept
template<typename WrapperType , typename NativeType = typename WrapperType::NativeType>
constexpr WrapperType & asWrapper (NativeType &native) noexcept
template<typename WrapperType , typename NativeType = typename WrapperType::NativeType>
constexpr const WrapperType & asWrapper (const NativeType &native) noexcept
template<typename WrapperType , typename NativeType = typename WrapperType::NativeType>
constexpr NativeType * asNative (WrapperType *wrapper) noexcept
template<typename WrapperType , typename NativeType = typename WrapperType::NativeType>
constexpr const NativeType * asNative (const WrapperType *wrapper) noexcept
template<typename WrapperType , typename NativeType = typename WrapperType::NativeType>
constexpr NativeType & asNative (WrapperType &wrapper) noexcept
template<typename WrapperType , typename NativeType = typename WrapperType::NativeType>
constexpr const NativeType & asNative (const WrapperType &wrapper) noexcept
Constructor & Destructor Documentation
EnumValueType()
opcua::ua::EnumValueType::EnumValueType (int64_t value, LocalizedText displayName, LocalizedText description) inline
Definition at line 139 of file types.hpp.
Member Function Documentation
value()
int64_t opcua::ua::EnumValueType::value () const inline noexcept
Definition at line 145 of file types.hpp.
Referenced by EnumValueType().
getValue()
int64_t opcua::ua::EnumValueType::getValue () const inline noexcept
Deprecated:
Use value instead
Definition at line 145 of file types.hpp.
displayName() [1/2]
const LocalizedText & opcua::ua::EnumValueType::displayName () const inline noexcept
Definition at line 146 of file types.hpp.
Referenced by EnumValueType().
getDisplayName() [1/2]
const LocalizedText & opcua::ua::EnumValueType::getDisplayName () const inline noexcept
Deprecated:
Use displayName instead
Definition at line 146 of file types.hpp.
displayName() [2/2]
LocalizedText & opcua::ua::EnumValueType::displayName () inline noexcept
Definition at line 146 of file types.hpp.
getDisplayName() [2/2]
LocalizedText & opcua::ua::EnumValueType::getDisplayName () inline noexcept
Deprecated:
Use displayName instead
Definition at line 146 of file types.hpp.
description() [1/2]
const LocalizedText & opcua::ua::EnumValueType::description () const inline noexcept
Definition at line 147 of file types.hpp.
Referenced by EnumValueType().
getDescription() [1/2]
const LocalizedText & opcua::ua::EnumValueType::getDescription () const inline noexcept
Deprecated:
Use description instead
Definition at line 147 of file types.hpp.
description() [2/2]
LocalizedText & opcua::ua::EnumValueType::description () inline noexcept
Definition at line 147 of file types.hpp.
getDescription() [2/2]
LocalizedText & opcua::ua::EnumValueType::getDescription () inline noexcept
Deprecated:
Use description instead
Definition at line 147 of file types.hpp.
TypeWrapper() [1/5]
constexpr opcua::TypeWrapper< T, Index >::TypeWrapper () constexpr default noexcept
TypeWrapper() [2/5]
constexpr opcua::TypeWrapper< T, Index >::TypeWrapper (const T & native) inline explicit constexpr
Constructor with native object (deep copy).
Definition at line 31 of file typewrapper.hpp.
TypeWrapper() [3/5]
constexpr opcua::TypeWrapper< T, Index >::TypeWrapper (T && native) inline constexpr noexcept
Constructor with native object (move rvalue).
Definition at line 35 of file typewrapper.hpp.
TypeWrapper() [4/5]
constexpr opcua::TypeWrapper< T, Index >::TypeWrapper (const TypeWrapper & other) inline constexpr
Copy constructor (deep copy).
Definition at line 43 of file typewrapper.hpp.
TypeWrapper() [5/5]
constexpr opcua::TypeWrapper< T, Index >::TypeWrapper (TypeWrapper && other) inline constexpr noexcept
Move constructor.
Definition at line 47 of file typewrapper.hpp.