open62541++: opcua::Client::Connection Class Reference
opcua::Client::Connection Class Reference
Public Member Functions
Connection ()
~Connection ()
Connection (const Connection &)=delete
Connection (Connection &&) noexcept=delete
Connection & operator= (const Connection &)=delete
Connection & operator= (Connection &&) noexcept=delete
void setLogger (Logger logger)
UA_Client * handle () noexcept
Detailed Description
Definition at line 28 of file Client.cpp.
Constructor & Destructor Documentation
Connection() [1/3]
opcua::Client::Connection::Connection () inline
Definition at line 30 of file Client.cpp.
References UA_Client_new().
~Connection()
opcua::Client::Connection::~Connection () inline
Definition at line 34 of file Client.cpp.
References UA_Client_delete(), and UA_Client_disconnect().
Connection() [2/3]
opcua::Client::Connection::Connection (const Connection &) delete
Connection() [3/3]
opcua::Client::Connection::Connection (Connection &&) delete noexcept
Member Function Documentation
handle()
UA_Client* opcua::Client::Connection::handle () inline noexcept
Definition at line 49 of file Client.cpp.
operator=() [1/2]
Connection& opcua::Client::Connection::operator= (Connection &&) delete noexcept
operator=() [2/2]
Connection& opcua::Client::Connection::operator= (const Connection &) delete
setLogger()
void opcua::Client::Connection::setLogger (Logger logger) inline
Definition at line 45 of file Client.cpp.
References opcua::CustomLogger::setLogger().