open62541pp: opcua::ua::EUInformation Class Reference
opcua::ua::EUInformation Class Reference
Wrapper classes
#include <types.hpp>
Detailed Description
UA_EUInformation wrapper class.
See also
https://reference.opcfoundation.org/Core/Part8/v105/docs/5.6.3
Definition at line 2576 of file types.hpp.
Public Member Functions
EUInformation (std::string_view namespaceUri, int32_t unitId, LocalizedText displayName, LocalizedText description)
const String & namespaceUri () const noexcept
const String & getNamespaceUri () const noexcept
String & namespaceUri () noexcept
String & getNamespaceUri () noexcept
int32_t unitId () const noexcept
int32_t getUnitId () const noexcept
const LocalizedText & displayName () const noexcept
const LocalizedText & getDisplayName () const noexcept
LocalizedText & displayName () noexcept
LocalizedText & getDisplayName () noexcept
const LocalizedText & description () const noexcept
const LocalizedText & getDescription () const noexcept
LocalizedText & description () noexcept
LocalizedText & getDescription () noexcept
constexpr TypeWrapper () noexcept=default
constexpr TypeWrapper (const T &native)
constexpr TypeWrapper (T &&native) noexcept
constexpr TypeWrapper (const TypeWrapper &other)
constexpr TypeWrapper (TypeWrapper &&other) noexcept
Public Member Functions inherited from opcua::TypeWrapper< UA_EUInformation, UA_TYPES_EUINFORMATION >
constexpr TypeWrapper () noexcept=default
constexpr TypeWrapper (const UA_EUInformation &native)
constexpr TypeWrapper (UA_EUInformation &&native) noexcept
constexpr TypeWrapper (const TypeWrapper &other)
constexpr TypeWrapper (TypeWrapper &&other) noexcept
~TypeWrapper ()
constexpr TypeWrapper & operator= (const TypeWrapper &other)
constexpr TypeWrapper & operator= (const UA_EUInformation &native)
constexpr TypeWrapper & operator= (TypeWrapper &&other) noexcept
constexpr TypeWrapper & operator= (UA_EUInformation &&native) noexcept
Public Member Functions inherited from opcua::Wrapper< UA_EUInformation >
constexpr Wrapper () noexcept=default
constexpr Wrapper (const UA_EUInformation &native) noexcept
constexpr Wrapper (UA_EUInformation &&native) noexcept
constexpr Wrapper & operator= (const UA_EUInformation &native) noexcept
constexpr Wrapper & operator= (UA_EUInformation &&native) noexcept
constexpr operator UA_EUInformation & () noexcept
constexpr operator const UA_EUInformation & () const noexcept
constexpr UA_EUInformation * operator-> () noexcept
constexpr const UA_EUInformation * operator-> () const noexcept
constexpr UA_EUInformation * handle () noexcept
constexpr const UA_EUInformation * handle () const noexcept
constexpr void swap (Wrapper &other) noexcept
constexpr void swap (UA_EUInformation &native) noexcept
Additional Inherited Members
Public Types inherited from opcua::Wrapper< UA_EUInformation >
using NativeType
Static Public Member Functions inherited from opcua::TypeWrapper< UA_EUInformation, UA_TYPES_EUINFORMATION >
static constexpr TypeIndex typeIndex ()
Protected Member Functions inherited from opcua::TypeWrapper< UA_EUInformation, UA_TYPES_EUINFORMATION >
constexpr void clear () noexcept
Protected Member Functions inherited from opcua::Wrapper< UA_EUInformation >
constexpr const UA_EUInformation & native () const noexcept
constexpr UA_EUInformation & native () noexcept
Related Symbols inherited from opcua::TypeWrapper< UA_EUInformation, UA_TYPES_EUINFORMATION >
String toString (const UA_EUInformation &object, const UA_DataType &type)
String toString (const UA_EUInformation &object)
String toString (const UA_EUInformation &object, const UA_DataType &type)
String toString (const UA_EUInformation &object)
Related Symbols inherited from opcua::Wrapper< UA_EUInformation >
constexpr WrapperType * asWrapper (NativeType *native) noexcept
constexpr const WrapperType * asWrapper (const NativeType *native) noexcept
constexpr WrapperType & asWrapper (NativeType &native) noexcept
constexpr const WrapperType & asWrapper (const NativeType &native) noexcept
constexpr NativeType * asNative (WrapperType *wrapper) noexcept
constexpr const NativeType * asNative (const WrapperType *wrapper) noexcept
constexpr NativeType & asNative (WrapperType &wrapper) noexcept
constexpr const NativeType & asNative (const WrapperType &wrapper) noexcept
constexpr WrapperType * asWrapper (NativeType *native) noexcept
constexpr const WrapperType * asWrapper (const NativeType *native) noexcept
constexpr WrapperType & asWrapper (NativeType &native) noexcept
constexpr const WrapperType & asWrapper (const NativeType &native) noexcept
constexpr NativeType * asNative (WrapperType *wrapper) noexcept
constexpr const NativeType * asNative (const WrapperType *wrapper) noexcept
constexpr NativeType & asNative (WrapperType &wrapper) noexcept
constexpr const NativeType & asNative (const WrapperType &wrapper) noexcept
Constructor & Destructor Documentation
EUInformation()
opcua::ua::EUInformation::EUInformation (std::string_view namespaceUri, int32_t unitId, LocalizedText displayName, LocalizedText description) inline
Definition at line 2580 of file types.hpp.
Member Function Documentation
namespaceUri() [1/2]
const String & opcua::ua::EUInformation::namespaceUri () const inline noexcept
Definition at line 2592 of file types.hpp.
Referenced by EUInformation(), and getNamespaceUri().
getNamespaceUri() [1/2]
const String & opcua::ua::EUInformation::getNamespaceUri () const inline noexcept
Deprecated
Use namespaceUri instead
Definition at line 2592 of file types.hpp.
Referenced by getNamespaceUri().
namespaceUri() [2/2]
String & opcua::ua::EUInformation::namespaceUri () inline noexcept
Definition at line 2592 of file types.hpp.
getNamespaceUri() [2/2]
String & opcua::ua::EUInformation::getNamespaceUri () inline noexcept
Deprecated
Use namespaceUri instead
Definition at line 2592 of file types.hpp.
unitId()
int32_t opcua::ua::EUInformation::unitId () const inline noexcept
Definition at line 2593 of file types.hpp.
Referenced by EUInformation(), and getUnitId().
getUnitId()
int32_t opcua::ua::EUInformation::getUnitId () const inline noexcept
Deprecated
Use unitId instead
Definition at line 2593 of file types.hpp.
Referenced by getUnitId().
displayName() [1/2]
const LocalizedText & opcua::ua::EUInformation::displayName () const inline noexcept
Definition at line 2594 of file types.hpp.
Referenced by displayName(), and EUInformation().
getDisplayName() [1/2]
const LocalizedText & opcua::ua::EUInformation::getDisplayName () const inline noexcept
Deprecated
Use displayName instead
Definition at line 2594 of file types.hpp.
Referenced by displayName().
displayName() [2/2]
LocalizedText & opcua::ua::EUInformation::displayName () inline noexcept
Definition at line 2594 of file types.hpp.
getDisplayName() [2/2]
LocalizedText & opcua::ua::EUInformation::getDisplayName () inline noexcept
Deprecated
Use displayName instead
Definition at line 2594 of file types.hpp.
description() [1/2]
const LocalizedText & opcua::ua::EUInformation::description () const inline noexcept
Definition at line 2595 of file types.hpp.
Referenced by description(), and EUInformation().
getDescription() [1/2]
const LocalizedText & opcua::ua::EUInformation::getDescription () const inline noexcept
Deprecated
Use description instead
Definition at line 2595 of file types.hpp.
Referenced by description().
description() [2/2]
LocalizedText & opcua::ua::EUInformation::description () inline noexcept
Definition at line 2595 of file types.hpp.
getDescription() [2/2]
LocalizedText & opcua::ua::EUInformation::getDescription () inline noexcept
Deprecated
Use description instead
Definition at line 2595 of file types.hpp.
TypeWrapper() [1/5]
opcua::TypeWrapper< T, Index >::TypeWrapper () constexpr default noexcept
TypeWrapper() [2/5]
opcua::TypeWrapper< T, Index >::TypeWrapper (const T & native) inline explicit constexpr
Constructor with native object (deep copy).
Definition at line 31 of file typewrapper.hpp.
TypeWrapper() [3/5]
opcua::TypeWrapper< T, Index >::TypeWrapper (T && native) inline constexpr noexcept
Constructor with native object (move rvalue).
Definition at line 35 of file typewrapper.hpp.
TypeWrapper() [4/5]
opcua::TypeWrapper< T, Index >::TypeWrapper (const TypeWrapper & other) inline constexpr
Copy constructor (deep copy).
Definition at line 43 of file typewrapper.hpp.
TypeWrapper() [5/5]
opcua::TypeWrapper< T, Index >::TypeWrapper (TypeWrapper && other) inline constexpr noexcept
Move constructor.
Definition at line 47 of file typewrapper.hpp.