open62541pp: opcua::ua::AddNodesItem Class Reference
opcua::ua::AddNodesItem Class Reference
Wrapper classes
#include <types.hpp>
Detailed Description
UA_AddNodesItem wrapper class.
See also
https://reference.opcfoundation.org/Core/Part4/v105/docs/5.7.2
Definition at line 759 of file types.hpp.
Public Member Functions
AddNodesItem (ExpandedNodeId parentNodeId, NodeId referenceTypeId, ExpandedNodeId requestedNewNodeId, QualifiedName browseName, NodeClass nodeClass, ExtensionObject nodeAttributes, ExpandedNodeId typeDefinition)
const ExpandedNodeId & parentNodeId () const noexcept
const ExpandedNodeId & getParentNodeId () const noexcept
ExpandedNodeId & parentNodeId () noexcept
ExpandedNodeId & getParentNodeId () noexcept
const NodeId & referenceTypeId () const noexcept
const NodeId & getReferenceTypeId () const noexcept
NodeId & referenceTypeId () noexcept
NodeId & getReferenceTypeId () noexcept
const ExpandedNodeId & requestedNewNodeId () const noexcept
const ExpandedNodeId & getRequestedNewNodeId () const noexcept
ExpandedNodeId & requestedNewNodeId () noexcept
ExpandedNodeId & getRequestedNewNodeId () noexcept
const QualifiedName & browseName () const noexcept
const QualifiedName & getBrowseName () const noexcept
QualifiedName & browseName () noexcept
QualifiedName & getBrowseName () noexcept
NodeClass nodeClass () const noexcept
NodeClass getNodeClass () const noexcept
const ExtensionObject & nodeAttributes () const noexcept
const ExtensionObject & getNodeAttributes () const noexcept
ExtensionObject & nodeAttributes () noexcept
ExtensionObject & getNodeAttributes () noexcept
const ExpandedNodeId & typeDefinition () const noexcept
const ExpandedNodeId & getTypeDefinition () const noexcept
ExpandedNodeId & typeDefinition () noexcept
ExpandedNodeId & getTypeDefinition () noexcept
constexpr TypeWrapper () noexcept=default
constexpr TypeWrapper (const T &native)
constexpr TypeWrapper (T &&native) noexcept
constexpr TypeWrapper (const TypeWrapper &other)
constexpr TypeWrapper (TypeWrapper &&other) noexcept
Public Member Functions inherited from opcua::TypeWrapper< UA_AddNodesItem, UA_TYPES_ADDNODESITEM >
constexpr TypeWrapper () noexcept=default
constexpr TypeWrapper (const UA_AddNodesItem &native)
constexpr TypeWrapper (UA_AddNodesItem &&native) noexcept
constexpr TypeWrapper (const TypeWrapper &other)
constexpr TypeWrapper (TypeWrapper &&other) noexcept
~TypeWrapper ()
constexpr TypeWrapper & operator= (const TypeWrapper &other)
constexpr TypeWrapper & operator= (const UA_AddNodesItem &native)
constexpr TypeWrapper & operator= (TypeWrapper &&other) noexcept
constexpr TypeWrapper & operator= (UA_AddNodesItem &&native) noexcept
Public Member Functions inherited from opcua::Wrapper< UA_AddNodesItem >
constexpr Wrapper () noexcept=default
constexpr Wrapper (const UA_AddNodesItem &native) noexcept
constexpr Wrapper (UA_AddNodesItem &&native) noexcept
constexpr Wrapper & operator= (const UA_AddNodesItem &native) noexcept
constexpr Wrapper & operator= (UA_AddNodesItem &&native) noexcept
constexpr operator UA_AddNodesItem & () noexcept
constexpr operator const UA_AddNodesItem & () const noexcept
constexpr UA_AddNodesItem * operator-> () noexcept
constexpr const UA_AddNodesItem * operator-> () const noexcept
constexpr UA_AddNodesItem * handle () noexcept
constexpr const UA_AddNodesItem * handle () const noexcept
constexpr void swap (Wrapper &other) noexcept
constexpr void swap (UA_AddNodesItem &native) noexcept
Additional Inherited Members
Public Types inherited from opcua::Wrapper< UA_AddNodesItem >
using NativeType
Static Public Member Functions inherited from opcua::TypeWrapper< UA_AddNodesItem, UA_TYPES_ADDNODESITEM >
static constexpr TypeIndex typeIndex ()
Protected Member Functions inherited from opcua::TypeWrapper< UA_AddNodesItem, UA_TYPES_ADDNODESITEM >
constexpr void clear () noexcept
Protected Member Functions inherited from opcua::Wrapper< UA_AddNodesItem >
constexpr const UA_AddNodesItem & native () const noexcept
constexpr UA_AddNodesItem & native () noexcept
Related Symbols inherited from opcua::TypeWrapper< UA_AddNodesItem, UA_TYPES_ADDNODESITEM >
String toString (const UA_AddNodesItem &object, const UA_DataType &type)
String toString (const UA_AddNodesItem &object)
String toString (const UA_AddNodesItem &object, const UA_DataType &type)
String toString (const UA_AddNodesItem &object)
Related Symbols inherited from opcua::Wrapper< UA_AddNodesItem >
constexpr WrapperType * asWrapper (NativeType *native) noexcept
constexpr const WrapperType * asWrapper (const NativeType *native) noexcept
constexpr WrapperType & asWrapper (NativeType &native) noexcept
constexpr const WrapperType & asWrapper (const NativeType &native) noexcept
constexpr NativeType * asNative (WrapperType *wrapper) noexcept
constexpr const NativeType * asNative (const WrapperType *wrapper) noexcept
constexpr NativeType & asNative (WrapperType &wrapper) noexcept
constexpr const NativeType & asNative (const WrapperType &wrapper) noexcept
constexpr WrapperType * asWrapper (NativeType *native) noexcept
constexpr const WrapperType * asWrapper (const NativeType *native) noexcept
constexpr WrapperType & asWrapper (NativeType &native) noexcept
constexpr const WrapperType & asWrapper (const NativeType &native) noexcept
constexpr NativeType * asNative (WrapperType *wrapper) noexcept
constexpr const NativeType * asNative (const WrapperType *wrapper) noexcept
constexpr NativeType & asNative (WrapperType &wrapper) noexcept
constexpr const NativeType & asNative (const WrapperType &wrapper) noexcept
Constructor & Destructor Documentation
AddNodesItem()
opcua::ua::AddNodesItem::AddNodesItem (ExpandedNodeId parentNodeId, NodeId referenceTypeId, ExpandedNodeId requestedNewNodeId, QualifiedName browseName, NodeClass nodeClass, ExtensionObject nodeAttributes, ExpandedNodeId typeDefinition) inline
Definition at line 763 of file types.hpp.
Member Function Documentation
parentNodeId() [1/2]
const ExpandedNodeId & opcua::ua::AddNodesItem::parentNodeId () const inline noexcept
Definition at line 781 of file types.hpp.
Referenced by AddNodesItem(), and getParentNodeId().
getParentNodeId() [1/2]
const ExpandedNodeId & opcua::ua::AddNodesItem::getParentNodeId () const inline noexcept
Deprecated
Use parentNodeId instead
Definition at line 781 of file types.hpp.
Referenced by getParentNodeId().
parentNodeId() [2/2]
ExpandedNodeId & opcua::ua::AddNodesItem::parentNodeId () inline noexcept
Definition at line 781 of file types.hpp.
getParentNodeId() [2/2]
ExpandedNodeId & opcua::ua::AddNodesItem::getParentNodeId () inline noexcept
Deprecated
Use parentNodeId instead
Definition at line 781 of file types.hpp.
referenceTypeId() [1/2]
const NodeId & opcua::ua::AddNodesItem::referenceTypeId () const inline noexcept
Definition at line 782 of file types.hpp.
Referenced by AddNodesItem(), and getReferenceTypeId().
getReferenceTypeId() [1/2]
const NodeId & opcua::ua::AddNodesItem::getReferenceTypeId () const inline noexcept
Deprecated
Use referenceTypeId instead
Definition at line 782 of file types.hpp.
Referenced by getReferenceTypeId().
referenceTypeId() [2/2]
NodeId & opcua::ua::AddNodesItem::referenceTypeId () inline noexcept
Definition at line 782 of file types.hpp.
getReferenceTypeId() [2/2]
NodeId & opcua::ua::AddNodesItem::getReferenceTypeId () inline noexcept
Deprecated
Use referenceTypeId instead
Definition at line 782 of file types.hpp.
requestedNewNodeId() [1/2]
const ExpandedNodeId & opcua::ua::AddNodesItem::requestedNewNodeId () const inline noexcept
Definition at line 783 of file types.hpp.
Referenced by AddNodesItem(), and getRequestedNewNodeId().
getRequestedNewNodeId() [1/2]
const ExpandedNodeId & opcua::ua::AddNodesItem::getRequestedNewNodeId () const inline noexcept
Deprecated
Use requestedNewNodeId instead
Definition at line 783 of file types.hpp.
Referenced by getRequestedNewNodeId().
requestedNewNodeId() [2/2]
ExpandedNodeId & opcua::ua::AddNodesItem::requestedNewNodeId () inline noexcept
Definition at line 783 of file types.hpp.
getRequestedNewNodeId() [2/2]
ExpandedNodeId & opcua::ua::AddNodesItem::getRequestedNewNodeId () inline noexcept
Deprecated
Use requestedNewNodeId instead
Definition at line 783 of file types.hpp.
browseName() [1/2]
const QualifiedName & opcua::ua::AddNodesItem::browseName () const inline noexcept
Definition at line 784 of file types.hpp.
Referenced by AddNodesItem(), and browseName().
getBrowseName() [1/2]
const QualifiedName & opcua::ua::AddNodesItem::getBrowseName () const inline noexcept
Deprecated
Use browseName instead
Definition at line 784 of file types.hpp.
Referenced by browseName().
browseName() [2/2]
QualifiedName & opcua::ua::AddNodesItem::browseName () inline noexcept
Definition at line 784 of file types.hpp.
getBrowseName() [2/2]
QualifiedName & opcua::ua::AddNodesItem::getBrowseName () inline noexcept
Deprecated
Use browseName instead
Definition at line 784 of file types.hpp.
nodeClass()
NodeClass opcua::ua::AddNodesItem::nodeClass () const inline noexcept
Definition at line 785 of file types.hpp.
Referenced by AddNodesItem(), and getNodeClass().
getNodeClass()
NodeClass opcua::ua::AddNodesItem::getNodeClass () const inline noexcept
Deprecated
Use nodeClass instead
Definition at line 785 of file types.hpp.
Referenced by getNodeClass().
nodeAttributes() [1/2]
const ExtensionObject & opcua::ua::AddNodesItem::nodeAttributes () const inline noexcept
Definition at line 786 of file types.hpp.
Referenced by AddNodesItem(), and getNodeAttributes().
getNodeAttributes() [1/2]
const ExtensionObject & opcua::ua::AddNodesItem::getNodeAttributes () const inline noexcept
Deprecated
Use nodeAttributes instead
Definition at line 786 of file types.hpp.
Referenced by getNodeAttributes().
nodeAttributes() [2/2]
ExtensionObject & opcua::ua::AddNodesItem::nodeAttributes () inline noexcept
Definition at line 786 of file types.hpp.
getNodeAttributes() [2/2]
ExtensionObject & opcua::ua::AddNodesItem::getNodeAttributes () inline noexcept
Deprecated
Use nodeAttributes instead
Definition at line 786 of file types.hpp.
typeDefinition() [1/2]
const ExpandedNodeId & opcua::ua::AddNodesItem::typeDefinition () const inline noexcept
Definition at line 787 of file types.hpp.
Referenced by AddNodesItem(), and getTypeDefinition().
getTypeDefinition() [1/2]
const ExpandedNodeId & opcua::ua::AddNodesItem::getTypeDefinition () const inline noexcept
Deprecated
Use typeDefinition instead
Definition at line 787 of file types.hpp.
Referenced by getTypeDefinition().
typeDefinition() [2/2]
ExpandedNodeId & opcua::ua::AddNodesItem::typeDefinition () inline noexcept
Definition at line 787 of file types.hpp.
getTypeDefinition() [2/2]
ExpandedNodeId & opcua::ua::AddNodesItem::getTypeDefinition () inline noexcept
Deprecated
Use typeDefinition instead
Definition at line 787 of file types.hpp.
TypeWrapper() [1/5]
opcua::TypeWrapper< T, Index >::TypeWrapper () constexpr default noexcept
TypeWrapper() [2/5]
opcua::TypeWrapper< T, Index >::TypeWrapper (const T & native) inline explicit constexpr
Constructor with native object (deep copy).
Definition at line 31 of file typewrapper.hpp.
TypeWrapper() [3/5]
opcua::TypeWrapper< T, Index >::TypeWrapper (T && native) inline constexpr noexcept
Constructor with native object (move rvalue).
Definition at line 35 of file typewrapper.hpp.
TypeWrapper() [4/5]
opcua::TypeWrapper< T, Index >::TypeWrapper (const TypeWrapper & other) inline constexpr
Copy constructor (deep copy).
Definition at line 43 of file typewrapper.hpp.
TypeWrapper() [5/5]
opcua::TypeWrapper< T, Index >::TypeWrapper (TypeWrapper && other) inline constexpr noexcept
Move constructor.
Definition at line 47 of file typewrapper.hpp.