open62541++: opcua::CustomLogger Class Reference
opcua::CustomLogger Class Reference
#include <CustomLogger.h>
Public Member Functions
CustomLogger (UA_Logger &logger)
void setLogger (Logger logger)
const Logger & getLogger () const noexcept
Detailed Description
Definition at line 9 of file CustomLogger.h.
Constructor & Destructor Documentation
CustomLogger()
opcua::CustomLogger::CustomLogger (UA_Logger & logger)
Definition at line 38 of file CustomLogger.cpp.
Member Function Documentation
getLogger()
const Logger & opcua::CustomLogger::getLogger () const noexcept
Definition at line 48 of file CustomLogger.cpp.
setLogger()
void opcua::CustomLogger::setLogger (Logger logger)
Definition at line 41 of file CustomLogger.cpp.
References UA_Logger::clear, UA_Logger::context, log(), and UA_Logger::log.
Referenced by opcua::Client::Connection::setLogger(), and opcua::Server::Connection::setLogger().