open62541pp: opcua::ua::AttributeOperand Class Reference
opcua::ua::AttributeOperand Class Reference
Wrapper classes
#include <types.hpp>
Detailed Description
UA_AttributeOperand wrapper class.
See also
https://reference.opcfoundation.org/Core/Part4/v105/docs/7.7.4.4
Definition at line 1776 of file types.hpp.
Public Member Functions
AttributeOperand (NodeId nodeId, std::string_view alias, RelativePath browsePath, AttributeId attributeId, std::string_view indexRange={})
const NodeId & nodeId () const noexcept
const NodeId & getNodeId () const noexcept
NodeId & nodeId () noexcept
NodeId & getNodeId () noexcept
const String & alias () const noexcept
const String & getAlias () const noexcept
String & alias () noexcept
String & getAlias () noexcept
const RelativePath & browsePath () const noexcept
const RelativePath & getBrowsePath () const noexcept
RelativePath & browsePath () noexcept
RelativePath & getBrowsePath () noexcept
AttributeId attributeId () const noexcept
AttributeId getAttributeId () const noexcept
const String & indexRange () const noexcept
const String & getIndexRange () const noexcept
String & indexRange () noexcept
String & getIndexRange () noexcept
constexpr TypeWrapper () noexcept=default
constexpr TypeWrapper (const T &native)
constexpr TypeWrapper (T &&native) noexcept
constexpr TypeWrapper (const TypeWrapper &other)
constexpr TypeWrapper (TypeWrapper &&other) noexcept
Public Member Functions inherited from opcua::TypeWrapper< UA_AttributeOperand, UA_TYPES_ATTRIBUTEOPERAND >
constexpr TypeWrapper () noexcept=default
constexpr TypeWrapper (const UA_AttributeOperand &native)
constexpr TypeWrapper (UA_AttributeOperand &&native) noexcept
constexpr TypeWrapper (const TypeWrapper &other)
constexpr TypeWrapper (TypeWrapper &&other) noexcept
~TypeWrapper ()
constexpr TypeWrapper & operator= (const TypeWrapper &other)
constexpr TypeWrapper & operator= (const UA_AttributeOperand &native)
constexpr TypeWrapper & operator= (TypeWrapper &&other) noexcept
constexpr TypeWrapper & operator= (UA_AttributeOperand &&native) noexcept
Public Member Functions inherited from opcua::Wrapper< UA_AttributeOperand >
constexpr Wrapper () noexcept=default
constexpr Wrapper (const UA_AttributeOperand &native) noexcept
constexpr Wrapper (UA_AttributeOperand &&native) noexcept
constexpr Wrapper & operator= (const UA_AttributeOperand &native) noexcept
constexpr Wrapper & operator= (UA_AttributeOperand &&native) noexcept
constexpr operator UA_AttributeOperand & () noexcept
constexpr operator const UA_AttributeOperand & () const noexcept
constexpr UA_AttributeOperand * operator-> () noexcept
constexpr const UA_AttributeOperand * operator-> () const noexcept
constexpr UA_AttributeOperand * handle () noexcept
constexpr const UA_AttributeOperand * handle () const noexcept
constexpr void swap (Wrapper &other) noexcept
constexpr void swap (UA_AttributeOperand &native) noexcept
Additional Inherited Members
Public Types inherited from opcua::Wrapper< UA_AttributeOperand >
using NativeType
Static Public Member Functions inherited from opcua::TypeWrapper< UA_AttributeOperand, UA_TYPES_ATTRIBUTEOPERAND >
static constexpr TypeIndex typeIndex ()
Protected Member Functions inherited from opcua::TypeWrapper< UA_AttributeOperand, UA_TYPES_ATTRIBUTEOPERAND >
constexpr void clear () noexcept
Protected Member Functions inherited from opcua::Wrapper< UA_AttributeOperand >
constexpr const UA_AttributeOperand & native () const noexcept
constexpr UA_AttributeOperand & native () noexcept
Related Symbols inherited from opcua::TypeWrapper< UA_AttributeOperand, UA_TYPES_ATTRIBUTEOPERAND >
String toString (const UA_AttributeOperand &object, const UA_DataType &type)
String toString (const UA_AttributeOperand &object)
String toString (const UA_AttributeOperand &object, const UA_DataType &type)
String toString (const UA_AttributeOperand &object)
Related Symbols inherited from opcua::Wrapper< UA_AttributeOperand >
constexpr WrapperType * asWrapper (NativeType *native) noexcept
constexpr const WrapperType * asWrapper (const NativeType *native) noexcept
constexpr WrapperType & asWrapper (NativeType &native) noexcept
constexpr const WrapperType & asWrapper (const NativeType &native) noexcept
constexpr NativeType * asNative (WrapperType *wrapper) noexcept
constexpr const NativeType * asNative (const WrapperType *wrapper) noexcept
constexpr NativeType & asNative (WrapperType &wrapper) noexcept
constexpr const NativeType & asNative (const WrapperType &wrapper) noexcept
constexpr WrapperType * asWrapper (NativeType *native) noexcept
constexpr const WrapperType * asWrapper (const NativeType *native) noexcept
constexpr WrapperType & asWrapper (NativeType &native) noexcept
constexpr const WrapperType & asWrapper (const NativeType &native) noexcept
constexpr NativeType * asNative (WrapperType *wrapper) noexcept
constexpr const NativeType * asNative (const WrapperType *wrapper) noexcept
constexpr NativeType & asNative (WrapperType &wrapper) noexcept
constexpr const NativeType & asNative (const WrapperType &wrapper) noexcept
Constructor & Destructor Documentation
AttributeOperand()
opcua::ua::AttributeOperand::AttributeOperand (NodeId nodeId, std::string_view alias, RelativePath browsePath, AttributeId attributeId, std::string_view indexRange = {}) inline
Definition at line 1780 of file types.hpp.
Member Function Documentation
nodeId() [1/2]
const NodeId & opcua::ua::AttributeOperand::nodeId () const inline noexcept
Definition at line 1794 of file types.hpp.
Referenced by AttributeOperand(), and getNodeId().
getNodeId() [1/2]
const NodeId & opcua::ua::AttributeOperand::getNodeId () const inline noexcept
Deprecated
Use nodeId instead
Definition at line 1794 of file types.hpp.
Referenced by getNodeId().
nodeId() [2/2]
NodeId & opcua::ua::AttributeOperand::nodeId () inline noexcept
Definition at line 1794 of file types.hpp.
getNodeId() [2/2]
NodeId & opcua::ua::AttributeOperand::getNodeId () inline noexcept
Deprecated
Use nodeId instead
Definition at line 1794 of file types.hpp.
alias() [1/2]
const String & opcua::ua::AttributeOperand::alias () const inline noexcept
Definition at line 1795 of file types.hpp.
Referenced by alias(), and AttributeOperand().
getAlias() [1/2]
const String & opcua::ua::AttributeOperand::getAlias () const inline noexcept
Deprecated
Use alias instead
Definition at line 1795 of file types.hpp.
Referenced by alias().
alias() [2/2]
String & opcua::ua::AttributeOperand::alias () inline noexcept
Definition at line 1795 of file types.hpp.
getAlias() [2/2]
String & opcua::ua::AttributeOperand::getAlias () inline noexcept
Deprecated
Use alias instead
Definition at line 1795 of file types.hpp.
browsePath() [1/2]
const RelativePath & opcua::ua::AttributeOperand::browsePath () const inline noexcept
Definition at line 1796 of file types.hpp.
Referenced by AttributeOperand(), and browsePath().
getBrowsePath() [1/2]
const RelativePath & opcua::ua::AttributeOperand::getBrowsePath () const inline noexcept
Deprecated
Use browsePath instead
Definition at line 1796 of file types.hpp.
Referenced by browsePath().
browsePath() [2/2]
RelativePath & opcua::ua::AttributeOperand::browsePath () inline noexcept
Definition at line 1796 of file types.hpp.
getBrowsePath() [2/2]
RelativePath & opcua::ua::AttributeOperand::getBrowsePath () inline noexcept
Deprecated
Use browsePath instead
Definition at line 1796 of file types.hpp.
attributeId()
AttributeId opcua::ua::AttributeOperand::attributeId () const inline noexcept
Definition at line 1797 of file types.hpp.
Referenced by attributeId(), and AttributeOperand().
getAttributeId()
AttributeId opcua::ua::AttributeOperand::getAttributeId () const inline noexcept
Deprecated
Use attributeId instead
Definition at line 1797 of file types.hpp.
Referenced by attributeId().
indexRange() [1/2]
const String & opcua::ua::AttributeOperand::indexRange () const inline noexcept
Definition at line 1798 of file types.hpp.
Referenced by AttributeOperand(), and getIndexRange().
getIndexRange() [1/2]
const String & opcua::ua::AttributeOperand::getIndexRange () const inline noexcept
Deprecated
Use indexRange instead
Definition at line 1798 of file types.hpp.
Referenced by getIndexRange().
indexRange() [2/2]
String & opcua::ua::AttributeOperand::indexRange () inline noexcept
Definition at line 1798 of file types.hpp.
getIndexRange() [2/2]
String & opcua::ua::AttributeOperand::getIndexRange () inline noexcept
Deprecated
Use indexRange instead
Definition at line 1798 of file types.hpp.
TypeWrapper() [1/5]
opcua::TypeWrapper< T, Index >::TypeWrapper () constexpr default noexcept
TypeWrapper() [2/5]
opcua::TypeWrapper< T, Index >::TypeWrapper (const T & native) inline explicit constexpr
Constructor with native object (deep copy).
Definition at line 31 of file typewrapper.hpp.
TypeWrapper() [3/5]
opcua::TypeWrapper< T, Index >::TypeWrapper (T && native) inline constexpr noexcept
Constructor with native object (move rvalue).
Definition at line 35 of file typewrapper.hpp.
TypeWrapper() [4/5]
opcua::TypeWrapper< T, Index >::TypeWrapper (const TypeWrapper & other) inline constexpr
Copy constructor (deep copy).
Definition at line 43 of file typewrapper.hpp.
TypeWrapper() [5/5]
opcua::TypeWrapper< T, Index >::TypeWrapper (TypeWrapper && other) inline constexpr noexcept
Move constructor.
Definition at line 47 of file typewrapper.hpp.