open62541pp: opcua::ua::DeleteReferencesItem Class Reference
opcua::ua::DeleteReferencesItem Class Reference
Wrapper classes
#include <types.hpp>
Detailed Description
UA_DeleteReferencesItem wrapper class.
See also
https://reference.opcfoundation.org/Core/Part4/v105/docs/5.7.5
Definition at line 961 of file types.hpp.
Public Member Functions
DeleteReferencesItem (NodeId sourceNodeId, NodeId referenceTypeId, bool isForward, ExpandedNodeId targetNodeId, bool deleteBidirectional)
const NodeId & sourceNodeId () const noexcept
const NodeId & getSourceNodeId () const noexcept
NodeId & sourceNodeId () noexcept
NodeId & getSourceNodeId () noexcept
const NodeId & referenceTypeId () const noexcept
const NodeId & getReferenceTypeId () const noexcept
NodeId & referenceTypeId () noexcept
NodeId & getReferenceTypeId () noexcept
bool isForward () const noexcept
bool getIsForward () const noexcept
const ExpandedNodeId & targetNodeId () const noexcept
const ExpandedNodeId & getTargetNodeId () const noexcept
ExpandedNodeId & targetNodeId () noexcept
ExpandedNodeId & getTargetNodeId () noexcept
bool deleteBidirectional () const noexcept
bool getDeleteBidirectional () const noexcept
constexpr TypeWrapper () noexcept=default
constexpr TypeWrapper (const T &native)
constexpr TypeWrapper (T &&native) noexcept
constexpr TypeWrapper (const TypeWrapper &other)
constexpr TypeWrapper (TypeWrapper &&other) noexcept
Public Member Functions inherited from opcua::TypeWrapper< UA_DeleteReferencesItem, UA_TYPES_DELETEREFERENCESITEM >
constexpr TypeWrapper () noexcept=default
constexpr TypeWrapper (const UA_DeleteReferencesItem &native)
constexpr TypeWrapper (UA_DeleteReferencesItem &&native) noexcept
constexpr TypeWrapper (const TypeWrapper &other)
constexpr TypeWrapper (TypeWrapper &&other) noexcept
~TypeWrapper ()
constexpr TypeWrapper & operator= (const TypeWrapper &other)
constexpr TypeWrapper & operator= (const UA_DeleteReferencesItem &native)
constexpr TypeWrapper & operator= (TypeWrapper &&other) noexcept
constexpr TypeWrapper & operator= (UA_DeleteReferencesItem &&native) noexcept
Public Member Functions inherited from opcua::Wrapper< UA_DeleteReferencesItem >
constexpr Wrapper () noexcept=default
constexpr Wrapper (const UA_DeleteReferencesItem &native) noexcept
constexpr Wrapper (UA_DeleteReferencesItem &&native) noexcept
constexpr Wrapper & operator= (const UA_DeleteReferencesItem &native) noexcept
constexpr Wrapper & operator= (UA_DeleteReferencesItem &&native) noexcept
constexpr operator UA_DeleteReferencesItem & () noexcept
constexpr operator const UA_DeleteReferencesItem & () const noexcept
constexpr UA_DeleteReferencesItem * operator-> () noexcept
constexpr const UA_DeleteReferencesItem * operator-> () const noexcept
constexpr UA_DeleteReferencesItem * handle () noexcept
constexpr const UA_DeleteReferencesItem * handle () const noexcept
constexpr void swap (Wrapper &other) noexcept
constexpr void swap (UA_DeleteReferencesItem &native) noexcept
Additional Inherited Members
Public Types inherited from opcua::Wrapper< UA_DeleteReferencesItem >
using NativeType
Static Public Member Functions inherited from opcua::TypeWrapper< UA_DeleteReferencesItem, UA_TYPES_DELETEREFERENCESITEM >
static constexpr TypeIndex typeIndex ()
Protected Member Functions inherited from opcua::TypeWrapper< UA_DeleteReferencesItem, UA_TYPES_DELETEREFERENCESITEM >
constexpr void clear () noexcept
Protected Member Functions inherited from opcua::Wrapper< UA_DeleteReferencesItem >
constexpr const UA_DeleteReferencesItem & native () const noexcept
constexpr UA_DeleteReferencesItem & native () noexcept
Related Symbols inherited from opcua::TypeWrapper< UA_DeleteReferencesItem, UA_TYPES_DELETEREFERENCESITEM >
String toString (const UA_DeleteReferencesItem &object, const UA_DataType &type)
String toString (const UA_DeleteReferencesItem &object)
String toString (const UA_DeleteReferencesItem &object, const UA_DataType &type)
String toString (const UA_DeleteReferencesItem &object)
Related Symbols inherited from opcua::Wrapper< UA_DeleteReferencesItem >
constexpr WrapperType * asWrapper (NativeType *native) noexcept
constexpr const WrapperType * asWrapper (const NativeType *native) noexcept
constexpr WrapperType & asWrapper (NativeType &native) noexcept
constexpr const WrapperType & asWrapper (const NativeType &native) noexcept
constexpr NativeType * asNative (WrapperType *wrapper) noexcept
constexpr const NativeType * asNative (const WrapperType *wrapper) noexcept
constexpr NativeType & asNative (WrapperType &wrapper) noexcept
constexpr const NativeType & asNative (const WrapperType &wrapper) noexcept
constexpr WrapperType * asWrapper (NativeType *native) noexcept
constexpr const WrapperType * asWrapper (const NativeType *native) noexcept
constexpr WrapperType & asWrapper (NativeType &native) noexcept
constexpr const WrapperType & asWrapper (const NativeType &native) noexcept
constexpr NativeType * asNative (WrapperType *wrapper) noexcept
constexpr const NativeType * asNative (const WrapperType *wrapper) noexcept
constexpr NativeType & asNative (WrapperType &wrapper) noexcept
constexpr const NativeType & asNative (const WrapperType &wrapper) noexcept
Constructor & Destructor Documentation
DeleteReferencesItem()
opcua::ua::DeleteReferencesItem::DeleteReferencesItem (NodeId sourceNodeId, NodeId referenceTypeId, bool isForward, ExpandedNodeId targetNodeId, bool deleteBidirectional) inline
Definition at line 966 of file types.hpp.
Member Function Documentation
sourceNodeId() [1/2]
const NodeId & opcua::ua::DeleteReferencesItem::sourceNodeId () const inline noexcept
Definition at line 980 of file types.hpp.
Referenced by DeleteReferencesItem(), and getSourceNodeId().
getSourceNodeId() [1/2]
const NodeId & opcua::ua::DeleteReferencesItem::getSourceNodeId () const inline noexcept
Deprecated
Use sourceNodeId instead
Definition at line 980 of file types.hpp.
Referenced by getSourceNodeId().
sourceNodeId() [2/2]
NodeId & opcua::ua::DeleteReferencesItem::sourceNodeId () inline noexcept
Definition at line 980 of file types.hpp.
getSourceNodeId() [2/2]
NodeId & opcua::ua::DeleteReferencesItem::getSourceNodeId () inline noexcept
Deprecated
Use sourceNodeId instead
Definition at line 980 of file types.hpp.
referenceTypeId() [1/2]
const NodeId & opcua::ua::DeleteReferencesItem::referenceTypeId () const inline noexcept
Definition at line 981 of file types.hpp.
Referenced by DeleteReferencesItem(), and getReferenceTypeId().
getReferenceTypeId() [1/2]
const NodeId & opcua::ua::DeleteReferencesItem::getReferenceTypeId () const inline noexcept
Deprecated
Use referenceTypeId instead
Definition at line 981 of file types.hpp.
Referenced by getReferenceTypeId().
referenceTypeId() [2/2]
NodeId & opcua::ua::DeleteReferencesItem::referenceTypeId () inline noexcept
Definition at line 981 of file types.hpp.
getReferenceTypeId() [2/2]
NodeId & opcua::ua::DeleteReferencesItem::getReferenceTypeId () inline noexcept
Deprecated
Use referenceTypeId instead
Definition at line 981 of file types.hpp.
isForward()
bool opcua::ua::DeleteReferencesItem::isForward () const inline noexcept
Definition at line 982 of file types.hpp.
Referenced by DeleteReferencesItem(), and getIsForward().
getIsForward()
bool opcua::ua::DeleteReferencesItem::getIsForward () const inline noexcept
Deprecated
Use isForward instead
Definition at line 982 of file types.hpp.
Referenced by getIsForward().
targetNodeId() [1/2]
const ExpandedNodeId & opcua::ua::DeleteReferencesItem::targetNodeId () const inline noexcept
Definition at line 983 of file types.hpp.
Referenced by DeleteReferencesItem(), and getTargetNodeId().
getTargetNodeId() [1/2]
const ExpandedNodeId & opcua::ua::DeleteReferencesItem::getTargetNodeId () const inline noexcept
Deprecated
Use targetNodeId instead
Definition at line 983 of file types.hpp.
Referenced by getTargetNodeId().
targetNodeId() [2/2]
ExpandedNodeId & opcua::ua::DeleteReferencesItem::targetNodeId () inline noexcept
Definition at line 983 of file types.hpp.
getTargetNodeId() [2/2]
ExpandedNodeId & opcua::ua::DeleteReferencesItem::getTargetNodeId () inline noexcept
Deprecated
Use targetNodeId instead
Definition at line 983 of file types.hpp.
deleteBidirectional()
bool opcua::ua::DeleteReferencesItem::deleteBidirectional () const inline noexcept
Definition at line 984 of file types.hpp.
Referenced by deleteBidirectional(), and DeleteReferencesItem().
getDeleteBidirectional()
bool opcua::ua::DeleteReferencesItem::getDeleteBidirectional () const inline noexcept
Deprecated
Use deleteBidirectional instead
Definition at line 984 of file types.hpp.
Referenced by deleteBidirectional().
TypeWrapper() [1/5]
opcua::TypeWrapper< T, Index >::TypeWrapper () constexpr default noexcept
TypeWrapper() [2/5]
opcua::TypeWrapper< T, Index >::TypeWrapper (const T & native) inline explicit constexpr
Constructor with native object (deep copy).
Definition at line 31 of file typewrapper.hpp.
TypeWrapper() [3/5]
opcua::TypeWrapper< T, Index >::TypeWrapper (T && native) inline constexpr noexcept
Constructor with native object (move rvalue).
Definition at line 35 of file typewrapper.hpp.
TypeWrapper() [4/5]
opcua::TypeWrapper< T, Index >::TypeWrapper (const TypeWrapper & other) inline constexpr
Copy constructor (deep copy).
Definition at line 43 of file typewrapper.hpp.
TypeWrapper() [5/5]
opcua::TypeWrapper< T, Index >::TypeWrapper (TypeWrapper && other) inline constexpr noexcept
Move constructor.
Definition at line 47 of file typewrapper.hpp.