open62541pp: opcua::MonitoredItem< Connection > Class Template Reference
opcua::MonitoredItem< Connection > Class Template Reference
#include <monitoreditem.hpp>
Detailed Description
template<typename Connection>
class opcua::MonitoredItem< Connection >
High-level monitored item class.
Template Parameters
Connection Server or Client
Note
Not all methods are available and implemented for servers.
Use the free functions in the opcua::services namespace for more advanced usage:
MonitoredItem service set
Examples
client_subscription.cpp, and events/client_eventfilter.cpp.
Definition at line 29 of file monitoreditem.hpp.
Public Member Functions
MonitoredItem (Connection &connection, IntegerId subscriptionId, IntegerId monitoredItemId) noexcept
Connection & connection () noexcept
const Connection & connection () const noexcept
IntegerId subscriptionId () const noexcept
IntegerId monitoredItemId () const noexcept
const NodeId & nodeId ()
AttributeId attributeId ()
void setMonitoringParameters (const MonitoringParametersEx &parameters)
void setMonitoringMode (MonitoringMode monitoringMode)
void deleteMonitoredItem ()
Related Symbols
(Note that these are not member symbols.)
template<typename T >
bool operator== (const MonitoredItem< T > &lhs, const MonitoredItem< T > &rhs) noexcept
template<typename T >
bool operator!= (const MonitoredItem< T > &lhs, const MonitoredItem< T > &rhs) noexcept
Constructor & Destructor Documentation
MonitoredItem()
template<typename Connection > opcua::MonitoredItem< Connection >::MonitoredItem (Connection & connection, IntegerId subscriptionId, IntegerId monitoredItemId) inline noexcept
Wrap an existing monitored item.
The subscriptionId is ignored and set to 0U for servers.
Definition at line 33 of file monitoreditem.hpp.
Member Function Documentation
attributeId()
template<typename Connection > AttributeId opcua::MonitoredItem< Connection >::attributeId ()
Get the monitored AttributeId.
connection() [1/2]
template<typename Connection > const Connection & opcua::MonitoredItem< Connection >::connection () const inline noexcept
Get the server/client instance.
Definition at line 46 of file monitoreditem.hpp.
connection() [2/2]
template<typename Connection > Connection & opcua::MonitoredItem< Connection >::connection () inline noexcept
Get the server/client instance.
Definition at line 41 of file monitoreditem.hpp.
Referenced by opcua::MonitoredItem< Connection >::deleteMonitoredItem(), opcua::MonitoredItem< Connection >::MonitoredItem(), opcua::MonitoredItem< Connection >::setMonitoringMode(), and opcua::MonitoredItem< Connection >::setMonitoringParameters().
deleteMonitoredItem()
template<typename Connection > void opcua::MonitoredItem< Connection >::deleteMonitoredItem () inline
Delete this monitored item.
See also
services::deleteMonitoredItem
Definition at line 87 of file monitoreditem.hpp.
monitoredItemId()
template<typename Connection > IntegerId opcua::MonitoredItem< Connection >::monitoredItemId () const inline noexcept
Get the server-assigned identifier of this monitored item.
Definition at line 56 of file monitoreditem.hpp.
Referenced by opcua::MonitoredItem< Connection >::deleteMonitoredItem(), opcua::MonitoredItem< Connection >::setMonitoringMode(), and opcua::MonitoredItem< Connection >::setMonitoringParameters().
nodeId()
template<typename Connection > const NodeId & opcua::MonitoredItem< Connection >::nodeId ()
Get the monitored NodeId.
setMonitoringMode()
template<typename Connection > void opcua::MonitoredItem< Connection >::setMonitoringMode (MonitoringMode monitoringMode) inline
Set the monitoring mode of this monitored item.
Note
Not implemented for Server.
See also
services::setMonitoringMode
Definition at line 78 of file monitoreditem.hpp.
setMonitoringParameters()
template<typename Connection > void opcua::MonitoredItem< Connection >::setMonitoringParameters (const MonitoringParametersEx & parameters) inline
Modify this monitored item.
Note
Not implemented for Server.
See also
services::modifyMonitoredItem
Definition at line 69 of file monitoreditem.hpp.
subscriptionId()
template<typename Connection > IntegerId opcua::MonitoredItem< Connection >::subscriptionId () const inline noexcept
Get the server-assigned identifier of the underlying subscription.
Definition at line 51 of file monitoreditem.hpp.
Referenced by opcua::MonitoredItem< Connection >::deleteMonitoredItem(), opcua::MonitoredItem< Connection >::setMonitoringMode(), and opcua::MonitoredItem< Connection >::setMonitoringParameters().
Friends And Related Symbol Documentation
operator!=()
template<typename T > bool operator!= (const MonitoredItem< T > & lhs, const MonitoredItem< T > & rhs) related
Definition at line 110 of file monitoreditem.hpp.
operator==()
template<typename T > bool operator== (const MonitoredItem< T > & lhs, const MonitoredItem< T > & rhs) related
Definition at line 102 of file monitoreditem.hpp.