open62541++: opcua::Bitmask< T > Class Template Reference
opcua::Bitmask< T > Class Template Reference
Bitmask abstraction
#include <Bitmask.h>
Detailed Description
template<typename T>
class opcua::Bitmask< T >
Bitmask using (scoped) enums.
Zero-cost abstraction to specify bitmasks with enums/ints or enum classes.
// construct with scoped enums
Bitmask<NodeClass> mask = NodeClass::Variable | NodeClass::Object;
// construct with unscoped enums or ints
Bitmask<NodeClass> mask = UA_NODECLASS_VARIABLE | UA_NODECLASS_OBJECT;
Template Parameters
T Enumeration type
See also
https://www.strikerx3.dev/cpp/2019/02/27/typesafe-enum-class-bitmasks-in-cpp.html
https://andreasfertig.blog/2024/01/cpp20-concepts-applied/
Examples
server_accesscontrol.cpp.
Definition at line 108 of file Bitmask.h.
Public Types
using Underlying = std::underlying_type_t<T>
Public Member Functions
constexpr Bitmask () noexcept=default
constexpr Bitmask (T mask) noexcept
constexpr Bitmask (Underlying mask) noexcept
constexpr operator T () const noexcept
constexpr operator Underlying () const noexcept
constexpr Underlying get () const noexcept
constexpr Bitmask & set () noexcept
constexpr Bitmask & set (T mask) noexcept
constexpr Bitmask & reset () noexcept
constexpr Bitmask & reset (T mask) noexcept
constexpr Bitmask & flip () noexcept
constexpr bool all () const noexcept
constexpr bool allOf (T mask) const noexcept
constexpr bool any () const noexcept
constexpr bool anyOf (T mask) const noexcept
constexpr bool none () const noexcept
constexpr bool noneOf (T mask) const noexcept
Related Symbols
(Note that these are not member symbols.)
template<typename T , typename U >
constexpr bool operator== (Bitmask< T > lhs, U rhs) noexcept
template<typename T , typename U >
constexpr bool operator!= (Bitmask< T > lhs, U rhs) noexcept
template<typename T , typename U >
constexpr bool operator== (U lhs, Bitmask< T > rhs) noexcept
template<typename T , typename U >
constexpr bool operator!= (U lhs, Bitmask< T > rhs) noexcept
Member Typedef Documentation
Underlying
template<typename T > using opcua::Bitmask< T >::Underlying = std::underlying_type_t<T>
Definition at line 113 of file Bitmask.h.
Constructor & Destructor Documentation
Bitmask() [1/3]
template<typename T > constexpr opcua::Bitmask< T >::Bitmask () constexpr default noexcept
Create an empty bitmask.
Bitmask() [2/3]
template<typename T > constexpr opcua::Bitmask< T >::Bitmask (T mask) inline constexpr noexcept
Create a bitmask from the enumeration type.
Definition at line 119 of file Bitmask.h.
Bitmask() [3/3]
template<typename T > constexpr opcua::Bitmask< T >::Bitmask (Underlying mask) inline constexpr noexcept
Create a bitmask from the underlying type.
Definition at line 123 of file Bitmask.h.
Member Function Documentation
operator T()
template<typename T > constexpr opcua::Bitmask< T >::operator T () const inline explicit constexpr noexcept
Conversion to the enum type.
Definition at line 127 of file Bitmask.h.
operator Underlying()
template<typename T > constexpr opcua::Bitmask< T >::operator Underlying () const inline constexpr noexcept
Conversion to the underlying type.
Deprecated
Implicit conversion to integer will be removed. Use the get() method instead.
Definition at line 135 of file Bitmask.h.
get()
template<typename T > constexpr Underlying opcua::Bitmask< T >::get () const inline constexpr noexcept
Get the bitmask as the underlying type (integer).
Definition at line 140 of file Bitmask.h.
Referenced by opcua::Bitmask< T >::operator!=(), opcua::Bitmask< T >::operator!=(), opcua::Bitmask< T >::operator==(), and opcua::Bitmask< T >::operator==().
set() [1/2]
template<typename T > constexpr Bitmask & opcua::Bitmask< T >::set () inline constexpr noexcept
Set all bits.
Definition at line 145 of file Bitmask.h.
set() [2/2]
template<typename T > constexpr Bitmask & opcua::Bitmask< T >::set (T mask) inline constexpr noexcept
Set specified bits.
Definition at line 151 of file Bitmask.h.
reset() [1/2]
template<typename T > constexpr Bitmask & opcua::Bitmask< T >::reset () inline constexpr noexcept
Reset all bits.
Definition at line 157 of file Bitmask.h.
reset() [2/2]
template<typename T > constexpr Bitmask & opcua::Bitmask< T >::reset (T mask) inline constexpr noexcept
Reset specified bits.
Definition at line 163 of file Bitmask.h.
flip()
template<typename T > constexpr Bitmask & opcua::Bitmask< T >::flip () inline constexpr noexcept
Flip all bits.
Definition at line 169 of file Bitmask.h.
all()
template<typename T > constexpr bool opcua::Bitmask< T >::all () const inline constexpr noexcept
Check if all bits are set.
Definition at line 175 of file Bitmask.h.
allOf()
template<typename T > constexpr bool opcua::Bitmask< T >::allOf (T mask) const inline constexpr noexcept
Check if all of the specified bits are set.
Definition at line 180 of file Bitmask.h.
any()
template<typename T > constexpr bool opcua::Bitmask< T >::any () const inline constexpr noexcept
Check if any bits are set.
Definition at line 185 of file Bitmask.h.
anyOf()
template<typename T > constexpr bool opcua::Bitmask< T >::anyOf (T mask) const inline constexpr noexcept
Check if any of the specified bits are set.
Definition at line 190 of file Bitmask.h.
none()
template<typename T > constexpr bool opcua::Bitmask< T >::none () const inline constexpr noexcept
Check if none bits are set.
Definition at line 195 of file Bitmask.h.
noneOf()
template<typename T > constexpr bool opcua::Bitmask< T >::noneOf (T mask) const inline constexpr noexcept
Check if none of the specified bits are set.
Definition at line 200 of file Bitmask.h.