open62541++: opcua::QualifiedName Class Reference
opcua::QualifiedName Class Reference
UA_QualifiedName wrapper class.
#include <TypeWrapper.h>
Public Member Functions
QualifiedName (uint16_t namespaceIndex, std::string_view name)
bool operator== (const QualifiedName &other) const
bool operator!= (const QualifiedName &other) const
uint16_t getNamespaceIndex () const
std::string getName () const
Public Member Functions inherited from opcua::TypeWrapper< UA_QualifiedName >
TypeWrapper ()
TypeWrapper (const UA_QualifiedName &data)
Constructor with native UA_* type (deep copy)
TypeWrapper (UA_QualifiedName &&data)
Constructor with native UA_* type (move rvalue)
TypeWrapper (const TypeWrapper &other)
Copy constructor (deep copy)
virtual ~TypeWrapper ()
TypeWrapper & operator= (const TypeWrapper &other)
Copy assignment (deep copy)
UA_QualifiedName * handle ()
Return pointer to wrapped UA data type.
const UA_QualifiedName * handle () const
Return const pointer to wrapped UA data type.
Public Member Functions inherited from opcua::TypeWrapperBase
virtual ~TypeWrapperBase ()
Additional Inherited Members
Public Types inherited from opcua::TypeWrapper< UA_QualifiedName >
using BaseClass = TypeWrapper< UA_QualifiedName, getType< UA_QualifiedName >() >
using UaType = UA_QualifiedName
Static Public Member Functions inherited from opcua::TypeWrapper< UA_QualifiedName >
constexpr static Type getType ()
Return type enum.
constexpr static const UA_DataType * getDataType ()
Return UA_DataType object.
Protected Member Functions inherited from opcua::TypeWrapper< UA_QualifiedName >
void init ()
void clear ()
void copy (const UA_QualifiedName &data)
Deep copy of data.
Protected Attributes inherited from opcua::TypeWrapper< UA_QualifiedName >
UA_QualifiedName data_
Detailed Description
UA_QualifiedName wrapper class.
Definition at line 149 of file TypeWrapper.h.
Constructor & Destructor Documentation
QualifiedName()
opcua::QualifiedName::QualifiedName (uint16_t namespaceIndex, std::string_view name) inline
Definition at line 153 of file TypeWrapper.h.
References opcua::allocUaString(), opcua::TypeWrapper< UA_QualifiedName >::data_, UA_QualifiedName::name, and UA_QualifiedName::namespaceIndex.
Member Function Documentation
getName()
std::string opcua::QualifiedName::getName () const inline
Definition at line 166 of file TypeWrapper.h.
References opcua::TypeWrapper< UA_QualifiedName >::data_, UA_QualifiedName::name, and opcua::uaStringToString().
getNamespaceIndex()
uint16_t opcua::QualifiedName::getNamespaceIndex () const inline
Definition at line 164 of file TypeWrapper.h.
References opcua::TypeWrapper< UA_QualifiedName >::data_, and UA_QualifiedName::namespaceIndex.
operator!=()
bool opcua::QualifiedName::operator!= (const QualifiedName & other) const inline
Definition at line 162 of file TypeWrapper.h.
References operator==().
operator==()
bool opcua::QualifiedName::operator== (const QualifiedName & other) const inline
Definition at line 158 of file TypeWrapper.h.
References opcua::TypeWrapper< UA_QualifiedName >::data_, opcua::TypeWrapper< T, type >::handle(), and UA_QualifiedName_equal().
Referenced by operator!=().
The documentation for this class was generated from the following file:
/home/runner/work/open62541pp/open62541pp/include/open62541pp/TypeWrapper.h