open62541pp: opcua::DataType Class Reference
opcua::DataType Class Reference
Wrapper classes
#include <datatype.hpp>
Detailed Description
UA_DataType wrapper class.
Examples
custom_datatypes/custom_datatypes.hpp.
Definition at line 108 of file datatype.hpp.
Public Member Functions
constexpr DataType () noexcept=default
DataType (const UA_DataType &native)
DataType (UA_DataType &&native) noexcept
DataType (TypeIndex typeIndex)
~DataType ()
DataType (const DataType &other)
DataType (DataType &&other) noexcept
DataType & operator= (const DataType &other)
DataType & operator= (DataType &&other) noexcept
std::string_view typeName () const noexcept
std::string_view getTypeName () const noexcept
void setTypeName (std::string_view typeName) noexcept
NodeId typeId () const noexcept
NodeId getTypeId () const noexcept
void setTypeId (NodeId typeId)
NodeId binaryEncodingId () const noexcept
NodeId getBinaryEncodingId () const noexcept
void setBinaryEncodingId (NodeId binaryEncodingId)
uint16_t memSize () const noexcept
uint16_t getMemSize () const noexcept
void setMemSize (uint16_t memSize) noexcept
uint8_t typeKind () const noexcept
uint8_t getTypeKind () const noexcept
void setTypeKind (uint8_t typeKind) noexcept
bool pointerFree () const noexcept
bool getPointerFree () const noexcept
void setPointerFree (bool pointerFree) noexcept
bool overlayable () const noexcept
bool getOverlayable () const noexcept
void setOverlayable (bool overlayable) noexcept
Span< const DataTypeMember > members () const noexcept
Span< const DataTypeMember > getMembers () const noexcept
void setMembers (Span< const DataTypeMember > members)
Public Member Functions inherited from opcua::Wrapper< UA_DataType >
constexpr Wrapper () noexcept=default
constexpr Wrapper (const UA_DataType &native) noexcept
constexpr Wrapper (UA_DataType &&native) noexcept
constexpr Wrapper & operator= (const UA_DataType &native) noexcept
constexpr Wrapper & operator= (UA_DataType &&native) noexcept
constexpr operator UA_DataType & () noexcept
constexpr operator const UA_DataType & () const noexcept
constexpr UA_DataType * operator-> () noexcept
constexpr const UA_DataType * operator-> () const noexcept
constexpr UA_DataType * handle () noexcept
constexpr const UA_DataType * handle () const noexcept
constexpr void swap (Wrapper &other) noexcept
constexpr void swap (UA_DataType &native) noexcept
Related Symbols
(Note that these are not member symbols.)
bool operator== (const UA_DataType &lhs, const UA_DataType &rhs) noexcept
bool operator!= (const UA_DataType &lhs, const UA_DataType &rhs) noexcept
bool operator== (const UA_DataTypeMember &lhs, const UA_DataTypeMember &rhs) noexcept
bool operator!= (const UA_DataTypeMember &lhs, const UA_DataTypeMember &rhs) noexcept
Related Symbols inherited from opcua::Wrapper< UA_DataType >
constexpr WrapperType * asWrapper (NativeType *native) noexcept
constexpr const WrapperType * asWrapper (const NativeType *native) noexcept
constexpr WrapperType & asWrapper (NativeType &native) noexcept
constexpr const WrapperType & asWrapper (const NativeType &native) noexcept
constexpr NativeType * asNative (WrapperType *wrapper) noexcept
constexpr const NativeType * asNative (const WrapperType *wrapper) noexcept
constexpr NativeType & asNative (WrapperType &wrapper) noexcept
constexpr const NativeType & asNative (const WrapperType &wrapper) noexcept
Additional Inherited Members
Public Types inherited from opcua::Wrapper< UA_DataType >
using NativeType = UA_DataType
Protected Member Functions inherited from opcua::Wrapper< UA_DataType >
constexpr const UA_DataType & native () const noexcept
constexpr UA_DataType & native () noexcept
Constructor & Destructor Documentation
DataType() [1/6]
constexpr opcua::DataType::DataType () constexpr default noexcept
DataType() [2/6]
opcua::DataType::DataType (const UA_DataType & native) explicit
DataType() [3/6]
opcua::DataType::DataType (UA_DataType && native) explicit noexcept
DataType() [4/6]
opcua::DataType::DataType (TypeIndex typeIndex) explicit
~DataType()
opcua::DataType::~DataType ()
DataType() [5/6]
opcua::DataType::DataType (const DataType & other)
DataType() [6/6]
opcua::DataType::DataType (DataType && other) noexcept
Member Function Documentation
operator=() [1/2]
DataType & opcua::DataType::operator= (const DataType & other)
operator=() [2/2]
DataType & opcua::DataType::operator= (DataType && other) noexcept
typeName()
std::string_view opcua::DataType::typeName () const inline noexcept
Definition at line 124 of file datatype.hpp.
Referenced by getTypeName(), and setTypeName().
getTypeName()
std::string_view opcua::DataType::getTypeName () const inline noexcept
Deprecated:
Use typeName() instead
Definition at line 134 of file datatype.hpp.
setTypeName()
void opcua::DataType::setTypeName (std::string_view typeName) inline noexcept
Definition at line 138 of file datatype.hpp.
Referenced by opcua::DataTypeBuilder< T, Tag, U >::createEnum(), opcua::DataTypeBuilder< T, Tag, U >::createStructure(), and opcua::DataTypeBuilder< T, Tag, U >::createUnion().
typeId()
NodeId opcua::DataType::typeId () const inline noexcept
Definition at line 145 of file datatype.hpp.
Referenced by binaryEncodingId(), getTypeId(), setTypeId(), and typeId().
getTypeId()
NodeId opcua::DataType::getTypeId () const inline noexcept
Deprecated:
Use typeId() instead
Definition at line 151 of file datatype.hpp.
setTypeId()
void opcua::DataType::setTypeId (NodeId typeId) inline
Definition at line 155 of file datatype.hpp.
Referenced by opcua::DataTypeBuilder< T, Tag, U >::createEnum(), opcua::DataTypeBuilder< T, Tag, U >::createStructure(), and opcua::DataTypeBuilder< T, Tag, U >::createUnion().
binaryEncodingId()
NodeId opcua::DataType::binaryEncodingId () const inline noexcept
Definition at line 159 of file datatype.hpp.
Referenced by binaryEncodingId(), getBinaryEncodingId(), and setBinaryEncodingId().
getBinaryEncodingId()
NodeId opcua::DataType::getBinaryEncodingId () const inline noexcept
Deprecated:
Use binaryEncodingId() instead
Definition at line 169 of file datatype.hpp.
setBinaryEncodingId()
void opcua::DataType::setBinaryEncodingId (NodeId binaryEncodingId) inline
Definition at line 173 of file datatype.hpp.
Referenced by opcua::DataTypeBuilder< T, Tag, U >::createEnum(), opcua::DataTypeBuilder< T, Tag, U >::createStructure(), and opcua::DataTypeBuilder< T, Tag, U >::createUnion().
memSize()
uint16_t opcua::DataType::memSize () const inline noexcept
Definition at line 181 of file datatype.hpp.
Referenced by getMemSize(), and setMemSize().
getMemSize()
uint16_t opcua::DataType::getMemSize () const inline noexcept
Deprecated:
Use memSize() instead
Definition at line 187 of file datatype.hpp.
setMemSize()
void opcua::DataType::setMemSize (uint16_t memSize) inline noexcept
Definition at line 191 of file datatype.hpp.
Referenced by opcua::DataTypeBuilder< T, Tag, U >::createEnum(), opcua::DataTypeBuilder< T, Tag, U >::createStructure(), and opcua::DataTypeBuilder< T, Tag, U >::createUnion().
typeKind()
uint8_t opcua::DataType::typeKind () const inline noexcept
Definition at line 195 of file datatype.hpp.
Referenced by getTypeKind(), and setTypeKind().
getTypeKind()
uint8_t opcua::DataType::getTypeKind () const inline noexcept
Deprecated:
Use typeKind() instead
Definition at line 201 of file datatype.hpp.
setTypeKind()
void opcua::DataType::setTypeKind (uint8_t typeKind) inline noexcept
Definition at line 205 of file datatype.hpp.
Referenced by opcua::DataTypeBuilder< T, Tag, U >::createEnum(), opcua::DataTypeBuilder< T, Tag, U >::createStructure(), and opcua::DataTypeBuilder< T, Tag, U >::createUnion().
pointerFree()
bool opcua::DataType::pointerFree () const inline noexcept
Definition at line 209 of file datatype.hpp.
Referenced by getPointerFree(), and setPointerFree().
getPointerFree()
bool opcua::DataType::getPointerFree () const inline noexcept
Deprecated:
Use pointerFree() instead
Definition at line 215 of file datatype.hpp.
setPointerFree()
void opcua::DataType::setPointerFree (bool pointerFree) inline noexcept
Definition at line 219 of file datatype.hpp.
Referenced by opcua::DataTypeBuilder< T, Tag, U >::createEnum(), opcua::DataTypeBuilder< T, Tag, U >::createStructure(), and opcua::DataTypeBuilder< T, Tag, U >::createUnion().
overlayable()
bool opcua::DataType::overlayable () const inline noexcept
Definition at line 223 of file datatype.hpp.
Referenced by getOverlayable(), and setOverlayable().
getOverlayable()
bool opcua::DataType::getOverlayable () const inline noexcept
Deprecated:
Use overlayable() instead
Definition at line 229 of file datatype.hpp.
setOverlayable()
void opcua::DataType::setOverlayable (bool overlayable) inline noexcept
Definition at line 233 of file datatype.hpp.
Referenced by opcua::DataTypeBuilder< T, Tag, U >::createEnum(), opcua::DataTypeBuilder< T, Tag, U >::createStructure(), and opcua::DataTypeBuilder< T, Tag, U >::createUnion().
members()
Span< const DataTypeMember > opcua::DataType::members () const inline noexcept
Definition at line 237 of file datatype.hpp.
Referenced by getMembers(), and members().
getMembers()
Span< const DataTypeMember > opcua::DataType::getMembers () const inline noexcept
Deprecated:
Use members() instead
Definition at line 243 of file datatype.hpp.
setMembers()
void opcua::DataType::setMembers (Span< const DataTypeMember > members)
Friends And Related Symbol Documentation
operator==() [1/2]
bool operator== (const UA_DataType & lhs, const UA_DataType & rhs) related
Definition at line 251 of file datatype.hpp.
operator!=() [1/2]
bool operator!= (const UA_DataType & lhs, const UA_DataType & rhs) related
Definition at line 256 of file datatype.hpp.
operator==() [2/2]
bool operator== (const UA_DataTypeMember & lhs, const UA_DataTypeMember & rhs) related
Definition at line 261 of file datatype.hpp.
operator!=() [2/2]
bool operator!= (const UA_DataTypeMember & lhs, const UA_DataTypeMember & rhs) related
Definition at line 273 of file datatype.hpp.