open62541pp: opcua::ua::ApplicationDescription Class Reference
opcua::ua::ApplicationDescription Class Reference
Wrapper classes
#include <types.hpp>
Detailed Description
UA_ApplicationDescription wrapper class.
See also
https://reference.opcfoundation.org/Core/Part4/v105/docs/7.2
Definition at line 166 of file types.hpp.
Public Member Functions
ApplicationDescription (std::string_view applicationUri, std::string_view productUri, LocalizedText applicationName, ApplicationType applicationType, std::string_view gatewayServerUri, std::string_view discoveryProfileUri, Span< const String > discoveryUrls)
const String & applicationUri () const noexcept
const String & getApplicationUri () const noexcept
String & applicationUri () noexcept
String & getApplicationUri () noexcept
const String & productUri () const noexcept
const String & getProductUri () const noexcept
String & productUri () noexcept
String & getProductUri () noexcept
const LocalizedText & applicationName () const noexcept
const LocalizedText & getApplicationName () const noexcept
LocalizedText & applicationName () noexcept
LocalizedText & getApplicationName () noexcept
ApplicationType applicationType () const noexcept
ApplicationType getApplicationType () const noexcept
const String & gatewayServerUri () const noexcept
const String & getGatewayServerUri () const noexcept
String & gatewayServerUri () noexcept
String & getGatewayServerUri () noexcept
const String & discoveryProfileUri () const noexcept
const String & getDiscoveryProfileUri () const noexcept
String & discoveryProfileUri () noexcept
String & getDiscoveryProfileUri () noexcept
Span< const String > discoveryUrls () const noexcept
Span< String > discoveryUrls () noexcept
Span< const String > getDiscoveryUrls () const noexcept
Span< String > getDiscoveryUrls () noexcept
constexpr TypeWrapper () noexcept=default
constexpr TypeWrapper (const T &native)
constexpr TypeWrapper (T &&native) noexcept
constexpr TypeWrapper (const TypeWrapper &other)
constexpr TypeWrapper (TypeWrapper &&other) noexcept
Public Member Functions inherited from opcua::TypeWrapper< UA_ApplicationDescription, UA_TYPES_APPLICATIONDESCRIPTION >
constexpr TypeWrapper () noexcept=default
constexpr TypeWrapper (const UA_ApplicationDescription &native)
constexpr TypeWrapper (UA_ApplicationDescription &&native) noexcept
constexpr TypeWrapper (const TypeWrapper &other)
constexpr TypeWrapper (TypeWrapper &&other) noexcept
~TypeWrapper ()
constexpr TypeWrapper & operator= (const TypeWrapper &other)
constexpr TypeWrapper & operator= (const UA_ApplicationDescription &native)
constexpr TypeWrapper & operator= (TypeWrapper &&other) noexcept
constexpr TypeWrapper & operator= (UA_ApplicationDescription &&native) noexcept
Public Member Functions inherited from opcua::Wrapper< UA_ApplicationDescription >
constexpr Wrapper () noexcept=default
constexpr Wrapper (const UA_ApplicationDescription &native) noexcept
constexpr Wrapper (UA_ApplicationDescription &&native) noexcept
constexpr Wrapper & operator= (const UA_ApplicationDescription &native) noexcept
constexpr Wrapper & operator= (UA_ApplicationDescription &&native) noexcept
constexpr operator UA_ApplicationDescription & () noexcept
constexpr operator const UA_ApplicationDescription & () const noexcept
constexpr UA_ApplicationDescription * operator-> () noexcept
constexpr const UA_ApplicationDescription * operator-> () const noexcept
constexpr UA_ApplicationDescription * handle () noexcept
constexpr const UA_ApplicationDescription * handle () const noexcept
constexpr void swap (Wrapper &other) noexcept
constexpr void swap (UA_ApplicationDescription &native) noexcept
Additional Inherited Members
Public Types inherited from opcua::Wrapper< UA_ApplicationDescription >
using NativeType
Static Public Member Functions inherited from opcua::TypeWrapper< UA_ApplicationDescription, UA_TYPES_APPLICATIONDESCRIPTION >
static constexpr TypeIndex typeIndex ()
Protected Member Functions inherited from opcua::TypeWrapper< UA_ApplicationDescription, UA_TYPES_APPLICATIONDESCRIPTION >
constexpr void clear () noexcept
Protected Member Functions inherited from opcua::Wrapper< UA_ApplicationDescription >
constexpr const UA_ApplicationDescription & native () const noexcept
constexpr UA_ApplicationDescription & native () noexcept
Related Symbols inherited from opcua::TypeWrapper< UA_ApplicationDescription, UA_TYPES_APPLICATIONDESCRIPTION >
String toString (const UA_ApplicationDescription &object, const UA_DataType &type)
String toString (const UA_ApplicationDescription &object)
String toString (const UA_ApplicationDescription &object, const UA_DataType &type)
String toString (const UA_ApplicationDescription &object)
Related Symbols inherited from opcua::Wrapper< UA_ApplicationDescription >
constexpr WrapperType * asWrapper (NativeType *native) noexcept
constexpr const WrapperType * asWrapper (const NativeType *native) noexcept
constexpr WrapperType & asWrapper (NativeType &native) noexcept
constexpr const WrapperType & asWrapper (const NativeType &native) noexcept
constexpr NativeType * asNative (WrapperType *wrapper) noexcept
constexpr const NativeType * asNative (const WrapperType *wrapper) noexcept
constexpr NativeType & asNative (WrapperType &wrapper) noexcept
constexpr const NativeType & asNative (const WrapperType &wrapper) noexcept
constexpr WrapperType * asWrapper (NativeType *native) noexcept
constexpr const WrapperType * asWrapper (const NativeType *native) noexcept
constexpr WrapperType & asWrapper (NativeType &native) noexcept
constexpr const WrapperType & asWrapper (const NativeType &native) noexcept
constexpr NativeType * asNative (WrapperType *wrapper) noexcept
constexpr const NativeType * asNative (const WrapperType *wrapper) noexcept
constexpr NativeType & asNative (WrapperType &wrapper) noexcept
constexpr const NativeType & asNative (const WrapperType &wrapper) noexcept
Constructor & Destructor Documentation
ApplicationDescription()
opcua::ua::ApplicationDescription::ApplicationDescription (std::string_view applicationUri, std::string_view productUri, LocalizedText applicationName, ApplicationType applicationType, std::string_view gatewayServerUri, std::string_view discoveryProfileUri, Span< const String > discoveryUrls) inline
Definition at line 171 of file types.hpp.
Member Function Documentation
applicationUri() [1/2]
const String & opcua::ua::ApplicationDescription::applicationUri () const inline noexcept
Definition at line 190 of file types.hpp.
Referenced by ApplicationDescription(), and applicationUri().
getApplicationUri() [1/2]
const String & opcua::ua::ApplicationDescription::getApplicationUri () const inline noexcept
Deprecated
Use applicationUri instead
Definition at line 190 of file types.hpp.
Referenced by applicationUri().
applicationUri() [2/2]
String & opcua::ua::ApplicationDescription::applicationUri () inline noexcept
Definition at line 190 of file types.hpp.
getApplicationUri() [2/2]
String & opcua::ua::ApplicationDescription::getApplicationUri () inline noexcept
Deprecated
Use applicationUri instead
Definition at line 190 of file types.hpp.
productUri() [1/2]
const String & opcua::ua::ApplicationDescription::productUri () const inline noexcept
Definition at line 191 of file types.hpp.
Referenced by ApplicationDescription(), and getProductUri().
getProductUri() [1/2]
const String & opcua::ua::ApplicationDescription::getProductUri () const inline noexcept
Deprecated
Use productUri instead
Definition at line 191 of file types.hpp.
Referenced by getProductUri().
productUri() [2/2]
String & opcua::ua::ApplicationDescription::productUri () inline noexcept
Definition at line 191 of file types.hpp.
getProductUri() [2/2]
String & opcua::ua::ApplicationDescription::getProductUri () inline noexcept
Deprecated
Use productUri instead
Definition at line 191 of file types.hpp.
applicationName() [1/2]
const LocalizedText & opcua::ua::ApplicationDescription::applicationName () const inline noexcept
Definition at line 192 of file types.hpp.
Referenced by ApplicationDescription(), and applicationName().
getApplicationName() [1/2]
const LocalizedText & opcua::ua::ApplicationDescription::getApplicationName () const inline noexcept
Deprecated
Use applicationName instead
Definition at line 192 of file types.hpp.
Referenced by applicationName().
applicationName() [2/2]
LocalizedText & opcua::ua::ApplicationDescription::applicationName () inline noexcept
Definition at line 192 of file types.hpp.
getApplicationName() [2/2]
LocalizedText & opcua::ua::ApplicationDescription::getApplicationName () inline noexcept
Deprecated
Use applicationName instead
Definition at line 192 of file types.hpp.
applicationType()
ApplicationType opcua::ua::ApplicationDescription::applicationType () const inline noexcept
Definition at line 193 of file types.hpp.
Referenced by ApplicationDescription(), and applicationType().
getApplicationType()
ApplicationType opcua::ua::ApplicationDescription::getApplicationType () const inline noexcept
Deprecated
Use applicationType instead
Definition at line 193 of file types.hpp.
Referenced by applicationType().
gatewayServerUri() [1/2]
const String & opcua::ua::ApplicationDescription::gatewayServerUri () const inline noexcept
Definition at line 194 of file types.hpp.
Referenced by ApplicationDescription(), and gatewayServerUri().
getGatewayServerUri() [1/2]
const String & opcua::ua::ApplicationDescription::getGatewayServerUri () const inline noexcept
Deprecated
Use gatewayServerUri instead
Definition at line 194 of file types.hpp.
Referenced by gatewayServerUri().
gatewayServerUri() [2/2]
String & opcua::ua::ApplicationDescription::gatewayServerUri () inline noexcept
Definition at line 194 of file types.hpp.
getGatewayServerUri() [2/2]
String & opcua::ua::ApplicationDescription::getGatewayServerUri () inline noexcept
Deprecated
Use gatewayServerUri instead
Definition at line 194 of file types.hpp.
discoveryProfileUri() [1/2]
const String & opcua::ua::ApplicationDescription::discoveryProfileUri () const inline noexcept
Definition at line 195 of file types.hpp.
Referenced by ApplicationDescription(), and discoveryProfileUri().
getDiscoveryProfileUri() [1/2]
const String & opcua::ua::ApplicationDescription::getDiscoveryProfileUri () const inline noexcept
Deprecated
Use discoveryProfileUri instead
Definition at line 195 of file types.hpp.
Referenced by discoveryProfileUri().
discoveryProfileUri() [2/2]
String & opcua::ua::ApplicationDescription::discoveryProfileUri () inline noexcept
Definition at line 195 of file types.hpp.
getDiscoveryProfileUri() [2/2]
String & opcua::ua::ApplicationDescription::getDiscoveryProfileUri () inline noexcept
Deprecated
Use discoveryProfileUri instead
Definition at line 195 of file types.hpp.
discoveryUrls() [1/2]
Span< const String > opcua::ua::ApplicationDescription::discoveryUrls () const inline noexcept
Definition at line 196 of file types.hpp.
Referenced by ApplicationDescription(), and discoveryUrls().
discoveryUrls() [2/2]
Span< String > opcua::ua::ApplicationDescription::discoveryUrls () inline noexcept
Definition at line 196 of file types.hpp.
getDiscoveryUrls() [1/2]
Span< const String > opcua::ua::ApplicationDescription::getDiscoveryUrls () const inline noexcept
Deprecated
Use discoveryUrls instead
Definition at line 196 of file types.hpp.
Referenced by discoveryUrls().
getDiscoveryUrls() [2/2]
Span< String > opcua::ua::ApplicationDescription::getDiscoveryUrls () inline noexcept
Deprecated
Use discoveryUrls instead
Definition at line 196 of file types.hpp.
TypeWrapper() [1/5]
opcua::TypeWrapper< T, Index >::TypeWrapper () constexpr default noexcept
TypeWrapper() [2/5]
opcua::TypeWrapper< T, Index >::TypeWrapper (const T & native) inline explicit constexpr
Constructor with native object (deep copy).
Definition at line 31 of file typewrapper.hpp.
TypeWrapper() [3/5]
opcua::TypeWrapper< T, Index >::TypeWrapper (T && native) inline constexpr noexcept
Constructor with native object (move rvalue).
Definition at line 35 of file typewrapper.hpp.
TypeWrapper() [4/5]
opcua::TypeWrapper< T, Index >::TypeWrapper (const TypeWrapper & other) inline constexpr
Copy constructor (deep copy).
Definition at line 43 of file typewrapper.hpp.
TypeWrapper() [5/5]
opcua::TypeWrapper< T, Index >::TypeWrapper (TypeWrapper && other) inline constexpr noexcept
Move constructor.
Definition at line 47 of file typewrapper.hpp.