open62541pp: opcua::Result< void > Class Reference
opcua::Result< void > Class Reference
#include <result.hpp>
Detailed Description
Template specialization of Result class for void types.
Result<void> contains only a StatusCode.
Definition at line 346 of file result.hpp.
Public Member Functions
constexpr Result () noexcept
constexpr Result (StatusCode code) noexcept
constexpr Result (BadResult error) noexcept
constexpr void operator* () const noexcept
constexpr StatusCode code () const noexcept
constexpr operator bool () const noexcept
constexpr bool hasValue () const noexcept
constexpr void value () const
Constructor & Destructor Documentation
Result() [1/3]
opcua::Result< void >::Result () inline constexpr noexcept
Create a default Result (good StatusCode).
Definition at line 351 of file result.hpp.
Result() [2/3]
opcua::Result< void >::Result (StatusCode code) inline constexpr noexcept
Create a Result with the given StatusCode.
Definition at line 357 of file result.hpp.
Result() [3/3]
opcua::Result< void >::Result (BadResult< void > error) inline constexpr noexcept
Create a Result with the given error.
Definition at line 363 of file result.hpp.
Member Function Documentation
operator*()
void opcua::Result< void >::operator* () const inline constexpr noexcept
Definition at line 366 of file result.hpp.
code()
StatusCode opcua::Result< void >::code () const inline constexpr noexcept
Get the code of the Result.
Definition at line 371 of file result.hpp.
operator bool()
opcua::Result< void >::operator bool () const inline explicit constexpr noexcept
Check if the Result has a non-bad StatusCode.
Definition at line 378 of file result.hpp.
hasValue()
bool opcua::Result< void >::hasValue () const inline constexpr noexcept
Definition at line 385 of file result.hpp.
value()
void opcua::Result< void >::value () const inline constexpr
Get the value of the Result.
Exceptions
BadStatus If the Result does have a bad StatusCode.
Definition at line 393 of file result.hpp.
Referenced by opcua::Node< Connection >::addModellingRule(), opcua::Node< Connection >::addReference(), opcua::MonitoredItem< Connection >::deleteMonitoredItem(), opcua::Node< Connection >::deleteNode(), opcua::Node< Connection >::deleteReference(), opcua::Subscription< Connection >::deleteSubscription(), opcua::MonitoredItem< Connection >::setMonitoringParameters(), opcua::Node< Connection >::writeAccessLevel(), opcua::Node< Connection >::writeArrayDimensions(), opcua::Node< Connection >::writeContainsNoLoops(), opcua::Node< Connection >::writeDataType(), opcua::Node< Connection >::writeDataValue(), opcua::Node< Connection >::writeDescription(), opcua::Node< Connection >::writeDisplayName(), opcua::Node< Connection >::writeEventNotifier(), opcua::Node< Connection >::writeExecutable(), opcua::Node< Connection >::writeHistorizing(), opcua::Node< Connection >::writeInverseName(), opcua::Node< Connection >::writeIsAbstract(), opcua::Node< Connection >::writeMinimumSamplingInterval(), opcua::Node< Connection >::writeSymmetric(), opcua::Node< Connection >::writeUserAccessLevel(), opcua::Node< Connection >::writeUserExecutable(), opcua::Node< Connection >::writeUserWriteMask(), opcua::Node< Connection >::writeValue(), opcua::Node< Connection >::writeValueRank(), and opcua::Node< Connection >::writeWriteMask().