open62541pp: opcua::Span< T > Class Template Reference
opcua::Span< T > Class Template Reference
#include <span.hpp>
Detailed Description
template<typename T>
class opcua::Span< T >
View to a contiguous sequence of objects, similar to std::span in C++20.
Spans are used to pass and return open62541 arrays without copy and to use them with the standard library algorithms. The view just holds two members: the pointer to T and the size, so it's lightweight and trivially copyable.
Template Parameters
T Type of the array object, use const T for an immutable view
See also
https://en.cppreference.com/w/cpp/container/span
Examples
custom_datatypes/client_custom_datatypes.cpp, custom_datatypes/server_custom_datatypes.cpp, events/client_eventfilter.cpp, events/server_events.cpp, method/server_method.cpp, method/server_method_async.cpp, and typeconversion.cpp.
Definition at line 29 of file span.hpp.
Public Types
using element_type = T
using value_type = std::remove_cv_t< T >
using size_type = size_t
using difference_type = std::ptrdiff_t
using pointer = T *
using const_pointer = const T *
using reference = T &
using const_reference = const T &
using iterator = pointer
using const_iterator = const_pointer
using reverse_iterator = std::reverse_iterator< iterator >
using const_reverse_iterator = std::reverse_iterator< const_iterator >
Public Member Functions
constexpr Span () noexcept=default
constexpr Span (T *data, size_t size) noexcept
template<typename Container , typename = EnableIfHasSizeAndData<Container>>
constexpr Span (Container &container) noexcept
template<typename Container , typename = EnableIfHasSizeAndData<Container>>
constexpr Span (const Container &container) noexcept
constexpr Span (std::initializer_list< value_type > values) noexcept
constexpr void swap (Span &other) noexcept
constexpr size_t size () const noexcept
constexpr bool empty () const noexcept
constexpr pointer data () const noexcept
constexpr reference operator[] (size_t index) const noexcept
constexpr reference at (size_t index) const
constexpr reference front () const noexcept
constexpr reference back () const noexcept
constexpr iterator begin () const noexcept
constexpr iterator end () const noexcept
constexpr const_iterator cbegin () const noexcept
constexpr const_iterator cend () const noexcept
constexpr reverse_iterator rbegin () const noexcept
constexpr reverse_iterator rend () const noexcept
constexpr const_reverse_iterator crbegin () const noexcept
constexpr const_reverse_iterator crend () const noexcept
constexpr Span subview (size_t offset, size_t count=(std::numeric_limits< std::size_t >::max)()) const noexcept
constexpr Span first (size_t count) const noexcept
constexpr Span last (size_t count) const noexcept
Related Symbols
(Note that these are not member symbols.)
template<typename Container >
Span (Container &) -> Span< typename Container::value_type >
template<typename Container >
Span (const Container &) -> Span< const typename Container::value_type >
template<typename T , typename U , typename = detail::EnableIfEqualityComparable<T, U>>
constexpr bool operator== (Span< T > lhs, Span< U > rhs)
template<typename T , typename U , typename = detail::EnableIfEqualityComparable<T, U>>
constexpr bool operator!= (Span< T > lhs, Span< U > rhs)
Member Typedef Documentation
const_iterator
template<typename T > using opcua::Span< T >::const_iterator = const_pointer
Definition at line 48 of file span.hpp.
const_pointer
template<typename T > using opcua::Span< T >::const_pointer = const T*
Definition at line 44 of file span.hpp.
const_reference
template<typename T > using opcua::Span< T >::const_reference = const T&
Definition at line 46 of file span.hpp.
const_reverse_iterator
template<typename T > using opcua::Span< T >::const_reverse_iterator = std::reverse_iterator<const_iterator>
Definition at line 50 of file span.hpp.
difference_type
template<typename T > using opcua::Span< T >::difference_type = std::ptrdiff_t
Definition at line 42 of file span.hpp.
element_type
template<typename T > using opcua::Span< T >::element_type = T
Definition at line 39 of file span.hpp.
iterator
template<typename T > using opcua::Span< T >::iterator = pointer
Definition at line 47 of file span.hpp.
pointer
template<typename T > using opcua::Span< T >::pointer = T*
Definition at line 43 of file span.hpp.
reference
template<typename T > using opcua::Span< T >::reference = T&
Definition at line 45 of file span.hpp.
reverse_iterator
template<typename T > using opcua::Span< T >::reverse_iterator = std::reverse_iterator<iterator>
Definition at line 49 of file span.hpp.
size_type
template<typename T > using opcua::Span< T >::size_type = size_t
Definition at line 41 of file span.hpp.
value_type
template<typename T > using opcua::Span< T >::value_type = std::remove_cv_t<T>
Definition at line 40 of file span.hpp.
Constructor & Destructor Documentation
Span() [1/5]
template<typename T > constexpr opcua::Span< T >::Span () constexpr default noexcept
Span() [2/5]
template<typename T > constexpr opcua::Span< T >::Span (T * data, size_t size) inline constexpr noexcept
Definition at line 55 of file span.hpp.
Span() [3/5]
template<typename T > template<typename Container , typename = EnableIfHasSizeAndData<Container>> constexpr opcua::Span< T >::Span (Container & container) inline constexpr noexcept
Implicit constructor from a container like std::array or std::vector.
Definition at line 63 of file span.hpp.
Span() [4/5]
template<typename T > template<typename Container , typename = EnableIfHasSizeAndData<Container>> constexpr opcua::Span< T >::Span (const Container & container) inline constexpr noexcept
Implicit constructor from a container like std::array or std::vector (const).
Definition at line 70 of file span.hpp.
Span() [5/5]
template<typename T > constexpr opcua::Span< T >::Span (std::initializer_list< value_type > values) inline constexpr noexcept
Implicit constructor from an initializer list.
Only safe to use if std::initializer_list itself outlives the Span:
void takeView(Span<const int> values);
// ok
takeView({1, 2, 3});
// not ok
Span<const int> values = {1, 2, 3};
takeView(values);
Definition at line 86 of file span.hpp.
Member Function Documentation
at()
template<typename T > constexpr reference opcua::Span< T >::at (size_t index) const inline constexpr
Access element by index with bounds checking.
Exceptions
std::out_of_range If `index` >= size()
Examples
events/client_eventfilter.cpp, events/server_events.cpp, method/server_method.cpp, and method/server_method_async.cpp.
Definition at line 114 of file span.hpp.
back()
template<typename T > constexpr reference opcua::Span< T >::back () const inline constexpr noexcept
Definition at line 126 of file span.hpp.
begin()
template<typename T > constexpr iterator opcua::Span< T >::begin () const inline constexpr noexcept
Definition at line 131 of file span.hpp.
Referenced by opcua::ByteString::ByteString(), opcua::Span< T >::operator==(), and opcua::Span< T >::rend().
cbegin()
template<typename T > constexpr const_iterator opcua::Span< T >::cbegin () const inline constexpr noexcept
Definition at line 139 of file span.hpp.
Referenced by opcua::Span< T >::crend().
cend()
template<typename T > constexpr const_iterator opcua::Span< T >::cend () const inline constexpr noexcept
Definition at line 143 of file span.hpp.
Referenced by opcua::Span< T >::crbegin().
crbegin()
template<typename T > constexpr const_reverse_iterator opcua::Span< T >::crbegin () const inline constexpr noexcept
Definition at line 155 of file span.hpp.
crend()
template<typename T > constexpr const_reverse_iterator opcua::Span< T >::crend () const inline constexpr noexcept
Definition at line 159 of file span.hpp.
data()
template<typename T > constexpr pointer opcua::Span< T >::data () const inline constexpr noexcept
Examples
typeconversion.cpp.
Definition at line 102 of file span.hpp.
Referenced by opcua::Span< T >::at(), opcua::Span< T >::back(), opcua::Span< T >::begin(), opcua::Span< T >::cbegin(), opcua::Span< T >::cend(), opcua::Span< T >::end(), opcua::Span< T >::first(), opcua::Span< T >::front(), opcua::Span< T >::last(), opcua::Span< T >::operator[](), and opcua::Span< T >::subview().
empty()
template<typename T > constexpr bool opcua::Span< T >::empty () const inline constexpr noexcept
Definition at line 98 of file span.hpp.
Referenced by opcua::Span< T >::back(), and opcua::Span< T >::front().
end()
template<typename T > constexpr iterator opcua::Span< T >::end () const inline constexpr noexcept
Definition at line 135 of file span.hpp.
Referenced by opcua::ByteString::ByteString(), opcua::Span< T >::operator==(), and opcua::Span< T >::rbegin().
first()
template<typename T > constexpr Span opcua::Span< T >::first (size_t count) const inline constexpr noexcept
Obtain a view over the first count elements of this Span.
Definition at line 177 of file span.hpp.
front()
template<typename T > constexpr reference opcua::Span< T >::front () const inline constexpr noexcept
Definition at line 121 of file span.hpp.
last()
template<typename T > constexpr Span opcua::Span< T >::last (size_t count) const inline constexpr noexcept
Obtain a view over the last count elements of this Span.
Definition at line 185 of file span.hpp.
operator[]()
template<typename T > constexpr reference opcua::Span< T >::operator[] (size_t index) const inline constexpr noexcept
Access element by index.
Definition at line 107 of file span.hpp.
rbegin()
template<typename T > constexpr reverse_iterator opcua::Span< T >::rbegin () const inline constexpr noexcept
Definition at line 147 of file span.hpp.
rend()
template<typename T > constexpr reverse_iterator opcua::Span< T >::rend () const inline constexpr noexcept
Definition at line 151 of file span.hpp.
size()
template<typename T > constexpr size_t opcua::Span< T >::size () const inline constexpr noexcept
Definition at line 94 of file span.hpp.
Referenced by opcua::ua::AddNodesRequest::AddNodesRequest(), opcua::ua::AddReferencesRequest::AddReferencesRequest(), opcua::ua::ApplicationDescription::ApplicationDescription(), opcua::Span< T >::at(), opcua::ua::AxisInformation::AxisInformation(), opcua::Span< T >::back(), opcua::ua::BrowseNextRequest::BrowseNextRequest(), opcua::ua::BrowseRequest::BrowseRequest(), opcua::ua::CallMethodRequest::CallMethodRequest(), opcua::ua::CallRequest::CallRequest(), opcua::Span< T >::cend(), opcua::ua::CreateMonitoredItemsRequest::CreateMonitoredItemsRequest(), opcua::ua::DeleteMonitoredItemsRequest::DeleteMonitoredItemsRequest(), opcua::ua::DeleteNodesRequest::DeleteNodesRequest(), opcua::ua::DeleteReferencesRequest::DeleteReferencesRequest(), opcua::ua::DeleteSubscriptionsRequest::DeleteSubscriptionsRequest(), opcua::Span< T >::empty(), opcua::Span< T >::end(), opcua::ua::EnumDefinition::EnumDefinition(), opcua::ua::EventFilter::EventFilter(), opcua::Span< T >::first(), opcua::Span< T >::last(), opcua::ua::ModifyMonitoredItemsRequest::ModifyMonitoredItemsRequest(), opcua::Span< T >::operator[](), opcua::ua::ReadRequest::ReadRequest(), opcua::ua::RegisterNodesRequest::RegisterNodesRequest(), opcua::ua::RelativePath::RelativePath(), opcua::ua::SetMonitoringModeRequest::SetMonitoringModeRequest(), opcua::ua::SetPublishingModeRequest::SetPublishingModeRequest(), opcua::ua::SetTriggeringRequest::SetTriggeringRequest(), opcua::Span< T >::Span(), opcua::Span< T >::subview(), opcua::ua::TranslateBrowsePathsToNodeIdsRequest::TranslateBrowsePathsToNodeIdsRequest(), opcua::ua::UnregisterNodesRequest::UnregisterNodesRequest(), and opcua::ua::WriteRequest::WriteRequest().
subview()
template<typename T > constexpr Span opcua::Span< T >::subview (size_t offset, size_t count = (std::numeric_limits<std::size_t>::max)()) const inline constexpr noexcept
Obtain a view over count elements of this Span starting at offset offset.
Definition at line 164 of file span.hpp.
swap()
template<typename T > constexpr void opcua::Span< T >::swap (Span< T > & other) inline constexpr noexcept
Definition at line 89 of file span.hpp.
Friends And Related Symbol Documentation
operator!=()
template<typename T , typename U , typename = detail::EnableIfEqualityComparable<T, U>> constexpr bool operator!= (Span< T > lhs, Span< U > rhs) related
Definition at line 238 of file span.hpp.
operator==()
template<typename T , typename U , typename = detail::EnableIfEqualityComparable<T, U>> constexpr bool operator== (Span< T > lhs, Span< U > rhs) related
Definition at line 232 of file span.hpp.
Span() [1/2]
template<typename Container > Span (const Container &) -> Span< const typename Container::value_type > related
Span() [2/2]
template<typename Container > Span (Container &) -> Span< typename Container::value_type > related