open62541pp: opcua::detail::StringWrapper< T, typeIndex, CharT > Class Template Reference
opcua::detail::StringWrapper< T, typeIndex, CharT > Class Template Reference
#include <types.hpp>
Detailed Description
template<typename T, TypeIndex typeIndex, typename CharT>
class opcua::detail::StringWrapper< T, typeIndex, CharT >
Definition at line 92 of file types.hpp.
Public Types
using value_type = CharT
using size_type = size_t
using difference_type = std::ptrdiff_t
using pointer = value_type*
using const_pointer = const value_type*
using reference = value_type&
using const_reference = const value_type&
using iterator = pointer
using const_iterator = const_pointer
using reverse_iterator = std::reverse_iterator<iterator>
using const_reverse_iterator = std::reverse_iterator<const_iterator>
Public Types inherited from opcua::Wrapper< T >
using NativeType = T
Public Member Functions
template<typename InputIt >
StringWrapper (InputIt first, InputIt last)
StringWrapper (std::initializer_list< CharT > init)
size_t size () const noexcept
size_t length () const noexcept
bool empty () const noexcept
pointer data () noexcept
const_pointer data () const noexcept
reference operator[] (size_t index) noexcept
const_reference operator[] (size_t index) const noexcept
reference front () noexcept
const_reference front () const noexcept
reference back () noexcept
const_reference back () const noexcept
iterator begin () noexcept
const_iterator begin () const noexcept
const_iterator cbegin () const noexcept
iterator end () noexcept
const_iterator end () const noexcept
const_iterator cend () const noexcept
reverse_iterator rbegin () noexcept
const_reverse_iterator rbegin () const noexcept
const_reverse_iterator crbegin () const noexcept
reverse_iterator rend () noexcept
const_reverse_iterator rend () const noexcept
const_reverse_iterator crend () const noexcept
Public Member Functions inherited from opcua::TypeWrapper< T, typeIndex >
constexpr TypeWrapper ()=default
constexpr TypeWrapper (const T &native)
constexpr TypeWrapper (T &&native) noexcept
~TypeWrapper ()
constexpr TypeWrapper (const TypeWrapper &other)
constexpr TypeWrapper (TypeWrapper &&other) noexcept
constexpr TypeWrapper & operator= (const TypeWrapper &other)
constexpr TypeWrapper & operator= (const T &native)
constexpr TypeWrapper & operator= (TypeWrapper &&other) noexcept
constexpr TypeWrapper & operator= (T &&native) noexcept
constexpr void swap (TypeWrapper &other) noexcept
constexpr void swap (T &native) noexcept
Public Member Functions inherited from opcua::Wrapper< T >
constexpr Wrapper ()=default
constexpr Wrapper (const T &native)
constexpr Wrapper (T &&native) noexcept
constexpr operator T& () noexcept
constexpr operator const T & () const noexcept
constexpr T * operator-> () noexcept
constexpr const T * operator-> () const noexcept
constexpr T * handle () noexcept
constexpr const T * handle () const noexcept
Protected Member Functions
void init (size_t length)
template<typename InputIt , typename Tag >
StringWrapper (InputIt first, InputIt last, Tag)
template<typename InputIt >
StringWrapper (InputIt first, InputIt last, std::input_iterator_tag)
Protected Member Functions inherited from opcua::TypeWrapper< T, typeIndex >
constexpr void clear () noexcept
Protected Member Functions inherited from opcua::Wrapper< T >
constexpr const T & native () const noexcept
constexpr T & native () noexcept
Additional Inherited Members
Static Public Member Functions inherited from opcua::TypeWrapper< T, typeIndex >
static constexpr TypeIndex getTypeIndex ()
Member Typedef Documentation
value_type
template<typename T , TypeIndex typeIndex, typename CharT > using opcua::detail::StringWrapper< T, typeIndex, CharT >::value_type = CharT
Definition at line 97 of file types.hpp.
size_type
template<typename T , TypeIndex typeIndex, typename CharT > using opcua::detail::StringWrapper< T, typeIndex, CharT >::size_type = size_t
Definition at line 98 of file types.hpp.
difference_type
template<typename T , TypeIndex typeIndex, typename CharT > using opcua::detail::StringWrapper< T, typeIndex, CharT >::difference_type = std::ptrdiff_t
Definition at line 99 of file types.hpp.
pointer
template<typename T , TypeIndex typeIndex, typename CharT > using opcua::detail::StringWrapper< T, typeIndex, CharT >::pointer = value_type*
Definition at line 100 of file types.hpp.
const_pointer
template<typename T , TypeIndex typeIndex, typename CharT > using opcua::detail::StringWrapper< T, typeIndex, CharT >::const_pointer = const value_type*
Definition at line 101 of file types.hpp.
reference
template<typename T , TypeIndex typeIndex, typename CharT > using opcua::detail::StringWrapper< T, typeIndex, CharT >::reference = value_type&
Definition at line 102 of file types.hpp.
const_reference
template<typename T , TypeIndex typeIndex, typename CharT > using opcua::detail::StringWrapper< T, typeIndex, CharT >::const_reference = const value_type&
Definition at line 103 of file types.hpp.
iterator
template<typename T , TypeIndex typeIndex, typename CharT > using opcua::detail::StringWrapper< T, typeIndex, CharT >::iterator = pointer
Definition at line 104 of file types.hpp.
const_iterator
template<typename T , TypeIndex typeIndex, typename CharT > using opcua::detail::StringWrapper< T, typeIndex, CharT >::const_iterator = const_pointer
Definition at line 105 of file types.hpp.
reverse_iterator
template<typename T , TypeIndex typeIndex, typename CharT > using opcua::detail::StringWrapper< T, typeIndex, CharT >::reverse_iterator = std::reverse_iterator<iterator>
Definition at line 106 of file types.hpp.
const_reverse_iterator
template<typename T , TypeIndex typeIndex, typename CharT > using opcua::detail::StringWrapper< T, typeIndex, CharT >::const_reverse_iterator = std::reverse_iterator<const_iterator>
Definition at line 107 of file types.hpp.
Constructor & Destructor Documentation
StringWrapper() [1/4]
template<typename T , TypeIndex typeIndex, typename CharT > template<typename InputIt > opcua::detail::StringWrapper< T, typeIndex, CharT >::StringWrapper (InputIt first, InputIt last) inline
Definition at line 113 of file types.hpp.
StringWrapper() [2/4]
template<typename T , TypeIndex typeIndex, typename CharT > opcua::detail::StringWrapper< T, typeIndex, CharT >::StringWrapper (std::initializer_list< CharT > init) inline
Definition at line 116 of file types.hpp.
StringWrapper() [3/4]
template<typename T , TypeIndex typeIndex, typename CharT > template<typename InputIt , typename Tag > opcua::detail::StringWrapper< T, typeIndex, CharT >::StringWrapper (InputIt first, InputIt last, Tag) inline protected
Definition at line 229 of file types.hpp.
StringWrapper() [4/4]
template<typename T , TypeIndex typeIndex, typename CharT > template<typename InputIt > opcua::detail::StringWrapper< T, typeIndex, CharT >::StringWrapper (InputIt first, InputIt last, std::input_iterator_tag) inline protected
Definition at line 235 of file types.hpp.
Member Function Documentation
size()
template<typename T , TypeIndex typeIndex, typename CharT > size_t opcua::detail::StringWrapper< T, typeIndex, CharT >::size () const inline noexcept
Definition at line 119 of file types.hpp.
Referenced by opcua::detail::StringWrapper< T, typeIndex, CharT >::back(), opcua::detail::StringWrapper< T, typeIndex, CharT >::back(), opcua::detail::StringWrapper< T, typeIndex, CharT >::cend(), opcua::detail::StringWrapper< T, typeIndex, CharT >::empty(), opcua::detail::StringWrapper< T, typeIndex, CharT >::end(), opcua::detail::StringWrapper< T, typeIndex, CharT >::end(), opcua::detail::StringWrapper< T, typeIndex, CharT >::length(), opcua::detail::StringWrapper< T, typeIndex, CharT >::operator[](), and opcua::detail::StringWrapper< T, typeIndex, CharT >::operator[]().
length()
template<typename T , TypeIndex typeIndex, typename CharT > size_t opcua::detail::StringWrapper< T, typeIndex, CharT >::length () const inline noexcept
Definition at line 123 of file types.hpp.
Referenced by opcua::detail::StringWrapper< T, typeIndex, CharT >::init().
empty()
template<typename T , TypeIndex typeIndex, typename CharT > bool opcua::detail::StringWrapper< T, typeIndex, CharT >::empty () const inline noexcept
Definition at line 127 of file types.hpp.
Referenced by opcua::detail::StringWrapper< T, typeIndex, CharT >::back(), opcua::detail::StringWrapper< T, typeIndex, CharT >::back(), opcua::detail::StringWrapper< T, typeIndex, CharT >::front(), and opcua::detail::StringWrapper< T, typeIndex, CharT >::front().
data() [1/2]
template<typename T , TypeIndex typeIndex, typename CharT > pointer opcua::detail::StringWrapper< T, typeIndex, CharT >::data () inline noexcept
Definition at line 131 of file types.hpp.
Referenced by opcua::detail::StringWrapper< T, typeIndex, CharT >::back(), opcua::detail::StringWrapper< T, typeIndex, CharT >::back(), opcua::detail::StringWrapper< T, typeIndex, CharT >::begin(), opcua::detail::StringWrapper< T, typeIndex, CharT >::begin(), opcua::detail::StringWrapper< T, typeIndex, CharT >::cbegin(), opcua::detail::StringWrapper< T, typeIndex, CharT >::cend(), opcua::detail::StringWrapper< T, typeIndex, CharT >::end(), opcua::detail::StringWrapper< T, typeIndex, CharT >::end(), opcua::detail::StringWrapper< T, typeIndex, CharT >::front(), opcua::detail::StringWrapper< T, typeIndex, CharT >::front(), opcua::detail::StringWrapper< T, typeIndex, CharT >::init(), opcua::detail::StringWrapper< T, typeIndex, CharT >::operator[](), opcua::detail::StringWrapper< T, typeIndex, CharT >::operator[](), opcua::detail::StringWrapper< T, typeIndex, CharT >::StringWrapper(), and opcua::detail::StringWrapper< T, typeIndex, CharT >::StringWrapper().
data() [2/2]
template<typename T , TypeIndex typeIndex, typename CharT > const_pointer opcua::detail::StringWrapper< T, typeIndex, CharT >::data () const inline noexcept
Definition at line 135 of file types.hpp.
operator[]() [1/2]
template<typename T , TypeIndex typeIndex, typename CharT > reference opcua::detail::StringWrapper< T, typeIndex, CharT >::operator[] (size_t index) inline noexcept
Definition at line 139 of file types.hpp.
operator[]() [2/2]
template<typename T , TypeIndex typeIndex, typename CharT > const_reference opcua::detail::StringWrapper< T, typeIndex, CharT >::operator[] (size_t index) const inline noexcept
Definition at line 144 of file types.hpp.
front() [1/2]
template<typename T , TypeIndex typeIndex, typename CharT > reference opcua::detail::StringWrapper< T, typeIndex, CharT >::front () inline noexcept
Definition at line 149 of file types.hpp.
front() [2/2]
template<typename T , TypeIndex typeIndex, typename CharT > const_reference opcua::detail::StringWrapper< T, typeIndex, CharT >::front () const inline noexcept
Definition at line 154 of file types.hpp.
back() [1/2]
template<typename T , TypeIndex typeIndex, typename CharT > reference opcua::detail::StringWrapper< T, typeIndex, CharT >::back () inline noexcept
Definition at line 159 of file types.hpp.
back() [2/2]
template<typename T , TypeIndex typeIndex, typename CharT > const_reference opcua::detail::StringWrapper< T, typeIndex, CharT >::back () const inline noexcept
Definition at line 164 of file types.hpp.
begin() [1/2]
template<typename T , TypeIndex typeIndex, typename CharT > iterator opcua::detail::StringWrapper< T, typeIndex, CharT >::begin () inline noexcept
Definition at line 169 of file types.hpp.
Referenced by opcua::detail::StringWrapper< T, typeIndex, CharT >::rend(), and opcua::detail::StringWrapper< T, typeIndex, CharT >::rend().
begin() [2/2]
template<typename T , TypeIndex typeIndex, typename CharT > const_iterator opcua::detail::StringWrapper< T, typeIndex, CharT >::begin () const inline noexcept
Definition at line 173 of file types.hpp.
cbegin()
template<typename T , TypeIndex typeIndex, typename CharT > const_iterator opcua::detail::StringWrapper< T, typeIndex, CharT >::cbegin () const inline noexcept
Definition at line 177 of file types.hpp.
Referenced by opcua::detail::StringWrapper< T, typeIndex, CharT >::crend().
end() [1/2]
template<typename T , TypeIndex typeIndex, typename CharT > iterator opcua::detail::StringWrapper< T, typeIndex, CharT >::end () inline noexcept
Definition at line 181 of file types.hpp.
Referenced by opcua::detail::StringWrapper< T, typeIndex, CharT >::rbegin(), and opcua::detail::StringWrapper< T, typeIndex, CharT >::rbegin().
end() [2/2]
template<typename T , TypeIndex typeIndex, typename CharT > const_iterator opcua::detail::StringWrapper< T, typeIndex, CharT >::end () const inline noexcept
Definition at line 185 of file types.hpp.
cend()
template<typename T , TypeIndex typeIndex, typename CharT > const_iterator opcua::detail::StringWrapper< T, typeIndex, CharT >::cend () const inline noexcept
Definition at line 189 of file types.hpp.
Referenced by opcua::detail::StringWrapper< T, typeIndex, CharT >::crbegin().
rbegin() [1/2]
template<typename T , TypeIndex typeIndex, typename CharT > reverse_iterator opcua::detail::StringWrapper< T, typeIndex, CharT >::rbegin () inline noexcept
Definition at line 193 of file types.hpp.
rbegin() [2/2]
template<typename T , TypeIndex typeIndex, typename CharT > const_reverse_iterator opcua::detail::StringWrapper< T, typeIndex, CharT >::rbegin () const inline noexcept
Definition at line 197 of file types.hpp.
crbegin()
template<typename T , TypeIndex typeIndex, typename CharT > const_reverse_iterator opcua::detail::StringWrapper< T, typeIndex, CharT >::crbegin () const inline noexcept
Definition at line 201 of file types.hpp.
rend() [1/2]
template<typename T , TypeIndex typeIndex, typename CharT > reverse_iterator opcua::detail::StringWrapper< T, typeIndex, CharT >::rend () inline noexcept
Definition at line 205 of file types.hpp.
rend() [2/2]
template<typename T , TypeIndex typeIndex, typename CharT > const_reverse_iterator opcua::detail::StringWrapper< T, typeIndex, CharT >::rend () const inline noexcept
Definition at line 209 of file types.hpp.
crend()
template<typename T , TypeIndex typeIndex, typename CharT > const_reverse_iterator opcua::detail::StringWrapper< T, typeIndex, CharT >::crend () const inline noexcept
Definition at line 213 of file types.hpp.
init()
template<typename T , TypeIndex typeIndex, typename CharT > void opcua::detail::StringWrapper< T, typeIndex, CharT >::init (size_t length) inline protected
Definition at line 218 of file types.hpp.
Referenced by opcua::detail::StringWrapper< T, typeIndex, CharT >::StringWrapper(), and opcua::detail::StringWrapper< T, typeIndex, CharT >::StringWrapper().