open62541pp: opcua::DataValue Class Reference
opcua::DataValue Class Reference
Wrapper classes
#include <types.hpp>
Detailed Description
UA_DataValue wrapper class.
See also
https://reference.opcfoundation.org/Core/Part4/v105/docs/7.11
Examples
client_async.cpp, client_subscription.cpp, server_datasource.cpp, and server_valuecallback.cpp.
Definition at line 1849 of file types.hpp.
Public Member Functions
DataValue (Variant value) noexcept
DataValue (Variant value, std::optional< DateTime > sourceTimestamp, std::optional< DateTime > serverTimestamp, std::optional< uint16_t > sourcePicoseconds, std::optional< uint16_t > serverPicoseconds, std::optional< StatusCode > status) noexcept
void setValue (const Variant &value)
void setValue (Variant &&value) noexcept
void setSourceTimestamp (DateTime sourceTimestamp) noexcept
void setServerTimestamp (DateTime serverTimestamp) noexcept
void setSourcePicoseconds (uint16_t sourcePicoseconds) noexcept
void setServerPicoseconds (uint16_t serverPicoseconds) noexcept
void setStatus (StatusCode status) noexcept
bool hasValue () const noexcept
bool hasSourceTimestamp () const noexcept
bool hasServerTimestamp () const noexcept
bool hasSourcePicoseconds () const noexcept
bool hasServerPicoseconds () const noexcept
bool hasStatus () const noexcept
Variant & value () &noexcept
const Variant & value () const &noexcept
Variant && value () &&noexcept
const Variant && value () const &&noexcept
Variant & getValue () &noexcept
const Variant & getValue () const &noexcept
Variant && getValue () &&noexcept
const Variant && getValue () const &&noexcept
DateTime sourceTimestamp () const noexcept
DateTime getSourceTimestamp () const noexcept
DateTime serverTimestamp () const noexcept
DateTime getServerTimestamp () const noexcept
uint16_t sourcePicoseconds () const noexcept
uint16_t getSourcePicoseconds () const noexcept
uint16_t serverPicoseconds () const noexcept
uint16_t getServerPicoseconds () const noexcept
StatusCode status () const noexcept
StatusCode getStatus () const noexcept
constexpr TypeWrapper () noexcept=default
constexpr TypeWrapper (const T &native)
constexpr TypeWrapper (T &&native) noexcept
constexpr TypeWrapper (const TypeWrapper &other)
constexpr TypeWrapper (TypeWrapper &&other) noexcept
Public Member Functions inherited from opcua::TypeWrapper< UA_DataValue, UA_TYPES_DATAVALUE >
constexpr TypeWrapper () noexcept=default
constexpr TypeWrapper (const UA_DataValue &native)
constexpr TypeWrapper (UA_DataValue &&native) noexcept
constexpr TypeWrapper (const TypeWrapper &other)
constexpr TypeWrapper (TypeWrapper &&other) noexcept
~TypeWrapper ()
constexpr TypeWrapper & operator= (const TypeWrapper &other)
constexpr TypeWrapper & operator= (const UA_DataValue &native)
constexpr TypeWrapper & operator= (TypeWrapper &&other) noexcept
constexpr TypeWrapper & operator= (UA_DataValue &&native) noexcept
Public Member Functions inherited from opcua::Wrapper< T >
constexpr Wrapper () noexcept=default
constexpr Wrapper (const T &native) noexcept
constexpr Wrapper (T &&native) noexcept
constexpr Wrapper & operator= (const T &native) noexcept
constexpr Wrapper & operator= (T &&native) noexcept
constexpr operator T& () noexcept
constexpr operator const T & () const noexcept
constexpr T * operator-> () noexcept
constexpr const T * operator-> () const noexcept
constexpr T * handle () noexcept
constexpr const T * handle () const noexcept
constexpr void swap (Wrapper &other) noexcept
constexpr void swap (T &native) noexcept
Static Public Member Functions
template<VariantPolicy Policy = VariantPolicy::Copy, typename... Args>
static DataValue fromScalar (Args &&... args)
template<VariantPolicy Policy = VariantPolicy::Copy, typename... Args>
static DataValue fromArray (Args &&... args)
Static Public Member Functions inherited from opcua::TypeWrapper< UA_DataValue, UA_TYPES_DATAVALUE >
static constexpr TypeIndex typeIndex ()
Additional Inherited Members
Public Types inherited from opcua::Wrapper< T >
using NativeType = T
Protected Member Functions inherited from opcua::TypeWrapper< UA_DataValue, UA_TYPES_DATAVALUE >
constexpr void clear () noexcept
Protected Member Functions inherited from opcua::Wrapper< T >
constexpr const T & native () const noexcept
constexpr T & native () noexcept
Related Symbols inherited from opcua::TypeWrapper< UA_DataValue, UA_TYPES_DATAVALUE >
String toString (const UA_DataValue &object, const UA_DataType &type)
String toString (const UA_DataValue &object)
Related Symbols inherited from opcua::Wrapper< T >
template<typename WrapperType , typename NativeType = typename WrapperType::NativeType>
constexpr WrapperType * asWrapper (NativeType *native) noexcept
template<typename WrapperType , typename NativeType = typename WrapperType::NativeType>
constexpr const WrapperType * asWrapper (const NativeType *native) noexcept
template<typename WrapperType , typename NativeType = typename WrapperType::NativeType>
constexpr WrapperType & asWrapper (NativeType &native) noexcept
template<typename WrapperType , typename NativeType = typename WrapperType::NativeType>
constexpr const WrapperType & asWrapper (const NativeType &native) noexcept
template<typename WrapperType , typename NativeType = typename WrapperType::NativeType>
constexpr NativeType * asNative (WrapperType *wrapper) noexcept
template<typename WrapperType , typename NativeType = typename WrapperType::NativeType>
constexpr const NativeType * asNative (const WrapperType *wrapper) noexcept
template<typename WrapperType , typename NativeType = typename WrapperType::NativeType>
constexpr NativeType & asNative (WrapperType &wrapper) noexcept
template<typename WrapperType , typename NativeType = typename WrapperType::NativeType>
constexpr const NativeType & asNative (const WrapperType &wrapper) noexcept
Constructor & Destructor Documentation
DataValue() [1/2]
opcua::DataValue::DataValue (Variant value) inline explicit noexcept
Definition at line 1853 of file types.hpp.
DataValue() [2/2]
opcua::DataValue::DataValue (Variant value, std::optional< DateTime > sourceTimestamp, std::optional< DateTime > serverTimestamp, std::optional< uint16_t > sourcePicoseconds, std::optional< uint16_t > serverPicoseconds, std::optional< StatusCode > status) inline noexcept
Definition at line 1857 of file types.hpp.
Member Function Documentation
fromScalar()
template<VariantPolicy Policy = VariantPolicy::Copy, typename... Args> static DataValue opcua::DataValue::fromScalar (Args &&... args) inline static
Create DataValue from scalar value.
Deprecated:
Use constructor with new universal Variant constructor instead: opcua::DataValue dv(opcua::Variant(value))
Definition at line 1887 of file types.hpp.
fromArray()
template<VariantPolicy Policy = VariantPolicy::Copy, typename... Args> static DataValue opcua::DataValue::fromArray (Args &&... args) inline static
Create DataValue from array.
See also
Variant::fromArray
Deprecated:
Use constructor with new universal Variant constructor instead: opcua::DataValue dv(opcua::Variant(array))
Definition at line 1897 of file types.hpp.
setValue() [1/2]
void opcua::DataValue::setValue (const Variant & value) inline
Set value (copy).
Examples
server_datasource.cpp.
Definition at line 1902 of file types.hpp.
Referenced by DataValue().
setValue() [2/2]
void opcua::DataValue::setValue (Variant && value) inline noexcept
Set value (move).
Definition at line 1908 of file types.hpp.
setSourceTimestamp()
void opcua::DataValue::setSourceTimestamp (DateTime sourceTimestamp) inline noexcept
Set source timestamp for the value.
Examples
server_datasource.cpp.
Definition at line 1914 of file types.hpp.
setServerTimestamp()
void opcua::DataValue::setServerTimestamp (DateTime serverTimestamp) inline noexcept
Set server timestamp for the value.
Definition at line 1920 of file types.hpp.
setSourcePicoseconds()
void opcua::DataValue::setSourcePicoseconds (uint16_t sourcePicoseconds) inline noexcept
Set picoseconds interval added to the source timestamp.
Definition at line 1926 of file types.hpp.
setServerPicoseconds()
void opcua::DataValue::setServerPicoseconds (uint16_t serverPicoseconds) inline noexcept
Set picoseconds interval added to the server timestamp.
Definition at line 1932 of file types.hpp.
setStatus()
void opcua::DataValue::setStatus (StatusCode status) inline noexcept
Set status.
Definition at line 1938 of file types.hpp.
hasValue()
bool opcua::DataValue::hasValue () const inline noexcept
Definition at line 1943 of file types.hpp.
hasSourceTimestamp()
bool opcua::DataValue::hasSourceTimestamp () const inline noexcept
Definition at line 1947 of file types.hpp.
hasServerTimestamp()
bool opcua::DataValue::hasServerTimestamp () const inline noexcept
Definition at line 1951 of file types.hpp.
hasSourcePicoseconds()
bool opcua::DataValue::hasSourcePicoseconds () const inline noexcept
Definition at line 1955 of file types.hpp.
hasServerPicoseconds()
bool opcua::DataValue::hasServerPicoseconds () const inline noexcept
Definition at line 1959 of file types.hpp.
hasStatus()
bool opcua::DataValue::hasStatus () const inline noexcept
Definition at line 1963 of file types.hpp.
value() [1/4]
Variant & opcua::DataValue::value () & inline noexcept
Get value.
Examples
server_datasource.cpp, and server_valuecallback.cpp.
Definition at line 1968 of file types.hpp.
Referenced by DataValue(), getValue(), getValue(), getValue(), getValue(), opcua::Node< Connection >::readDataValue(), setValue(), setValue(), value(), value(), value(), and value().
value() [2/4]
const Variant & opcua::DataValue::value () const & inline noexcept
Get value.
Definition at line 1973 of file types.hpp.
value() [3/4]
Variant && opcua::DataValue::value () && inline noexcept
Get value (rvalue).
Definition at line 1978 of file types.hpp.
value() [4/4]
const Variant && opcua::DataValue::value () const && inline noexcept
Get value (rvalue).
Definition at line 1983 of file types.hpp.
getValue() [1/4]
Variant & opcua::DataValue::getValue () & inline noexcept
Deprecated:
Use value() instead
Definition at line 1989 of file types.hpp.
getValue() [2/4]
const Variant & opcua::DataValue::getValue () const & inline noexcept
Deprecated:
Use value() instead
Definition at line 1995 of file types.hpp.
getValue() [3/4]
Variant && opcua::DataValue::getValue () && inline noexcept
Deprecated:
Use value() instead
Definition at line 2001 of file types.hpp.
getValue() [4/4]
const Variant && opcua::DataValue::getValue () const && inline noexcept
Deprecated:
Use value() instead
Definition at line 2007 of file types.hpp.
sourceTimestamp()
DateTime opcua::DataValue::sourceTimestamp () const inline noexcept
Get source timestamp for the value.
Definition at line 2012 of file types.hpp.
Referenced by DataValue(), getSourceTimestamp(), setSourceTimestamp(), and sourceTimestamp().
getSourceTimestamp()
DateTime opcua::DataValue::getSourceTimestamp () const inline noexcept
Deprecated:
Use sourceTimestamp() instead
Definition at line 2018 of file types.hpp.
serverTimestamp()
DateTime opcua::DataValue::serverTimestamp () const inline noexcept
Get server timestamp for the value.
Definition at line 2023 of file types.hpp.
Referenced by DataValue(), getServerTimestamp(), serverTimestamp(), and setServerTimestamp().
getServerTimestamp()
DateTime opcua::DataValue::getServerTimestamp () const inline noexcept
Deprecated:
Use serverTimestamp() instead
Definition at line 2029 of file types.hpp.
sourcePicoseconds()
uint16_t opcua::DataValue::sourcePicoseconds () const inline noexcept
Get picoseconds interval added to the source timestamp.
Definition at line 2034 of file types.hpp.
Referenced by DataValue(), getSourcePicoseconds(), and setSourcePicoseconds().
getSourcePicoseconds()
uint16_t opcua::DataValue::getSourcePicoseconds () const inline noexcept
Deprecated:
Use sourcePicoseconds() instead
Definition at line 2040 of file types.hpp.
serverPicoseconds()
uint16_t opcua::DataValue::serverPicoseconds () const inline noexcept
Get picoseconds interval added to the server timestamp.
Definition at line 2045 of file types.hpp.
Referenced by DataValue(), getServerPicoseconds(), and setServerPicoseconds().
getServerPicoseconds()
uint16_t opcua::DataValue::getServerPicoseconds () const inline noexcept
Deprecated:
Use serverPicoseconds() instead
Definition at line 2051 of file types.hpp.
status()
StatusCode opcua::DataValue::status () const inline noexcept
Get status.
Definition at line 2056 of file types.hpp.
Referenced by getStatus(), and setStatus().
getStatus()
StatusCode opcua::DataValue::getStatus () const inline noexcept
Deprecated:
Use status() instead
Definition at line 2062 of file types.hpp.
TypeWrapper() [1/5]
constexpr opcua::TypeWrapper< T, Index >::TypeWrapper () constexpr default noexcept
TypeWrapper() [2/5]
constexpr opcua::TypeWrapper< T, Index >::TypeWrapper (const T & native) inline explicit constexpr
Constructor with native object (deep copy).
Definition at line 31 of file typewrapper.hpp.
TypeWrapper() [3/5]
constexpr opcua::TypeWrapper< T, Index >::TypeWrapper (T && native) inline constexpr noexcept
Constructor with native object (move rvalue).
Definition at line 35 of file typewrapper.hpp.
TypeWrapper() [4/5]
constexpr opcua::TypeWrapper< T, Index >::TypeWrapper (const TypeWrapper & other) inline constexpr
Copy constructor (deep copy).
Definition at line 43 of file typewrapper.hpp.
TypeWrapper() [5/5]
constexpr opcua::TypeWrapper< T, Index >::TypeWrapper (TypeWrapper && other) inline constexpr noexcept
Move constructor.
Definition at line 47 of file typewrapper.hpp.