open62541pp: opcua::DateTime Class Reference
opcua::DateTime Class Reference
Wrapper classes
#include <types.hpp>
Detailed Description
UA_DateTime wrapper class.
An instance in time. A DateTime value is encoded as a 64-bit signed integer which represents the number of 100 nanosecond intervals since January 1, 1601 (UTC).
See also
https://reference.opcfoundation.org/Core/Part6/v105/docs/5.2.2.5
Examples
client_connect.cpp, client_minimal.cpp, events/client_eventfilter.cpp, and server_valuecallback.cpp.
Definition at line 359 of file types.hpp.
Public Types
using Clock = std::chrono::system_clock
using Duration = std::chrono::duration< int64_t, std::ratio< 1, 10 '000 '000 > >
Public Types inherited from opcua::Wrapper< UA_DateTime >
using NativeType = UA_DateTime
using HandlerType = TypeHandler< UA_DateTime >
Public Member Functions
template<typename D >
constexpr DateTime (std::chrono::time_point< Clock, D > timePoint) noexcept
template<typename D = Duration>
constexpr std::chrono::time_point< Clock, D > toTimePoint () const
constexpr int64_t toUnixTime () const noexcept
UA_DateTimeStruct toStruct () const noexcept
template<typename Rep , typename Period >
constexpr DateTime & operator+= (std::chrono::duration< Rep, Period > duration) noexcept
template<typename Rep , typename Period >
constexpr DateTime & operator-= (std::chrono::duration< Rep, Period > duration) noexcept
constexpr int64_t get () const noexcept
String format (std::string_view format, bool localtime=false) const
constexpr Wrapper () noexcept=default
constexpr Wrapper (const Wrapper &other)
constexpr Wrapper (const T &native)
constexpr Wrapper (Wrapper &&other) noexcept
constexpr Wrapper (T &&native) noexcept
Public Member Functions inherited from opcua::Wrapper< UA_DateTime >
constexpr Wrapper () noexcept=default
constexpr Wrapper (const Wrapper &other)
constexpr Wrapper (const UA_DateTime &native)
constexpr Wrapper (Wrapper &&other) noexcept
constexpr Wrapper (UA_DateTime &&native) noexcept
~Wrapper () noexcept=default
constexpr Wrapper & operator= (const Wrapper &other)
constexpr Wrapper & operator= (const UA_DateTime &native)
constexpr Wrapper & operator= (Wrapper &&other) noexcept
constexpr Wrapper & operator= (UA_DateTime &&native) noexcept
constexpr operator UA_DateTime & () noexcept
constexpr operator const UA_DateTime & () const noexcept
constexpr UA_DateTime * operator-> () noexcept
constexpr const UA_DateTime * operator-> () const noexcept
constexpr UA_DateTime * handle () noexcept
constexpr const UA_DateTime * handle () const noexcept
constexpr void swap (Wrapper &other) noexcept
constexpr void swap (UA_DateTime &native) noexcept
Static Public Member Functions
static DateTime now () noexcept
template<typename D >
static constexpr DateTime fromTimePoint (std::chrono::time_point< Clock, D > timePoint) noexcept
static constexpr DateTime fromUnixTime (int64_t unixTime) noexcept
static int64_t localTimeUtcOffset () noexcept
Related Symbols
(Note that these are not member symbols.)
template<typename Rep , typename Period >
constexpr DateTime operator+ (const DateTime &dt, std::chrono::duration< Rep, Period > duration) noexcept
template<typename Rep , typename Period >
constexpr DateTime operator- (const DateTime &dt, std::chrono::duration< Rep, Period > duration) noexcept
constexpr DateTime::Duration operator- (const DateTime &lhs, const DateTime &rhs) noexcept
Related Symbols inherited from opcua::Wrapper< UA_DateTime >
constexpr UA_DateTime * asWrapper (typename T::NativeType *native) noexcept
constexpr const UA_DateTime * asWrapper (const typename T::NativeType *native) noexcept
constexpr UA_DateTime & asWrapper (typename T::NativeType &native) noexcept
constexpr const UA_DateTime & asWrapper (const typename T::NativeType &native) noexcept
constexpr T::NativeType * asNative (UA_DateTime *wrapper) noexcept
constexpr const T::NativeType * asNative (const UA_DateTime *wrapper) noexcept
constexpr T::NativeType & asNative (UA_DateTime &wrapper) noexcept
constexpr const T::NativeType & asNative (const UA_DateTime &wrapper) noexcept
Additional Inherited Members
Protected Member Functions inherited from opcua::Wrapper< UA_DateTime >
constexpr const UA_DateTime & native () const noexcept
constexpr UA_DateTime & native () noexcept
constexpr void clear () noexcept
Member Typedef Documentation
Clock
using opcua::DateTime::Clock = std::chrono::system_clock
Definition at line 361 of file types.hpp.
Duration
using opcua::DateTime::Duration = std::chrono::duration<int64_t, std::ratio<1, 10'000'000> >
Definition at line 362 of file types.hpp.
Constructor & Destructor Documentation
DateTime()
template<typename D > constexpr opcua::DateTime::DateTime (std::chrono::time_point< Clock, D > timePoint) inline explicit constexpr noexcept
Create DateTime from std::chrono::time_point.
Definition at line 368 of file types.hpp.
Member Function Documentation
format()
String opcua::DateTime::format (std::string_view format, bool localtime = false) const
Convert to string with given format (same format codes as strftime).
See also
https://en.cppreference.com/w/cpp/chrono/c/strftime
Examples
client_minimal.cpp, and server_valuecallback.cpp.
fromTimePoint()
template<typename D > static constexpr DateTime opcua::DateTime::fromTimePoint (std::chrono::time_point< Clock, D > timePoint) inline static constexpr noexcept
Get DateTime from std::chrono::time_point.
Definition at line 381 of file types.hpp.
Referenced by opcua::TypeConverter< std::chrono::time_point< std::chrono::system_clock, Duration > >::toNative().
fromUnixTime()
static constexpr DateTime opcua::DateTime::fromUnixTime (int64_t unixTime) inline static constexpr noexcept
Get DateTime from Unix time.
Definition at line 386 of file types.hpp.
get()
constexpr int64_t opcua::DateTime::get () const inline constexpr noexcept
Get DateTime value as 100 nanosecond intervals since January 1, 1601 (UTC).
Definition at line 428 of file types.hpp.
Referenced by operator+(), and operator-().
localTimeUtcOffset()
static int64_t opcua::DateTime::localTimeUtcOffset () inline static noexcept
Offset of local time to UTC.
Definition at line 391 of file types.hpp.
now()
static DateTime opcua::DateTime::now () inline static noexcept
Get current DateTime.
Examples
events/server_events.cpp, server_callback.cpp, server_datasource.cpp, and server_valuecallback.cpp.
Definition at line 375 of file types.hpp.
operator+=()
template<typename Rep , typename Period > constexpr DateTime & opcua::DateTime::operator+= (std::chrono::duration< Rep, Period > duration) inline constexpr noexcept
Add a duration to the DateTime.
Definition at line 415 of file types.hpp.
operator-=()
template<typename Rep , typename Period > constexpr DateTime & opcua::DateTime::operator-= (std::chrono::duration< Rep, Period > duration) inline constexpr noexcept
Subtract a duration from the DateTime.
Definition at line 422 of file types.hpp.
toStruct()
UA_DateTimeStruct opcua::DateTime::toStruct () const inline noexcept
Convert to UA_DateTimeStruct.
Definition at line 409 of file types.hpp.
toTimePoint()
template<typename D = Duration> constexpr std::chrono::time_point< Clock, D > opcua::DateTime::toTimePoint () const inline constexpr
Convert to std::chrono::time_point.
Definition at line 397 of file types.hpp.
Referenced by opcua::TypeConverter< std::chrono::time_point< std::chrono::system_clock, Duration > >::fromNative().
toUnixTime()
constexpr int64_t opcua::DateTime::toUnixTime () const inline constexpr noexcept
Convert to Unix time (number of seconds since January 1, 1970 UTC).
Definition at line 404 of file types.hpp.
Wrapper() [1/5]
constexpr opcua::Wrapper< T, Handler >::Wrapper () constexpr default noexcept
Wrapper() [2/5]
constexpr opcua::Wrapper< T, Handler >::Wrapper (const T & native) inline explicit constexpr
Copy constructor with native object.
Definition at line 151 of file wrapper.hpp.
Wrapper() [3/5]
constexpr opcua::Wrapper< T, Handler >::Wrapper (const Wrapper & other) inline constexpr
Copy constructor.
Definition at line 147 of file wrapper.hpp.
Wrapper() [4/5]
constexpr opcua::Wrapper< T, Handler >::Wrapper (T && native) inline constexpr noexcept
Move constructor with native object.
Definition at line 159 of file wrapper.hpp.
Wrapper() [5/5]
constexpr opcua::Wrapper< T, Handler >::Wrapper (Wrapper && other) inline constexpr noexcept
Move constructor.
Definition at line 155 of file wrapper.hpp.
Friends And Related Symbol Documentation
operator+()
template<typename Rep , typename Period > constexpr DateTime operator+ (const DateTime & dt, std::chrono::duration< Rep, Period > duration) related
Add a duration to DateTime.
Definition at line 440 of file types.hpp.
operator-() [1/2]
template<typename Rep , typename Period > constexpr DateTime operator- (const DateTime & dt, std::chrono::duration< Rep, Period > duration) related
Subtract a duration from DateTime.
Definition at line 449 of file types.hpp.
operator-() [2/2]
constexpr DateTime::Duration operator- (const DateTime & lhs, const DateTime & rhs) related
Compute the difference between two DateTimes.
Definition at line 457 of file types.hpp.