open62541++: opcua::Server::Connection Class Reference
opcua::Server::Connection Class Reference
Public Member Functions
Connection ()
~Connection ()
Connection (const Connection &)=delete
Connection (Connection &&) noexcept=delete
Connection & operator= (const Connection &)=delete
Connection & operator= (Connection &&) noexcept=delete
void applyDefaults ()
void run ()
void stop ()
bool isRunning () const noexcept
void setLogger (Logger logger)
UA_Server * handle () noexcept
Static Public Member Functions
static void log (void *context, UA_LogLevel level, UA_LogCategory category, const char *msg, va_list args)
Detailed Description
Definition at line 35 of file Server.cpp.
Constructor & Destructor Documentation
Connection() [1/3]
opcua::Server::Connection::Connection () inline
Definition at line 37 of file Server.cpp.
References UA_Server_new().
~Connection()
opcua::Server::Connection::~Connection () inline
Definition at line 40 of file Server.cpp.
References UA_Server_delete(), and UA_Server_run_shutdown().
Connection() [2/3]
opcua::Server::Connection::Connection (const Connection &) delete
Connection() [3/3]
opcua::Server::Connection::Connection (Connection &&) delete noexcept
Member Function Documentation
applyDefaults()
void opcua::Server::Connection::applyDefaults () inline
Definition at line 54 of file Server.cpp.
References UA_RULEHANDLING_ACCEPT.
handle()
UA_Server* opcua::Server::Connection::handle () inline noexcept
Definition at line 125 of file Server.cpp.
isRunning()
bool opcua::Server::Connection::isRunning () const inline noexcept
Definition at line 90 of file Server.cpp.
log()
static void opcua::Server::Connection::log (void * context, UA_LogLevel level, UA_LogCategory category, const char * msg, va_list args) inline static
Definition at line 102 of file Server.cpp.
References args, category, msg, and va_end().
Referenced by setLogger().
operator=() [1/2]
Connection& opcua::Server::Connection::operator= (Connection &&) delete noexcept
operator=() [2/2]
Connection& opcua::Server::Connection::operator= (const Connection &) delete
run()
void opcua::Server::Connection::run () inline
Definition at line 63 of file Server.cpp.
References opcua::detail::throwOnBadStatus(), UA_Server_run_iterate(), and UA_Server_run_startup().
setLogger()
void opcua::Server::Connection::setLogger (Logger logger) inline
Definition at line 94 of file Server.cpp.
References log().
stop()
void opcua::Server::Connection::stop () inline
Definition at line 80 of file Server.cpp.
References opcua::detail::throwOnBadStatus(), and UA_Server_run_shutdown().