open62541pp: opcua::ExpandedNodeId Class Reference
opcua::ExpandedNodeId Class Reference
Wrapper classes
#include <types.hpp>
Detailed Description
UA_ExpandedNodeId wrapper class.
See also
https://reference.opcfoundation.org/Core/Part4/v105/docs/7.16
Definition at line 913 of file types.hpp.
Public Member Functions
ExpandedNodeId (NodeId id) noexcept
ExpandedNodeId (NodeId id, std::string_view namespaceUri, uint32_t serverIndex)
bool isLocal () const noexcept
uint32_t hash () const noexcept
NodeId & nodeId () noexcept
const NodeId & nodeId () const noexcept
NodeId & getNodeId () noexcept
const NodeId & getNodeId () const noexcept
std::string_view namespaceUri () const
std::string_view getNamespaceUri () const
uint32_t serverIndex () const noexcept
uint32_t getServerIndex () const noexcept
std::string toString () const
constexpr TypeWrapper () noexcept=default
constexpr TypeWrapper (const T &native)
constexpr TypeWrapper (T &&native) noexcept
constexpr TypeWrapper (const TypeWrapper &other)
constexpr TypeWrapper (TypeWrapper &&other) noexcept
Public Member Functions inherited from opcua::TypeWrapper< UA_ExpandedNodeId, UA_TYPES_EXPANDEDNODEID >
constexpr TypeWrapper () noexcept=default
constexpr TypeWrapper (const UA_ExpandedNodeId &native)
constexpr TypeWrapper (UA_ExpandedNodeId &&native) noexcept
constexpr TypeWrapper (const TypeWrapper &other)
constexpr TypeWrapper (TypeWrapper &&other) noexcept
~TypeWrapper ()
constexpr TypeWrapper & operator= (const TypeWrapper &other)
constexpr TypeWrapper & operator= (const UA_ExpandedNodeId &native)
constexpr TypeWrapper & operator= (TypeWrapper &&other) noexcept
constexpr TypeWrapper & operator= (UA_ExpandedNodeId &&native) noexcept
Public Member Functions inherited from opcua::Wrapper< UA_ExpandedNodeId >
constexpr Wrapper () noexcept=default
constexpr Wrapper (const UA_ExpandedNodeId &native) noexcept
constexpr Wrapper (UA_ExpandedNodeId &&native) noexcept
constexpr Wrapper & operator= (const UA_ExpandedNodeId &native) noexcept
constexpr Wrapper & operator= (UA_ExpandedNodeId &&native) noexcept
constexpr operator UA_ExpandedNodeId & () noexcept
constexpr operator const UA_ExpandedNodeId & () const noexcept
constexpr UA_ExpandedNodeId * operator-> () noexcept
constexpr const UA_ExpandedNodeId * operator-> () const noexcept
constexpr UA_ExpandedNodeId * handle () noexcept
constexpr const UA_ExpandedNodeId * handle () const noexcept
constexpr void swap (Wrapper &other) noexcept
constexpr void swap (UA_ExpandedNodeId &native) noexcept
Static Public Member Functions
static ExpandedNodeId parse (std::string_view str)
Static Public Member Functions inherited from opcua::TypeWrapper< UA_ExpandedNodeId, UA_TYPES_EXPANDEDNODEID >
static constexpr TypeIndex typeIndex ()
Related Symbols
(Note that these are not member symbols.)
bool operator== (const UA_ExpandedNodeId &lhs, const UA_ExpandedNodeId &rhs) noexcept
bool operator!= (const UA_ExpandedNodeId &lhs, const UA_ExpandedNodeId &rhs) noexcept
bool operator< (const UA_ExpandedNodeId &lhs, const UA_ExpandedNodeId &rhs) noexcept
bool operator> (const UA_ExpandedNodeId &lhs, const UA_ExpandedNodeId &rhs) noexcept
bool operator<= (const UA_ExpandedNodeId &lhs, const UA_ExpandedNodeId &rhs) noexcept
bool operator>= (const UA_ExpandedNodeId &lhs, const UA_ExpandedNodeId &rhs) noexcept
Related Symbols inherited from opcua::TypeWrapper< UA_ExpandedNodeId, UA_TYPES_EXPANDEDNODEID >
String toString (const UA_ExpandedNodeId &object, const UA_DataType &type)
String toString (const UA_ExpandedNodeId &object)
String toString (const UA_ExpandedNodeId &object, const UA_DataType &type)
String toString (const UA_ExpandedNodeId &object)
Related Symbols inherited from opcua::Wrapper< UA_ExpandedNodeId >
constexpr WrapperType * asWrapper (NativeType *native) noexcept
constexpr const WrapperType * asWrapper (const NativeType *native) noexcept
constexpr WrapperType & asWrapper (NativeType &native) noexcept
constexpr const WrapperType & asWrapper (const NativeType &native) noexcept
constexpr NativeType * asNative (WrapperType *wrapper) noexcept
constexpr const NativeType * asNative (const WrapperType *wrapper) noexcept
constexpr NativeType & asNative (WrapperType &wrapper) noexcept
constexpr const NativeType & asNative (const WrapperType &wrapper) noexcept
constexpr WrapperType * asWrapper (NativeType *native) noexcept
constexpr const WrapperType * asWrapper (const NativeType *native) noexcept
constexpr WrapperType & asWrapper (NativeType &native) noexcept
constexpr const WrapperType & asWrapper (const NativeType &native) noexcept
constexpr NativeType * asNative (WrapperType *wrapper) noexcept
constexpr const NativeType * asNative (const WrapperType *wrapper) noexcept
constexpr NativeType & asNative (WrapperType &wrapper) noexcept
constexpr const NativeType & asNative (const WrapperType &wrapper) noexcept
Additional Inherited Members
Public Types inherited from opcua::Wrapper< UA_ExpandedNodeId >
using NativeType
Protected Member Functions inherited from opcua::TypeWrapper< UA_ExpandedNodeId, UA_TYPES_EXPANDEDNODEID >
constexpr void clear () noexcept
Protected Member Functions inherited from opcua::Wrapper< UA_ExpandedNodeId >
constexpr const UA_ExpandedNodeId & native () const noexcept
constexpr UA_ExpandedNodeId & native () noexcept
Constructor & Destructor Documentation
ExpandedNodeId() [1/2]
opcua::ExpandedNodeId::ExpandedNodeId (NodeId id) inline explicit noexcept
Definition at line 917 of file types.hpp.
Referenced by parse().
ExpandedNodeId() [2/2]
opcua::ExpandedNodeId::ExpandedNodeId (NodeId id, std::string_view namespaceUri, uint32_t serverIndex) inline
Definition at line 921 of file types.hpp.
Member Function Documentation
parse()
static ExpandedNodeId opcua::ExpandedNodeId::parse (std::string_view str) inline static
Parse ExpandedNodeId from its string representation.
Format: svr=<serverindex>;ns=<namespaceindex>;<type>=<value> or svr=<serverindex>;nsu=<uri>;<type>=<value>
See also
https://reference.opcfoundation.org/Core/Part6/v104/docs/5.3.1.11
Definition at line 932 of file types.hpp.
isLocal()
bool opcua::ExpandedNodeId::isLocal () const inline noexcept
Definition at line 939 of file types.hpp.
hash()
uint32_t opcua::ExpandedNodeId::hash () const inline noexcept
Definition at line 943 of file types.hpp.
nodeId() [1/2]
NodeId & opcua::ExpandedNodeId::nodeId () inline noexcept
Definition at line 947 of file types.hpp.
Referenced by ExpandedNodeId(), ExpandedNodeId(), getNodeId(), getNodeId(), nodeId(), and nodeId().
nodeId() [2/2]
const NodeId & opcua::ExpandedNodeId::nodeId () const inline noexcept
Definition at line 951 of file types.hpp.
getNodeId() [1/2]
NodeId & opcua::ExpandedNodeId::getNodeId () inline noexcept
Deprecated
Use nodeId() instead
Definition at line 957 of file types.hpp.
getNodeId() [2/2]
const NodeId & opcua::ExpandedNodeId::getNodeId () const inline noexcept
Deprecated
Use nodeId() instead
Definition at line 963 of file types.hpp.
namespaceUri()
std::string_view opcua::ExpandedNodeId::namespaceUri () const inline
Definition at line 967 of file types.hpp.
Referenced by ExpandedNodeId(), getNamespaceUri(), and namespaceUri().
getNamespaceUri()
std::string_view opcua::ExpandedNodeId::getNamespaceUri () const inline
Deprecated
Use namespaceUri() instead
Definition at line 973 of file types.hpp.
serverIndex()
uint32_t opcua::ExpandedNodeId::serverIndex () const inline noexcept
Definition at line 977 of file types.hpp.
Referenced by ExpandedNodeId(), and getServerIndex().
getServerIndex()
uint32_t opcua::ExpandedNodeId::getServerIndex () const inline noexcept
Deprecated
Use serverIndex() instead
Definition at line 983 of file types.hpp.
toString()
std::string opcua::ExpandedNodeId::toString () const
Deprecated
Use free function opcua::toString(const T&) instead
TypeWrapper() [1/5]
opcua::TypeWrapper< T, Index >::TypeWrapper () constexpr default noexcept
TypeWrapper() [2/5]
opcua::TypeWrapper< T, Index >::TypeWrapper (const T & native) inline explicit constexpr
Constructor with native object (deep copy).
Definition at line 31 of file typewrapper.hpp.
TypeWrapper() [3/5]
opcua::TypeWrapper< T, Index >::TypeWrapper (T && native) inline constexpr noexcept
Constructor with native object (move rvalue).
Definition at line 35 of file typewrapper.hpp.
TypeWrapper() [4/5]
opcua::TypeWrapper< T, Index >::TypeWrapper (const TypeWrapper & other) inline constexpr
Copy constructor (deep copy).
Definition at line 43 of file typewrapper.hpp.
TypeWrapper() [5/5]
opcua::TypeWrapper< T, Index >::TypeWrapper (TypeWrapper && other) inline constexpr noexcept
Move constructor.
Definition at line 47 of file typewrapper.hpp.
Friends And Related Symbol Documentation
operator==()
bool operator== (const UA_ExpandedNodeId & lhs, const UA_ExpandedNodeId & rhs) related
Definition at line 993 of file types.hpp.
operator!=()
bool operator!= (const UA_ExpandedNodeId & lhs, const UA_ExpandedNodeId & rhs) related
Definition at line 998 of file types.hpp.
operator<()
bool operator< (const UA_ExpandedNodeId & lhs, const UA_ExpandedNodeId & rhs) related
Definition at line 1003 of file types.hpp.
operator>()
bool operator> (const UA_ExpandedNodeId & lhs, const UA_ExpandedNodeId & rhs) related
Definition at line 1008 of file types.hpp.
operator<=()
bool operator<= (const UA_ExpandedNodeId & lhs, const UA_ExpandedNodeId & rhs) related
Definition at line 1013 of file types.hpp.
operator>=()
bool operator>= (const UA_ExpandedNodeId & lhs, const UA_ExpandedNodeId & rhs) related
Definition at line 1018 of file types.hpp.