open62541++: /home/runner/work/open62541pp/open62541pp/include/open62541pp/Comparison.h File Reference
Comparison.h File Reference
#include "open62541pp/open62541.h"
Functions
bool operator== (const UA_String &left, const UA_String &right) noexcept
bool operator!= (const UA_String &left, const UA_String &right) noexcept
bool operator== (const UA_Guid &left, const UA_Guid &right) noexcept
bool operator!= (const UA_Guid &left, const UA_Guid &right) noexcept
bool operator== (const UA_NodeId &left, const UA_NodeId &right) noexcept
bool operator!= (const UA_NodeId &left, const UA_NodeId &right) noexcept
bool operator< (const UA_NodeId &left, const UA_NodeId &right) noexcept
bool operator> (const UA_NodeId &left, const UA_NodeId &right) noexcept
bool operator<= (const UA_NodeId &left, const UA_NodeId &right) noexcept
bool operator>= (const UA_NodeId &left, const UA_NodeId &right) noexcept
bool operator== (const UA_ExpandedNodeId &left, const UA_ExpandedNodeId &right) noexcept
bool operator!= (const UA_ExpandedNodeId &left, const UA_ExpandedNodeId &right) noexcept
bool operator< (const UA_ExpandedNodeId &left, const UA_ExpandedNodeId &right) noexcept
bool operator> (const UA_ExpandedNodeId &left, const UA_ExpandedNodeId &right) noexcept
bool operator<= (const UA_ExpandedNodeId &left, const UA_ExpandedNodeId &right) noexcept
bool operator>= (const UA_ExpandedNodeId &left, const UA_ExpandedNodeId &right) noexcept
bool operator== (const UA_QualifiedName &left, const UA_QualifiedName &right) noexcept
bool operator!= (const UA_QualifiedName &left, const UA_QualifiedName &right) noexcept
bool operator== (const UA_LocalizedText &left, const UA_LocalizedText &right) noexcept
bool operator!= (const UA_LocalizedText &left, const UA_LocalizedText &right) noexcept
Function Documentation
operator!=() [1/6]
bool operator!= (const UA_ExpandedNodeId & left, const UA_ExpandedNodeId & right) inline noexcept
Definition at line 57 of file Comparison.h.
operator!=() [2/6]
bool operator!= (const UA_Guid & left, const UA_Guid & right) inline noexcept
Definition at line 21 of file Comparison.h.
operator!=() [3/6]
bool operator!= (const UA_LocalizedText & left, const UA_LocalizedText & right) inline noexcept
Definition at line 93 of file Comparison.h.
operator!=() [4/6]
bool operator!= (const UA_NodeId & left, const UA_NodeId & right) inline noexcept
Definition at line 31 of file Comparison.h.
operator!=() [5/6]
bool operator!= (const UA_QualifiedName & left, const UA_QualifiedName & right) inline noexcept
Definition at line 83 of file Comparison.h.
operator!=() [6/6]
bool operator!= (const UA_String & left, const UA_String & right) inline noexcept
Definition at line 11 of file Comparison.h.
operator<() [1/2]
bool operator< (const UA_ExpandedNodeId & left, const UA_ExpandedNodeId & right) inline noexcept
Definition at line 61 of file Comparison.h.
References UA_ExpandedNodeId_order(), and UA_ORDER_LESS.
operator<() [2/2]
bool operator< (const UA_NodeId & left, const UA_NodeId & right) inline noexcept
Definition at line 35 of file Comparison.h.
References UA_NodeId_order(), and UA_ORDER_LESS.
operator<=() [1/2]
bool operator<= (const UA_ExpandedNodeId & left, const UA_ExpandedNodeId & right) inline noexcept
Definition at line 69 of file Comparison.h.
operator<=() [2/2]
bool operator<= (const UA_NodeId & left, const UA_NodeId & right) inline noexcept
Definition at line 43 of file Comparison.h.
operator==() [1/6]
bool operator== (const UA_ExpandedNodeId & left, const UA_ExpandedNodeId & right) inline noexcept
Definition at line 53 of file Comparison.h.
operator==() [2/6]
bool operator== (const UA_Guid & left, const UA_Guid & right) inline noexcept
Definition at line 17 of file Comparison.h.
References UA_Guid_equal().
operator==() [3/6]
bool operator== (const UA_LocalizedText & left, const UA_LocalizedText & right) inline noexcept
Definition at line 89 of file Comparison.h.
operator==() [4/6]
bool operator== (const UA_NodeId & left, const UA_NodeId & right) inline noexcept
Definition at line 27 of file Comparison.h.
operator==() [5/6]
bool operator== (const UA_QualifiedName & left, const UA_QualifiedName & right) inline noexcept
Definition at line 79 of file Comparison.h.
operator==() [6/6]
bool operator== (const UA_String & left, const UA_String & right) inline noexcept
Definition at line 7 of file Comparison.h.
References UA_String_equal().
operator>() [1/2]
bool operator> (const UA_ExpandedNodeId & left, const UA_ExpandedNodeId & right) inline noexcept
Definition at line 65 of file Comparison.h.
References UA_ExpandedNodeId_order(), and UA_ORDER_MORE.
operator>() [2/2]
bool operator> (const UA_NodeId & left, const UA_NodeId & right) inline noexcept
Definition at line 39 of file Comparison.h.
References UA_NodeId_order(), and UA_ORDER_MORE.
operator>=() [1/2]
bool operator>= (const UA_ExpandedNodeId & left, const UA_ExpandedNodeId & right) inline noexcept
Definition at line 73 of file Comparison.h.
operator>=() [2/2]
bool operator>= (const UA_NodeId & left, const UA_NodeId & right) inline noexcept
Definition at line 47 of file Comparison.h.