open62541pp: Browse service
Browse service
Services » View service set
Detailed Description
Discover references of nodes.
See also
https://reference.opcfoundation.org/Core/Part4/v105/docs/5.8.2
Functions
BrowseResponse opcua::services::browse (Client &connection, const BrowseRequest &request) noexcept
template<typename CompletionToken = DefaultCompletionToken>
auto opcua::services::browseAsync (Client &connection, const BrowseRequest &request, CompletionToken &&token=DefaultCompletionToken())
template<typename T >
Result< BrowseResult > opcua::services::browse (T &connection, const BrowseDescription &bd, uint32_t maxReferences=0) noexcept
template<typename CompletionToken = DefaultCompletionToken>
auto opcua::services::browseAsync (Client &connection, const BrowseDescription &bd, uint32_t maxReferences=0, CompletionToken &&token=DefaultCompletionToken())
template<typename T >
Result< std::vector< ReferenceDescription > > opcua::services::browseAll (T &connection, const BrowseDescription &bd, uint32_t maxReferences=0)
Result< std::vector< ExpandedNodeId > > opcua::services::browseRecursive (Server &connection, const BrowseDescription &bd)
Function Documentation
browse() [1/2]
BrowseResponse opcua::services::browse (Client & connection, const BrowseRequest & request) noexcept
Discover the references of one or more nodes (client only).
See also
https://reference.opcfoundation.org/Core/Part4/v105/docs/5.8.2
Parameters
connection Instance of type Client
request Browse request
Referenced by opcua::services::browseAll().
browseAsync() [1/2]
template<typename CompletionToken = DefaultCompletionToken> auto opcua::services::browseAsync (Client & connection, const BrowseRequest & request, CompletionToken && token = DefaultCompletionToken())
Asynchronously discover the references of one or more nodes (client only).
See also
https://reference.opcfoundation.org/Core/Part4/v105/docs/5.8.2
Parameters
connection Instance of type Client
request Browse request
token
The completion token that will be used to produce a completion handler, which will be called when the operation completes. Potential completion tokens include useFuture (default), useDeferred, useDetached, or a function (object) with the correct completion signature. The function signature of the completion handler must be:
void(BrowseResponse&)
Definition at line 54 of file view.hpp.
browse() [2/2]
template<typename T > Result< BrowseResult > opcua::services::browse (T & connection, const BrowseDescription & bd, uint32_t maxReferences = 0) noexcept
Discover the references of a specified node.
See also
https://reference.opcfoundation.org/Core/Part4/v105/docs/5.8.2
Parameters
connection Instance of type Server or Client
bd Browse description
maxReferences The maximum number of references to return (0 if no limit)
browseAsync() [2/2]
template<typename CompletionToken = DefaultCompletionToken> auto opcua::services::browseAsync (Client & connection, const BrowseDescription & bd, uint32_t maxReferences = 0, CompletionToken && token = DefaultCompletionToken())
Asynchronously discover the references of a specified node.
See also
https://reference.opcfoundation.org/Core/Part4/v105/docs/5.8.2
Parameters
connection Instance of type Server or Client
bd Browse description
maxReferences The maximum number of references to return (0 if no limit)
token
The completion token that will be used to produce a completion handler, which will be called when the operation completes. Potential completion tokens include useFuture (default), useDeferred, useDetached, or a function (object) with the correct completion signature. The function signature of the completion handler must be:
void(Result<BrowseResult>&)
Definition at line 82 of file view.hpp.
browseAll()
template<typename T > Result< std::vector< ReferenceDescription > > opcua::services::browseAll (T & connection, const BrowseDescription & bd, uint32_t maxReferences = 0)
Discover all the references of a specified node (without calling browseNext).
See also
https://reference.opcfoundation.org/Core/Part4/v105/docs/5.8.2
Parameters
connection Instance of type Server or Client
bd Browse description
maxReferences The maximum number of references to return (0 if no limit)
Definition at line 365 of file view.hpp.
Referenced by opcua::Node< Connection >::browseReferencedNodes(), and opcua::Node< Connection >::browseReferences().
browseRecursive()
Result< std::vector< ExpandedNodeId > > opcua::services::browseRecursive (Server & connection, const BrowseDescription & bd)
Discover child nodes recursively (non-standard).
Possible loops (that can occur for non-hierarchical references) are handled internally. Every node is added at most once to the results array. Nodes are only added if they match the nodeClassMask in the BrowseDescription. However, child nodes are still recursed into if the NodeClass does not match. So it is possible, for example, to get all VariableNodes below a certain ObjectNode, with additional objects in the hierarchy below.
Note
No implementation for Client.
Parameters
connection Instance of type Server
bd Browse description
See also
UA_Server_browseRecursive