open62541pp: DeleteSubscriptions service
DeleteSubscriptions service
Services » Subscription service set
Detailed Description
Delete subscriptions.
See also
https://reference.opcfoundation.org/Core/Part4/v105/docs/5.14.8
Functions
DeleteSubscriptionsResponse opcua::services::deleteSubscriptions (Client &connection, const DeleteSubscriptionsRequest &request) noexcept
template<typename CompletionToken >
auto opcua::services::deleteSubscriptionsAsync (Client &connection, const DeleteSubscriptionsRequest &request, CompletionToken &&token)
StatusCode opcua::services::deleteSubscription (Client &connection, IntegerId subscriptionId) noexcept
template<typename CompletionToken >
auto opcua::services::deleteSubscriptionAsync (Client &connection, IntegerId subscriptionId, CompletionToken &&token)
Function Documentation
deleteSubscription()
StatusCode opcua::services::deleteSubscription (Client & connection, IntegerId subscriptionId) inline noexcept
Delete a single subscription.
Parameters
connection Instance of type Client
subscriptionId Identifier of the subscription returned by createSubscription
Definition at line 357 of file subscription.hpp.
Referenced by opcua::Subscription< Connection >::deleteSubscription(), and opcua::services::deleteSubscription().
deleteSubscriptionAsync()
template<typename CompletionToken > auto opcua::services::deleteSubscriptionAsync (Client & connection, IntegerId subscriptionId, CompletionToken && token)
Delete a single subscription.
Parameters
connection Instance of type Client
subscriptionId Identifier of the subscription returned by createSubscription
token The completion token that will be used to produce a completion handler, which will be called when the operation completes. Potential completion tokens include useFuture, useDeferred, useDetached, or a function (object) with the correct completion signature. The function signature of the completion handler must be:
void(StatusCode)
Returns
void if token is a callback function (object)
std::future<StatusCode> if token is of type UseFutureToken
auto(auto&& token) callable for deferred execution if token is of type UseDeferredToken
void if token is of type UseDetachedToken
Definition at line 371 of file subscription.hpp.
Referenced by opcua::services::deleteSubscriptionAsync().
deleteSubscriptions()
DeleteSubscriptionsResponse opcua::services::deleteSubscriptions (Client & connection, const DeleteSubscriptionsRequest & request) noexcept
Delete subscriptions.
Parameters
connection Instance of type Client
request Delete subscriptions request
Referenced by opcua::services::deleteSubscription(), and opcua::services::deleteSubscriptions().
deleteSubscriptionsAsync()
template<typename CompletionToken > auto opcua::services::deleteSubscriptionsAsync (Client & connection, const DeleteSubscriptionsRequest & request, CompletionToken && token)
Delete subscriptions.
Parameters
connection Instance of type Client
request Delete subscriptions request
token The completion token that will be used to produce a completion handler, which will be called when the operation completes. Potential completion tokens include useFuture, useDeferred, useDetached, or a function (object) with the correct completion signature. The function signature of the completion handler must be:
void(DeleteSubscriptionsResponse&)
Returns
void if token is a callback function (object)
std::future<DeleteSubscriptionsResponse> if token is of type UseFutureToken
auto(auto&& token) callable for deferred execution if token is of type UseDeferredToken
void if token is of type UseDetachedToken
Definition at line 337 of file subscription.hpp.
Referenced by opcua::services::deleteSubscriptionAsync(), and opcua::services::deleteSubscriptionsAsync().