open62541pp: ModifySubscription service
ModifySubscription service
Services » Subscription service set
Detailed Description
Modify subscriptions.
See also
https://reference.opcfoundation.org/Core/Part4/v105/docs/5.14.3
Functions
ModifySubscriptionResponse opcua::services::modifySubscription (Client &connection, const ModifySubscriptionRequest &request) noexcept
ModifySubscriptionResponse opcua::services::modifySubscription (Client &connection, IntegerId subscriptionId, const SubscriptionParameters &parameters) noexcept
template<typename CompletionToken>
auto opcua::services::modifySubscriptionAsync (Client &connection, const ModifySubscriptionRequest &request, CompletionToken &&token)
template<typename CompletionToken>
auto opcua::services::modifySubscriptionAsync (Client &connection, IntegerId subscriptionId, const SubscriptionParameters &parameters, CompletionToken &&token)
Function Documentation
modifySubscription() [1/2]
ModifySubscriptionResponse opcua::services::modifySubscription (Client & connection, const ModifySubscriptionRequest & request) noexcept
Modify a subscription.
Parameters
connection Instance of type Client
request Modify subscription request
Referenced by modifySubscription(), modifySubscription(), and opcua::Subscription< Connection >::setSubscriptionParameters().
modifySubscription() [2/2]
ModifySubscriptionResponse opcua::services::modifySubscription (Client & connection, IntegerId subscriptionId, const SubscriptionParameters & parameters) inline noexcept
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 200 of file subscription.hpp.
modifySubscriptionAsync() [1/2]
template<typename CompletionToken> auto opcua::services::modifySubscriptionAsync (Client & connection, const ModifySubscriptionRequest & request, CompletionToken && token)
Modify a subscription.
Parameters
connection Instance of type Client
request Modify subscription request
token The completion token that will be used to produce a completion handler, which will be called when the operation completes. Potential completion tokens include useFuture, useDeferred, useDetached, or a function (object) with the correct completion signature. The function signature of the completion handler must be:
void(ModifySubscriptionResponse&)
Returns
void if token is a callback function (object)
std::future<ModifySubscriptionResponse> if token is of type UseFutureToken
auto(auto&& token) callable for deferred execution if token is of type UseDeferredToken
void if token is of type UseDetachedToken
Definition at line 214 of file subscription.hpp.
Referenced by modifySubscriptionAsync(), and modifySubscriptionAsync().
modifySubscriptionAsync() [2/2]
template<typename CompletionToken> auto opcua::services::modifySubscriptionAsync (Client & connection, IntegerId subscriptionId, const SubscriptionParameters & parameters, CompletionToken && token)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 230 of file subscription.hpp.