open62541++: NodeManagement service set
NodeManagement service set
Services
Typedefs
using opcua::services::MethodCallback = std::function< void(Span< const Variant > input, Span< Variant > output)>
Functions
AddNodesResponse opcua::services::addNodes (Client &client, const AddNodesRequest &request)
AddNodesResponse opcua::services::addNodes (Client &client, Span< const AddNodesItem > nodesToAdd)
AddReferencesResponse opcua::services::addReferences (Client &client, const AddReferencesRequest &request)
AddReferencesResponse opcua::services::addReferences (Client &client, Span< const AddReferencesItem > referencesToAdd)
DeleteNodesResponse opcua::services::deleteNodes (Client &client, const DeleteNodesRequest &request)
DeleteNodesResponse opcua::services::deleteNodes (Client &client, Span< const DeleteNodesItem > nodesToDelete)
DeleteReferencesResponse opcua::services::deleteReferences (Client &client, const DeleteReferencesRequest &request)
DeleteReferencesResponse opcua::services::deleteReferences (Client &client, Span< const DeleteReferencesItem > referencesToDelete)
template<typename T >
NodeId opcua::services::addNode (T &serverOrClient, NodeClass nodeClass, const NodeId &parentId, const NodeId &id, std::string_view browseName, const ExtensionObject &nodeAttributes, const NodeId &typeDefinition, const NodeId &referenceType)
template<typename T >
NodeId opcua::services::addObject (T &serverOrClient, const NodeId &parentId, const NodeId &id, std::string_view browseName, const ObjectAttributes &attributes={}, const NodeId &objectType=ObjectTypeId::BaseObjectType, const NodeId &referenceType=ReferenceTypeId::HasComponent)
template<typename T >
NodeId opcua::services::addFolder (T &serverOrClient, const NodeId &parentId, const NodeId &id, std::string_view browseName, const ObjectAttributes &attributes={}, const NodeId &referenceType=ReferenceTypeId::HasComponent)
template<typename T >
NodeId opcua::services::addVariable (T &serverOrClient, const NodeId &parentId, const NodeId &id, std::string_view browseName, const VariableAttributes &attributes={}, const NodeId &variableType=VariableTypeId::BaseDataVariableType, const NodeId &referenceType=ReferenceTypeId::HasComponent)
template<typename T >
NodeId opcua::services::addProperty (T &serverOrClient, const NodeId &parentId, const NodeId &id, std::string_view browseName, const VariableAttributes &attributes={})
template<typename T >
NodeId opcua::services::addMethod (T &serverOrClient, const NodeId &parentId, const NodeId &id, std::string_view browseName, MethodCallback callback, Span< const Argument > inputArguments, Span< const Argument > outputArguments, const MethodAttributes &attributes={}, const NodeId &referenceType=ReferenceTypeId::HasComponent)
template<typename T >
NodeId opcua::services::addObjectType (T &serverOrClient, const NodeId &parentId, const NodeId &id, std::string_view browseName, const ObjectTypeAttributes &attributes={}, const NodeId &referenceType=ReferenceTypeId::HasSubtype)
template<typename T >
NodeId opcua::services::addVariableType (T &serverOrClient, const NodeId &parentId, const NodeId &id, std::string_view browseName, const VariableTypeAttributes &attributes={}, const NodeId &variableType=VariableTypeId::BaseDataVariableType, const NodeId &referenceType=ReferenceTypeId::HasSubtype)
template<typename T >
NodeId opcua::services::addReferenceType (T &serverOrClient, const NodeId &parentId, const NodeId &id, std::string_view browseName, const ReferenceTypeAttributes &attributes={}, const NodeId &referenceType=ReferenceTypeId::HasSubtype)
template<typename T >
NodeId opcua::services::addDataType (T &serverOrClient, const NodeId &parentId, const NodeId &id, std::string_view browseName, const DataTypeAttributes &attributes={}, const NodeId &referenceType=ReferenceTypeId::HasSubtype)
template<typename T >
NodeId opcua::services::addView (T &serverOrClient, const NodeId &parentId, const NodeId &id, std::string_view browseName, const ViewAttributes &attributes={}, const NodeId &referenceType=ReferenceTypeId::Organizes)
template<typename T >
void opcua::services::addReference (T &serverOrClient, const NodeId &sourceId, const NodeId &targetId, const NodeId &referenceType, bool forward=true)
template<typename T >
void opcua::services::addModellingRule (T &serverOrClient, const NodeId &id, ModellingRule rule)
template<typename T >
void opcua::services::deleteNode (T &serverOrClient, const NodeId &id, bool deleteReferences=true)
template<typename T >
void opcua::services::deleteReference (T &serverOrClient, const NodeId &sourceId, const NodeId &targetId, const NodeId &referenceType, bool isForward, bool deleteBidirectional)
Detailed Description
Add/delete nodes and references.
See also
https://reference.opcfoundation.org/Core/Part4/v105/docs/5.7
Typedef Documentation
MethodCallback
using opcua::services::MethodCallback = typedef std::function<void(Span<const Variant> input, Span<Variant> output)>
Method callback.
Parameters
input Input parameters
output Output parameters
Definition at line 208 of file NodeManagement.h.
Function Documentation
addNodes() [1/2]
AddNodesResponse opcua::services::addNodes (Client & client, const AddNodesRequest & request)
Generic function to add one or more nodes (client only).
addNodes() [2/2]
AddNodesResponse opcua::services::addNodes (Client & client, Span< const AddNodesItem > nodesToAdd)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
addReferences() [1/2]
AddReferencesResponse opcua::services::addReferences (Client & client, const AddReferencesRequest & request)
Generic function to add one or more references (client only).
addReferences() [2/2]
AddReferencesResponse opcua::services::addReferences (Client & client, Span< const AddReferencesItem > referencesToAdd)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
deleteNodes() [1/2]
DeleteNodesResponse opcua::services::deleteNodes (Client & client, const DeleteNodesRequest & request)
Generic function to delete one or more nodes (client only).
deleteNodes() [2/2]
DeleteNodesResponse opcua::services::deleteNodes (Client & client, Span< const DeleteNodesItem > nodesToDelete)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
deleteReferences() [1/2]
DeleteReferencesResponse opcua::services::deleteReferences (Client & client, const DeleteReferencesRequest & request)
Generic function to delete one or more references (client only).
deleteReferences() [2/2]
DeleteReferencesResponse opcua::services::deleteReferences (Client & client, Span< const DeleteReferencesItem > referencesToDelete)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
addNode()
template<typename T > NodeId opcua::services::addNode (T & serverOrClient, NodeClass nodeClass, const NodeId & parentId, const NodeId & id, std::string_view browseName, const ExtensionObject & nodeAttributes, const NodeId & typeDefinition, const NodeId & referenceType)
Add node.
Exceptions
BadStatus
addObject()
template<typename T > NodeId opcua::services::addObject (T & serverOrClient, const NodeId & parentId, const NodeId & id, std::string_view browseName, const ObjectAttributes & attributes = {}, const NodeId & objectType = ObjectTypeId::BaseObjectType, const NodeId & referenceType = ReferenceTypeId::HasComponent) inline
Add object.
Exceptions
BadStatus
Definition at line 104 of file NodeManagement.h.
addFolder()
template<typename T > NodeId opcua::services::addFolder (T & serverOrClient, const NodeId & parentId, const NodeId & id, std::string_view browseName, const ObjectAttributes & attributes = {}, const NodeId & referenceType = ReferenceTypeId::HasComponent) inline
Add folder.
Exceptions
BadStatus
Definition at line 131 of file NodeManagement.h.
addVariable()
template<typename T > NodeId opcua::services::addVariable (T & serverOrClient, const NodeId & parentId, const NodeId & id, std::string_view browseName, const VariableAttributes & attributes = {}, const NodeId & variableType = VariableTypeId::BaseDataVariableType, const NodeId & referenceType = ReferenceTypeId::HasComponent) inline
Add variable.
Exceptions
BadStatus
Definition at line 156 of file NodeManagement.h.
addProperty()
template<typename T > NodeId opcua::services::addProperty (T & serverOrClient, const NodeId & parentId, const NodeId & id, std::string_view browseName, const VariableAttributes & attributes = {}) inline
Add property.
Exceptions
BadStatus
Definition at line 183 of file NodeManagement.h.
addMethod()
template<typename T > NodeId opcua::services::addMethod (T & serverOrClient, const NodeId & parentId, const NodeId & id, std::string_view browseName, MethodCallback callback, Span< const Argument > inputArguments, Span< const Argument > outputArguments, const MethodAttributes & attributes = {}, const NodeId & referenceType = ReferenceTypeId::HasComponent)
Add method.
Callbacks can not be set by clients. Servers can assign callbacks to method nodes afterwards.
Exceptions
BadStatus
addObjectType()
template<typename T > NodeId opcua::services::addObjectType (T & serverOrClient, const NodeId & parentId, const NodeId & id, std::string_view browseName, const ObjectTypeAttributes & attributes = {}, const NodeId & referenceType = ReferenceTypeId::HasSubtype) inline
Add object type.
Exceptions
BadStatus
Definition at line 236 of file NodeManagement.h.
addVariableType()
template<typename T > NodeId opcua::services::addVariableType (T & serverOrClient, const NodeId & parentId, const NodeId & id, std::string_view browseName, const VariableTypeAttributes & attributes = {}, const NodeId & variableType = VariableTypeId::BaseDataVariableType, const NodeId & referenceType = ReferenceTypeId::HasSubtype) inline
Add variable type.
Exceptions
BadStatus
Definition at line 262 of file NodeManagement.h.
addReferenceType()
template<typename T > NodeId opcua::services::addReferenceType (T & serverOrClient, const NodeId & parentId, const NodeId & id, std::string_view browseName, const ReferenceTypeAttributes & attributes = {}, const NodeId & referenceType = ReferenceTypeId::HasSubtype) inline
Add reference type.
Exceptions
BadStatus
Definition at line 289 of file NodeManagement.h.
addDataType()
template<typename T > NodeId opcua::services::addDataType (T & serverOrClient, const NodeId & parentId, const NodeId & id, std::string_view browseName, const DataTypeAttributes & attributes = {}, const NodeId & referenceType = ReferenceTypeId::HasSubtype) inline
Add data type.
Exceptions
BadStatus
Definition at line 315 of file NodeManagement.h.
addView()
template<typename T > NodeId opcua::services::addView (T & serverOrClient, const NodeId & parentId, const NodeId & id, std::string_view browseName, const ViewAttributes & attributes = {}, const NodeId & referenceType = ReferenceTypeId::Organizes) inline
Add view.
Exceptions
BadStatus
Definition at line 341 of file NodeManagement.h.
addReference()
template<typename T > void opcua::services::addReference (T & serverOrClient, const NodeId & sourceId, const NodeId & targetId, const NodeId & referenceType, bool forward = true)
Add reference.
Exceptions
BadStatus
Referenced by opcua::services::addModellingRule(), and opcua::Node< ServerOrClient >::addReference().
addModellingRule()
template<typename T > void opcua::services::addModellingRule (T & serverOrClient, const NodeId & id, ModellingRule rule) inline
Add modelling rule.
Exceptions
BadStatus
Definition at line 381 of file NodeManagement.h.
Referenced by opcua::Node< ServerOrClient >::addModellingRule().
deleteNode()
template<typename T > void opcua::services::deleteNode (T & serverOrClient, const NodeId & id, bool deleteReferences = true)
Delete node.
Exceptions
BadStatus
Referenced by opcua::Node< ServerOrClient >::deleteNode().
deleteReference()
template<typename T > void opcua::services::deleteReference (T & serverOrClient, const NodeId & sourceId, const NodeId & targetId, const NodeId & referenceType, bool isForward, bool deleteBidirectional)
Delete reference.
Exceptions
BadStatus
Referenced by opcua::Node< ServerOrClient >::deleteReference().