open62541pp: SetMonitoringMode service
SetMonitoringMode service
Services » MonitoredItem service set
Detailed Description
Set the monitoring mode of a monitored items.
See also
https://reference.opcfoundation.org/Core/Part4/v105/docs/5.12.4
Functions
SetMonitoringModeResponse opcua::services::setMonitoringMode (Client &connection, const SetMonitoringModeRequest &request) noexcept
template<typename CompletionToken >
auto opcua::services::setMonitoringModeAsync (Client &connection, const SetMonitoringModeRequest &request, CompletionToken &&token)
StatusCode opcua::services::setMonitoringMode (Client &connection, uint32_t subscriptionId, uint32_t monitoredItemId, MonitoringMode monitoringMode) noexcept
template<typename CompletionToken >
auto opcua::services::setMonitoringModeAsync (Client &connection, uint32_t subscriptionId, uint32_t monitoredItemId, MonitoringMode monitoringMode, CompletionToken &&token)
Function Documentation
setMonitoringMode() [1/2]
SetMonitoringModeResponse opcua::services::setMonitoringMode (Client & connection, const SetMonitoringModeRequest & request) noexcept
Set the monitoring mode of monitored items.
Parameters
connection Instance of type Client
request Set monitoring mode request
Referenced by opcua::MonitoredItem< Connection >::setMonitoringMode(), and opcua::services::setMonitoringMode().
setMonitoringModeAsync() [1/2]
template<typename CompletionToken > auto opcua::services::setMonitoringModeAsync (Client & connection, const SetMonitoringModeRequest & request, CompletionToken && token)
Set the monitoring mode of monitored items.
Parameters
connection Instance of type Client
request Set monitoring mode request
token The completion token that will be used to produce a completion handler, which will be called when the operation completes. Potential completion tokens include useFuture, useDeferred, useDetached, or a function (object) with the correct completion signature. The function signature of the completion handler must be:
void(SetMonitoringModeResponse&)
Returns
void if token is a callback function (object)
std::future<SetMonitoringModeResponse> if token is of type UseFutureToken
auto(auto&& token) callable for deferred execution if token is of type UseDeferredToken
void if token is of type UseDetachedToken
Definition at line 506 of file monitoreditem.hpp.
Referenced by opcua::services::setMonitoringModeAsync().
setMonitoringMode() [2/2]
StatusCode opcua::services::setMonitoringMode (Client & connection, uint32_t subscriptionId, uint32_t monitoredItemId, MonitoringMode monitoringMode) inline noexcept
Set the monitoring mode of a monitored item.
Parameters
connection Instance of type Client
subscriptionId Identifier of the subscription returned by createSubscription
monitoredItemId Identifier of the monitored item
monitoringMode Monitoring mode
Definition at line 522 of file monitoreditem.hpp.
setMonitoringModeAsync() [2/2]
template<typename CompletionToken > auto opcua::services::setMonitoringModeAsync (Client & connection, uint32_t subscriptionId, uint32_t monitoredItemId, MonitoringMode monitoringMode, CompletionToken && token)
Set the monitoring mode of a monitored item.
Parameters
connection Instance of type Client
subscriptionId Identifier of the subscription returned by createSubscription
monitoredItemId Identifier of the monitored item
monitoringMode Monitoring mode
token The completion token that will be used to produce a completion handler, which will be called when the operation completes. Potential completion tokens include useFuture, useDeferred, useDetached, or a function (object) with the correct completion signature. The function signature of the completion handler must be:
void(StatusCode)
Returns
void if token is a callback function (object)
std::future<StatusCode> if token is of type UseFutureToken
auto(auto&& token) callable for deferred execution if token is of type UseDeferredToken
void if token is of type UseDetachedToken
Definition at line 542 of file monitoreditem.hpp.