open62541pp: AddReferences service
AddReferences service
Services » NodeManagement service set
Detailed Description
Add references to nodes.
See also
https://reference.opcfoundation.org/Core/Part4/v105/docs/5.8.3
Functions
AddReferencesResponse opcua::services::addReferences (Client &connection, const AddReferencesRequest &request) noexcept
template<typename CompletionToken>
auto opcua::services::addReferencesAsync (Client &connection, const AddReferencesRequest &request, CompletionToken &&token)
template<typename T>
StatusCode opcua::services::addReference (T &connection, const NodeId &sourceId, const NodeId &targetId, const NodeId &referenceType, bool forward) noexcept
template<typename CompletionToken>
auto opcua::services::addReferenceAsync (Client &connection, const NodeId &sourceId, const NodeId &targetId, const NodeId &referenceType, bool forward, CompletionToken &&token)
template<typename T>
StatusCode opcua::services::addModellingRule (T &connection, const NodeId &id, ModellingRule rule) noexcept
template<typename CompletionToken>
auto opcua::services::addModellingRuleAsync (Client &connection, const NodeId &id, ModellingRule rule, CompletionToken &&token)
Function Documentation
addReferences()
AddReferencesResponse opcua::services::addReferences (Client & connection, const AddReferencesRequest & request) noexcept
Add one or more references (client only).
Parameters
connection Instance of type Client
request Add references request
addReferencesAsync()
template<typename CompletionToken> auto opcua::services::addReferencesAsync (Client & connection, const AddReferencesRequest & request, CompletionToken && token)
Add one or more references (client only).
Parameters
connection Instance of type Client
request Add references request
token The completion token that will be used to produce a completion handler, which will be called when the operation completes. Potential completion tokens include useFuture, useDeferred, useDetached, or a function (object) with the correct completion signature. The function signature of the completion handler must be:
void(AddReferencesResponse&)
Returns
void if token is a callback function (object)
std::future<AddReferencesReponse> if token is of type UseFutureToken
auto(auto&& token) callable for deferred execution if token is of type UseDeferredToken
void if token is of type UseDetachedToken
Definition at line 142 of file nodemanagement.hpp.
Referenced by addReferenceAsync().
addReference()
template<typename T> StatusCode opcua::services::addReference (T & connection, const NodeId & sourceId, const NodeId & targetId, const NodeId & referenceType, bool forward) noexcept
Add reference.
Parameters
connection Instance of type Client (or Server)
sourceId Node to which the reference is to be added
targetId Target node
referenceType NodeId of the reference type that defines the reference
forward Create a forward reference if true or a inverse reference if false
Referenced by addModellingRule(), and opcua::Node< Connection >::addReference().
addReferenceAsync()
template<typename CompletionToken> auto opcua::services::addReferenceAsync (Client & connection, const NodeId & sourceId, const NodeId & targetId, const NodeId & referenceType, bool forward, CompletionToken && token)
Add reference.
Parameters
connection Instance of type Client (or Server)
sourceId Node to which the reference is to be added
targetId Target node
referenceType NodeId of the reference type that defines the reference
forward Create a forward reference if true or a inverse reference if false
token The completion token that will be used to produce a completion handler, which will be called when the operation completes. Potential completion tokens include useFuture, useDeferred, useDetached, or a function (object) with the correct completion signature. The function signature of the completion handler must be:
void(StatusCode)
Returns
void if token is a callback function (object)
std::future<StatusCode> if token is of type UseFutureToken
auto(auto&& token) callable for deferred execution if token is of type UseDeferredToken
void if token is of type UseDetachedToken
Definition at line 173 of file nodemanagement.hpp.
Referenced by addModellingRuleAsync(), and opcua::Node< Connection >::addReferenceAsync().
addModellingRule()
template<typename T> StatusCode opcua::services::addModellingRule (T & connection, const NodeId & id, ModellingRule rule) noexcept
Add modelling rule.
Parameters
connection Instance of type Client (or Server)
id Node
rule Modelling rule to add
See also
https://reference.opcfoundation.org/Core/Part3/v105/docs/6.4.4
Definition at line 946 of file nodemanagement.hpp.
Referenced by opcua::Node< Connection >::addModellingRule().
addModellingRuleAsync()
template<typename CompletionToken> auto opcua::services::addModellingRuleAsync (Client & connection, const NodeId & id, ModellingRule rule, CompletionToken && token)
Add modelling rule.
Parameters
connection Instance of type Client (or Server)
id Node
rule Modelling rule to add
See also
https://reference.opcfoundation.org/Core/Part3/v105/docs/6.4.4
Parameters
token The completion token that will be used to produce a completion handler, which will be called when the operation completes. Potential completion tokens include useFuture, useDeferred, useDetached, or a function (object) with the correct completion signature. The function signature of the completion handler must be:
void(StatusCode)
Returns
void if token is a callback function (object)
std::future<StatusCode> if token is of type UseFutureToken
auto(auto&& token) callable for deferred execution if token is of type UseDeferredToken
void if token is of type UseDetachedToken
Definition at line 958 of file nodemanagement.hpp.
Referenced by opcua::Node< Connection >::addModellingRuleAsync().