open62541pp: Read service
Read service
Services » Attribute service set
Detailed Description
This service is used to read attributes of nodes.
See also
https://reference.opcfoundation.org/Core/Part4/v105/docs/5.11.2
Functions
ReadResponse opcua::services::read (Client &connection, const ReadRequest &request) noexcept
ReadResponse opcua::services::read (Client &connection, Span< const ReadValueId > nodesToRead, TimestampsToReturn timestamps) noexcept
template<typename CompletionToken >
auto opcua::services::readAsync (Client &connection, const ReadRequest &request, CompletionToken &&token)
template<typename CompletionToken >
auto opcua::services::readAsync (Client &connection, Span< const ReadValueId > nodesToRead, TimestampsToReturn timestamps, CompletionToken &&token)
template<typename T >
Result< DataValue > opcua::services::readAttribute (T &connection, const NodeId &id, AttributeId attributeId, TimestampsToReturn timestamps) noexcept
template<typename CompletionToken >
auto opcua::services::readAttributeAsync (Client &connection, const NodeId &id, AttributeId attributeId, TimestampsToReturn timestamps, CompletionToken &&token)
template<typename T >
Result< DataValue > opcua::services::readDataValue (T &connection, const NodeId &id) noexcept
template<typename CompletionToken >
auto opcua::services::readDataValueAsync (Client &connection, const NodeId &id, CompletionToken &&token)
template<typename T >
Result< NodeId > opcua::services::readNodeId (T &connection, const NodeId &id) noexcept
template<typename CompletionToken >
auto opcua::services::readNodeIdAsync (Client &connection, const NodeId &id, CompletionToken &&token)
template<typename T >
Result< NodeClass > opcua::services::readNodeClass (T &connection, const NodeId &id) noexcept
template<typename CompletionToken >
auto opcua::services::readNodeClassAsync (Client &connection, const NodeId &id, CompletionToken &&token)
template<typename T >
Result< QualifiedName > opcua::services::readBrowseName (T &connection, const NodeId &id) noexcept
template<typename CompletionToken >
auto opcua::services::readBrowseNameAsync (Client &connection, const NodeId &id, CompletionToken &&token)
template<typename T >
Result< LocalizedText > opcua::services::readDisplayName (T &connection, const NodeId &id) noexcept
template<typename CompletionToken >
auto opcua::services::readDisplayNameAsync (Client &connection, const NodeId &id, CompletionToken &&token)
template<typename T >
Result< LocalizedText > opcua::services::readDescription (T &connection, const NodeId &id) noexcept
template<typename CompletionToken >
auto opcua::services::readDescriptionAsync (Client &connection, const NodeId &id, CompletionToken &&token)
template<typename T >
Result< Bitmask< WriteMask > > opcua::services::readWriteMask (T &connection, const NodeId &id) noexcept
template<typename CompletionToken >
auto opcua::services::readWriteMaskAsync (Client &connection, const NodeId &id, CompletionToken &&token)
template<typename T >
Result< Bitmask< WriteMask > > opcua::services::readUserWriteMask (T &connection, const NodeId &id) noexcept
template<typename CompletionToken >
auto opcua::services::readUserWriteMaskAsync (Client &connection, const NodeId &id, CompletionToken &&token)
template<typename T >
Result< bool > opcua::services::readIsAbstract (T &connection, const NodeId &id) noexcept
template<typename CompletionToken >
auto opcua::services::readIsAbstractAsync (Client &connection, const NodeId &id, CompletionToken &&token)
template<typename T >
Result< bool > opcua::services::readSymmetric (T &connection, const NodeId &id) noexcept
template<typename CompletionToken >
auto opcua::services::readSymmetricAsync (Client &connection, const NodeId &id, CompletionToken &&token)
template<typename T >
Result< LocalizedText > opcua::services::readInverseName (T &connection, const NodeId &id) noexcept
template<typename CompletionToken >
auto opcua::services::readInverseNameAsync (Client &connection, const NodeId &id, CompletionToken &&token)
template<typename T >
Result< bool > opcua::services::readContainsNoLoops (T &connection, const NodeId &id) noexcept
template<typename CompletionToken >
auto opcua::services::readContainsNoLoopsAsync (Client &connection, const NodeId &id, CompletionToken &&token)
template<typename T >
Result< Bitmask< EventNotifier > > opcua::services::readEventNotifier (T &connection, const NodeId &id) noexcept
template<typename CompletionToken >
auto opcua::services::readEventNotifierAsync (Client &connection, const NodeId &id, CompletionToken &&token)
template<typename T >
Result< Variant > opcua::services::readValue (T &connection, const NodeId &id) noexcept
template<typename CompletionToken >
auto opcua::services::readValueAsync (Client &connection, const NodeId &id, CompletionToken &&token)
template<typename T >
Result< NodeId > opcua::services::readDataType (T &connection, const NodeId &id) noexcept
template<typename CompletionToken >
auto opcua::services::readDataTypeAsync (Client &connection, const NodeId &id, CompletionToken &&token)
template<typename T >
Result< ValueRank > opcua::services::readValueRank (T &connection, const NodeId &id) noexcept
template<typename CompletionToken >
auto opcua::services::readValueRankAsync (Client &connection, const NodeId &id, CompletionToken &&token)
template<typename T >
Result< std::vector< uint32_t > > opcua::services::readArrayDimensions (T &connection, const NodeId &id) noexcept
template<typename CompletionToken >
auto opcua::services::readArrayDimensionsAsync (Client &connection, const NodeId &id, CompletionToken &&token)
template<typename T >
Result< Bitmask< AccessLevel > > opcua::services::readAccessLevel (T &connection, const NodeId &id) noexcept
template<typename CompletionToken >
auto opcua::services::readAccessLevelAsync (Client &connection, const NodeId &id, CompletionToken &&token)
template<typename T >
Result< Bitmask< AccessLevel > > opcua::services::readUserAccessLevel (T &connection, const NodeId &id) noexcept
template<typename CompletionToken >
auto opcua::services::readUserAccessLevelAsync (Client &connection, const NodeId &id, CompletionToken &&token)
template<typename T >
Result< double > opcua::services::readMinimumSamplingInterval (T &connection, const NodeId &id) noexcept
template<typename CompletionToken >
auto opcua::services::readMinimumSamplingIntervalAsync (Client &connection, const NodeId &id, CompletionToken &&token)
template<typename T >
Result< bool > opcua::services::readHistorizing (T &connection, const NodeId &id) noexcept
template<typename CompletionToken >
auto opcua::services::readHistorizingAsync (Client &connection, const NodeId &id, CompletionToken &&token)
template<typename T >
Result< bool > opcua::services::readExecutable (T &connection, const NodeId &id) noexcept
template<typename CompletionToken >
auto opcua::services::readExecutableAsync (Client &connection, const NodeId &id, CompletionToken &&token)
template<typename T >
Result< bool > opcua::services::readUserExecutable (T &connection, const NodeId &id) noexcept
template<typename CompletionToken >
auto opcua::services::readUserExecutableAsync (Client &connection, const NodeId &id, CompletionToken &&token)
template<typename T >
Result< Variant > opcua::services::readDataTypeDefinition (T &connection, const NodeId &id) noexcept
template<typename CompletionToken >
auto opcua::services::readDataTypeDefinitionAsync (Client &connection, const NodeId &id, CompletionToken &&token)
Function Documentation
read() [1/2]
ReadResponse opcua::services::read (Client & connection, const ReadRequest & request) noexcept
Read one or more attributes of one or more nodes (client only).
Parameters
connection Instance of type Client
request Read request
Referenced by opcua::services::read().
read() [2/2]
ReadResponse opcua::services::read (Client & connection, Span< const ReadValueId > nodesToRead, TimestampsToReturn timestamps) inline noexcept
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 48 of file attribute.hpp.
readAccessLevel()
template<typename T > Result< Bitmask< AccessLevel > > opcua::services::readAccessLevel (T & connection, const NodeId & id) noexcept
Read the AttributeId::AccessLevel attribute of a node.
Parameters
connection Instance of type Client (or Server)
id Node to read
Definition at line 806 of file attribute_highlevel.hpp.
Referenced by opcua::Node< Connection >::readAccessLevel().
readAccessLevelAsync()
template<typename CompletionToken > auto opcua::services::readAccessLevelAsync (Client & connection, const NodeId & id, CompletionToken && token)
Read the AttributeId::AccessLevel attribute of a node.
Parameters
connection Instance of type Client (or Server)
id Node to read
token The completion token that will be used to produce a completion handler, which will be called when the operation completes. Potential completion tokens include useFuture, useDeferred, useDetached, or a function (object) with the correct completion signature. The function signature of the completion handler must be:
void(Result<Bitmask<AccessLevel>>)
Returns
void if token is a callback function (object)
std::future<Result<Bitmask<AccessLevel>>> if token is of type UseFutureToken
auto(auto&& token) callable for deferred execution if token is of type UseDeferredToken
void if token is of type UseDetachedToken
Definition at line 817 of file attribute_highlevel.hpp.
readArrayDimensions()
template<typename T > Result< std::vector< uint32_t > > opcua::services::readArrayDimensions (T & connection, const NodeId & id) noexcept
Read the AttributeId::ArrayDimensions attribute of a node.
Parameters
connection Instance of type Client (or Server)
id Node to read
Definition at line 748 of file attribute_highlevel.hpp.
Referenced by opcua::Node< Connection >::readArrayDimensions().
readArrayDimensionsAsync()
template<typename CompletionToken > auto opcua::services::readArrayDimensionsAsync (Client & connection, const NodeId & id, CompletionToken && token)
Read the AttributeId::ArrayDimensions attribute of a node.
Parameters
connection Instance of type Client (or Server)
id Node to read
token The completion token that will be used to produce a completion handler, which will be called when the operation completes. Potential completion tokens include useFuture, useDeferred, useDetached, or a function (object) with the correct completion signature. The function signature of the completion handler must be:
void(Result<std::vector<uint32_t>>&)
Returns
void if token is a callback function (object)
std::future<Result<std::vector<uint32_t>>> if token is of type UseFutureToken
auto(auto&& token) callable for deferred execution if token is of type UseDeferredToken
void if token is of type UseDetachedToken
Definition at line 759 of file attribute_highlevel.hpp.
readAsync() [1/2]
template<typename CompletionToken > auto opcua::services::readAsync (Client & connection, const ReadRequest & request, CompletionToken && token)
Read one or more attributes of one or more nodes (client only).
Parameters
connection Instance of type Client
request Read request
token The completion token that will be used to produce a completion handler, which will be called when the operation completes. Potential completion tokens include useFuture, useDeferred, useDetached, or a function (object) with the correct completion signature. The function signature of the completion handler must be:
void(ReadResponse&)
Returns
void if token is a callback function (object)
std::future<ReadResponse> if token is of type UseFutureToken
auto(auto&& token) callable for deferred execution if token is of type UseDeferredToken
void if token is of type UseDetachedToken
Definition at line 61 of file attribute.hpp.
Referenced by opcua::services::readAsync(), and opcua::services::readAttributeAsync().
readAsync() [2/2]
template<typename CompletionToken > auto opcua::services::readAsync (Client & connection, Span< const ReadValueId > nodesToRead, TimestampsToReturn timestamps, CompletionToken && token)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 69 of file attribute.hpp.
readAttribute()
template<typename T > Result< DataValue > opcua::services::readAttribute (T & connection, const NodeId & id, AttributeId attributeId, TimestampsToReturn timestamps) noexcept
Read node attribute.
Parameters
connection Instance of type Client (or Server)
id Node to read
attributeId Attribute to read
timestamps Timestamps to return, e.g. TimestampsToReturn::Neither
Referenced by opcua::services::readDataValue().
readAttributeAsync()
template<typename CompletionToken > auto opcua::services::readAttributeAsync (Client & connection, const NodeId & id, AttributeId attributeId, TimestampsToReturn timestamps, CompletionToken && token)
Read node attribute.
Parameters
connection Instance of type Client (or Server)
id Node to read
attributeId Attribute to read
timestamps Timestamps to return, e.g. TimestampsToReturn::Neither
token The completion token that will be used to produce a completion handler, which will be called when the operation completes. Potential completion tokens include useFuture, useDeferred, useDetached, or a function (object) with the correct completion signature. The function signature of the completion handler must be:
void(Result<DataValue>&)
Returns
void if token is a callback function (object)
std::future<Result<DataValue>> if token is of type UseFutureToken
auto(auto&& token) callable for deferred execution if token is of type UseDeferredToken
void if token is of type UseDetachedToken
Definition at line 99 of file attribute.hpp.
Referenced by opcua::services::readDataValueAsync().
readBrowseName()
template<typename T > Result< QualifiedName > opcua::services::readBrowseName (T & connection, const NodeId & id) noexcept
Read the AttributeId::BrowseName attribute of a node.
Parameters
connection Instance of type Client (or Server)
id Node to read
Definition at line 66 of file attribute_highlevel.hpp.
Referenced by opcua::Node< Connection >::readBrowseName().
readBrowseNameAsync()
template<typename CompletionToken > auto opcua::services::readBrowseNameAsync (Client & connection, const NodeId & id, CompletionToken && token)
Read the AttributeId::BrowseName attribute of a node.
Parameters
connection Instance of type Client (or Server)
id Node to read
token The completion token that will be used to produce a completion handler, which will be called when the operation completes. Potential completion tokens include useFuture, useDeferred, useDetached, or a function (object) with the correct completion signature. The function signature of the completion handler must be:
void(Result<QualifiedName>&)
Returns
void if token is a callback function (object)
std::future<Result<QualifiedName>> if token is of type UseFutureToken
auto(auto&& token) callable for deferred execution if token is of type UseDeferredToken
void if token is of type UseDetachedToken
Definition at line 77 of file attribute_highlevel.hpp.
readContainsNoLoops()
template<typename T > Result< bool > opcua::services::readContainsNoLoops (T & connection, const NodeId & id) noexcept
Read the AttributeId::ContainsNoLoops attribute of a node.
Parameters
connection Instance of type Client (or Server)
id Node to read
Definition at line 484 of file attribute_highlevel.hpp.
Referenced by opcua::Node< Connection >::readContainsNoLoops().
readContainsNoLoopsAsync()
template<typename CompletionToken > auto opcua::services::readContainsNoLoopsAsync (Client & connection, const NodeId & id, CompletionToken && token)
Read the AttributeId::ContainsNoLoops attribute of a node.
Parameters
connection Instance of type Client (or Server)
id Node to read
token The completion token that will be used to produce a completion handler, which will be called when the operation completes. Potential completion tokens include useFuture, useDeferred, useDetached, or a function (object) with the correct completion signature. The function signature of the completion handler must be:
void(Result<bool>&)
Returns
void if token is a callback function (object)
std::future<Result<bool>> if token is of type UseFutureToken
auto(auto&& token) callable for deferred execution if token is of type UseDeferredToken
void if token is of type UseDetachedToken
Definition at line 495 of file attribute_highlevel.hpp.
readDataType()
template<typename T > Result< NodeId > opcua::services::readDataType (T & connection, const NodeId & id) noexcept
Read the AttributeId::DataType attribute of a node.
Parameters
connection Instance of type Client (or Server)
id Node to read
Definition at line 646 of file attribute_highlevel.hpp.
Referenced by opcua::Node< Connection >::readDataType().
readDataTypeAsync()
template<typename CompletionToken > auto opcua::services::readDataTypeAsync (Client & connection, const NodeId & id, CompletionToken && token)
Read the AttributeId::DataType attribute of a node.
Parameters
connection Instance of type Client (or Server)
id Node to read
token The completion token that will be used to produce a completion handler, which will be called when the operation completes. Potential completion tokens include useFuture, useDeferred, useDetached, or a function (object) with the correct completion signature. The function signature of the completion handler must be:
void(Result<NodeId>&)
Returns
void if token is a callback function (object)
std::future<Result<NodeId>> if token is of type UseFutureToken
auto(auto&& token) callable for deferred execution if token is of type UseDeferredToken
void if token is of type UseDetachedToken
Definition at line 657 of file attribute_highlevel.hpp.
readDataTypeDefinition()
template<typename T > Result< Variant > opcua::services::readDataTypeDefinition (T & connection, const NodeId & id) noexcept
Read the AttributeId::DataTypeDefinition attribute of a node.
The attribute value can be of type EnumDefinition or StructureDefinition.
Parameters
connection Instance of type Client (or Server)
id Node to read
Definition at line 1128 of file attribute_highlevel.hpp.
Referenced by opcua::Node< Connection >::readDataTypeDefinition().
readDataTypeDefinitionAsync()
template<typename CompletionToken > auto opcua::services::readDataTypeDefinitionAsync (Client & connection, const NodeId & id, CompletionToken && token)
Read the AttributeId::DataTypeDefinition attribute of a node.
The attribute value can be of type EnumDefinition or StructureDefinition.
Parameters
connection Instance of type Client (or Server)
id Node to read
token The completion token that will be used to produce a completion handler, which will be called when the operation completes. Potential completion tokens include useFuture, useDeferred, useDetached, or a function (object) with the correct completion signature. The function signature of the completion handler must be:
void(Result<Variant>&)
Returns
void if token is a callback function (object)
std::future<Result<Variant>> if token is of type UseFutureToken
auto(auto&& token) callable for deferred execution if token is of type UseDeferredToken
void if token is of type UseDetachedToken
Definition at line 1139 of file attribute_highlevel.hpp.
readDataValue()
template<typename T > Result< DataValue > opcua::services::readDataValue (T & connection, const NodeId & id) noexcept
Read the AttributeId::Value attribute of a node as a DataValue object.
Parameters
connection Instance of type Client (or Server)
id Node to read
Definition at line 268 of file attribute.hpp.
Referenced by opcua::Node< Connection >::readDataValue().
readDataValueAsync()
template<typename CompletionToken > auto opcua::services::readDataValueAsync (Client & connection, const NodeId & id, CompletionToken && token)
Read the AttributeId::Value attribute of a node as a DataValue object.
Parameters
connection Instance of type Client (or Server)
id Node to read
token The completion token that will be used to produce a completion handler, which will be called when the operation completes. Potential completion tokens include useFuture, useDeferred, useDetached, or a function (object) with the correct completion signature. The function signature of the completion handler must be:
void(Result<DataValue>&)
Returns
void if token is a callback function (object)
std::future<Result<DataValue>> if token is of type UseFutureToken
auto(auto&& token) callable for deferred execution if token is of type UseDeferredToken
void if token is of type UseDetachedToken
Definition at line 279 of file attribute.hpp.
readDescription()
template<typename T > Result< LocalizedText > opcua::services::readDescription (T & connection, const NodeId & id) noexcept
Read the AttributeId::Description attribute of a node.
Parameters
connection Instance of type Client (or Server)
id Node to read
Definition at line 172 of file attribute_highlevel.hpp.
Referenced by opcua::Node< Connection >::readDescription().
readDescriptionAsync()
template<typename CompletionToken > auto opcua::services::readDescriptionAsync (Client & connection, const NodeId & id, CompletionToken && token)
Read the AttributeId::Description attribute of a node.
Parameters
connection Instance of type Client (or Server)
id Node to read
token The completion token that will be used to produce a completion handler, which will be called when the operation completes. Potential completion tokens include useFuture, useDeferred, useDetached, or a function (object) with the correct completion signature. The function signature of the completion handler must be:
void(Result<LocalizedText>&)
Returns
void if token is a callback function (object)
std::future<Result<LocalizedText>> if token is of type UseFutureToken
auto(auto&& token) callable for deferred execution if token is of type UseDeferredToken
void if token is of type UseDetachedToken
Definition at line 183 of file attribute_highlevel.hpp.
readDisplayName()
template<typename T > Result< LocalizedText > opcua::services::readDisplayName (T & connection, const NodeId & id) noexcept
Read the AttributeId::DisplayName attribute of a node.
Parameters
connection Instance of type Client (or Server)
id Node to read
Definition at line 119 of file attribute_highlevel.hpp.
Referenced by opcua::Node< Connection >::readDisplayName().
readDisplayNameAsync()
template<typename CompletionToken > auto opcua::services::readDisplayNameAsync (Client & connection, const NodeId & id, CompletionToken && token)
Read the AttributeId::DisplayName attribute of a node.
Parameters
connection Instance of type Client (or Server)
id Node to read
token The completion token that will be used to produce a completion handler, which will be called when the operation completes. Potential completion tokens include useFuture, useDeferred, useDetached, or a function (object) with the correct completion signature. The function signature of the completion handler must be:
void(Result<LocalizedText>&)
Returns
void if token is a callback function (object)
std::future<Result<LocalizedText>> if token is of type UseFutureToken
auto(auto&& token) callable for deferred execution if token is of type UseDeferredToken
void if token is of type UseDetachedToken
Definition at line 130 of file attribute_highlevel.hpp.
readEventNotifier()
template<typename T > Result< Bitmask< EventNotifier > > opcua::services::readEventNotifier (T & connection, const NodeId & id) noexcept
Read the AttributeId::EventNotifier attribute of a node.
Parameters
connection Instance of type Client (or Server)
id Node to read
Definition at line 539 of file attribute_highlevel.hpp.
Referenced by opcua::Node< Connection >::readEventNotifier().
readEventNotifierAsync()
template<typename CompletionToken > auto opcua::services::readEventNotifierAsync (Client & connection, const NodeId & id, CompletionToken && token)
Read the AttributeId::EventNotifier attribute of a node.
Parameters
connection Instance of type Client (or Server)
id Node to read
token The completion token that will be used to produce a completion handler, which will be called when the operation completes. Potential completion tokens include useFuture, useDeferred, useDetached, or a function (object) with the correct completion signature. The function signature of the completion handler must be:
void(Result<Bitmask<EventNotifier>>)
Returns
void if token is a callback function (object)
std::future<Result<Bitmask<EventNotifier>>> if token is of type UseFutureToken
auto(auto&& token) callable for deferred execution if token is of type UseDeferredToken
void if token is of type UseDetachedToken
Definition at line 550 of file attribute_highlevel.hpp.
readExecutable()
template<typename T > Result< bool > opcua::services::readExecutable (T & connection, const NodeId & id) noexcept
Read the AttributeId::Executable attribute of a node.
Parameters
connection Instance of type Client (or Server)
id Node to read
Definition at line 1025 of file attribute_highlevel.hpp.
Referenced by opcua::Node< Connection >::readExecutable().
readExecutableAsync()
template<typename CompletionToken > auto opcua::services::readExecutableAsync (Client & connection, const NodeId & id, CompletionToken && token)
Read the AttributeId::Executable attribute of a node.
Parameters
connection Instance of type Client (or Server)
id Node to read
token The completion token that will be used to produce a completion handler, which will be called when the operation completes. Potential completion tokens include useFuture, useDeferred, useDetached, or a function (object) with the correct completion signature. The function signature of the completion handler must be:
void(Result<bool>)
Returns
void if token is a callback function (object)
std::future<Result<bool>> if token is of type UseFutureToken
auto(auto&& token) callable for deferred execution if token is of type UseDeferredToken
void if token is of type UseDetachedToken
Definition at line 1036 of file attribute_highlevel.hpp.
readHistorizing()
template<typename T > Result< bool > opcua::services::readHistorizing (T & connection, const NodeId & id) noexcept
Read the AttributeId::Historizing attribute of a node.
Parameters
connection Instance of type Client (or Server)
id Node to read
Definition at line 974 of file attribute_highlevel.hpp.
Referenced by opcua::Node< Connection >::readHistorizing().
readHistorizingAsync()
template<typename CompletionToken > auto opcua::services::readHistorizingAsync (Client & connection, const NodeId & id, CompletionToken && token)
Read the AttributeId::Historizing attribute of a node.
Parameters
connection Instance of type Client (or Server)
id Node to read
token The completion token that will be used to produce a completion handler, which will be called when the operation completes. Potential completion tokens include useFuture, useDeferred, useDetached, or a function (object) with the correct completion signature. The function signature of the completion handler must be:
void(Result<bool>)
Returns
void if token is a callback function (object)
std::future<Result<bool>> if token is of type UseFutureToken
auto(auto&& token) callable for deferred execution if token is of type UseDeferredToken
void if token is of type UseDetachedToken
Definition at line 985 of file attribute_highlevel.hpp.
readInverseName()
template<typename T > Result< LocalizedText > opcua::services::readInverseName (T & connection, const NodeId & id) noexcept
Read the AttributeId::InverseName attribute of a node.
Parameters
connection Instance of type Client (or Server)
id Node to read
Definition at line 431 of file attribute_highlevel.hpp.
Referenced by opcua::Node< Connection >::readInverseName().
readInverseNameAsync()
template<typename CompletionToken > auto opcua::services::readInverseNameAsync (Client & connection, const NodeId & id, CompletionToken && token)
Read the AttributeId::InverseName attribute of a node.
Parameters
connection Instance of type Client (or Server)
id Node to read
token The completion token that will be used to produce a completion handler, which will be called when the operation completes. Potential completion tokens include useFuture, useDeferred, useDetached, or a function (object) with the correct completion signature. The function signature of the completion handler must be:
void(Result<LocalizedText>&)
Returns
void if token is a callback function (object)
std::future<Result<LocalizedText>> if token is of type UseFutureToken
auto(auto&& token) callable for deferred execution if token is of type UseDeferredToken
void if token is of type UseDetachedToken
Definition at line 442 of file attribute_highlevel.hpp.
readIsAbstract()
template<typename T > Result< bool > opcua::services::readIsAbstract (T & connection, const NodeId & id) noexcept
Read the AttributeId::IsAbstract attribute of a node.
Parameters
connection Instance of type Client (or Server)
id Node to read
Definition at line 329 of file attribute_highlevel.hpp.
Referenced by opcua::Node< Connection >::readIsAbstract().
readIsAbstractAsync()
template<typename CompletionToken > auto opcua::services::readIsAbstractAsync (Client & connection, const NodeId & id, CompletionToken && token)
Read the AttributeId::IsAbstract attribute of a node.
Parameters
connection Instance of type Client (or Server)
id Node to read
token The completion token that will be used to produce a completion handler, which will be called when the operation completes. Potential completion tokens include useFuture, useDeferred, useDetached, or a function (object) with the correct completion signature. The function signature of the completion handler must be:
void(Result<bool>)
Returns
void if token is a callback function (object)
std::future<Result<bool>> if token is of type UseFutureToken
auto(auto&& token) callable for deferred execution if token is of type UseDeferredToken
void if token is of type UseDetachedToken
Definition at line 340 of file attribute_highlevel.hpp.
readMinimumSamplingInterval()
template<typename T > Result< double > opcua::services::readMinimumSamplingInterval (T & connection, const NodeId & id) noexcept
Read the AttributeId::MinimumSamplingInterval attribute of a node.
Parameters
connection Instance of type Client (or Server)
id Node to read
Definition at line 917 of file attribute_highlevel.hpp.
Referenced by opcua::Node< Connection >::readMinimumSamplingInterval().
readMinimumSamplingIntervalAsync()
template<typename CompletionToken > auto opcua::services::readMinimumSamplingIntervalAsync (Client & connection, const NodeId & id, CompletionToken && token)
Read the AttributeId::MinimumSamplingInterval attribute of a node.
Parameters
connection Instance of type Client (or Server)
id Node to read
token The completion token that will be used to produce a completion handler, which will be called when the operation completes. Potential completion tokens include useFuture, useDeferred, useDetached, or a function (object) with the correct completion signature. The function signature of the completion handler must be:
void(Result<double>)
Returns
void if token is a callback function (object)
std::future<Result<double>> if token is of type UseFutureToken
auto(auto&& token) callable for deferred execution if token is of type UseDeferredToken
void if token is of type UseDetachedToken
Definition at line 928 of file attribute_highlevel.hpp.
readNodeClass()
template<typename T > Result< NodeClass > opcua::services::readNodeClass (T & connection, const NodeId & id) noexcept
Read the AttributeId::NodeClass attribute of a node.
Parameters
connection Instance of type Client (or Server)
id Node to read
Definition at line 42 of file attribute_highlevel.hpp.
Referenced by opcua::Node< Connection >::readNodeClass().
readNodeClassAsync()
template<typename CompletionToken > auto opcua::services::readNodeClassAsync (Client & connection, const NodeId & id, CompletionToken && token)
Read the AttributeId::NodeClass attribute of a node.
Parameters
connection Instance of type Client (or Server)
id Node to read
token The completion token that will be used to produce a completion handler, which will be called when the operation completes. Potential completion tokens include useFuture, useDeferred, useDetached, or a function (object) with the correct completion signature. The function signature of the completion handler must be:
void(Result<NodeClass>)
Returns
void if token is a callback function (object)
std::future<Result<NodeClass>> if token is of type UseFutureToken
auto(auto&& token) callable for deferred execution if token is of type UseDeferredToken
void if token is of type UseDetachedToken
Definition at line 53 of file attribute_highlevel.hpp.
readNodeId()
template<typename T > Result< NodeId > opcua::services::readNodeId (T & connection, const NodeId & id) noexcept
Read the AttributeId::NodeId attribute of a node.
Parameters
connection Instance of type Client (or Server)
id Node to read
Definition at line 18 of file attribute_highlevel.hpp.
readNodeIdAsync()
template<typename CompletionToken > auto opcua::services::readNodeIdAsync (Client & connection, const NodeId & id, CompletionToken && token)
Read the AttributeId::NodeId attribute of a node.
Parameters
connection Instance of type Client (or Server)
id Node to read
token The completion token that will be used to produce a completion handler, which will be called when the operation completes. Potential completion tokens include useFuture, useDeferred, useDetached, or a function (object) with the correct completion signature. The function signature of the completion handler must be:
void(Result<NodeId>&)
Returns
void if token is a callback function (object)
std::future<Result<NodeId>> if token is of type UseFutureToken
auto(auto&& token) callable for deferred execution if token is of type UseDeferredToken
void if token is of type UseDetachedToken
Definition at line 29 of file attribute_highlevel.hpp.
readSymmetric()
template<typename T > Result< bool > opcua::services::readSymmetric (T & connection, const NodeId & id) noexcept
Read the AttributeId::Symmetric attribute of a node.
Parameters
connection Instance of type Client (or Server)
id Node to read
Definition at line 380 of file attribute_highlevel.hpp.
Referenced by opcua::Node< Connection >::readSymmetric().
readSymmetricAsync()
template<typename CompletionToken > auto opcua::services::readSymmetricAsync (Client & connection, const NodeId & id, CompletionToken && token)
Read the AttributeId::Symmetric attribute of a node.
Parameters
connection Instance of type Client (or Server)
id Node to read
token The completion token that will be used to produce a completion handler, which will be called when the operation completes. Potential completion tokens include useFuture, useDeferred, useDetached, or a function (object) with the correct completion signature. The function signature of the completion handler must be:
void(Result<bool>)
Returns
void if token is a callback function (object)
std::future<Result<bool>> if token is of type UseFutureToken
auto(auto&& token) callable for deferred execution if token is of type UseDeferredToken
void if token is of type UseDetachedToken
Definition at line 391 of file attribute_highlevel.hpp.
readUserAccessLevel()
template<typename T > Result< Bitmask< AccessLevel > > opcua::services::readUserAccessLevel (T & connection, const NodeId & id) noexcept
Read the AttributeId::UserAccessLevel attribute of a node.
Parameters
connection Instance of type Client (or Server)
id Node to read
Definition at line 859 of file attribute_highlevel.hpp.
Referenced by opcua::Node< Connection >::readUserAccessLevel().
readUserAccessLevelAsync()
template<typename CompletionToken > auto opcua::services::readUserAccessLevelAsync (Client & connection, const NodeId & id, CompletionToken && token)
Read the AttributeId::UserAccessLevel attribute of a node.
Parameters
connection Instance of type Client (or Server)
id Node to read
token The completion token that will be used to produce a completion handler, which will be called when the operation completes. Potential completion tokens include useFuture, useDeferred, useDetached, or a function (object) with the correct completion signature. The function signature of the completion handler must be:
void(Result<Bitmask<AccessLevel>>)
Returns
void if token is a callback function (object)
std::future<Result<Bitmask<AccessLevel>>> if token is of type UseFutureToken
auto(auto&& token) callable for deferred execution if token is of type UseDeferredToken
void if token is of type UseDetachedToken
Definition at line 870 of file attribute_highlevel.hpp.
readUserExecutable()
template<typename T > Result< bool > opcua::services::readUserExecutable (T & connection, const NodeId & id) noexcept
Read the AttributeId::UserExecutable attribute of a node.
Parameters
connection Instance of type Client (or Server)
id Node to read
Definition at line 1076 of file attribute_highlevel.hpp.
Referenced by opcua::Node< Connection >::readUserExecutable().
readUserExecutableAsync()
template<typename CompletionToken > auto opcua::services::readUserExecutableAsync (Client & connection, const NodeId & id, CompletionToken && token)
Read the AttributeId::UserExecutable attribute of a node.
Parameters
connection Instance of type Client (or Server)
id Node to read
token The completion token that will be used to produce a completion handler, which will be called when the operation completes. Potential completion tokens include useFuture, useDeferred, useDetached, or a function (object) with the correct completion signature. The function signature of the completion handler must be:
void(Result<bool>)
Returns
void if token is a callback function (object)
std::future<Result<bool>> if token is of type UseFutureToken
auto(auto&& token) callable for deferred execution if token is of type UseDeferredToken
void if token is of type UseDetachedToken
Definition at line 1087 of file attribute_highlevel.hpp.
readUserWriteMask()
template<typename T > Result< Bitmask< WriteMask > > opcua::services::readUserWriteMask (T & connection, const NodeId & id) noexcept
Read the AttributeId::UserWriteMask attribute of a node.
Parameters
connection Instance of type Client (or Server)
id Node to read
Definition at line 276 of file attribute_highlevel.hpp.
Referenced by opcua::Node< Connection >::readUserWriteMask().
readUserWriteMaskAsync()
template<typename CompletionToken > auto opcua::services::readUserWriteMaskAsync (Client & connection, const NodeId & id, CompletionToken && token)
Read the AttributeId::UserWriteMask attribute of a node.
Parameters
connection Instance of type Client (or Server)
id Node to read
token The completion token that will be used to produce a completion handler, which will be called when the operation completes. Potential completion tokens include useFuture, useDeferred, useDetached, or a function (object) with the correct completion signature. The function signature of the completion handler must be:
void(Result<Bitmask<WriteMask>>)
Returns
void if token is a callback function (object)
std::future<Result<Bitmask<WriteMask>>> if token is of type UseFutureToken
auto(auto&& token) callable for deferred execution if token is of type UseDeferredToken
void if token is of type UseDetachedToken
Definition at line 287 of file attribute_highlevel.hpp.
readValue()
template<typename T > Result< Variant > opcua::services::readValue (T & connection, const NodeId & id) noexcept
Read the AttributeId::Value attribute of a node.
Parameters
connection Instance of type Client (or Server)
id Node to read
Definition at line 595 of file attribute_highlevel.hpp.
Referenced by opcua::Node< Connection >::readValue().
readValueAsync()
template<typename CompletionToken > auto opcua::services::readValueAsync (Client & connection, const NodeId & id, CompletionToken && token)
Read the AttributeId::Value attribute of a node.
Parameters
connection Instance of type Client (or Server)
id Node to read
token The completion token that will be used to produce a completion handler, which will be called when the operation completes. Potential completion tokens include useFuture, useDeferred, useDetached, or a function (object) with the correct completion signature. The function signature of the completion handler must be:
void(Result<Variant>&)
Returns
void if token is a callback function (object)
std::future<Result<Variant>> if token is of type UseFutureToken
auto(auto&& token) callable for deferred execution if token is of type UseDeferredToken
void if token is of type UseDetachedToken
Examples
client_async.cpp.
Definition at line 606 of file attribute_highlevel.hpp.
readValueRank()
template<typename T > Result< ValueRank > opcua::services::readValueRank (T & connection, const NodeId & id) noexcept
Read the AttributeId::ValueRank attribute of a node.
Parameters
connection Instance of type Client (or Server)
id Node to read
Definition at line 697 of file attribute_highlevel.hpp.
Referenced by opcua::Node< Connection >::readValueRank().
readValueRankAsync()
template<typename CompletionToken > auto opcua::services::readValueRankAsync (Client & connection, const NodeId & id, CompletionToken && token)
Read the AttributeId::ValueRank attribute of a node.
Parameters
connection Instance of type Client (or Server)
id Node to read
token The completion token that will be used to produce a completion handler, which will be called when the operation completes. Potential completion tokens include useFuture, useDeferred, useDetached, or a function (object) with the correct completion signature. The function signature of the completion handler must be:
void(Result<ValueRank>)
Returns
void if token is a callback function (object)
std::future<Result<ValueRank>> if token is of type UseFutureToken
auto(auto&& token) callable for deferred execution if token is of type UseDeferredToken
void if token is of type UseDetachedToken
Definition at line 708 of file attribute_highlevel.hpp.
readWriteMask()
template<typename T > Result< Bitmask< WriteMask > > opcua::services::readWriteMask (T & connection, const NodeId & id) noexcept
Read the AttributeId::WriteMask attribute of a node.
Parameters
connection Instance of type Client (or Server)
id Node to read
Definition at line 225 of file attribute_highlevel.hpp.
Referenced by opcua::Node< Connection >::readWriteMask().
readWriteMaskAsync()
template<typename CompletionToken > auto opcua::services::readWriteMaskAsync (Client & connection, const NodeId & id, CompletionToken && token)
Read the AttributeId::WriteMask attribute of a node.
Parameters
connection Instance of type Client (or Server)
id Node to read
token The completion token that will be used to produce a completion handler, which will be called when the operation completes. Potential completion tokens include useFuture, useDeferred, useDetached, or a function (object) with the correct completion signature. The function signature of the completion handler must be:
void(Result<Bitmask<WriteMask>>)
Returns
void if token is a callback function (object)
std::future<Result<Bitmask<WriteMask>>> if token is of type UseFutureToken
auto(auto&& token) callable for deferred execution if token is of type UseDeferredToken
void if token is of type UseDetachedToken
Definition at line 236 of file attribute_highlevel.hpp.