open62541pp: Write service
Write service
Services » Attribute service set
Detailed Description
This service is used to write attributes of nodes.
The following node attributes cannot be changed once a node has been created:
AttributeId::NodeClass
AttributeId::NodeId
AttributeId::Symmetric
AttributeId::ContainsNoLoops
The following attributes cannot be written from the server, as they are specific to the different users and set by the access control callback:
AttributeId::UserWriteMask
AttributeId::UserAccessLevel
AttributeId::UserExecutable
See also
https://reference.opcfoundation.org/Core/Part4/v105/docs/5.11.4
Functions
WriteResponse opcua::services::write (Client &connection, const WriteRequest &request) noexcept
WriteResponse opcua::services::write (Client &connection, Span< const WriteValue > nodesToWrite) noexcept
template<typename CompletionToken >
auto opcua::services::writeAsync (Client &connection, const WriteRequest &request, CompletionToken &&token)
template<typename CompletionToken >
auto opcua::services::writeAsync (Client &connection, Span< const WriteValue > nodesToWrite, CompletionToken &&token)
template<typename T >
StatusCode opcua::services::writeAttribute (T &connection, const NodeId &id, AttributeId attributeId, const DataValue &value) noexcept
template<typename CompletionToken >
auto opcua::services::writeAttributeAsync (Client &connection, const NodeId &id, AttributeId attributeId, const DataValue &value, CompletionToken &&token)
template<typename T >
StatusCode opcua::services::writeDataValue (T &connection, const NodeId &id, const DataValue &value) noexcept
template<typename CompletionToken >
auto opcua::services::writeDataValueAsync (Client &connection, const NodeId &id, const DataValue &value, CompletionToken &&token)
template<typename T >
StatusCode opcua::services::writeBrowseName (T &connection, const NodeId &id, const QualifiedName &browseName) noexcept
template<typename CompletionToken >
auto opcua::services::writeBrowseNameAsync (Client &connection, const NodeId &id, const QualifiedName &browseName, CompletionToken &&token)
template<typename T >
StatusCode opcua::services::writeDisplayName (T &connection, const NodeId &id, const LocalizedText &displayName) noexcept
template<typename CompletionToken >
auto opcua::services::writeDisplayNameAsync (Client &connection, const NodeId &id, const LocalizedText &displayName, CompletionToken &&token)
template<typename T >
StatusCode opcua::services::writeDescription (T &connection, const NodeId &id, const LocalizedText &description) noexcept
template<typename CompletionToken >
auto opcua::services::writeDescriptionAsync (Client &connection, const NodeId &id, const LocalizedText &description, CompletionToken &&token)
template<typename T >
StatusCode opcua::services::writeWriteMask (T &connection, const NodeId &id, Bitmask< WriteMask > writeMask) noexcept
template<typename CompletionToken >
auto opcua::services::writeWriteMaskAsync (Client &connection, const NodeId &id, Bitmask< WriteMask > writeMask, CompletionToken &&token)
template<typename T >
StatusCode opcua::services::writeUserWriteMask (T &connection, const NodeId &id, Bitmask< WriteMask > userWriteMask) noexcept
template<typename CompletionToken >
auto opcua::services::writeUserWriteMaskAsync (Client &connection, const NodeId &id, Bitmask< WriteMask > userWriteMask, CompletionToken &&token)
template<typename T >
StatusCode opcua::services::writeIsAbstract (T &connection, const NodeId &id, bool isAbstract) noexcept
template<typename CompletionToken >
auto opcua::services::writeIsAbstractAsync (Client &connection, const NodeId &id, bool isAbstract, CompletionToken &&token)
template<typename T >
StatusCode opcua::services::writeSymmetric (T &connection, const NodeId &id, bool symmetric) noexcept
template<typename CompletionToken >
auto opcua::services::writeSymmetricAsync (Client &connection, const NodeId &id, bool symmetric, CompletionToken &&token)
template<typename T >
StatusCode opcua::services::writeInverseName (T &connection, const NodeId &id, const LocalizedText &inverseName) noexcept
template<typename CompletionToken >
auto opcua::services::writeInverseNameAsync (Client &connection, const NodeId &id, const LocalizedText &inverseName, CompletionToken &&token)
template<typename T >
StatusCode opcua::services::writeContainsNoLoops (T &connection, const NodeId &id, const bool &containsNoLoops) noexcept
template<typename CompletionToken >
auto opcua::services::writeContainsNoLoopsAsync (Client &connection, const NodeId &id, const bool &containsNoLoops, CompletionToken &&token)
template<typename T >
StatusCode opcua::services::writeEventNotifier (T &connection, const NodeId &id, Bitmask< EventNotifier > eventNotifier) noexcept
template<typename CompletionToken >
auto opcua::services::writeEventNotifierAsync (Client &connection, const NodeId &id, Bitmask< EventNotifier > eventNotifier, CompletionToken &&token)
template<typename T >
StatusCode opcua::services::writeValue (T &connection, const NodeId &id, const Variant &value) noexcept
template<typename CompletionToken >
auto opcua::services::writeValueAsync (Client &connection, const NodeId &id, const Variant &value, CompletionToken &&token)
template<typename T >
StatusCode opcua::services::writeDataType (T &connection, const NodeId &id, const NodeId &dataType) noexcept
template<typename CompletionToken >
auto opcua::services::writeDataTypeAsync (Client &connection, const NodeId &id, const NodeId &dataType, CompletionToken &&token)
template<typename T >
StatusCode opcua::services::writeValueRank (T &connection, const NodeId &id, ValueRank valueRank) noexcept
template<typename CompletionToken >
auto opcua::services::writeValueRankAsync (Client &connection, const NodeId &id, ValueRank valueRank, CompletionToken &&token)
template<typename T >
StatusCode opcua::services::writeArrayDimensions (T &connection, const NodeId &id, Span< const uint32_t > arrayDimensions) noexcept
template<typename CompletionToken >
auto opcua::services::writeArrayDimensionsAsync (Client &connection, const NodeId &id, Span< const uint32_t > arrayDimensions, CompletionToken &&token)
template<typename T >
StatusCode opcua::services::writeAccessLevel (T &connection, const NodeId &id, Bitmask< AccessLevel > accessLevel) noexcept
template<typename CompletionToken >
auto opcua::services::writeAccessLevelAsync (Client &connection, const NodeId &id, Bitmask< AccessLevel > accessLevel, CompletionToken &&token)
template<typename T >
StatusCode opcua::services::writeUserAccessLevel (T &connection, const NodeId &id, Bitmask< AccessLevel > userAccessLevel) noexcept
template<typename CompletionToken >
auto opcua::services::writeUserAccessLevelAsync (Client &connection, const NodeId &id, Bitmask< AccessLevel > userAccessLevel, CompletionToken &&token)
template<typename T >
StatusCode opcua::services::writeMinimumSamplingInterval (T &connection, const NodeId &id, double minimumSamplingInterval) noexcept
template<typename CompletionToken >
auto opcua::services::writeMinimumSamplingIntervalAsync (Client &connection, const NodeId &id, double minimumSamplingInterval, CompletionToken &&token)
template<typename T >
StatusCode opcua::services::writeHistorizing (T &connection, const NodeId &id, bool historizing) noexcept
template<typename CompletionToken >
auto opcua::services::writeHistorizingAsync (Client &connection, const NodeId &id, bool historizing, CompletionToken &&token)
template<typename T >
StatusCode opcua::services::writeExecutable (T &connection, const NodeId &id, bool executable) noexcept
template<typename CompletionToken >
auto opcua::services::writeExecutableAsync (Client &connection, const NodeId &id, bool executable, CompletionToken &&token)
template<typename T >
StatusCode opcua::services::writeUserExecutable (T &connection, const NodeId &id, bool userExecutable) noexcept
template<typename CompletionToken >
auto opcua::services::writeUserExecutableAsync (Client &connection, const NodeId &id, bool userExecutable, CompletionToken &&token)
Function Documentation
write() [1/2]
WriteResponse opcua::services::write (Client & connection, const WriteRequest & request) noexcept
Write one or more attributes of one or more nodes (client only).
Parameters
connection Instance of type Client
request Write request
Referenced by opcua::services::write().
write() [2/2]
WriteResponse opcua::services::write (Client & connection, Span< const WriteValue > nodesToWrite) inline noexcept
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 147 of file attribute.hpp.
writeAsync() [1/2]
template<typename CompletionToken > auto opcua::services::writeAsync (Client & connection, const WriteRequest & request, CompletionToken && token)
Write one or more attributes of one or more nodes (client only).
Parameters
connection Instance of type Client
request Write request
token The completion token that will be used to produce a completion handler, which will be called when the operation completes. Potential completion tokens include useFuture, useDeferred, useDetached, or a function (object) with the correct completion signature. The function signature of the completion handler must be:
void(WriteResponse&)
Returns
void if token is a callback function (object)
std::future<WriteResponse> if token is of type UseFutureToken
auto(auto&& token) callable for deferred execution if token is of type UseDeferredToken
void if token is of type UseDetachedToken
Definition at line 158 of file attribute.hpp.
Referenced by opcua::services::writeAsync(), and opcua::services::writeAttributeAsync().
writeAsync() [2/2]
template<typename CompletionToken > auto opcua::services::writeAsync (Client & connection, Span< const WriteValue > nodesToWrite, CompletionToken && token)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 166 of file attribute.hpp.
writeAttribute()
template<typename T > StatusCode opcua::services::writeAttribute (T & connection, const NodeId & id, AttributeId attributeId, const DataValue & value) noexcept
Write node attribute.
Parameters
connection Instance of type Client
id Node to write
attributeId Attribute to write
value Value to write
Referenced by opcua::services::writeDataValue().
writeAttributeAsync()
template<typename CompletionToken > auto opcua::services::writeAttributeAsync (Client & connection, const NodeId & id, AttributeId attributeId, const DataValue & value, CompletionToken && token)
Write node attribute.
Parameters
connection Instance of type Client
id Node to write
attributeId Attribute to write
value Value to write
token The completion token that will be used to produce a completion handler, which will be called when the operation completes. Potential completion tokens include useFuture, useDeferred, useDetached, or a function (object) with the correct completion signature. The function signature of the completion handler must be:
void(StatusCode)
Returns
void if token is a callback function (object)
std::future<StatusCode> if token is of type UseFutureToken
auto(auto&& token) callable for deferred execution if token is of type UseDeferredToken
void if token is of type UseDetachedToken
Definition at line 191 of file attribute.hpp.
Referenced by opcua::services::writeDataValueAsync().
writeDataValue()
template<typename T > StatusCode opcua::services::writeDataValue (T & connection, const NodeId & id, const DataValue & value) noexcept
Write the AttributeId::Value attribute of a node as a DataValue object.
Parameters
connection Instance of type Client (or Server)
id Node to write
value Value to write
Definition at line 297 of file attribute.hpp.
Referenced by opcua::Node< Connection >::writeDataValue().
writeDataValueAsync()
template<typename CompletionToken > auto opcua::services::writeDataValueAsync (Client & connection, const NodeId & id, const DataValue & value, CompletionToken && token)
Write the AttributeId::Value attribute of a node as a DataValue object.
Parameters
connection Instance of type Client (or Server)
id Node to write
value Value to write
token The completion token that will be used to produce a completion handler, which will be called when the operation completes. Potential completion tokens include useFuture, useDeferred, useDetached, or a function (object) with the correct completion signature. The function signature of the completion handler must be:
void(StatusCode)
Returns
void if token is a callback function (object)
std::future<StatusCode> if token is of type UseFutureToken
auto(auto&& token) callable for deferred execution if token is of type UseDeferredToken
void if token is of type UseDetachedToken
Definition at line 308 of file attribute.hpp.
Referenced by opcua::Node< Connection >::writeDataValueAsync().
writeBrowseName()
template<typename T > StatusCode opcua::services::writeBrowseName (T & connection, const NodeId & id, const QualifiedName & browseName) noexcept
Write the AttributeId::BrowseName attribute of a node.
Parameters
connection Instance of type Client (or Server)
id Node to write
browseName Value to write
Definition at line 91 of file attribute_highlevel.hpp.
writeBrowseNameAsync()
template<typename CompletionToken > auto opcua::services::writeBrowseNameAsync (Client & connection, const NodeId & id, const QualifiedName & browseName, CompletionToken && token)
Write the AttributeId::BrowseName attribute of a node.
Parameters
connection Instance of type Client (or Server)
id Node to write
browseName Value to write
token The completion token that will be used to produce a completion handler, which will be called when the operation completes. Potential completion tokens include useFuture, useDeferred, useDetached, or a function (object) with the correct completion signature. The function signature of the completion handler must be:
void(StatusCode)
Returns
void if token is a callback function (object)
std::future<StatusCode> if token is of type UseFutureToken
auto(auto&& token) callable for deferred execution if token is of type UseDeferredToken
void if token is of type UseDetachedToken
Definition at line 104 of file attribute_highlevel.hpp.
writeDisplayName()
template<typename T > StatusCode opcua::services::writeDisplayName (T & connection, const NodeId & id, const LocalizedText & displayName) noexcept
Write the AttributeId::DisplayName attribute of a node.
Parameters
connection Instance of type Client (or Server)
id Node to write
displayName Value to write
Definition at line 144 of file attribute_highlevel.hpp.
Referenced by opcua::Node< Connection >::writeDisplayName().
writeDisplayNameAsync()
template<typename CompletionToken > auto opcua::services::writeDisplayNameAsync (Client & connection, const NodeId & id, const LocalizedText & displayName, CompletionToken && token)
Write the AttributeId::DisplayName attribute of a node.
Parameters
connection Instance of type Client (or Server)
id Node to write
displayName Value to write
token The completion token that will be used to produce a completion handler, which will be called when the operation completes. Potential completion tokens include useFuture, useDeferred, useDetached, or a function (object) with the correct completion signature. The function signature of the completion handler must be:
void(StatusCode)
Returns
void if token is a callback function (object)
std::future<StatusCode> if token is of type UseFutureToken
auto(auto&& token) callable for deferred execution if token is of type UseDeferredToken
void if token is of type UseDetachedToken
Definition at line 157 of file attribute_highlevel.hpp.
Referenced by opcua::Node< Connection >::writeDisplayNameAsync().
writeDescription()
template<typename T > StatusCode opcua::services::writeDescription (T & connection, const NodeId & id, const LocalizedText & description) noexcept
Write the AttributeId::Description attribute of a node.
Parameters
connection Instance of type Client (or Server)
id Node to write
description Value to write
Definition at line 197 of file attribute_highlevel.hpp.
Referenced by opcua::Node< Connection >::writeDescription().
writeDescriptionAsync()
template<typename CompletionToken > auto opcua::services::writeDescriptionAsync (Client & connection, const NodeId & id, const LocalizedText & description, CompletionToken && token)
Write the AttributeId::Description attribute of a node.
Parameters
connection Instance of type Client (or Server)
id Node to write
description Value to write
token The completion token that will be used to produce a completion handler, which will be called when the operation completes. Potential completion tokens include useFuture, useDeferred, useDetached, or a function (object) with the correct completion signature. The function signature of the completion handler must be:
void(StatusCode)
Returns
void if token is a callback function (object)
std::future<StatusCode> if token is of type UseFutureToken
auto(auto&& token) callable for deferred execution if token is of type UseDeferredToken
void if token is of type UseDetachedToken
Definition at line 210 of file attribute_highlevel.hpp.
Referenced by opcua::Node< Connection >::writeDescriptionAsync().
writeWriteMask()
template<typename T > StatusCode opcua::services::writeWriteMask (T & connection, const NodeId & id, Bitmask< WriteMask > writeMask) noexcept
Write the AttributeId::WriteMask attribute of a node.
Parameters
connection Instance of type Client (or Server)
id Node to write
writeMask Value to write
Definition at line 250 of file attribute_highlevel.hpp.
Referenced by opcua::Node< Connection >::writeWriteMask().
writeWriteMaskAsync()
template<typename CompletionToken > auto opcua::services::writeWriteMaskAsync (Client & connection, const NodeId & id, Bitmask< WriteMask > writeMask, CompletionToken && token)
Write the AttributeId::WriteMask attribute of a node.
Parameters
connection Instance of type Client (or Server)
id Node to write
writeMask Value to write
token The completion token that will be used to produce a completion handler, which will be called when the operation completes. Potential completion tokens include useFuture, useDeferred, useDetached, or a function (object) with the correct completion signature. The function signature of the completion handler must be:
void(StatusCode)
Returns
void if token is a callback function (object)
std::future<StatusCode> if token is of type UseFutureToken
auto(auto&& token) callable for deferred execution if token is of type UseDeferredToken
void if token is of type UseDetachedToken
Definition at line 261 of file attribute_highlevel.hpp.
Referenced by opcua::Node< Connection >::writeWriteMaskAsync().
writeUserWriteMask()
template<typename T > StatusCode opcua::services::writeUserWriteMask (T & connection, const NodeId & id, Bitmask< WriteMask > userWriteMask) noexcept
Write the AttributeId::UserWriteMask attribute of a node.
Parameters
connection Instance of type Client (or Server)
id Node to write
userWriteMask Value to write
Definition at line 301 of file attribute_highlevel.hpp.
Referenced by opcua::Node< Connection >::writeUserWriteMask().
writeUserWriteMaskAsync()
template<typename CompletionToken > auto opcua::services::writeUserWriteMaskAsync (Client & connection, const NodeId & id, Bitmask< WriteMask > userWriteMask, CompletionToken && token)
Write the AttributeId::UserWriteMask attribute of a node.
Parameters
connection Instance of type Client (or Server)
id Node to write
userWriteMask Value to write
token The completion token that will be used to produce a completion handler, which will be called when the operation completes. Potential completion tokens include useFuture, useDeferred, useDetached, or a function (object) with the correct completion signature. The function signature of the completion handler must be:
void(StatusCode)
Returns
void if token is a callback function (object)
std::future<StatusCode> if token is of type UseFutureToken
auto(auto&& token) callable for deferred execution if token is of type UseDeferredToken
void if token is of type UseDetachedToken
Definition at line 314 of file attribute_highlevel.hpp.
Referenced by opcua::Node< Connection >::writeUserWriteMaskAsync().
writeIsAbstract()
template<typename T > StatusCode opcua::services::writeIsAbstract (T & connection, const NodeId & id, bool isAbstract) noexcept
Write the AttributeId::IsAbstract attribute of a node.
Parameters
connection Instance of type Client (or Server)
id Node to write
isAbstract Value to write
Definition at line 354 of file attribute_highlevel.hpp.
Referenced by opcua::Node< Connection >::writeIsAbstract().
writeIsAbstractAsync()
template<typename CompletionToken > auto opcua::services::writeIsAbstractAsync (Client & connection, const NodeId & id, bool isAbstract, CompletionToken && token)
Write the AttributeId::IsAbstract attribute of a node.
Parameters
connection Instance of type Client (or Server)
id Node to write
isAbstract Value to write
token The completion token that will be used to produce a completion handler, which will be called when the operation completes. Potential completion tokens include useFuture, useDeferred, useDetached, or a function (object) with the correct completion signature. The function signature of the completion handler must be:
void(StatusCode)
Returns
void if token is a callback function (object)
std::future<StatusCode> if token is of type UseFutureToken
auto(auto&& token) callable for deferred execution if token is of type UseDeferredToken
void if token is of type UseDetachedToken
Definition at line 365 of file attribute_highlevel.hpp.
Referenced by opcua::Node< Connection >::writeIsAbstractAsync().
writeSymmetric()
template<typename T > StatusCode opcua::services::writeSymmetric (T & connection, const NodeId & id, bool symmetric) noexcept
Write the AttributeId::Symmetric attribute of a node.
Parameters
connection Instance of type Client (or Server)
id Node to write
symmetric Value to write
Definition at line 405 of file attribute_highlevel.hpp.
Referenced by opcua::Node< Connection >::writeSymmetric().
writeSymmetricAsync()
template<typename CompletionToken > auto opcua::services::writeSymmetricAsync (Client & connection, const NodeId & id, bool symmetric, CompletionToken && token)
Write the AttributeId::Symmetric attribute of a node.
Parameters
connection Instance of type Client (or Server)
id Node to write
symmetric Value to write
token The completion token that will be used to produce a completion handler, which will be called when the operation completes. Potential completion tokens include useFuture, useDeferred, useDetached, or a function (object) with the correct completion signature. The function signature of the completion handler must be:
void(StatusCode)
Returns
void if token is a callback function (object)
std::future<StatusCode> if token is of type UseFutureToken
auto(auto&& token) callable for deferred execution if token is of type UseDeferredToken
void if token is of type UseDetachedToken
Definition at line 416 of file attribute_highlevel.hpp.
Referenced by opcua::Node< Connection >::writeSymmetricAsync().
writeInverseName()
template<typename T > StatusCode opcua::services::writeInverseName (T & connection, const NodeId & id, const LocalizedText & inverseName) noexcept
Write the AttributeId::InverseName attribute of a node.
Parameters
connection Instance of type Client (or Server)
id Node to write
inverseName Value to write
Definition at line 456 of file attribute_highlevel.hpp.
Referenced by opcua::Node< Connection >::writeInverseName().
writeInverseNameAsync()
template<typename CompletionToken > auto opcua::services::writeInverseNameAsync (Client & connection, const NodeId & id, const LocalizedText & inverseName, CompletionToken && token)
Write the AttributeId::InverseName attribute of a node.
Parameters
connection Instance of type Client (or Server)
id Node to write
inverseName Value to write
token The completion token that will be used to produce a completion handler, which will be called when the operation completes. Potential completion tokens include useFuture, useDeferred, useDetached, or a function (object) with the correct completion signature. The function signature of the completion handler must be:
void(StatusCode)
Returns
void if token is a callback function (object)
std::future<StatusCode> if token is of type UseFutureToken
auto(auto&& token) callable for deferred execution if token is of type UseDeferredToken
void if token is of type UseDetachedToken
Definition at line 469 of file attribute_highlevel.hpp.
Referenced by opcua::Node< Connection >::writeInverseNameAsync().
writeContainsNoLoops()
template<typename T > StatusCode opcua::services::writeContainsNoLoops (T & connection, const NodeId & id, const bool & containsNoLoops) noexcept
Write the AttributeId::ContainsNoLoops attribute of a node.
Parameters
connection Instance of type Client (or Server)
id Node to write
containsNoLoops Value to write
Definition at line 509 of file attribute_highlevel.hpp.
Referenced by opcua::Node< Connection >::writeContainsNoLoops().
writeContainsNoLoopsAsync()
template<typename CompletionToken > auto opcua::services::writeContainsNoLoopsAsync (Client & connection, const NodeId & id, const bool & containsNoLoops, CompletionToken && token)
Write the AttributeId::ContainsNoLoops attribute of a node.
Parameters
connection Instance of type Client (or Server)
id Node to write
containsNoLoops Value to write
token The completion token that will be used to produce a completion handler, which will be called when the operation completes. Potential completion tokens include useFuture, useDeferred, useDetached, or a function (object) with the correct completion signature. The function signature of the completion handler must be:
void(StatusCode)
Returns
void if token is a callback function (object)
std::future<StatusCode> if token is of type UseFutureToken
auto(auto&& token) callable for deferred execution if token is of type UseDeferredToken
void if token is of type UseDetachedToken
Definition at line 524 of file attribute_highlevel.hpp.
Referenced by opcua::Node< Connection >::writeContainsNoLoopsAsync().
writeEventNotifier()
template<typename T > StatusCode opcua::services::writeEventNotifier (T & connection, const NodeId & id, Bitmask< EventNotifier > eventNotifier) noexcept
Write the AttributeId::EventNotifier attribute of a node.
Parameters
connection Instance of type Client (or Server)
id Node to write
eventNotifier Value to write
Definition at line 564 of file attribute_highlevel.hpp.
Referenced by opcua::Node< Connection >::writeEventNotifier().
writeEventNotifierAsync()
template<typename CompletionToken > auto opcua::services::writeEventNotifierAsync (Client & connection, const NodeId & id, Bitmask< EventNotifier > eventNotifier, CompletionToken && token)
Write the AttributeId::EventNotifier attribute of a node.
Parameters
connection Instance of type Client (or Server)
id Node to write
eventNotifier Value to write
token The completion token that will be used to produce a completion handler, which will be called when the operation completes. Potential completion tokens include useFuture, useDeferred, useDetached, or a function (object) with the correct completion signature. The function signature of the completion handler must be:
void(StatusCode)
Returns
void if token is a callback function (object)
std::future<StatusCode> if token is of type UseFutureToken
auto(auto&& token) callable for deferred execution if token is of type UseDeferredToken
void if token is of type UseDetachedToken
Definition at line 577 of file attribute_highlevel.hpp.
Referenced by opcua::Node< Connection >::writeEventNotifierAsync().
writeValue()
template<typename T > StatusCode opcua::services::writeValue (T & connection, const NodeId & id, const Variant & value) noexcept
Write the AttributeId::Value attribute of a node.
Parameters
connection Instance of type Client (or Server)
id Node to write
value Value to write
Definition at line 620 of file attribute_highlevel.hpp.
Referenced by opcua::Node< Connection >::writeValue().
writeValueAsync()
template<typename CompletionToken > auto opcua::services::writeValueAsync (Client & connection, const NodeId & id, const Variant & value, CompletionToken && token)
Write the AttributeId::Value attribute of a node.
Parameters
connection Instance of type Client (or Server)
id Node to write
value Value to write
token The completion token that will be used to produce a completion handler, which will be called when the operation completes. Potential completion tokens include useFuture, useDeferred, useDetached, or a function (object) with the correct completion signature. The function signature of the completion handler must be:
void(StatusCode)
Returns
void if token is a callback function (object)
std::future<StatusCode> if token is of type UseFutureToken
auto(auto&& token) callable for deferred execution if token is of type UseDeferredToken
void if token is of type UseDetachedToken
Definition at line 631 of file attribute_highlevel.hpp.
Referenced by opcua::Node< Connection >::writeValueAsync().
writeDataType()
template<typename T > StatusCode opcua::services::writeDataType (T & connection, const NodeId & id, const NodeId & dataType) noexcept
Write the AttributeId::DataType attribute of a node.
Parameters
connection Instance of type Client (or Server)
id Node to write
dataType Value to write
Definition at line 671 of file attribute_highlevel.hpp.
Referenced by opcua::Node< Connection >::writeDataType().
writeDataTypeAsync()
template<typename CompletionToken > auto opcua::services::writeDataTypeAsync (Client & connection, const NodeId & id, const NodeId & dataType, CompletionToken && token)
Write the AttributeId::DataType attribute of a node.
Parameters
connection Instance of type Client (or Server)
id Node to write
dataType Value to write
token The completion token that will be used to produce a completion handler, which will be called when the operation completes. Potential completion tokens include useFuture, useDeferred, useDetached, or a function (object) with the correct completion signature. The function signature of the completion handler must be:
void(StatusCode)
Returns
void if token is a callback function (object)
std::future<StatusCode> if token is of type UseFutureToken
auto(auto&& token) callable for deferred execution if token is of type UseDeferredToken
void if token is of type UseDetachedToken
Definition at line 682 of file attribute_highlevel.hpp.
Referenced by opcua::Node< Connection >::writeDataTypeAsync().
writeValueRank()
template<typename T > StatusCode opcua::services::writeValueRank (T & connection, const NodeId & id, ValueRank valueRank) noexcept
Write the AttributeId::ValueRank attribute of a node.
Parameters
connection Instance of type Client (or Server)
id Node to write
valueRank Value to write
Definition at line 722 of file attribute_highlevel.hpp.
Referenced by opcua::Node< Connection >::writeValueRank().
writeValueRankAsync()
template<typename CompletionToken > auto opcua::services::writeValueRankAsync (Client & connection, const NodeId & id, ValueRank valueRank, CompletionToken && token)
Write the AttributeId::ValueRank attribute of a node.
Parameters
connection Instance of type Client (or Server)
id Node to write
valueRank Value to write
token The completion token that will be used to produce a completion handler, which will be called when the operation completes. Potential completion tokens include useFuture, useDeferred, useDetached, or a function (object) with the correct completion signature. The function signature of the completion handler must be:
void(StatusCode)
Returns
void if token is a callback function (object)
std::future<StatusCode> if token is of type UseFutureToken
auto(auto&& token) callable for deferred execution if token is of type UseDeferredToken
void if token is of type UseDetachedToken
Definition at line 733 of file attribute_highlevel.hpp.
Referenced by opcua::Node< Connection >::writeValueRankAsync().
writeArrayDimensions()
template<typename T > StatusCode opcua::services::writeArrayDimensions (T & connection, const NodeId & id, Span< const uint32_t > arrayDimensions) noexcept
Write the AttributeId::ArrayDimensions attribute of a node.
Parameters
connection Instance of type Client (or Server)
id Node to write
arrayDimensions Value to write
Definition at line 773 of file attribute_highlevel.hpp.
Referenced by opcua::Node< Connection >::writeArrayDimensions().
writeArrayDimensionsAsync()
template<typename CompletionToken > auto opcua::services::writeArrayDimensionsAsync (Client & connection, const NodeId & id, Span< const uint32_t > arrayDimensions, CompletionToken && token)
Write the AttributeId::ArrayDimensions attribute of a node.
Parameters
connection Instance of type Client (or Server)
id Node to write
arrayDimensions Value to write
token The completion token that will be used to produce a completion handler, which will be called when the operation completes. Potential completion tokens include useFuture, useDeferred, useDetached, or a function (object) with the correct completion signature. The function signature of the completion handler must be:
void(StatusCode)
Returns
void if token is a callback function (object)
std::future<StatusCode> if token is of type UseFutureToken
auto(auto&& token) callable for deferred execution if token is of type UseDeferredToken
void if token is of type UseDetachedToken
Definition at line 788 of file attribute_highlevel.hpp.
Referenced by opcua::Node< Connection >::writeArrayDimensionsAsync().
writeAccessLevel()
template<typename T > StatusCode opcua::services::writeAccessLevel (T & connection, const NodeId & id, Bitmask< AccessLevel > accessLevel) noexcept
Write the AttributeId::AccessLevel attribute of a node.
Parameters
connection Instance of type Client (or Server)
id Node to write
accessLevel Value to write
Definition at line 831 of file attribute_highlevel.hpp.
Referenced by opcua::Node< Connection >::writeAccessLevel().
writeAccessLevelAsync()
template<typename CompletionToken > auto opcua::services::writeAccessLevelAsync (Client & connection, const NodeId & id, Bitmask< AccessLevel > accessLevel, CompletionToken && token)
Write the AttributeId::AccessLevel attribute of a node.
Parameters
connection Instance of type Client (or Server)
id Node to write
accessLevel Value to write
token The completion token that will be used to produce a completion handler, which will be called when the operation completes. Potential completion tokens include useFuture, useDeferred, useDetached, or a function (object) with the correct completion signature. The function signature of the completion handler must be:
void(StatusCode)
Returns
void if token is a callback function (object)
std::future<StatusCode> if token is of type UseFutureToken
auto(auto&& token) callable for deferred execution if token is of type UseDeferredToken
void if token is of type UseDetachedToken
Definition at line 844 of file attribute_highlevel.hpp.
Referenced by opcua::Node< Connection >::writeAccessLevelAsync().
writeUserAccessLevel()
template<typename T > StatusCode opcua::services::writeUserAccessLevel (T & connection, const NodeId & id, Bitmask< AccessLevel > userAccessLevel) noexcept
Write the AttributeId::UserAccessLevel attribute of a node.
Parameters
connection Instance of type Client (or Server)
id Node to write
userAccessLevel Value to write
Definition at line 884 of file attribute_highlevel.hpp.
Referenced by opcua::Node< Connection >::writeUserAccessLevel().
writeUserAccessLevelAsync()
template<typename CompletionToken > auto opcua::services::writeUserAccessLevelAsync (Client & connection, const NodeId & id, Bitmask< AccessLevel > userAccessLevel, CompletionToken && token)
Write the AttributeId::UserAccessLevel attribute of a node.
Parameters
connection Instance of type Client (or Server)
id Node to write
userAccessLevel Value to write
token The completion token that will be used to produce a completion handler, which will be called when the operation completes. Potential completion tokens include useFuture, useDeferred, useDetached, or a function (object) with the correct completion signature. The function signature of the completion handler must be:
void(StatusCode)
Returns
void if token is a callback function (object)
std::future<StatusCode> if token is of type UseFutureToken
auto(auto&& token) callable for deferred execution if token is of type UseDeferredToken
void if token is of type UseDetachedToken
Definition at line 899 of file attribute_highlevel.hpp.
Referenced by opcua::Node< Connection >::writeUserAccessLevelAsync().
writeMinimumSamplingInterval()
template<typename T > StatusCode opcua::services::writeMinimumSamplingInterval (T & connection, const NodeId & id, double minimumSamplingInterval) noexcept
Write the AttributeId::MinimumSamplingInterval attribute of a node.
Parameters
connection Instance of type Client (or Server)
id Node to write
minimumSamplingInterval Value to write
Definition at line 944 of file attribute_highlevel.hpp.
Referenced by opcua::Node< Connection >::writeMinimumSamplingInterval().
writeMinimumSamplingIntervalAsync()
template<typename CompletionToken > auto opcua::services::writeMinimumSamplingIntervalAsync (Client & connection, const NodeId & id, double minimumSamplingInterval, CompletionToken && token)
Write the AttributeId::MinimumSamplingInterval attribute of a node.
Parameters
connection Instance of type Client (or Server)
id Node to write
minimumSamplingInterval Value to write
token The completion token that will be used to produce a completion handler, which will be called when the operation completes. Potential completion tokens include useFuture, useDeferred, useDetached, or a function (object) with the correct completion signature. The function signature of the completion handler must be:
void(StatusCode)
Returns
void if token is a callback function (object)
std::future<StatusCode> if token is of type UseFutureToken
auto(auto&& token) callable for deferred execution if token is of type UseDeferredToken
void if token is of type UseDetachedToken
Definition at line 959 of file attribute_highlevel.hpp.
Referenced by opcua::Node< Connection >::writeMinimumSamplingIntervalAsync().
writeHistorizing()
template<typename T > StatusCode opcua::services::writeHistorizing (T & connection, const NodeId & id, bool historizing) noexcept
Write the AttributeId::Historizing attribute of a node.
Parameters
connection Instance of type Client (or Server)
id Node to write
historizing Value to write
Definition at line 999 of file attribute_highlevel.hpp.
Referenced by opcua::Node< Connection >::writeHistorizing().
writeHistorizingAsync()
template<typename CompletionToken > auto opcua::services::writeHistorizingAsync (Client & connection, const NodeId & id, bool historizing, CompletionToken && token)
Write the AttributeId::Historizing attribute of a node.
Parameters
connection Instance of type Client (or Server)
id Node to write
historizing Value to write
token The completion token that will be used to produce a completion handler, which will be called when the operation completes. Potential completion tokens include useFuture, useDeferred, useDetached, or a function (object) with the correct completion signature. The function signature of the completion handler must be:
void(StatusCode)
Returns
void if token is a callback function (object)
std::future<StatusCode> if token is of type UseFutureToken
auto(auto&& token) callable for deferred execution if token is of type UseDeferredToken
void if token is of type UseDetachedToken
Definition at line 1010 of file attribute_highlevel.hpp.
Referenced by opcua::Node< Connection >::writeHistorizingAsync().
writeExecutable()
template<typename T > StatusCode opcua::services::writeExecutable (T & connection, const NodeId & id, bool executable) noexcept
Write the AttributeId::Executable attribute of a node.
Parameters
connection Instance of type Client (or Server)
id Node to write
executable Value to write
Definition at line 1050 of file attribute_highlevel.hpp.
Referenced by opcua::Node< Connection >::writeExecutable().
writeExecutableAsync()
template<typename CompletionToken > auto opcua::services::writeExecutableAsync (Client & connection, const NodeId & id, bool executable, CompletionToken && token)
Write the AttributeId::Executable attribute of a node.
Parameters
connection Instance of type Client (or Server)
id Node to write
executable Value to write
token The completion token that will be used to produce a completion handler, which will be called when the operation completes. Potential completion tokens include useFuture, useDeferred, useDetached, or a function (object) with the correct completion signature. The function signature of the completion handler must be:
void(StatusCode)
Returns
void if token is a callback function (object)
std::future<StatusCode> if token is of type UseFutureToken
auto(auto&& token) callable for deferred execution if token is of type UseDeferredToken
void if token is of type UseDetachedToken
Definition at line 1061 of file attribute_highlevel.hpp.
Referenced by opcua::Node< Connection >::writeExecutableAsync().
writeUserExecutable()
template<typename T > StatusCode opcua::services::writeUserExecutable (T & connection, const NodeId & id, bool userExecutable) noexcept
Write the AttributeId::UserExecutable attribute of a node.
Parameters
connection Instance of type Client (or Server)
id Node to write
userExecutable Value to write
Definition at line 1101 of file attribute_highlevel.hpp.
Referenced by opcua::Node< Connection >::writeUserExecutable().
writeUserExecutableAsync()
template<typename CompletionToken > auto opcua::services::writeUserExecutableAsync (Client & connection, const NodeId & id, bool userExecutable, CompletionToken && token)
Write the AttributeId::UserExecutable attribute of a node.
Parameters
connection Instance of type Client (or Server)
id Node to write
userExecutable Value to write
token The completion token that will be used to produce a completion handler, which will be called when the operation completes. Potential completion tokens include useFuture, useDeferred, useDetached, or a function (object) with the correct completion signature. The function signature of the completion handler must be:
void(StatusCode)
Returns
void if token is a callback function (object)
std::future<StatusCode> if token is of type UseFutureToken
auto(auto&& token) callable for deferred execution if token is of type UseDeferredToken
void if token is of type UseDetachedToken
Definition at line 1112 of file attribute_highlevel.hpp.
Referenced by opcua::Node< Connection >::writeUserExecutableAsync().