open62541pp: TranslateBrowsePathsToNodeIds service
TranslateBrowsePathsToNodeIds service
Services » View service set
Detailed Description
Request that the server translates browse paths to node ids.
See also
https://reference.opcfoundation.org/Core/Part4/v105/docs/5.8.4
Functions
TranslateBrowsePathsToNodeIdsResponse opcua::services::translateBrowsePathsToNodeIds (Client &connection, const TranslateBrowsePathsToNodeIdsRequest &request) noexcept
template<typename CompletionToken >
auto opcua::services::translateBrowsePathsToNodeIdsAsync (Client &connection, const TranslateBrowsePathsToNodeIdsRequest &request, CompletionToken &&token)
template<typename T >
BrowsePathResult opcua::services::translateBrowsePathToNodeIds (T &connection, const BrowsePath &browsePath) noexcept
template<typename CompletionToken >
auto opcua::services::translateBrowsePathToNodeIdsAsync (Client &connection, const BrowsePath &browsePath, CompletionToken &&token)
template<typename T >
BrowsePathResult opcua::services::browseSimplifiedBrowsePath (T &connection, const NodeId &origin, Span< const QualifiedName > browsePath)
template<typename CompletionToken >
auto opcua::services::browseSimplifiedBrowsePathAsync (Client &connection, const NodeId &origin, Span< const QualifiedName > browsePath, CompletionToken &&token)
Function Documentation
translateBrowsePathsToNodeIds()
TranslateBrowsePathsToNodeIdsResponse opcua::services::translateBrowsePathsToNodeIds (Client & connection, const TranslateBrowsePathsToNodeIdsRequest & request) noexcept
Translate browse paths to NodeIds (client only).
See also
https://reference.opcfoundation.org/Core/Part4/v105/docs/5.8.4
Parameters
connection Instance of type Client
request Request
translateBrowsePathsToNodeIdsAsync()
template<typename CompletionToken > auto opcua::services::translateBrowsePathsToNodeIdsAsync (Client & connection, const TranslateBrowsePathsToNodeIdsRequest & request, CompletionToken && token)
Translate browse paths to NodeIds (client only).
See also
https://reference.opcfoundation.org/Core/Part4/v105/docs/5.8.4
Parameters
connection Instance of type Client
request Request
token
The @ref async_model "completion token" that will be used to produce a completion handler, which will be called when the operation completes.
Potential completion tokens include @ref useFuture, @ref useDeferred, @ref useDetached, or a function (object) with the correct completion signature.
The function signature of the completion handler must be:
void(TranslateBrowsePathsToNodeIdsResponse&)
Returns
void if token is a callback function (object)
std::future<TranslateBrowsePathsToNodeIdsResponse> if token is of type UseFutureToken
auto(auto&& token) callable for deferred execution if token is of type UseDeferredToken
void if token is of type UseDetachedToken
Definition at line 183 of file view.hpp.
Referenced by opcua::services::translateBrowsePathToNodeIdsAsync().
translateBrowsePathToNodeIds()
template<typename T > BrowsePathResult opcua::services::translateBrowsePathToNodeIds (T & connection, const BrowsePath & browsePath) noexcept
Translate a browse path to NodeIds.
See also
https://reference.opcfoundation.org/Core/Part4/v105/docs/5.8.4
Parameters
connection Instance of type Server or Client
browsePath Browse path (starting node & relative path)
Referenced by opcua::services::browseSimplifiedBrowsePath().
translateBrowsePathToNodeIdsAsync()
template<typename CompletionToken > auto opcua::services::translateBrowsePathToNodeIdsAsync (Client & connection, const BrowsePath & browsePath, CompletionToken && token)
Translate a browse path to NodeIds.
See also
https://reference.opcfoundation.org/Core/Part4/v105/docs/5.8.4
Parameters
connection Instance of type Server or Client
browsePath Browse path (starting node & relative path)
token
The @ref async_model "completion token" that will be used to produce a completion handler, which will be called when the operation completes.
Potential completion tokens include @ref useFuture, @ref useDeferred, @ref useDetached, or a function (object) with the correct completion signature.
The function signature of the completion handler must be:
void(BrowsePathResult&)
Returns
void if token is a callback function (object)
std::future<BrowsePathResult> if token is of type UseFutureToken
auto(auto&& token) callable for deferred execution if token is of type UseDeferredToken
void if token is of type UseDetachedToken
Definition at line 208 of file view.hpp.
Referenced by opcua::services::browseSimplifiedBrowsePathAsync().
browseSimplifiedBrowsePath()
template<typename T > BrowsePathResult opcua::services::browseSimplifiedBrowsePath (T & connection, const NodeId & origin, Span< const QualifiedName > browsePath)
A simplified version of translateBrowsePathToNodeIds.
The relative path is specified using browse names instead of the RelativePath structure. The list of browse names is equivalent to a RelativePath that specifies forward references which are subtypes of the HierarchicalReferences ReferenceTypeId.
Parameters
connection Instance of type Server or Client
origin Starting node of the browse path
browsePath Browse path as a list of browse names
Definition at line 236 of file view.hpp.
Referenced by opcua::Node< Connection >::browseChild().
browseSimplifiedBrowsePathAsync()
template<typename CompletionToken > auto opcua::services::browseSimplifiedBrowsePathAsync (Client & connection, const NodeId & origin, Span< const QualifiedName > browsePath, CompletionToken && token)
A simplified version of translateBrowsePathToNodeIds.
The relative path is specified using browse names instead of the RelativePath structure. The list of browse names is equivalent to a RelativePath that specifies forward references which are subtypes of the HierarchicalReferences ReferenceTypeId.
Parameters
connection Instance of type Server or Client
origin Starting node of the browse path
browsePath Browse path as a list of browse names
token
The @ref async_model "completion token" that will be used to produce a completion handler, which will be called when the operation completes.
Potential completion tokens include @ref useFuture, @ref useDeferred, @ref useDetached, or a function (object) with the correct completion signature.
The function signature of the completion handler must be:
void(BrowsePathResult&)
Returns
void if token is a callback function (object)
std::future<BrowsePathResult> if token is of type UseFutureToken
auto(auto&& token) callable for deferred execution if token is of type UseDeferredToken
void if token is of type UseDetachedToken
Definition at line 248 of file view.hpp.