open62541++: Attribute service set
Attribute service set
Services
Detailed Description
Read and write node attributes.
The following node attributes cannot be changed once a node has been created:
NodeClass
NodeId
Symmetric
ContainsNoLoops
The following attributes cannot be written from the server, as they are specific to the different users and set by the access control callback:
UserWriteMask
UserAccessLevel
UserExecutable
See also
https://www.open62541.org/doc/1.3/server.html
https://reference.opcfoundation.org/Core/Part4/v105/docs/5.10
Functions
ReadResponse opcua::services::read (Client &client, const ReadRequest &request)
ReadResponse opcua::services::read (Client &client, Span< const ReadValueId > nodesToRead, TimestampsToReturn timestamps=TimestampsToReturn::Neither)
template<typename T >
DataValue opcua::services::readAttribute (T &serverOrClient, const NodeId &id, AttributeId attributeId, TimestampsToReturn timestamps=TimestampsToReturn::Neither)
template<typename AttributeType , typename T >
auto opcua::services::readAttributeScalar (T &serverOrClient, const NodeId &id, AttributeId attributeId)
WriteResponse opcua::services::write (Client &client, const WriteRequest &request)
WriteResponse opcua::services::write (Client &client, Span< const WriteValue > nodesToWrite)
template<typename T >
void opcua::services::writeAttribute (T &serverOrClient, const NodeId &id, AttributeId attributeId, const DataValue &value)
template<typename T >
NodeId opcua::services::readNodeId (T &serverOrClient, const NodeId &id)
template<typename T >
NodeClass opcua::services::readNodeClass (T &serverOrClient, const NodeId &id)
template<typename T >
QualifiedName opcua::services::readBrowseName (T &serverOrClient, const NodeId &id)
template<typename T >
LocalizedText opcua::services::readDisplayName (T &serverOrClient, const NodeId &id)
template<typename T >
LocalizedText opcua::services::readDescription (T &serverOrClient, const NodeId &id)
template<typename T >
Bitmask< WriteMask > opcua::services::readWriteMask (T &serverOrClient, const NodeId &id)
template<typename T >
Bitmask< WriteMask > opcua::services::readUserWriteMask (T &serverOrClient, const NodeId &id)
template<typename T >
bool opcua::services::readIsAbstract (T &serverOrClient, const NodeId &id)
template<typename T >
bool opcua::services::readSymmetric (T &serverOrClient, const NodeId &id)
template<typename T >
LocalizedText opcua::services::readInverseName (T &serverOrClient, const NodeId &id)
template<typename T >
bool opcua::services::readContainsNoLoops (T &serverOrClient, const NodeId &id)
template<typename T >
Bitmask< EventNotifier > opcua::services::readEventNotifier (T &serverOrClient, const NodeId &id)
template<typename T >
DataValue opcua::services::readDataValue (T &serverOrClient, const NodeId &id)
template<typename T >
Variant opcua::services::readValue (T &serverOrClient, const NodeId &id)
template<typename T >
NodeId opcua::services::readDataType (T &serverOrClient, const NodeId &id)
template<typename T >
ValueRank opcua::services::readValueRank (T &serverOrClient, const NodeId &id)
template<typename T >
std::vector< uint32_t > opcua::services::readArrayDimensions (T &serverOrClient, const NodeId &id)
template<typename T >
Bitmask< AccessLevel > opcua::services::readAccessLevel (T &serverOrClient, const NodeId &id)
template<typename T >
Bitmask< AccessLevel > opcua::services::readUserAccessLevel (T &serverOrClient, const NodeId &id)
template<typename T >
double opcua::services::readMinimumSamplingInterval (T &serverOrClient, const NodeId &id)
template<typename T >
bool opcua::services::readHistorizing (T &serverOrClient, const NodeId &id)
template<typename T >
bool opcua::services::readExecutable (T &serverOrClient, const NodeId &id)
template<typename T >
bool opcua::services::readUserExecutable (T &serverOrClient, const NodeId &id)
template<typename T >
void opcua::services::writeDisplayName (T &serverOrClient, const NodeId &id, const LocalizedText &name)
template<typename T >
void opcua::services::writeDescription (T &serverOrClient, const NodeId &id, const LocalizedText &desc)
template<typename T >
void opcua::services::writeWriteMask (T &serverOrClient, const NodeId &id, Bitmask< WriteMask > mask)
template<typename T >
void opcua::services::writeUserWriteMask (T &serverOrClient, const NodeId &id, Bitmask< WriteMask > mask)
template<typename T >
void opcua::services::writeIsAbstract (T &serverOrClient, const NodeId &id, bool isAbstract)
template<typename T >
void opcua::services::writeSymmetric (T &serverOrClient, const NodeId &id, bool symmetric)
template<typename T >
void opcua::services::writeInverseName (T &serverOrClient, const NodeId &id, const LocalizedText &name)
template<typename T >
void opcua::services::writeContainsNoLoops (T &serverOrClient, const NodeId &id, bool containsNoLoops)
template<typename T >
void opcua::services::writeEventNotifier (T &serverOrClient, const NodeId &id, Bitmask< EventNotifier > mask)
template<typename T >
void opcua::services::writeDataValue (T &serverOrClient, const NodeId &id, const DataValue &value)
template<typename T >
void opcua::services::writeValue (T &serverOrClient, const NodeId &id, const Variant &value)
template<typename T >
void opcua::services::writeDataType (T &serverOrClient, const NodeId &id, const NodeId &typeId)
template<typename T >
void opcua::services::writeValueRank (T &serverOrClient, const NodeId &id, ValueRank valueRank)
template<typename T >
void opcua::services::writeArrayDimensions (T &serverOrClient, const NodeId &id, Span< const uint32_t > dimensions)
template<typename T >
void opcua::services::writeAccessLevel (T &serverOrClient, const NodeId &id, Bitmask< AccessLevel > mask)
template<typename T >
void opcua::services::writeUserAccessLevel (T &serverOrClient, const NodeId &id, Bitmask< AccessLevel > mask)
template<typename T >
void opcua::services::writeMinimumSamplingInterval (T &serverOrClient, const NodeId &id, double milliseconds)
template<typename T >
void opcua::services::writeHistorizing (T &serverOrClient, const NodeId &id, bool historizing)
template<typename T >
void opcua::services::writeExecutable (T &serverOrClient, const NodeId &id, bool executable)
template<typename T >
void opcua::services::writeUserExecutable (T &serverOrClient, const NodeId &id, bool userExecutable)
Function Documentation
read() [1/2]
ReadResponse opcua::services::read (Client & client, const ReadRequest & request)
Generic function to read one or more attributes of one or more nodes (client only).
read() [2/2]
ReadResponse opcua::services::read (Client & client, Span< const ReadValueId > nodesToRead, TimestampsToReturn timestamps = TimestampsToReturn::Neither)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
readAttribute()
template<typename T > DataValue opcua::services::readAttribute (T & serverOrClient, const NodeId & id, AttributeId attributeId, TimestampsToReturn timestamps = TimestampsToReturn::Neither)
Generic function to read node attributes.
Referenced by opcua::services::readArrayDimensions(), opcua::services::readAttributeScalar(), opcua::services::readDataValue(), opcua::services::readNodeClass(), and opcua::services::readValue().
readAttributeScalar()
template<typename AttributeType , typename T > auto opcua::services::readAttributeScalar (T & serverOrClient, const NodeId & id, AttributeId attributeId) inline
Helper function to read scalar node attributes.
Definition at line 75 of file Attribute.h.
write() [1/2]
WriteResponse opcua::services::write (Client & client, const WriteRequest & request)
Generic function to write one or more attributes of one or more nodes (client only).
write() [2/2]
WriteResponse opcua::services::write (Client & client, Span< const WriteValue > nodesToWrite)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
writeAttribute()
template<typename T > void opcua::services::writeAttribute (T & serverOrClient, const NodeId & id, AttributeId attributeId, const DataValue & value)
Generic function to write node attributes.
Referenced by opcua::services::writeAccessLevel(), opcua::services::writeArrayDimensions(), opcua::services::writeContainsNoLoops(), opcua::services::writeDataType(), opcua::services::writeDataValue(), opcua::services::writeDescription(), opcua::services::writeDisplayName(), opcua::services::writeEventNotifier(), opcua::services::writeExecutable(), opcua::services::writeHistorizing(), opcua::services::writeInverseName(), opcua::services::writeIsAbstract(), opcua::services::writeMinimumSamplingInterval(), opcua::services::writeSymmetric(), opcua::services::writeUserAccessLevel(), opcua::services::writeUserExecutable(), opcua::services::writeUserWriteMask(), opcua::services::writeValue(), opcua::services::writeValueRank(), and opcua::services::writeWriteMask().
readNodeId()
template<typename T > NodeId opcua::services::readNodeId (T & serverOrClient, const NodeId & id) inline
Read the NodeId attribute of a node.
This function is mainly used to check the existence of a node.
Definition at line 106 of file Attribute.h.
readNodeClass()
template<typename T > NodeClass opcua::services::readNodeClass (T & serverOrClient, const NodeId & id) inline
Read the NodeClass attribute of a node.
Definition at line 114 of file Attribute.h.
Referenced by opcua::Node< ServerOrClient >::readNodeClass().
readBrowseName()
template<typename T > QualifiedName opcua::services::readBrowseName (T & serverOrClient, const NodeId & id) inline
Read the BrowseName attribute of a node.
A non-localised human-readable name used to browse the address space. The browse name of a reference type must be unique in a server.
Definition at line 127 of file Attribute.h.
Referenced by opcua::Node< ServerOrClient >::readBrowseName().
readDisplayName()
template<typename T > LocalizedText opcua::services::readDisplayName (T & serverOrClient, const NodeId & id) inline
Read the DisplayName attribute of a node.
Used to display the node to the user.
Definition at line 137 of file Attribute.h.
Referenced by opcua::Node< ServerOrClient >::readDisplayName().
readDescription()
template<typename T > LocalizedText opcua::services::readDescription (T & serverOrClient, const NodeId & id) inline
Read the Description attribute of a node.
The description shall explain the meaning of the node.
Definition at line 147 of file Attribute.h.
Referenced by opcua::Node< ServerOrClient >::readDescription().
readWriteMask()
template<typename T > Bitmask< WriteMask > opcua::services::readWriteMask (T & serverOrClient, const NodeId & id) inline
Read the WriteMask attribute of a node.
Definition at line 155 of file Attribute.h.
Referenced by opcua::Node< ServerOrClient >::readWriteMask().
readUserWriteMask()
template<typename T > Bitmask< WriteMask > opcua::services::readUserWriteMask (T & serverOrClient, const NodeId & id) inline
Read the UserWriteMask attribute of a node.
In contrast to the write mask, the user write mask is taking access rights into account.
Definition at line 165 of file Attribute.h.
Referenced by opcua::Node< ServerOrClient >::readUserWriteMask().
readIsAbstract()
template<typename T > bool opcua::services::readIsAbstract (T & serverOrClient, const NodeId & id) inline
Read the IsAbtract attribute of a reference type node.
If a reference is abstract, no reference of this type shall exist, only of its subtypes.
Definition at line 175 of file Attribute.h.
Referenced by opcua::Node< ServerOrClient >::readIsAbstract().
readSymmetric()
template<typename T > bool opcua::services::readSymmetric (T & serverOrClient, const NodeId & id) inline
Read the Symmetric attribute of a reference type node.
If a reference is symmetric it can seen from both the source and target node.
Definition at line 185 of file Attribute.h.
Referenced by opcua::Node< ServerOrClient >::readSymmetric().
readInverseName()
template<typename T > LocalizedText opcua::services::readInverseName (T & serverOrClient, const NodeId & id) inline
Read the InverseName attribute of a reference type node.
The inverse name describes the reference type as seen from the target node. For example, the reference type HasSubtype has the inverse name HasSupertype.
Definition at line 196 of file Attribute.h.
Referenced by opcua::Node< ServerOrClient >::readInverseName().
readContainsNoLoops()
template<typename T > bool opcua::services::readContainsNoLoops (T & serverOrClient, const NodeId & id) inline
Read the ContainsNoLoops attribute of a view node.
Definition at line 204 of file Attribute.h.
Referenced by opcua::Node< ServerOrClient >::readContainsNoLoops().
readEventNotifier()
template<typename T > Bitmask< EventNotifier > opcua::services::readEventNotifier (T & serverOrClient, const NodeId & id) inline
Read the EventNotifier attribute of an object or view node.
Definition at line 212 of file Attribute.h.
Referenced by opcua::Node< ServerOrClient >::readEventNotifier().
readDataValue()
template<typename T > DataValue opcua::services::readDataValue (T & serverOrClient, const NodeId & id) inline
Read the Value attribute of a variable node as a DataValue object.
Definition at line 220 of file Attribute.h.
Referenced by opcua::Node< ServerOrClient >::readDataValue().
readValue()
template<typename T > Variant opcua::services::readValue (T & serverOrClient, const NodeId & id) inline
Read the Value attribute of a variable node as a Variant object.
Definition at line 228 of file Attribute.h.
Referenced by opcua::Node< ServerOrClient >::readValue().
readDataType()
template<typename T > NodeId opcua::services::readDataType (T & serverOrClient, const NodeId & id) inline
Read the DataType attribute of a variable (type) node as NodeId.
Definition at line 237 of file Attribute.h.
Referenced by opcua::Node< ServerOrClient >::readDataType().
readValueRank()
template<typename T > ValueRank opcua::services::readValueRank (T & serverOrClient, const NodeId & id) inline
Read the ValueRank attribute of a variable (type) node.
Indicates whether the value attribute of the variable node is an array and how many dimensions the array has.
Definition at line 248 of file Attribute.h.
Referenced by opcua::Node< ServerOrClient >::readValueRank().
readArrayDimensions()
template<typename T > std::vector< uint32_t > opcua::services::readArrayDimensions (T & serverOrClient, const NodeId & id) inline
Read the ArrayDimensions attribute of a variable (type) node.
Specifies the maximum supported length of each dimension (0 if unknown).
Definition at line 259 of file Attribute.h.
Referenced by opcua::Node< ServerOrClient >::readArrayDimensions().
readAccessLevel()
template<typename T > Bitmask< AccessLevel > opcua::services::readAccessLevel (T & serverOrClient, const NodeId & id) inline
Read the AccessLevel attribute of a variable node.
The access level attribute is used to indicate how the value of a variable can be accessed (read/write) and if it contains current and/or historic data.
Definition at line 274 of file Attribute.h.
Referenced by opcua::Node< ServerOrClient >::readAccessLevel().
readUserAccessLevel()
template<typename T > Bitmask< AccessLevel > opcua::services::readUserAccessLevel (T & serverOrClient, const NodeId & id) inline
Read the UserAccessLevel attribute a variable node.
The access level attribute is used to indicate how the value of a variable can be accessed (read/write) and if it contains current and/or historic data. In contrast to the access level, the user access level is taking access rights into account.
Definition at line 285 of file Attribute.h.
Referenced by opcua::Node< ServerOrClient >::readUserAccessLevel().
readMinimumSamplingInterval()
template<typename T > double opcua::services::readMinimumSamplingInterval (T & serverOrClient, const NodeId & id) inline
Read the MinimumSamplingInterval attribute of a variable node.
Specifies (in milliseconds) how fast the server can reasonably sample the value for changes. A minimum sampling interval of 0 indicates that the server is to monitor the item continuously. A minimum sampling interval of -1 means indeterminate.
Definition at line 297 of file Attribute.h.
Referenced by opcua::Node< ServerOrClient >::readMinimumSamplingInterval().
readHistorizing()
template<typename T > bool opcua::services::readHistorizing (T & serverOrClient, const NodeId & id) inline
Read the Historizing attribute of a variable node.
Definition at line 305 of file Attribute.h.
Referenced by opcua::Node< ServerOrClient >::readHistorizing().
readExecutable()
template<typename T > bool opcua::services::readExecutable (T & serverOrClient, const NodeId & id) inline
Read the Executable attribute of a method node.
Definition at line 313 of file Attribute.h.
Referenced by opcua::Node< ServerOrClient >::readExecutable().
readUserExecutable()
template<typename T > bool opcua::services::readUserExecutable (T & serverOrClient, const NodeId & id) inline
Read the UserExecutable attribute of a method node.
Definition at line 321 of file Attribute.h.
Referenced by opcua::Node< ServerOrClient >::readUserExecutable().
writeDisplayName()
template<typename T > void opcua::services::writeDisplayName (T & serverOrClient, const NodeId & id, const LocalizedText & name) inline
Write the DisplayName attribute of a node.
Used to display the node to the user.
Definition at line 332 of file Attribute.h.
Referenced by opcua::Node< ServerOrClient >::writeDisplayName().
writeDescription()
template<typename T > void opcua::services::writeDescription (T & serverOrClient, const NodeId & id, const LocalizedText & desc) inline
Write the Description attribute of a node.
The description shall explain the meaning of the node.
Definition at line 341 of file Attribute.h.
Referenced by opcua::Node< ServerOrClient >::writeDescription().
writeWriteMask()
template<typename T > void opcua::services::writeWriteMask (T & serverOrClient, const NodeId & id, Bitmask< WriteMask > mask) inline
Write the WriteMask attribute of a node.
Definition at line 350 of file Attribute.h.
Referenced by opcua::Node< ServerOrClient >::writeWriteMask().
writeUserWriteMask()
template<typename T > void opcua::services::writeUserWriteMask (T & serverOrClient, const NodeId & id, Bitmask< WriteMask > mask) inline
Write the UserWriteMask attribute of a node.
In contrast to the write mask, the user write mask is taking access rights into account.
Note
Cannot be written from the server.
Definition at line 360 of file Attribute.h.
Referenced by opcua::Node< ServerOrClient >::writeUserWriteMask().
writeIsAbstract()
template<typename T > void opcua::services::writeIsAbstract (T & serverOrClient, const NodeId & id, bool isAbstract) inline
Write the IsAbstract attribute of a reference type node.
If a reference is abstract, no reference of this type shall exist, only of its subtypes.
Definition at line 371 of file Attribute.h.
Referenced by opcua::Node< ServerOrClient >::writeIsAbstract().
writeSymmetric()
template<typename T > void opcua::services::writeSymmetric (T & serverOrClient, const NodeId & id, bool symmetric) inline
Write the Symmetric attribute of a reference type node.
If a reference is symmetric it can seen from both the source and target node.
Definition at line 380 of file Attribute.h.
Referenced by opcua::Node< ServerOrClient >::writeSymmetric().
writeInverseName()
template<typename T > void opcua::services::writeInverseName (T & serverOrClient, const NodeId & id, const LocalizedText & name) inline
Write the InverseName of a reference type node.
The inverse name describes the reference type as seen from the target node. For example, the reference type HasSubtype has the inverse name HasSupertype.
Definition at line 389 of file Attribute.h.
Referenced by opcua::Node< ServerOrClient >::writeInverseName().
writeContainsNoLoops()
template<typename T > void opcua::services::writeContainsNoLoops (T & serverOrClient, const NodeId & id, bool containsNoLoops) inline
Write the ContainsNoLoops attribute of a view node.
Definition at line 398 of file Attribute.h.
Referenced by opcua::Node< ServerOrClient >::writeContainsNoLoops().
writeEventNotifier()
template<typename T > void opcua::services::writeEventNotifier (T & serverOrClient, const NodeId & id, Bitmask< EventNotifier > mask) inline
Write the EventNotifier attribute of an object or view node.
Definition at line 409 of file Attribute.h.
Referenced by opcua::Node< ServerOrClient >::writeEventNotifier().
writeDataValue()
template<typename T > void opcua::services::writeDataValue (T & serverOrClient, const NodeId & id, const DataValue & value) inline
Write the Value attribute of a variable node as a DataValue object.
Definition at line 420 of file Attribute.h.
Referenced by opcua::Node< ServerOrClient >::writeDataValue().
writeValue()
template<typename T > void opcua::services::writeValue (T & serverOrClient, const NodeId & id, const Variant & value) inline
Write the Value attribute of a variable node as a Variant object.
Definition at line 429 of file Attribute.h.
Referenced by opcua::Node< ServerOrClient >::writeValue().
writeDataType()
template<typename T > void opcua::services::writeDataType (T & serverOrClient, const NodeId & id, const NodeId & typeId) inline
Write the DataType attribute of a variable (type) node.
Definition at line 441 of file Attribute.h.
Referenced by opcua::services::addModellingRule(), opcua::services::readAccessLevel(), opcua::services::readArrayDimensions(), opcua::services::readAttributeScalar(), opcua::services::readBrowseName(), opcua::services::readContainsNoLoops(), opcua::services::readDataType(), opcua::services::readDataValue(), opcua::services::readDescription(), opcua::services::readDisplayName(), opcua::services::readEventNotifier(), opcua::services::readExecutable(), opcua::services::readHistorizing(), opcua::services::readInverseName(), opcua::services::readIsAbstract(), opcua::services::readMinimumSamplingInterval(), opcua::services::readNodeClass(), opcua::services::readNodeId(), opcua::services::readSymmetric(), opcua::services::readUserAccessLevel(), opcua::services::readUserExecutable(), opcua::services::readUserWriteMask(), opcua::services::readValue(), opcua::services::readValueRank(), opcua::services::readWriteMask(), opcua::services::writeAccessLevel(), opcua::services::writeArrayDimensions(), opcua::services::writeContainsNoLoops(), opcua::Node< ServerOrClient >::writeDataType(), opcua::services::writeDataType(), opcua::services::writeDataValue(), opcua::services::writeDescription(), opcua::services::writeDisplayName(), opcua::services::writeEventNotifier(), opcua::services::writeExecutable(), opcua::services::writeHistorizing(), opcua::services::writeInverseName(), opcua::services::writeIsAbstract(), opcua::services::writeMinimumSamplingInterval(), opcua::services::writeSymmetric(), opcua::services::writeUserAccessLevel(), opcua::services::writeUserExecutable(), opcua::services::writeUserWriteMask(), opcua::services::writeValue(), opcua::services::writeValueRank(), and opcua::services::writeWriteMask().
writeValueRank()
template<typename T > void opcua::services::writeValueRank (T & serverOrClient, const NodeId & id, ValueRank valueRank) inline
Write the ValueRank attribute of a variable (type) node.
Indicates whether the value attribute of the variable node is an array and how many dimensions the array has.
Definition at line 450 of file Attribute.h.
Referenced by opcua::Node< ServerOrClient >::writeValueRank().
writeArrayDimensions()
template<typename T > void opcua::services::writeArrayDimensions (T & serverOrClient, const NodeId & id, Span< const uint32_t > dimensions) inline
Write the ArrayDimensions attribute of a variable (type) node.
Should be unspecified if ValueRank is <= 0 (ValueRank::Any, ValueRank::Scalar, ValueRank::ScalarOrOneDimension, ValueRank::OneOrMoreDimensions). The dimension zero is a wildcard and the actual value may have any length in this dimension.
Specifies the maximum supported length of each dimension (0 if unknown).
Definition at line 464 of file Attribute.h.
Referenced by opcua::Node< ServerOrClient >::writeArrayDimensions().
writeAccessLevel()
template<typename T > void opcua::services::writeAccessLevel (T & serverOrClient, const NodeId & id, Bitmask< AccessLevel > mask) inline
Write the AccessLevel attribute of a variable node.
The access level attribute is used to indicate how the value of a variable can be accessed (read/write) and if it contains current and/or historic data.
Definition at line 477 of file Attribute.h.
Referenced by opcua::Node< ServerOrClient >::writeAccessLevel().
writeUserAccessLevel()
template<typename T > void opcua::services::writeUserAccessLevel (T & serverOrClient, const NodeId & id, Bitmask< AccessLevel > mask) inline
Write the UserAccessLevel attribute of a variable node.
The access level attribute is used to indicate how the value of a variable can be accessed (read/write) and if it contains current and/or historic data. In contrast to the access level, the user access level is taking access rights into account.
Note
Cannot be written from the server.
Definition at line 487 of file Attribute.h.
Referenced by opcua::Node< ServerOrClient >::writeUserAccessLevel().
writeMinimumSamplingInterval()
template<typename T > void opcua::services::writeMinimumSamplingInterval (T & serverOrClient, const NodeId & id, double milliseconds) inline
Write the MinimumSamplingInterval attribute of a variable node.
Specifies (in milliseconds) how fast the server can reasonably sample the value for changes. A minimum sampling interval of 0 indicates that the server is to monitor the item continuously. A minimum sampling interval of -1 means indeterminate.
Definition at line 498 of file Attribute.h.
Referenced by opcua::Node< ServerOrClient >::writeMinimumSamplingInterval().
writeHistorizing()
template<typename T > void opcua::services::writeHistorizing (T & serverOrClient, const NodeId & id, bool historizing) inline
Write the Historizing attribute of a variable node.
Definition at line 512 of file Attribute.h.
Referenced by opcua::Node< ServerOrClient >::writeHistorizing().
writeExecutable()
template<typename T > void opcua::services::writeExecutable (T & serverOrClient, const NodeId & id, bool executable) inline
Write the Executable attribute of a method node.
Definition at line 523 of file Attribute.h.
Referenced by opcua::Node< ServerOrClient >::writeExecutable().
writeUserExecutable()
template<typename T > void opcua::services::writeUserExecutable (T & serverOrClient, const NodeId & id, bool userExecutable) inline
Write the UserExecutable attribute of a method node.
Definition at line 532 of file Attribute.h.
Referenced by opcua::Node< ServerOrClient >::writeUserExecutable().