open62541pp: ModifyMonitoredItems service
ModifyMonitoredItems service
Services » MonitoredItem service set
Detailed Description
Modify a monitored items of a subscription.
See also
https://reference.opcfoundation.org/Core/Part4/v105/docs/5.13.3
Functions
ModifyMonitoredItemsResponse opcua::services::modifyMonitoredItems (Client &connection, const ModifyMonitoredItemsRequest &request) noexcept
template<typename CompletionToken >
auto opcua::services::modifyMonitoredItemsAsync (Client &connection, const ModifyMonitoredItemsRequest &request, CompletionToken &&token)
MonitoredItemModifyResult opcua::services::modifyMonitoredItem (Client &connection, IntegerId subscriptionId, IntegerId monitoredItemId, const MonitoringParametersEx &parameters) noexcept
template<typename CompletionToken >
auto opcua::services::modifyMonitoredItemAsync (Client &connection, IntegerId subscriptionId, IntegerId monitoredItemId, const MonitoringParametersEx &parameters, CompletionToken &&token)
Function Documentation
modifyMonitoredItem()
MonitoredItemModifyResult opcua::services::modifyMonitoredItem (Client & connection, IntegerId subscriptionId, IntegerId monitoredItemId, const MonitoringParametersEx & parameters) inline noexcept
Modify a monitored item of a subscription.
Parameters
connection Instance of type Client
subscriptionId Identifier of the subscription returned by createSubscription
monitoredItemId Identifier of the monitored item
parameters Monitoring parameters
Definition at line 438 of file monitoreditem.hpp.
Referenced by opcua::MonitoredItem< Connection >::setMonitoringParameters().
modifyMonitoredItemAsync()
template<typename CompletionToken > auto opcua::services::modifyMonitoredItemAsync (Client & connection, IntegerId subscriptionId, IntegerId monitoredItemId, const MonitoringParametersEx & parameters, CompletionToken && token)
Parameters
token The completion token that will be used to produce a completion handler, which will be called when the operation completes. Potential completion tokens include useFuture, useDeferred, useDetached, or a function (object) with the correct completion signature. The function signature of the completion handler must be:
void(MonitoredItemModifyResult&)
Returns
void if token is a callback function (object)
std::future<MonitoredItemModifyResult> if token is of type UseFutureToken
auto(auto&& token) callable for deferred execution if token is of type UseDeferredToken
void if token is of type UseDetachedToken
Definition at line 459 of file monitoreditem.hpp.
modifyMonitoredItems()
ModifyMonitoredItemsResponse opcua::services::modifyMonitoredItems (Client & connection, const ModifyMonitoredItemsRequest & request) noexcept
Modify monitored items of a subscription.
Parameters
connection Instance of type Client
request Modify monitored items request
Referenced by opcua::services::modifyMonitoredItem().
modifyMonitoredItemsAsync()
template<typename CompletionToken > auto opcua::services::modifyMonitoredItemsAsync (Client & connection, const ModifyMonitoredItemsRequest & request, CompletionToken && token)
Modify monitored items of a subscription.
Parameters
connection Instance of type Client
request Modify monitored items request
token The completion token that will be used to produce a completion handler, which will be called when the operation completes. Potential completion tokens include useFuture, useDeferred, useDetached, or a function (object) with the correct completion signature. The function signature of the completion handler must be:
void(ModifyMonitoredItemsResponse&)
Returns
void if token is a callback function (object)
std::future<ModifyMonitoredItemsResponse> if token is of type UseFutureToken
auto(auto&& token) callable for deferred execution if token is of type UseDeferredToken
void if token is of type UseDetachedToken
Definition at line 415 of file monitoreditem.hpp.
Referenced by opcua::services::modifyMonitoredItemAsync().