open62541pp: Wrapper classes
Wrapper classes
Detailed Description
All wrapper classes inherit from Wrapper.
Native open62541 objects can be accessed using the Wrapper::handle() member function.
Wrapper types are pointer-interconvertible to the wrapped native type and vice versa:
Use asNative(T*) or asNative(const T*) to cast wrapper object pointers to native object pointers.
Use asNative(T&) or asNative(const T&) to cast wrapper object references to native object references.
Use asWrapper<T>(typename T::NativeType*) or asWrapper<T>(const typename T::NativeType*) to cast native object pointers to wrapper object pointers.
Use asWrapper<T>(typename T::NativeType&) or asWrapper<T>(const typename T::NativeType&) to cast native object references to wrapper object references.
According to the standard:
‍Two objects a and b are pointer-interconvertible if: One is a standard-layout class object [wrapper] and the other is the first non-static data member of that object [wrapped native type].
Derived classes must fulfill the requirements of standard-layout types to be convertible.
See also
https://en.cppreference.com/w/cpp/language/static_cast#pointer-interconvertible
Classes
class opcua::DataType
class opcua::StatusCode
class opcua::String
class opcua::DateTime
class opcua::Guid
class opcua::ByteString
class opcua::XmlElement
class opcua::NodeId
class opcua::ExpandedNodeId
class opcua::QualifiedName
class opcua::LocalizedText
class opcua::Variant
class opcua::DataValue
class opcua::ExtensionObject
class opcua::DiagnosticInfo
class opcua::NumericRange
class opcua::ua::EnumValueType
class opcua::ua::ApplicationDescription
class opcua::ua::RequestHeader
class opcua::ua::ResponseHeader
class opcua::ua::UserTokenPolicy
class opcua::ua::EndpointDescription
class opcua::ua::NodeAttributes
class opcua::ua::ObjectAttributes
class opcua::ua::VariableAttributes
class opcua::ua::MethodAttributes
class opcua::ua::ObjectTypeAttributes
class opcua::ua::VariableTypeAttributes
class opcua::ua::ReferenceTypeAttributes
class opcua::ua::DataTypeAttributes
class opcua::ua::ViewAttributes
class opcua::ua::UserIdentityToken
class opcua::ua::AnonymousIdentityToken
class opcua::ua::UserNameIdentityToken
class opcua::ua::X509IdentityToken
class opcua::ua::IssuedIdentityToken
class opcua::ua::AddNodesItem
class opcua::ua::AddNodesResult
class opcua::ua::AddNodesRequest
class opcua::ua::AddNodesResponse
class opcua::ua::AddReferencesItem
class opcua::ua::AddReferencesRequest
class opcua::ua::AddReferencesResponse
class opcua::ua::DeleteNodesItem
class opcua::ua::DeleteNodesRequest
class opcua::ua::DeleteNodesResponse
class opcua::ua::DeleteReferencesItem
class opcua::ua::DeleteReferencesRequest
class opcua::ua::DeleteReferencesResponse
class opcua::ua::ViewDescription
class opcua::ua::BrowseDescription
class opcua::ua::BrowseRequest
class opcua::ua::ReferenceDescription
class opcua::ua::BrowseResult
class opcua::ua::BrowseResponse
class opcua::ua::BrowseNextRequest
class opcua::ua::BrowseNextResponse
class opcua::ua::RelativePathElement
class opcua::ua::RelativePath
class opcua::ua::BrowsePath
class opcua::ua::BrowsePathTarget
class opcua::ua::BrowsePathResult
class opcua::ua::TranslateBrowsePathsToNodeIdsRequest
class opcua::ua::TranslateBrowsePathsToNodeIdsResponse
class opcua::ua::RegisterNodesRequest
class opcua::ua::RegisterNodesResponse
class opcua::ua::UnregisterNodesRequest
class opcua::ua::UnregisterNodesResponse
class opcua::ua::ReadValueId
class opcua::ua::ReadRequest
class opcua::ua::ReadResponse
class opcua::ua::WriteValue
class opcua::ua::WriteRequest
class opcua::ua::WriteResponse
class opcua::ua::BuildInfo
class opcua::ua::Argument
class opcua::ua::CallMethodRequest
class opcua::ua::CallMethodResult
class opcua::ua::CallRequest
class opcua::ua::CallResponse
class opcua::ua::ElementOperand
class opcua::ua::LiteralOperand
class opcua::ua::AttributeOperand
class opcua::ua::SimpleAttributeOperand
class opcua::ua::ContentFilterElement
class opcua::ua::ContentFilter
class opcua::ua::DataChangeFilter
class opcua::ua::EventFilter
class opcua::ua::AggregateFilter
class opcua::ua::MonitoringParameters
class opcua::ua::MonitoredItemCreateRequest
class opcua::ua::MonitoredItemCreateResult
class opcua::ua::CreateMonitoredItemsRequest
class opcua::ua::CreateMonitoredItemsResponse
class opcua::ua::MonitoredItemModifyRequest
class opcua::ua::MonitoredItemModifyResult
class opcua::ua::ModifyMonitoredItemsRequest
class opcua::ua::ModifyMonitoredItemsResponse
class opcua::ua::SetMonitoringModeRequest
class opcua::ua::SetMonitoringModeResponse
class opcua::ua::SetTriggeringRequest
class opcua::ua::SetTriggeringResponse
class opcua::ua::DeleteMonitoredItemsRequest
class opcua::ua::DeleteMonitoredItemsResponse
class opcua::ua::CreateSubscriptionRequest
class opcua::ua::CreateSubscriptionResponse
class opcua::ua::ModifySubscriptionRequest
class opcua::ua::ModifySubscriptionResponse
class opcua::ua::SetPublishingModeRequest
class opcua::ua::SetPublishingModeResponse
class opcua::ua::StatusChangeNotification
class opcua::ua::DeleteSubscriptionsRequest
class opcua::ua::DeleteSubscriptionsResponse
class opcua::ua::Range
class opcua::ua::EUInformation
class opcua::ua::ComplexNumberType
class opcua::ua::DoubleComplexNumberType
class opcua::ua::AxisInformation
class opcua::ua::XVType
class opcua::ua::StructureField
class opcua::ua::StructureDefinition
class opcua::ua::EnumField
class opcua::ua::EnumDefinition
struct opcua::TypeHandler< T >
struct opcua::TypeHandlerNative< T, Index >
class opcua::Wrapper< T, Handler >
class opcua::TypeWrapper< T, Index >
struct opcua::IsWrapper< T >
struct opcua::TypeRegistry< T, std::enable_if_t< IsWrapper< T >::value &&IsRegistered< typename T::NativeType >::value > >
Macros
#define UAPP_NODEATTR(Type, suffix, member, flag)
#define UAPP_NODEATTR_CAST(Type, suffix, member, flag)
#define UAPP_NODEATTR_WRAPPER(Type, suffix, member, flag)
#define UAPP_NODEATTR_ARRAY(Type, suffix, member, memberSize, flag)
#define UAPP_NODEATTR_COMMON
Typedefs
using opcua::ua::FilterOperand = std::variant< ElementOperand, LiteralOperand, AttributeOperand, SimpleAttributeOperand, ExtensionObject >
using opcua::ua::AggregateConfiguration = UA_AggregateConfiguration
template<typename T , TypeIndex Index>
using opcua::WrapperNative = Wrapper< T, TypeHandlerNative< T, Index > >
Enumerations
enum class opcua::ua::ApplicationType : int32_t
enum class opcua::ua::MessageSecurityMode : int32_t
enum class opcua::ua::UserTokenType : int32_t
enum class opcua::ua::NodeAttributesMask : uint32_t
enum class opcua::ua::BrowseDirection : int32_t
enum class opcua::ua::BrowseResultMask : uint32_t
enum class opcua::ua::TimestampsToReturn : int32_t
enum class opcua::ua::MonitoringMode : int32_t
enum class opcua::ua::FilterOperator : int32_t
enum class opcua::ua::DataChangeTrigger : int32_t
enum class opcua::ua::DeadbandType : int32_t
enum class opcua::ua::PerformUpdateType : int32_t
enum class opcua::ua::AxisScaleEnumeration : int32_t
enum class opcua::ua::StructureType : int32_t
Functions
constexpr std::true_type opcua::ua::isBitmaskEnum (NodeAttributesMask)
constexpr std::true_type opcua::ua::isBitmaskEnum (BrowseResultMask)
ContentFilter opcua::ua::operator&& (const ContentFilterElement &lhs, const ContentFilter &rhs)
ContentFilter opcua::ua::operator&& (const ContentFilter &lhs, const ContentFilterElement &rhs)
ContentFilter opcua::ua::operator|| (const ContentFilterElement &lhs, const ContentFilter &rhs)
ContentFilter opcua::ua::operator|| (const ContentFilter &lhs, const ContentFilterElement &rhs)
template<typename T >
constexpr T * opcua::asWrapper (typename T::NativeType *native) noexcept
template<typename T >
constexpr const T * opcua::asWrapper (const typename T::NativeType *native) noexcept
template<typename T >
constexpr T & opcua::asWrapper (typename T::NativeType &native) noexcept
template<typename T >
constexpr const T & opcua::asWrapper (const typename T::NativeType &native) noexcept
template<typename T >
constexpr T::NativeType * opcua::asNative (T *wrapper) noexcept
template<typename T >
constexpr const T::NativeType * opcua::asNative (const T *wrapper) noexcept
template<typename T >
constexpr T::NativeType & opcua::asNative (T &wrapper) noexcept
template<typename T >
constexpr const T::NativeType & opcua::asNative (const T &wrapper) noexcept
template<typename T >
String toString (const T &object, const UA_DataType &type)
template<typename T , typename = std::enable_if_t<IsRegistered<T>::value>>
String toString (const T &object)
template<typename T , typename = std::enable_if_t<IsRegistered<T>::value>>
bool operator== (const T &lhs, const T &rhs) noexcept
template<typename T , typename = std::enable_if_t<IsRegistered<T>::value>>
bool operator!= (const T &lhs, const T &rhs) noexcept
template<typename T , typename = std::enable_if_t<IsRegistered<T>::value>>
bool operator< (const T &lhs, const T &rhs) noexcept
template<typename T , typename = std::enable_if_t<IsRegistered<T>::value>>
bool operator<= (const T &lhs, const T &rhs) noexcept
template<typename T , typename = std::enable_if_t<IsRegistered<T>::value>>
bool operator> (const T &lhs, const T &rhs) noexcept
template<typename T , typename = std::enable_if_t<IsRegistered<T>::value>>
bool operator>= (const T &lhs, const T &rhs) noexcept
ContentFilter operator! (const ContentFilterElement &filterElement)
ContentFilter operator! (const ContentFilter &filter)
ContentFilter operator&& (const ContentFilterElement &lhs, const ContentFilterElement &rhs)
ContentFilter operator&& (const ContentFilterElement &lhs, const ContentFilter &rhs)
ContentFilter operator&& (const ContentFilter &lhs, const ContentFilterElement &rhs)
ContentFilter operator&& (const ContentFilter &lhs, const ContentFilter &rhs)
ContentFilter operator|| (const ContentFilterElement &lhs, const ContentFilterElement &rhs)
ContentFilter operator|| (const ContentFilterElement &lhs, const ContentFilter &rhs)
ContentFilter operator|| (const ContentFilter &lhs, const ContentFilterElement &rhs)
ContentFilter operator|| (const ContentFilter &lhs, const ContentFilter &rhs)
template<typename T >
constexpr T * asWrapper (typename T::NativeType *native) noexcept
template<typename T >
constexpr const T * asWrapper (const typename T::NativeType *native) noexcept
template<typename T >
constexpr T & asWrapper (typename T::NativeType &native) noexcept
template<typename T >
constexpr const T & asWrapper (const typename T::NativeType &native) noexcept
template<typename T >
constexpr T::NativeType * asNative (T *wrapper) noexcept
template<typename T >
constexpr const T::NativeType * asNative (const T *wrapper) noexcept
template<typename T >
constexpr T::NativeType & asNative (T &wrapper) noexcept
template<typename T >
constexpr const T::NativeType & asNative (const T &wrapper) noexcept
Macro Definition Documentation
UAPP_NODEATTR
#define UAPP_NODEATTR (Type, suffix, member, flag)
Value:
    UAPP_GETTER(Type, member)                                                                      \
    auto& set##suffix(Type member) noexcept {                                                      \
        handle()->specifiedAttributes |= flag;                                                     \
        handle()->member = member;                                                                 \
        return *this;                                                                              \
    }
Definition at line 339 of file types.hpp.
UAPP_NODEATTR_ARRAY
#define UAPP_NODEATTR_ARRAY (Type, suffix, member, memberSize, flag)
Value:
    UAPP_GETTER_SPAN(Type, member, memberSize)                                                     \
    auto& set##suffix(Span<const Type> member) {                                                   \
        const auto& type = opcua::getDataType<Type>();                                             \
        handle()->specifiedAttributes |= flag;                                                     \
        detail::deallocateArray(handle()->member, handle()->memberSize, type);                     \
        handle()->member = detail::copyArray(member.data(), member.size(), type);                  \
        handle()->memberSize = member.size();                                                      \
        return *this;                                                                              \
    }
Definition at line 360 of file types.hpp.
UAPP_NODEATTR_CAST
#define UAPP_NODEATTR_CAST (Type, suffix, member, flag)
Value:
    UAPP_GETTER_CAST(Type, member)                                                                 \
    auto& set##suffix(Type member) noexcept {                                                      \
        handle()->specifiedAttributes |= flag;                                                     \
        handle()->member = static_cast<decltype(handle()->member)>(member);                        \
        return *this;                                                                              \
    }
Definition at line 346 of file types.hpp.
UAPP_NODEATTR_COMMON
#define UAPP_NODEATTR_COMMON
Value:
    UAPP_GETTER(Bitmask<NodeAttributesMask>, specifiedAttributes)                                  \
    UAPP_NODEATTR_WRAPPER(                                                                         \
        LocalizedText, DisplayName, displayName, UA_NODEATTRIBUTESMASK_DISPLAYNAME                 \
    )                                                                                              \
    UAPP_NODEATTR_WRAPPER(                                                                         \
        LocalizedText, Description, description, UA_NODEATTRIBUTESMASK_DESCRIPTION                 \
    )                                                                                              \
    UAPP_NODEATTR_CAST(Bitmask<WriteMask>, WriteMask, writeMask, UA_NODEATTRIBUTESMASK_WRITEMASK)  \
    UAPP_NODEATTR_CAST(                                                                            \
        Bitmask<WriteMask>, UserWriteMask, userWriteMask, UA_NODEATTRIBUTESMASK_USERWRITEMASK      \
    )
Definition at line 370 of file types.hpp.
UAPP_NODEATTR_WRAPPER
#define UAPP_NODEATTR_WRAPPER (Type, suffix, member, flag)
Value:
    UAPP_GETTER_WRAPPER_CONST(Type, member)                                                        \
    auto& set##suffix(Type member) {                                                               \
        handle()->specifiedAttributes |= flag;                                                     \
        asWrapper<Type>(handle()->member) = std::move(member);                                     \
        return *this;                                                                              \
    }
Definition at line 353 of file types.hpp.
Typedef Documentation
AggregateConfiguration
using opcua::ua::AggregateConfiguration = typedef UA_AggregateConfiguration
Definition at line 1905 of file types.hpp.
FilterOperand
using opcua::ua::FilterOperand = typedef std::variant< ElementOperand, LiteralOperand, AttributeOperand, SimpleAttributeOperand, ExtensionObject>
Filter operand.
The FilterOperand is an extensible parameter and can be of type:
ElementOperand
LiteralOperand
AttributeOperand
SimpleAttributeOperand
ExtensionObject (other types)
See also
https://reference.opcfoundation.org/Core/Part4/v105/docs/7.7.4
Definition at line 1768 of file types.hpp.
WrapperNative
template<typename T , TypeIndex Index> using opcua::WrapperNative = typedef Wrapper<T, TypeHandlerNative<T, Index> >
Convenience alias for Wrapper using TypeHandlerNative.
See also
Wrapper
Definition at line 268 of file wrapper.hpp.
Enumeration Type Documentation
ApplicationType
enum class opcua::ua::ApplicationType : int32_t strong
Application type.
See also
UA_ApplicationType
https://reference.opcfoundation.org/Core/Part4/v105/docs/7.4
Enumerator
Server
Client
ClientAndServer
DiscoveryServer
Definition at line 115 of file types.hpp.
AxisScaleEnumeration
enum class opcua::ua::AxisScaleEnumeration : int32_t strong
Axis scale.
See also
https://reference.opcfoundation.org/Core/Part8/v105/docs/5.6.7
Enumerator
Linear
Log
Ln
Definition at line 2542 of file types.hpp.
BrowseDirection
enum class opcua::ua::BrowseDirection : int32_t strong
Browse direction.
An enumeration that specifies the direction of references to follow.
See also
UA_BrowseDirection
https://reference.opcfoundation.org/Core/Part4/v105/docs/7.5
Enumerator
Forward
Inverse
Both
Invalid
Definition at line 995 of file types.hpp.
BrowseResultMask
enum class opcua::ua::BrowseResultMask : uint32_t strong
Browse result mask.
The enum can be used as a bitmask and allows bitwise operations, e.g.:
auto mask = BrowseResultMask::ReferenceTypeId | BrowseResultMask::IsForward;
See also
UA_BrowseResultMask
https://reference.opcfoundation.org/Core/Part4/v105/docs/5.8.2
Enumerator
None
ReferenceTypeId
IsForward
NodeClass
BrowseName
DisplayName
TypeDefinition
All
ReferenceTypeInfo
TargetInfo
Definition at line 1015 of file types.hpp.
DataChangeTrigger
enum class opcua::ua::DataChangeTrigger : int32_t strong
Data change trigger.
See also
https://reference.opcfoundation.org/Core/Part4/v105/docs/7.10
Enumerator
Status
StatusValue
StatusValueTimestamp
Definition at line 1848 of file types.hpp.
DeadbandType
enum class opcua::ua::DeadbandType : int32_t strong
Deadband type.
See also
https://reference.opcfoundation.org/Core/Part4/v105/docs/7.22.2
Enumerator
None
Absolute
Percent
Definition at line 1860 of file types.hpp.
FilterOperator
enum class opcua::ua::FilterOperator : int32_t strong
Filter operator.
See also
https://reference.opcfoundation.org/Core/Part4/v105/docs/7.7.3
Enumerator
Equals
IsNull
GreaterThan
LessThan
GreaterThanOrEqual
LessThanOrEqual
Like
Not
Between
InList
And
Or
Cast
InView
OfType
RelatedTo
BitwiseAnd
BitwiseOr
Definition at line 1635 of file types.hpp.
MessageSecurityMode
enum class opcua::ua::MessageSecurityMode : int32_t strong
Message security mode.
See also
UA_MessageSecurityMode
https://reference.opcfoundation.org/Core/Part4/v105/docs/7.20
Enumerator
Invalid
Will always be rejected.
None
No security applied.
Sign
All messages are signed but not encrypted.
SignAndEncrypt
All messages are signed and encrypted.
Definition at line 215 of file types.hpp.
MonitoringMode
enum class opcua::ua::MonitoringMode : int32_t strong
Monitoring mode.
See also
UA_MonitoringMode
https://reference.opcfoundation.org/Core/Part4/v105/docs/7.23
Enumerator
Disabled
Sampling
Reporting
Definition at line 1623 of file types.hpp.
NodeAttributesMask
enum class opcua::ua::NodeAttributesMask : uint32_t strong
Node attributes mask.
Bitmask used in the node attributes parameters to specify which attributes are set.
See also
UA_NodeAttributesMask
Enumerator
None
AccessLevel
ArrayDimensions
BrowseName
ContainsNoLoops
DataType
Description
DisplayName
EventNotifier
Executable
Historizing
InverseName
IsAbstract
MinimumSamplingInterval
NodeClass
NodeId
Symmetric
UserAccessLevel
UserExecutable
UserWriteMask
ValueRank
WriteMask
Value
DataTypeDefinition
RolePermissions
AccessRestrictions
All
BaseNode
Object
ObjectType
Variable
VariableType
Method
ReferenceType
View
Definition at line 292 of file types.hpp.
PerformUpdateType
enum class opcua::ua::PerformUpdateType : int32_t strong
Perform update type for structured data history updates.
See also
UA_PerformUpdateType
https://reference.opcfoundation.org/Core/Part11/v104/docs/6.8.3
Enumerator
Insert
Replace
Update
Remove
Definition at line 2447 of file types.hpp.
StructureType
enum class opcua::ua::StructureType : int32_t strong
Structure type.
See also
https://reference.opcfoundation.org/Core/Part3/v105/docs/8.49
Enumerator
Structure
StructureWithOptionalFields
Union
Definition at line 2605 of file types.hpp.
TimestampsToReturn
enum class opcua::ua::TimestampsToReturn : int32_t strong
Timestamps to return.
See also
UA_TimestampsToReturn
https://reference.opcfoundation.org/Core/Part4/v105/docs/7.40
Enumerator
Source
Server
Both
Neither
Invalid
Definition at line 1349 of file types.hpp.
UserTokenType
enum class opcua::ua::UserTokenType : int32_t strong
User identity token type.
See also
https://reference.opcfoundation.org/Core/Part4/v105/docs/7.43
Enumerator
Anonymous
No token is required.
Username
A username/password token.
Certificate
An X.509 v3 certificate token.
IssuedToken
Any token issued by an authorization service.
Definition at line 228 of file types.hpp.
Function Documentation
asNative() [1/8]
template<typename T > constexpr const T::NativeType & asNative (const T & wrapper) related
Cast Wrapper object references to native object references.
Definition at line 365 of file wrapper.hpp.
asNative() [2/8]
template<typename T > constexpr const T::NativeType & asNative (const T & wrapper) constexpr noexcept
Cast Wrapper object references to native object references.
Definition at line 365 of file wrapper.hpp.
asNative() [3/8]
template<typename T > constexpr const T::NativeType * asNative (const T * wrapper) related
Cast Wrapper object pointers to native object pointers.
Definition at line 350 of file wrapper.hpp.
asNative() [4/8]
template<typename T > constexpr const T::NativeType * asNative (const T * wrapper) constexpr noexcept
Cast Wrapper object pointers to native object pointers.
Definition at line 350 of file wrapper.hpp.
asNative() [5/8]
template<typename T > constexpr T::NativeType & asNative (T & wrapper) related
Cast Wrapper object references to native object references.
Definition at line 358 of file wrapper.hpp.
asNative() [6/8]
template<typename T > constexpr T::NativeType & asNative (T & wrapper) constexpr noexcept
Cast Wrapper object references to native object references.
Definition at line 358 of file wrapper.hpp.
asNative() [7/8]
template<typename T > constexpr T::NativeType * asNative (T * wrapper) related
Cast Wrapper object pointers to native object pointers.
Definition at line 342 of file wrapper.hpp.
asNative() [8/8]
template<typename T > constexpr T::NativeType * asNative (T * wrapper) constexpr noexcept
Cast Wrapper object pointers to native object pointers.
Definition at line 342 of file wrapper.hpp.
Referenced by opcua::Wrapper< T, Handler >::asNative(), opcua::Wrapper< T, Handler >::asNative(), opcua::services::createMonitoredItemsDataChangeAsync(), opcua::services::createMonitoredItemsEventAsync(), opcua::services::deleteMonitoredItemsAsync(), opcua::services::deleteSubscriptionsAsync(), opcua::services::modifyMonitoredItemsAsync(), opcua::services::modifySubscriptionAsync(), and opcua::String::operator==().
asWrapper() [1/8]
template<typename T > constexpr const T & asWrapper (const typename T::NativeType & native) related
Cast native object references to Wrapper object references.
Definition at line 335 of file wrapper.hpp.
asWrapper() [2/8]
template<typename T > constexpr const T & asWrapper (const typename T::NativeType & native) constexpr noexcept
Cast native object references to Wrapper object references.
Definition at line 335 of file wrapper.hpp.
asWrapper() [3/8]
template<typename T > constexpr const T * asWrapper (const typename T::NativeType * native) related
Cast native object pointers to Wrapper object pointers.
Definition at line 320 of file wrapper.hpp.
asWrapper() [4/8]
template<typename T > constexpr const T * asWrapper (const typename T::NativeType * native) constexpr noexcept
Cast native object pointers to Wrapper object pointers.
Definition at line 320 of file wrapper.hpp.
asWrapper() [5/8]
template<typename T > constexpr T & asWrapper (typename T::NativeType & native) constexpr noexcept
Cast native object references to Wrapper object references.
Definition at line 328 of file wrapper.hpp.
asWrapper() [6/8]
template<typename T > constexpr T & asWrapper (typename T::NativeType & native) related
Cast native object references to Wrapper object references.
Definition at line 328 of file wrapper.hpp.
asWrapper() [7/8]
template<typename T > constexpr T * asWrapper (typename T::NativeType * native) constexpr noexcept
Cast native object pointers to Wrapper object pointers.
Definition at line 312 of file wrapper.hpp.
asWrapper() [8/8]
template<typename T > constexpr T * asWrapper (typename T::NativeType * native) related
Cast native object pointers to Wrapper object pointers.
Definition at line 312 of file wrapper.hpp.
isBitmaskEnum() [1/2]
constexpr std::true_type opcua::ua::isBitmaskEnum (BrowseResultMask) constexpr
isBitmaskEnum() [2/2]
constexpr std::true_type opcua::ua::isBitmaskEnum (NodeAttributesMask) constexpr
operator!() [1/2]
ContentFilter operator! (const ContentFilter & filter) related
operator!() [2/2]
ContentFilter operator! (const ContentFilterElement & filterElement) related
operator!=()
template<typename T , typename = std::enable_if_t<IsRegistered<T>::value>> bool operator!= (const T & lhs, const T & rhs) related
Definition at line 2138 of file types.hpp.
operator&&() [1/6]
ContentFilter operator&& (const ContentFilter & lhs, const ContentFilter & rhs) related
operator&&() [2/6]
ContentFilter operator&& (const ContentFilter & lhs, const ContentFilterElement & rhs)
operator&&() [3/6]
ContentFilter operator&& (const ContentFilter & lhs, const ContentFilterElement & rhs) related
operator&&() [4/6]
ContentFilter operator&& (const ContentFilterElement & lhs, const ContentFilter & rhs)
operator&&() [5/6]
ContentFilter operator&& (const ContentFilterElement & lhs, const ContentFilter & rhs) related
operator&&() [6/6]
ContentFilter operator&& (const ContentFilterElement & lhs, const ContentFilterElement & rhs) related
operator<()
template<typename T , typename = std::enable_if_t<IsRegistered<T>::value>> bool operator< (const T & lhs, const T & rhs) related
Definition at line 2145 of file types.hpp.
operator<=()
template<typename T , typename = std::enable_if_t<IsRegistered<T>::value>> bool operator<= (const T & lhs, const T & rhs) related
Definition at line 2152 of file types.hpp.
operator==()
template<typename T , typename = std::enable_if_t<IsRegistered<T>::value>> bool operator== (const T & lhs, const T & rhs) related
Definition at line 2131 of file types.hpp.
operator>()
template<typename T , typename = std::enable_if_t<IsRegistered<T>::value>> bool operator> (const T & lhs, const T & rhs) related
Definition at line 2159 of file types.hpp.
operator>=()
template<typename T , typename = std::enable_if_t<IsRegistered<T>::value>> bool operator>= (const T & lhs, const T & rhs) related
Definition at line 2166 of file types.hpp.
operator||() [1/6]
ContentFilter operator|| (const ContentFilter & lhs, const ContentFilter & rhs) related
operator||() [2/6]
ContentFilter operator|| (const ContentFilter & lhs, const ContentFilterElement & rhs) related
operator||() [3/6]
ContentFilter operator|| (const ContentFilter & lhs, const ContentFilterElement & rhs)
operator||() [4/6]
ContentFilter operator|| (const ContentFilterElement & lhs, const ContentFilter & rhs) related
operator||() [5/6]
ContentFilter operator|| (const ContentFilterElement & lhs, const ContentFilter & rhs)
operator||() [6/6]
ContentFilter operator|| (const ContentFilterElement & lhs, const ContentFilterElement & rhs) related
toString() [1/2]
template<typename T , typename = std::enable_if_t<IsRegistered<T>::value>> String toString (const T & object) related
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 2120 of file types.hpp.
toString() [2/2]
template<typename T > String toString (const T & object, const UA_DataType & type) related
Converts an object to its string representation.
This function wraps UA_print to generate a string representation of the given object, based on its data type description.
Note
Requires open62541 v1.2 or later. The open62541 library must be compiled with the UA_ENABLE_TYPEDESCRIPTION option. If these conditions are not met, the function returns an empty String.
Parameters
object Native or wrapper object.
type Data type of object.
Definition at line 2106 of file types.hpp.