open62541++: View service set
View service set
Services
Detailed Description
Browse the address space / view created by a server.
See also
https://reference.opcfoundation.org/Core/Part4/v105/docs/5.8
Functions
BrowseResponse opcua::services::browse (Client &client, const BrowseRequest &request)
template<typename T >
BrowseResult opcua::services::browse (T &serverOrClient, const BrowseDescription &bd, uint32_t maxReferences=0)
BrowseNextResponse opcua::services::browseNext (Client &client, const BrowseNextRequest &request)
template<typename T >
BrowseResult opcua::services::browseNext (T &serverOrClient, bool releaseContinuationPoint, const ByteString &continuationPoint)
template<typename T >
std::vector< ReferenceDescription > opcua::services::browseAll (T &serverOrClient, const BrowseDescription &bd, uint32_t maxReferences=0)
std::vector< ExpandedNodeId > opcua::services::browseRecursive (Server &server, const BrowseDescription &bd)
TranslateBrowsePathsToNodeIdsResponse opcua::services::translateBrowsePathsToNodeIds (Client &client, const TranslateBrowsePathsToNodeIdsRequest &request)
template<typename T >
BrowsePathResult opcua::services::translateBrowsePathToNodeIds (T &serverOrClient, const BrowsePath &browsePath)
template<typename T >
BrowsePathResult opcua::services::browseSimplifiedBrowsePath (T &serverOrClient, const NodeId &origin, Span< const QualifiedName > browsePath)
RegisterNodesResponse opcua::services::registerNodes (Client &client, const RegisterNodesRequest &request)
UnregisterNodesResponse opcua::services::unregisterNodes (Client &client, const UnregisterNodesRequest &request)
Function Documentation
browse() [1/2]
BrowseResponse opcua::services::browse (Client & client, const BrowseRequest & request)
Discover the references of one or more nodes (client only).
See also
https://reference.opcfoundation.org/Core/Part4/v105/docs/5.8.2
browse() [2/2]
template<typename T > BrowseResult opcua::services::browse (T & serverOrClient, const BrowseDescription & bd, uint32_t maxReferences = 0)
Discover the references of a specified node.
Parameters
serverOrClient Instance of type Server or Client
bd Browse description
maxReferences The maximum number of references to return (0 if no limit)
See also
https://reference.opcfoundation.org/Core/Part4/v105/docs/5.8.2
browseNext() [1/2]
BrowseNextResponse opcua::services::browseNext (Client & client, const BrowseNextRequest & request)
Request the next sets of browse / browseNext responses (client only).
See also
https://reference.opcfoundation.org/Core/Part4/v105/docs/5.8.3
browseNext() [2/2]
template<typename T > BrowseResult opcua::services::browseNext (T & serverOrClient, bool releaseContinuationPoint, const ByteString & continuationPoint)
Request the next set of a browse or browseNext response.
The response might get split up if the information is too large to be sent in a single response.
Parameters
serverOrClient Instance of type Server or Client
releaseContinuationPoint Free resources in server if true, get next result if false
continuationPoint Continuation point from a preview browse/browseNext request
See also
https://reference.opcfoundation.org/Core/Part4/v105/docs/5.8.3
browseAll()
template<typename T > std::vector< ReferenceDescription > opcua::services::browseAll (T & serverOrClient, const BrowseDescription & bd, uint32_t maxReferences = 0)
Discover all the references of a specified node (without calling browseNext).
See also
https://reference.opcfoundation.org/Core/Part4/v105/docs/5.8.2
Referenced by opcua::Node< ServerOrClient >::browseReferencedNodes(), and opcua::Node< ServerOrClient >::browseReferences().
browseRecursive()
std::vector< ExpandedNodeId > opcua::services::browseRecursive (Server & server, const BrowseDescription & bd)
Discover child nodes recursively (non-standard).
Possible loops (that can occur for non-hierarchical references) are handled internally. Every node is added at most once to the results array. Nodes are only added if they match the nodeClassMask in the BrowseDescription. However, child nodes are still recursed into if the NodeClass does not match. So it is possible, for example, to get all VariableNodes below a certain ObjectNode, with additional objects in the hierarchy below.
Note
No implementation for Client.
Parameters
server Instance of type Server
bd Browse description
See also
UA_Server_browseRecursive
translateBrowsePathsToNodeIds()
TranslateBrowsePathsToNodeIdsResponse opcua::services::translateBrowsePathsToNodeIds (Client & client, const TranslateBrowsePathsToNodeIdsRequest & request)
Translate browse paths to NodeIds (client only).
See also
https://reference.opcfoundation.org/Core/Part4/v105/docs/5.8.4
translateBrowsePathToNodeIds()
template<typename T > BrowsePathResult opcua::services::translateBrowsePathToNodeIds (T & serverOrClient, const BrowsePath & browsePath)
Translate a browse path to NodeIds.
Parameters
serverOrClient Instance of type Server or Client
browsePath Browse path (starting node & relative path)
See also
https://reference.opcfoundation.org/Core/Part4/v105/docs/5.8.4
browseSimplifiedBrowsePath()
template<typename T > BrowsePathResult opcua::services::browseSimplifiedBrowsePath (T & serverOrClient, const NodeId & origin, Span< const QualifiedName > browsePath)
A simplified version of translateBrowsePathToNodeIds.
The relative path is specified using browse names instead of the RelativePath structure. The list of browse names is equivalent to a RelativePath that specifies forward references which are subtypes of the HierarchicalReferences ReferenceTypeId.
Parameters
serverOrClient Instance of type Server or Client
origin Starting node of the browse path
browsePath Browse path as a list of browse names
Referenced by opcua::Node< ServerOrClient >::browseChild().
registerNodes()
RegisterNodesResponse opcua::services::registerNodes (Client & client, const RegisterNodesRequest & request)
Register nodes for efficient access operations (client only).
Clients shall unregister unneeded nodes immediately to free up resources.
See also
https://reference.opcfoundation.org/Core/Part4/v105/docs/5.8.5
unregisterNodes()
UnregisterNodesResponse opcua::services::unregisterNodes (Client & client, const UnregisterNodesRequest & request)
Unregister nodes (client only).
See also
https://reference.opcfoundation.org/Core/Part4/v105/docs/5.8.6