open62541pp: DeleteReferences service
DeleteReferences service
Services » NodeManagement service set
Detailed Description
Delete references from nodes.
See also
https://reference.opcfoundation.org/Core/Part4/v105/docs/5.8.5
Functions
DeleteReferencesResponse opcua::services::deleteReferences (Client &connection, const DeleteReferencesRequest &request) noexcept
template<typename CompletionToken >
auto opcua::services::deleteReferencesAsync (Client &connection, const DeleteReferencesRequest &request, CompletionToken &&token)
template<typename T >
StatusCode opcua::services::deleteReference (T &connection, const NodeId &sourceId, const NodeId &targetId, const NodeId &referenceType, bool isForward, bool deleteBidirectional) noexcept
template<typename CompletionToken >
auto opcua::services::deleteReferenceAsync (Client &connection, const NodeId &sourceId, const NodeId &targetId, const NodeId &referenceType, bool isForward, bool deleteBidirectional, CompletionToken &&token)
Function Documentation
deleteReferences()
DeleteReferencesResponse opcua::services::deleteReferences (Client & connection, const DeleteReferencesRequest & request) noexcept
Delete one or more references (client only).
Parameters
connection Instance of type Client
request Delete references request
Referenced by opcua::services::deleteNodeAsync().
deleteReferencesAsync()
template<typename CompletionToken > auto opcua::services::deleteReferencesAsync (Client & connection, const DeleteReferencesRequest & request, CompletionToken && token)
Delete one or more references (client only).
Parameters
connection Instance of type Client
request Delete references request
token The completion token that will be used to produce a completion handler, which will be called when the operation completes. Potential completion tokens include useFuture, useDeferred, useDetached, or a function (object) with the correct completion signature. The function signature of the completion handler must be:
void(DeleteReferencesResponse&)
Returns
void if token is a callback function (object)
std::future<DeleteReferencesResponse> if token is of type UseFutureToken
auto(auto&& token) callable for deferred execution if token is of type UseDeferredToken
void if token is of type UseDetachedToken
Definition at line 273 of file nodemanagement.hpp.
Referenced by opcua::services::deleteReferenceAsync().
deleteReference()
template<typename T > StatusCode opcua::services::deleteReference (T & connection, const NodeId & sourceId, const NodeId & targetId, const NodeId & referenceType, bool isForward, bool deleteBidirectional) noexcept
Delete reference.
Parameters
connection Instance of type Client (or Server)
sourceId Node that contains the reference to delete
targetId Target node of the reference to delete
referenceType NodeId of the reference type that defines the reference to delete
isForward Delete the forward reference if true, delete the inverse reference if false
deleteBidirectional Delete the specified and opposite reference from the target node
Referenced by opcua::Node< Connection >::deleteReference().
deleteReferenceAsync()
template<typename CompletionToken > auto opcua::services::deleteReferenceAsync (Client & connection, const NodeId & sourceId, const NodeId & targetId, const NodeId & referenceType, bool isForward, bool deleteBidirectional, CompletionToken && token)
Delete reference.
Parameters
connection Instance of type Client (or Server)
sourceId Node that contains the reference to delete
targetId Target node of the reference to delete
referenceType NodeId of the reference type that defines the reference to delete
isForward Delete the forward reference if true, delete the inverse reference if false
deleteBidirectional Delete the specified and opposite reference from the target node
token The completion token that will be used to produce a completion handler, which will be called when the operation completes. Potential completion tokens include useFuture, useDeferred, useDetached, or a function (object) with the correct completion signature. The function signature of the completion handler must be:
void(StatusCode)
Returns
void if token is a callback function (object)
std::future<StatusCode> if token is of type UseFutureToken
auto(auto&& token) callable for deferred execution if token is of type UseDeferredToken
void if token is of type UseDetachedToken
Definition at line 306 of file nodemanagement.hpp.
Referenced by opcua::Node< Connection >::deleteReferenceAsync().