open62541pp: CreateMonitoredItems service
CreateMonitoredItems service
Services » MonitoredItem service set
Detailed Description
Create and add a monitored item to a subscription.
See also
https://reference.opcfoundation.org/Core/Part4/v105/docs/5.13.2
Typedefs
using opcua::services::DeleteMonitoredItemCallback = std::function< void(IntegerId subId, IntegerId monId)>
using opcua::services::DataChangeNotificationCallback = std::function< void(IntegerId subId, IntegerId monId, const DataValue &value)>
using opcua::services::EventNotificationCallback = std::function< void(IntegerId subId, IntegerId monId, Span< const Variant > eventFields)>
Functions
CreateMonitoredItemsResponse opcua::services::createMonitoredItemsDataChange (Client &connection, const CreateMonitoredItemsRequest &request, DataChangeNotificationCallback dataChangeCallback, DeleteMonitoredItemCallback deleteCallback)
template<typename CompletionToken >
auto opcua::services::createMonitoredItemsDataChangeAsync (Client &connection, const CreateMonitoredItemsRequest &request, DataChangeNotificationCallback dataChangeCallback, DeleteMonitoredItemCallback deleteCallback, CompletionToken &&token)
template<typename T >
MonitoredItemCreateResult opcua::services::createMonitoredItemDataChange (T &connection, IntegerId subscriptionId, const ReadValueId &itemToMonitor, MonitoringMode monitoringMode, const MonitoringParametersEx &parameters, DataChangeNotificationCallback dataChangeCallback, DeleteMonitoredItemCallback deleteCallback)
template<typename CompletionToken >
auto opcua::services::createMonitoredItemDataChangeAsync (Client &connection, IntegerId subscriptionId, const ReadValueId &itemToMonitor, MonitoringMode monitoringMode, const MonitoringParametersEx &parameters, DataChangeNotificationCallback dataChangeCallback, DeleteMonitoredItemCallback deleteCallback, CompletionToken &&token)
CreateMonitoredItemsResponse opcua::services::createMonitoredItemsEvent (Client &connection, const CreateMonitoredItemsRequest &request, EventNotificationCallback eventCallback, DeleteMonitoredItemCallback deleteCallback)
template<typename CompletionToken >
auto opcua::services::createMonitoredItemsEventAsync (Client &connection, const CreateMonitoredItemsRequest &request, EventNotificationCallback eventCallback, DeleteMonitoredItemCallback deleteCallback, CompletionToken &&token)
MonitoredItemCreateResult opcua::services::createMonitoredItemEvent (Client &connection, IntegerId subscriptionId, const ReadValueId &itemToMonitor, MonitoringMode monitoringMode, const MonitoringParametersEx &parameters, EventNotificationCallback eventCallback, DeleteMonitoredItemCallback deleteCallback={})
template<typename CompletionToken >
auto opcua::services::createMonitoredItemEventAsync (Client &connection, IntegerId subscriptionId, const ReadValueId &itemToMonitor, MonitoringMode monitoringMode, const MonitoringParametersEx &parameters, EventNotificationCallback eventCallback, DeleteMonitoredItemCallback deleteCallback, CompletionToken &&token)
Typedef Documentation
DataChangeNotificationCallback
using opcua::services::DataChangeNotificationCallback = typedef std::function<void(IntegerId subId, IntegerId monId, const DataValue& value)>
Data change notification callback.
Parameters
subId Subscription identifier (0U for local (server-side) monitored item)
monId MonitoredItem identifier
value Changed value
Definition at line 98 of file monitoreditem.hpp.
DeleteMonitoredItemCallback
using opcua::services::DeleteMonitoredItemCallback = typedef std::function<void(IntegerId subId, IntegerId monId)>
MonitoredItem deletion callback.
Parameters
subId Subscription identifier
monId MonitoredItem identifier
Definition at line 90 of file monitoreditem.hpp.
EventNotificationCallback
using opcua::services::EventNotificationCallback = typedef std::function<void(IntegerId subId, IntegerId monId, Span<const Variant> eventFields)>
Event notification callback.
Parameters
subId Subscription identifier (0U for local (server-side) monitored item)
monId MonitoredItem identifier
eventFields Event fields
Definition at line 107 of file monitoreditem.hpp.
Function Documentation
createMonitoredItemDataChange()
template<typename T > MonitoredItemCreateResult opcua::services::createMonitoredItemDataChange (T & connection, IntegerId subscriptionId, const ReadValueId & itemToMonitor, MonitoringMode monitoringMode, const MonitoringParametersEx & parameters, DataChangeNotificationCallback dataChangeCallback, DeleteMonitoredItemCallback deleteCallback)
Create and add a monitored item to a subscription for data change notifications.
Don't use this function to monitor the EventNotifier attribute. Create a monitored item with createMonitoredItemEvent instead.
Parameters
connection Instance of type Server or Client
subscriptionId Identifier of the subscription returned by createSubscription. Use 0U for a local server-side monitored item.
itemToMonitor Item to monitor
monitoringMode Monitoring mode
parameters Monitoring parameters
dataChangeCallback Invoked when the monitored item is changed
deleteCallback Invoked when the monitored item is deleted
Referenced by opcua::Subscription< Connection >::subscribeDataChange().
createMonitoredItemDataChangeAsync()
template<typename CompletionToken > auto opcua::services::createMonitoredItemDataChangeAsync (Client & connection, IntegerId subscriptionId, const ReadValueId & itemToMonitor, MonitoringMode monitoringMode, const MonitoringParametersEx & parameters, DataChangeNotificationCallback dataChangeCallback, DeleteMonitoredItemCallback deleteCallback, CompletionToken && token)
Parameters
token The completion token that will be used to produce a completion handler, which will be called when the operation completes. Potential completion tokens include useFuture, useDeferred, useDetached, or a function (object) with the correct completion signature. The function signature of the completion handler must be:
void(MonitoredItemCreateResult&)
Returns
void if token is a callback function (object)
std::future<MonitoredItemCreateResult> if token is of type UseFutureToken
auto(auto&& token) callable for deferred execution if token is of type UseDeferredToken
void if token is of type UseDetachedToken
Examples
client_async.cpp.
Definition at line 236 of file monitoreditem.hpp.
createMonitoredItemEvent()
MonitoredItemCreateResult opcua::services::createMonitoredItemEvent (Client & connection, IntegerId subscriptionId, const ReadValueId & itemToMonitor, MonitoringMode monitoringMode, const MonitoringParametersEx & parameters, EventNotificationCallback eventCallback, DeleteMonitoredItemCallback deleteCallback = {})
Create and add a monitored item to a subscription for event notifications.
The attributeId of ReadValueId must be set to AttributeId::EventNotifier.
Parameters
connection Instance of type Client
subscriptionId Identifier of the subscription returned by createSubscription
itemToMonitor Item to monitor
monitoringMode Monitoring mode
parameters Monitoring parameters
eventCallback Invoked when an event is published
deleteCallback Invoked when the monitored item is deleted
Referenced by opcua::Subscription< Connection >::subscribeEvent().
createMonitoredItemEventAsync()
template<typename CompletionToken > auto opcua::services::createMonitoredItemEventAsync (Client & connection, IntegerId subscriptionId, const ReadValueId & itemToMonitor, MonitoringMode monitoringMode, const MonitoringParametersEx & parameters, EventNotificationCallback eventCallback, DeleteMonitoredItemCallback deleteCallback, CompletionToken && token)
Create and add a monitored item to a subscription for event notifications.
The attributeId of ReadValueId must be set to AttributeId::EventNotifier.
Parameters
connection Instance of type Client
subscriptionId Identifier of the subscription returned by createSubscription
itemToMonitor Item to monitor
monitoringMode Monitoring mode
parameters Monitoring parameters
eventCallback Invoked when an event is published
deleteCallback Invoked when the monitored item is deleted
token The completion token that will be used to produce a completion handler, which will be called when the operation completes. Potential completion tokens include useFuture, useDeferred, useDetached, or a function (object) with the correct completion signature. The function signature of the completion handler must be:
void(MonitoredItemCreateResult&)
Returns
void if token is a callback function (object)
std::future<MonitoredItemCreateResult> if token is of type UseFutureToken
auto(auto&& token) callable for deferred execution if token is of type UseDeferredToken
void if token is of type UseDetachedToken
Definition at line 361 of file monitoreditem.hpp.
createMonitoredItemsDataChange()
CreateMonitoredItemsResponse opcua::services::createMonitoredItemsDataChange (Client & connection, const CreateMonitoredItemsRequest & request, DataChangeNotificationCallback dataChangeCallback, DeleteMonitoredItemCallback deleteCallback)
Create and add monitored items to a subscription for data change notifications.
Don't use this function to monitor the EventNotifier attribute. Create monitored items with createMonitoredItemsEvent instead.
Parameters
connection Instance of type Client
request Create monitored items request
dataChangeCallback Invoked when the monitored item is changed
deleteCallback Invoked when the monitored item is deleted
createMonitoredItemsDataChangeAsync()
template<typename CompletionToken > auto opcua::services::createMonitoredItemsDataChangeAsync (Client & connection, const CreateMonitoredItemsRequest & request, DataChangeNotificationCallback dataChangeCallback, DeleteMonitoredItemCallback deleteCallback, CompletionToken && token)
Create and add monitored items to a subscription for data change notifications.
Don't use this function to monitor the EventNotifier attribute. Create monitored items with createMonitoredItemsEvent instead.
Parameters
connection Instance of type Client
request Create monitored items request
dataChangeCallback Invoked when the monitored item is changed
deleteCallback Invoked when the monitored item is deleted
token The completion token that will be used to produce a completion handler, which will be called when the operation completes. Potential completion tokens include useFuture, useDeferred, useDetached, or a function (object) with the correct completion signature. The function signature of the completion handler must be:
void(CreateMonitoredItemsResponse&)
Returns
void if token is a callback function (object)
std::future<CreateMonitoredItemsResponse> if token is of type UseFutureToken
auto(auto&& token) callable for deferred execution if token is of type UseDeferredToken
void if token is of type UseDetachedToken
Definition at line 160 of file monitoreditem.hpp.
Referenced by opcua::services::createMonitoredItemDataChangeAsync().
createMonitoredItemsEvent()
CreateMonitoredItemsResponse opcua::services::createMonitoredItemsEvent (Client & connection, const CreateMonitoredItemsRequest & request, EventNotificationCallback eventCallback, DeleteMonitoredItemCallback deleteCallback)
Create and add monitored items to a subscription for event notifications.
The attributeId of ReadValueId must be set to AttributeId::EventNotifier.
Parameters
connection Instance of type Client
request Create monitored items request
eventCallback Invoked when an event is published
deleteCallback Invoked when the monitored item is deleted
createMonitoredItemsEventAsync()
template<typename CompletionToken > auto opcua::services::createMonitoredItemsEventAsync (Client & connection, const CreateMonitoredItemsRequest & request, EventNotificationCallback eventCallback, DeleteMonitoredItemCallback deleteCallback, CompletionToken && token)
Create and add monitored items to a subscription for event notifications.
The attributeId of ReadValueId must be set to AttributeId::EventNotifier.
Parameters
connection Instance of type Client
request Create monitored items request
eventCallback Invoked when an event is published
deleteCallback Invoked when the monitored item is deleted
token The completion token that will be used to produce a completion handler, which will be called when the operation completes. Potential completion tokens include useFuture, useDeferred, useDetached, or a function (object) with the correct completion signature. The function signature of the completion handler must be:
void(CreateMonitoredItemsResponse&)
Returns
void if token is a callback function (object)
std::future<CreateMonitoredItemsResponse> if token is of type UseFutureToken
auto(auto&& token) callable for deferred execution if token is of type UseDeferredToken
void if token is of type UseDetachedToken
Definition at line 289 of file monitoreditem.hpp.
Referenced by opcua::services::createMonitoredItemEventAsync().