open62541pp: SetPublishingMode service
SetPublishingMode service
Services » Subscription service set
Detailed Description
Enable/disable sending of notifications on subscriptions.
Disable publishing of NotificationMessages of the subscription doesn't discontinue the sending of keep-alive messages, nor change the monitoring mode.
See also
https://reference.opcfoundation.org/Core/Part4/v105/docs/5.13.4
Functions
SetPublishingModeResponse opcua::services::setPublishingMode (Client &connection, const SetPublishingModeRequest &request) noexcept
template<typename CompletionToken >
auto opcua::services::setPublishingModeAsync (Client &connection, const SetPublishingModeRequest &request, CompletionToken &&token)
StatusCode opcua::services::setPublishingMode (Client &connection, uint32_t subscriptionId, bool publishing) noexcept
template<typename CompletionToken >
auto opcua::services::setPublishingModeAsync (Client &connection, uint32_t subscriptionId, bool publishing, CompletionToken &&token)
Function Documentation
setPublishingMode() [1/2]
SetPublishingModeResponse opcua::services::setPublishingMode (Client & connection, const SetPublishingModeRequest & request) noexcept
Enable/disable publishing of notification messages of subscriptions.
Parameters
connection Instance of type Client
request Set publishing mode request
Referenced by opcua::services::setPublishingMode(), opcua::services::setPublishingMode(), and opcua::Subscription< Connection >::setPublishingMode().
setPublishingModeAsync() [1/2]
template<typename CompletionToken > auto opcua::services::setPublishingModeAsync (Client & connection, const SetPublishingModeRequest & request, CompletionToken && token)
Enable/disable publishing of notification messages of subscriptions.
Parameters
connection Instance of type Client
request Set publishing mode request
token
The @ref async_model "completion token" that will be used to produce a completion handler, which will be called when the operation completes.
Potential completion tokens include @ref useFuture, @ref useDeferred, @ref useDetached, or a function (object) with the correct completion signature.
The function signature of the completion handler must be:
void(SetPublishingModeResponse&)
Returns
void if token is a callback function (object)
std::future<SetPublishingModeResponse> if token is of type UseFutureToken
auto(auto&& token) callable for deferred execution if token is of type UseDeferredToken
void if token is of type UseDetachedToken
Definition at line 270 of file subscription.hpp.
Referenced by opcua::services::setPublishingModeAsync(), and opcua::services::setPublishingModeAsync().
setPublishingMode() [2/2]
StatusCode opcua::services::setPublishingMode (Client & connection, uint32_t subscriptionId, bool publishing) inline noexcept
Enable/disable publishing of notification messages of a single subscription.
Parameters
connection Instance of type Client
subscriptionId Identifier of the subscription returned by createSubscription
publishing Enable/disable publishing
Definition at line 284 of file subscription.hpp.
setPublishingModeAsync() [2/2]
template<typename CompletionToken > auto opcua::services::setPublishingModeAsync (Client & connection, uint32_t subscriptionId, bool publishing, CompletionToken && token)
Enable/disable publishing of notification messages of a single subscription.
Parameters
connection Instance of type Client
subscriptionId Identifier of the subscription returned by createSubscription
publishing Enable/disable publishing
token
The @ref async_model "completion token" that will be used to produce a completion handler, which will be called when the operation completes.
Potential completion tokens include @ref useFuture, @ref useDeferred, @ref useDetached, or a function (object) with the correct completion signature.
The function signature of the completion handler must be:
void(StatusCode)
Returns
void if token is a callback function (object)
std::future<StatusCode> if token is of type UseFutureToken
auto(auto&& token) callable for deferred execution if token is of type UseDeferredToken
void if token is of type UseDetachedToken
Definition at line 299 of file subscription.hpp.