open62541pp: DeleteNodes service
DeleteNodes service
Services » NodeManagement service set
Detailed Description
Delete nodes from the address space.
See also
https://reference.opcfoundation.org/Core/Part4/v105/docs/5.7.4
Functions
DeleteNodesResponse opcua::services::deleteNodes (Client &connection, const DeleteNodesRequest &request) noexcept
template<typename CompletionToken >
auto opcua::services::deleteNodesAsync (Client &connection, const DeleteNodesRequest &request, CompletionToken &&token)
template<typename T >
StatusCode opcua::services::deleteNode (T &connection, const NodeId &id, bool deleteReferences) noexcept
template<typename CompletionToken >
auto opcua::services::deleteNodeAsync (Client &connection, const NodeId &id, bool deleteReferences, CompletionToken &&token)
Function Documentation
deleteNodes()
DeleteNodesResponse opcua::services::deleteNodes (Client & connection, const DeleteNodesRequest & request) noexcept
Delete one or more nodes (client only).
Parameters
connection Instance of type Client
request Delete nodes request
deleteNodesAsync()
template<typename CompletionToken > auto opcua::services::deleteNodesAsync (Client & connection, const DeleteNodesRequest & request, CompletionToken && token)
Delete one or more nodes (client only).
Parameters
connection Instance of type Client
request Delete nodes request
token
The @ref async_model "completion token" that will be used to produce a completion handler, which will be called when the operation completes.
Potential completion tokens include @ref useFuture, @ref useDeferred, @ref useDetached, or a function (object) with the correct completion signature.
The function signature of the completion handler must be:
void(DeleteNodesResponse&)
Returns
void if token is a callback function (object)
std::future<DeleteNodesResponse> if token is of type UseFutureToken
auto(auto&& token) callable for deferred execution if token is of type UseDeferredToken
void if token is of type UseDetachedToken
Definition at line 213 of file nodemanagement.hpp.
Referenced by opcua::services::deleteNodeAsync().
deleteNode()
template<typename T > StatusCode opcua::services::deleteNode (T & connection, const NodeId & id, bool deleteReferences) noexcept
Delete node.
Parameters
connection Instance of type Client (or Server)
id Node to delete
deleteReferences Delete references in target nodes that reference the node to delete
Referenced by opcua::Node< Connection >::deleteNode().
deleteNodeAsync()
template<typename CompletionToken > auto opcua::services::deleteNodeAsync (Client & connection, const NodeId & id, bool deleteReferences, CompletionToken && token)
Delete node.
Parameters
connection Instance of type Client (or Server)
id Node to delete
deleteReferences Delete references in target nodes that reference the node to delete
token
The @ref async_model "completion token" that will be used to produce a completion handler, which will be called when the operation completes.
Potential completion tokens include @ref useFuture, @ref useDeferred, @ref useDetached, or a function (object) with the correct completion signature.
The function signature of the completion handler must be:
void(StatusCode)
Returns
void if token is a callback function (object)
std::future<StatusCode> if token is of type UseFutureToken
auto(auto&& token) callable for deferred execution if token is of type UseDeferredToken
void if token is of type UseDetachedToken
Definition at line 236 of file nodemanagement.hpp.
Referenced by opcua::Node< Connection >::deleteNodeAsync().