open62541pp: opcua Namespace Reference
opcua Namespace Reference
Namespaces
namespace crypto
namespace detail
namespace services
Classes
class AccessControlBase
class AccessControlDefault
class AddNodesItem
class AddNodesRequest
class AddNodesResponse
class AddNodesResult
class AddReferencesItem
class AddReferencesRequest
class AddReferencesResponse
class AggregateFilter
class AnonymousIdentityToken
class ApplicationDescription
class Argument
struct AsyncResult
struct AsyncResult< services::detail::HookToken< HookFunction, CompletionToken >, T >
struct AsyncResult< services::detail::TransformToken< TransformFunction, CompletionToken >, T >
struct AsyncResult< UseDeferredToken, T >
struct AsyncResult< UseDetachedToken, T >
struct AsyncResult< UseFutureToken, T >
class AttributeOperand
class BadDisconnect
class BadResult
class BadStatus
class BadVariantAccess
class Bitmask
class BrowseDescription
class BrowseNextRequest
class BrowseNextResponse
class BrowsePath
class BrowsePathResult
class BrowsePathTarget
class BrowseRequest
class BrowseResponse
class BrowseResult
class BuildInfo
class ByteString
class CallMethodRequest
class CallMethodResult
class CallRequest
class CallResponse
class Client
class ClientConfig
class ContentFilter
class ContentFilterElement
class CreateCertificateError
class CreateMonitoredItemsRequest
class CreateMonitoredItemsResponse
class CreateSubscriptionRequest
class CreateSubscriptionResponse
class DataChangeFilter
class DataType
class DataTypeAttributes
class DataTypeBuilder
class DataValue
class DateTime
class DeleteMonitoredItemsRequest
class DeleteMonitoredItemsResponse
class DeleteNodesItem
class DeleteNodesRequest
class DeleteNodesResponse
class DeleteReferencesItem
class DeleteReferencesRequest
class DeleteReferencesResponse
class DeleteSubscriptionsRequest
class DeleteSubscriptionsResponse
class DiagnosticInfo
class ElementOperand
class EndpointDescription
class EnumDefinition
class EnumField
class EnumValueType
class Event
class EventFilter
class ExpandedNodeId
class ExtensionObject
class Guid
struct IsBitmaskEnum
struct IsBitmaskEnum< AccessLevel >
struct IsBitmaskEnum< BrowseResultMask >
struct IsBitmaskEnum< EventNotifier >
struct IsBitmaskEnum< NodeAttributesMask >
struct IsBitmaskEnum< NodeClass >
struct IsBitmaskEnum< WriteMask >
class IssuedIdentityToken
class LiteralOperand
class LocalizedText
class LoggerBase
class LoggerDefault
struct Login
class MethodAttributes
class ModifyMonitoredItemsRequest
class ModifyMonitoredItemsResponse
class ModifySubscriptionRequest
class ModifySubscriptionResponse
class MonitoredItem
class MonitoredItemCreateRequest
class MonitoredItemCreateResult
class MonitoredItemModifyRequest
class MonitoredItemModifyResult
class MonitoringParameters
struct Namespace
class Node
class NodeAttributes
class NodeId
class NumericRange
class ObjectAttributes
class ObjectTypeAttributes
class PluginAdapter
class QualifiedName
class ReadRequest
class ReadResponse
class ReadValueId
class ReferenceDescription
class ReferenceTypeAttributes
class RegisterNodesRequest
class RegisterNodesResponse
class RelativePath
class RelativePathElement
class RequestHeader
class ResponseHeader
class Result
class Result< void >
class Server
class ServerConfig
class Session
class SetMonitoringModeRequest
class SetMonitoringModeResponse
class SetPublishingModeRequest
class SetPublishingModeResponse
class SetTriggeringRequest
class SetTriggeringResponse
class SimpleAttributeOperand
class Span
class StatusChangeNotification
class StatusCode
class String
class StructureDefinition
class StructureField
class Subscription
class TranslateBrowsePathsToNodeIdsRequest
class TranslateBrowsePathsToNodeIdsResponse
struct TypeConverter
struct TypeConverter< char[N]>
struct TypeConverter< const char * >
struct TypeConverter< std::chrono::time_point< Clock, Duration > >
struct TypeConverter< std::string >
struct TypeConverter< std::string_view >
struct TypeRegistry
struct TypeRegistry< T, std::enable_if_t< detail::isTypeWrapper< T > > >
class TypeWrapper
class UnregisterNodesRequest
class UnregisterNodesResponse
struct UseDeferredToken
struct UseDetachedToken
struct UseFutureToken
class UserIdentityToken
class UserNameIdentityToken
class UserTokenPolicy
struct ValueBackendDataSource
struct ValueCallback
class VariableAttributes
class VariableTypeAttributes
class Variant
class ViewAttributes
class ViewDescription
class Wrapper
class WriteRequest
class WriteResponse
class WriteValue
class X509IdentityToken
class XmlElement
Typedefs
using DefaultCompletionToken = UseFutureToken
using StateCallback = std::function<void()>
using InactivityCallback = std::function<void()>
using NamespaceIndex = uint16_t
using TypeIndex = uint16_t
using DataTypeMember = UA_DataTypeMember
using MonitoringParametersEx = services::MonitoringParametersEx
using LogFunction = std::function<void(LogLevel, LogCategory, std::string_view msg)>
using SubscriptionParameters = services::SubscriptionParameters
using DataChangeNotificationCallback = services::DataChangeNotificationCallback
using EventNotificationCallback = services::EventNotificationCallback
using NumericRangeDimension = UA_NumericRangeDimension
using FilterOperand
using AggregateConfiguration = UA_AggregateConfiguration
Enumerations
enum class AttributeId : int32_t
enum class NodeClass : int32_t
enum class AccessLevel : uint8_t
enum class WriteMask : uint32_t
enum class ValueRank : int32_t
enum class EventNotifier : uint8_t
enum class ModellingRule : uint16_t
enum class BrowseDirection : int32_t
enum class TimestampsToReturn : int32_t
enum class MonitoringMode : int32_t
enum class MessageSecurityMode : int32_t
enum class DataTypeId : int32_t
enum class ReferenceTypeId : int32_t
enum class ObjectTypeId : int32_t
enum class VariableTypeId : int32_t
enum class ObjectId : int32_t
enum class VariableId : int32_t
enum class MethodId : int32_t
enum class LogLevel
enum class LogCategory
enum class NodeIdType : uint8_t
enum class VariantPolicy
enum class ExtensionObjectEncoding
enum class UserTokenType : int32_t
enum class NodeAttributesMask : uint32_t
enum class BrowseResultMask : uint32_t
enum class FilterOperator : int32_t
enum class DataChangeTrigger : int32_t
enum class DeadbandType : int32_t
enum class PerformUpdateType : int32_t
enum class StructureType : int32_t
Functions
template<typename T , typename Initiation , typename CompletionToken , typename... Args>
auto asyncInitiate (Initiation &&initiation, CompletionToken &&token, Args &&... args)
template<typename T >
constexpr std::false_type isBitmaskEnum (T)
Client * asWrapper (UA_Client *client) noexcept
bool operator== (const Client &lhs, const Client &rhs) noexcept
bool operator!= (const Client &lhs, const Client &rhs) noexcept
bool operator== (const UA_DataType &lhs, const UA_DataType &rhs) noexcept
bool operator!= (const UA_DataType &lhs, const UA_DataType &rhs) noexcept
bool operator== (const UA_DataTypeMember &lhs, const UA_DataTypeMember &rhs) noexcept
bool operator!= (const UA_DataTypeMember &lhs, const UA_DataTypeMember &rhs) noexcept
bool operator== (const Event &lhs, const Event &rhs) noexcept
bool operator!= (const Event &lhs, const Event &rhs) noexcept
constexpr void throwIfBad (UA_StatusCode code)
template<typename T >
bool operator== (const MonitoredItem< T > &lhs, const MonitoredItem< T > &rhs) noexcept
template<typename T >
bool operator!= (const MonitoredItem< T > &lhs, const MonitoredItem< T > &rhs) noexcept
template<typename Connection >
bool operator== (const Node< Connection > &lhs, const Node< Connection > &rhs) noexcept
template<typename Connection >
bool operator!= (const Node< Connection > &lhs, const Node< Connection > &rhs) noexcept
constexpr Namespace getNamespace (DataTypeId) noexcept
constexpr Namespace getNamespace (ReferenceTypeId) noexcept
constexpr Namespace getNamespace (ObjectTypeId) noexcept
constexpr Namespace getNamespace (VariableTypeId) noexcept
constexpr Namespace getNamespace (ObjectId) noexcept
constexpr Namespace getNamespace (VariableId) noexcept
constexpr Namespace getNamespace (MethodId) noexcept
Server * asWrapper (UA_Server *server) noexcept
bool operator== (const Server &lhs, const Server &rhs) noexcept
bool operator!= (const Server &lhs, const Server &rhs) noexcept
bool operator== (const Session &lhs, const Session &rhs) noexcept
bool operator!= (const Session &lhs, const Session &rhs) noexcept
template<typename Container >
Span (Container &) -> Span< typename Container::value_type >
template<typename Container >
Span (const Container &) -> Span< const typename Container::value_type >
template<typename T , typename U , typename = detail::EnableIfEqualityComparable<T, U>>
constexpr bool operator== (Span< T > lhs, Span< U > rhs)
template<typename T , typename U , typename = detail::EnableIfEqualityComparable<T, U>>
constexpr bool operator!= (Span< T > lhs, Span< U > rhs)
template<typename T >
bool operator== (const Subscription< T > &lhs, const Subscription< T > &rhs) noexcept
template<typename T >
bool operator!= (const Subscription< T > &lhs, const Subscription< T > &rhs) noexcept
template<typename T >
const UA_DataType & getDataType () noexcept
bool operator== (const UA_String &lhs, const UA_String &rhs) noexcept
bool operator!= (const UA_String &lhs, const UA_String &rhs) noexcept
bool operator== (const String &lhs, std::string_view rhs) noexcept
bool operator!= (const String &lhs, std::string_view rhs) noexcept
bool operator== (std::string_view lhs, const String &rhs) noexcept
bool operator!= (std::string_view lhs, const String &rhs) noexcept
std::ostream & operator<< (std::ostream &os, const String &str)
bool operator== (const UA_Guid &lhs, const UA_Guid &rhs) noexcept
bool operator!= (const UA_Guid &lhs, const UA_Guid &rhs) noexcept
std::ostream & operator<< (std::ostream &os, const Guid &guid)
bool operator== (const ByteString &lhs, std::string_view rhs) noexcept
bool operator!= (const ByteString &lhs, std::string_view rhs) noexcept
bool operator== (std::string_view lhs, const ByteString &rhs) noexcept
bool operator!= (std::string_view lhs, const ByteString &rhs) noexcept
std::ostream & operator<< (std::ostream &os, const XmlElement &xmlElement)
bool operator== (const UA_NodeId &lhs, const UA_NodeId &rhs) noexcept
bool operator!= (const UA_NodeId &lhs, const UA_NodeId &rhs) noexcept
bool operator< (const UA_NodeId &lhs, const UA_NodeId &rhs) noexcept
bool operator> (const UA_NodeId &lhs, const UA_NodeId &rhs) noexcept
bool operator<= (const UA_NodeId &lhs, const UA_NodeId &rhs) noexcept
bool operator>= (const UA_NodeId &lhs, const UA_NodeId &rhs) noexcept
bool operator== (const UA_ExpandedNodeId &lhs, const UA_ExpandedNodeId &rhs) noexcept
bool operator!= (const UA_ExpandedNodeId &lhs, const UA_ExpandedNodeId &rhs) noexcept
bool operator< (const UA_ExpandedNodeId &lhs, const UA_ExpandedNodeId &rhs) noexcept
bool operator> (const UA_ExpandedNodeId &lhs, const UA_ExpandedNodeId &rhs) noexcept
bool operator<= (const UA_ExpandedNodeId &lhs, const UA_ExpandedNodeId &rhs) noexcept
bool operator>= (const UA_ExpandedNodeId &lhs, const UA_ExpandedNodeId &rhs) noexcept
bool operator== (const UA_QualifiedName &lhs, const UA_QualifiedName &rhs) noexcept
bool operator!= (const UA_QualifiedName &lhs, const UA_QualifiedName &rhs) noexcept
bool operator== (const UA_LocalizedText &lhs, const UA_LocalizedText &rhs) noexcept
bool operator!= (const UA_LocalizedText &lhs, const UA_LocalizedText &rhs) noexcept
bool operator== (const NumericRangeDimension &lhs, const NumericRangeDimension &rhs) noexcept
bool operator!= (const NumericRangeDimension &lhs, const NumericRangeDimension &rhs) noexcept
ContentFilter operator! (const ContentFilterElement &filterElement)
ContentFilter operator! (const ContentFilter &filter)
ContentFilter operator&& (const ContentFilterElement &lhs, const ContentFilterElement &rhs)
ContentFilter operator&& (const ContentFilterElement &lhs, const ContentFilter &rhs)
ContentFilter operator&& (const ContentFilter &lhs, const ContentFilterElement &rhs)
ContentFilter operator&& (const ContentFilter &lhs, const ContentFilter &rhs)
ContentFilter operator|| (const ContentFilterElement &lhs, const ContentFilterElement &rhs)
ContentFilter operator|| (const ContentFilterElement &lhs, const ContentFilter &rhs)
ContentFilter operator|| (const ContentFilter &lhs, const ContentFilterElement &rhs)
ContentFilter operator|| (const ContentFilter &lhs, const ContentFilter &rhs)
template<typename WrapperType , typename NativeType = typename WrapperType::NativeType>
constexpr WrapperType * asWrapper (NativeType *native) noexcept
template<typename WrapperType , typename NativeType = typename WrapperType::NativeType>
constexpr const WrapperType * asWrapper (const NativeType *native) noexcept
template<typename WrapperType , typename NativeType = typename WrapperType::NativeType>
constexpr WrapperType & asWrapper (NativeType &native) noexcept
template<typename WrapperType , typename NativeType = typename WrapperType::NativeType>
constexpr const WrapperType & asWrapper (const NativeType &native) noexcept
template<typename WrapperType , typename NativeType = typename WrapperType::NativeType>
constexpr NativeType * asNative (WrapperType *wrapper) noexcept
template<typename WrapperType , typename NativeType = typename WrapperType::NativeType>
constexpr const NativeType * asNative (const WrapperType *wrapper) noexcept
template<typename WrapperType , typename NativeType = typename WrapperType::NativeType>
constexpr NativeType & asNative (WrapperType &wrapper) noexcept
template<typename WrapperType , typename NativeType = typename WrapperType::NativeType>
constexpr const NativeType & asNative (const WrapperType &wrapper) noexcept
Variables
constexpr UseFutureToken useFuture
constexpr UseDeferredToken useDeferred
constexpr UseDetachedToken useDetached
Typedef Documentation
StateCallback
using opcua::StateCallback = std::function<void()>
Definition at line 101 of file client.hpp.
InactivityCallback
using opcua::InactivityCallback = std::function<void()>
Definition at line 102 of file client.hpp.
NamespaceIndex
using opcua::NamespaceIndex = uint16_t
Namespace index.
See also
https://reference.opcfoundation.org/Core/Part3/v105/docs/8.2.2
Definition at line 12 of file common.hpp.
TypeIndex
using opcua::TypeIndex = uint16_t
Type index of the UA_TYPES array.
Definition at line 21 of file common.hpp.
DataTypeMember
using opcua::DataTypeMember = UA_DataTypeMember
Definition at line 22 of file datatype.hpp.
MonitoringParametersEx
typedef services::MonitoringParametersEx opcua::MonitoringParametersEx = services::MonitoringParametersEx
Definition at line 17 of file monitoreditem.hpp.
LogFunction
using opcua::LogFunction = std::function<void(LogLevel, LogCategory, std::string_view msg)>
Log function.
Definition at line 11 of file log_default.hpp.
SubscriptionParameters
using opcua::SubscriptionParameters = services::SubscriptionParameters
Definition at line 22 of file subscription.hpp.
DataChangeNotificationCallback
using opcua::DataChangeNotificationCallback = services::DataChangeNotificationCallback
Definition at line 24 of file subscription.hpp.
EventNotificationCallback
using opcua::EventNotificationCallback = services::EventNotificationCallback
Definition at line 25 of file subscription.hpp.
NumericRangeDimension
using opcua::NumericRangeDimension = UA_NumericRangeDimension
Definition at line 1872 of file types.hpp.
Enumeration Type Documentation
AttributeId
enum class opcua::AttributeId : int32_t strong
Attribute identifiers.
See also
UA_AttributeId
https://reference.opcfoundation.org/Core/Part3/v105/docs/5.9
Enumerator
NodeId
Unambiguous identifier of a node.
NodeClass
Identifies the class of the node.
BrowseName
A non-localised human-readable name used to browse the address space.
The browse name of a reference type must be unique in a server.
DisplayName
The localized name of the node.
Description
Explains the meaning of the node in a localized text.
WriteMask
Exposes the possibilities of a client to write the attributes of the node.
UserWriteMask
Exposes the possibilities of a client to write the attributes of the node.
In contrast to the write mask, the user write mask is taking access rights into account.
IsAbstract
If a reference is abstract, no reference of this type shall exist, only of its subtypes.
Symmetric
If a reference is symmetric, it can seen from both the source and target node.
InverseName
The inverse name describes the reference type as seen from the target node.
For example, the reference type HasSubtype has the inverse name HasSupertype.
ContainsNoLoops
Indicates that by following the references in the context of the view there are no loops.
EventNotifier
Indicates if the node can be used to subscribe to events or the read/write historic events.
Value
The most recent value of the variable that the server has.
DataType
The NodeId of the data type definition for the Value attribute.
ValueRank
Indicates whether the Value attribute of the variable node is an array and how many dimensions the array has.
See also
ValueRank
ArrayDimensions
Specifies the maximum supported length of each dimension of the Value attribute.
Should be unspecified if ValueRank <= 0 (ValueRank::Any, ValueRank::Scalar, ValueRank::ScalarOrOneDimension, ValueRank::OneOrMoreDimensions). The dimension 0 is a wildcard and the actual value may have any length in this dimension.
AccessLevel
Indicate how the value of a variable can be accessed (read/write) and if it contains current and/or historic data.
UserAccessLevel
Indicates how the value of a variable can be accessed (read/write) and if it contains current and/or historic data.
In contrast to the AccessLevel, the UserAccessLevel is taking access rights into account.
MinimumSamplingInterval
Specifies (in milliseconds) how fast the server can reasonably sample the value for changes.
A minimum sampling interval of 0 indicates that the server is to monitor the item continuously. A minimum sampling interval of -1 means indeterminate.
Historizing
Indicates whether the server is actively collecting data for the history of the variable.
Executable
Indicates if the method is currently executable.
UserExecutable
Indicates if the method is currently executable taking user access rights into account.
DataTypeDefinition
Provides the meta data and encoding information for custom data types.
See also
https://reference.opcfoundation.org/Core/Part3/v105/docs/5.8.3
RolePermissions
Permissions that apply to a node.
See also
https://reference.opcfoundation.org/Core/Part3/v105/docs/5.2.9
UserRolePermissions
Specifies the permissions that apply to a node for all roles granted to current session.
See also
https://reference.opcfoundation.org/Core/Part3/v105/docs/5.2.10
AccessRestrictions
Specifies access restrictions that apply to a node.
See also
https://reference.opcfoundation.org/Core/Part3/v105/docs/5.2.11
AccessLevelEx
Extended version of the AccessLevel attribute.
See also
https://reference.opcfoundation.org/Core/Part3/v104/docs/8.58
Definition at line 28 of file common.hpp.
NodeClass
enum class opcua::NodeClass : int32_t strong
Node class.
The enum can be used as a bitmask and allows bitwise operations, e.g.:
auto mask = NodeClass::Object | NodeClass::Variable;
See also
UA_NodeClass
https://reference.opcfoundation.org/Core/Part3/v105/docs/8.29
Enumerator
Unspecified
Object
Variable
Method
ObjectType
VariableType
ReferenceType
DataType
View
Definition at line 138 of file common.hpp.
AccessLevel
enum class opcua::AccessLevel : uint8_t strong
Access level.
Indicates how the value of an variable can be accessed (read/write) and if it contains current and/or historic data.
See also
https://reference.opcfoundation.org/Core/Part3/v104/docs/8.57
Enumerator
None
CurrentRead
CurrentWrite
HistoryRead
HistoryWrite
SemanticChange
StatusWrite
TimestampWrite
Definition at line 161 of file common.hpp.
WriteMask
enum class opcua::WriteMask : uint32_t strong
Write mask.
Indicates which attributes of a node a writeable.
See also
https://reference.opcfoundation.org/Core/Part3/v105/docs/5.2.7
https://reference.opcfoundation.org/Core/Part3/v105/docs/8.60
Enumerator
None
AccessLevel
ArrayDimensions
BrowseName
ContainsNoLoops
DataType
Description
DisplayName
EventNotifier
Executable
Historizing
InverseName
IsAbstract
MinimumSamplingInterval
NodeClass
NodeId
Symmetric
UserAccessLevel
UserExecutable
UserWriteMask
ValueRank
WriteMask
ValueForVariableType
DataTypeDefinition
RolePermissions
AccessRestrictions
AccessLevelEx
Definition at line 183 of file common.hpp.
ValueRank
enum class opcua::ValueRank : int32_t strong
Value rank.
Indicates whether the value attribute of the variable is an array and how many dimensions the array has.
See also
https://reference.opcfoundation.org/Core/Part3/v105/docs/5.6.2
Enumerator
ScalarOrOneDimension
Any
Scalar
OneOrMoreDimensions
OneDimension
TwoDimensions
ThreeDimensions
Definition at line 224 of file common.hpp.
EventNotifier
enum class opcua::EventNotifier : uint8_t strong
Event notifier.
Indicates if a node can be used to subscribe to events or read/write historic events.
See also
https://reference.opcfoundation.org/Core/Part3/v105/docs/8.59
Enumerator
None
SubscribeToEvents
HistoryRead
HistoryWrite
Definition at line 241 of file common.hpp.
ModellingRule
enum class opcua::ModellingRule : uint16_t strong
Modelling rules.
See also
https://reference.opcfoundation.org/Core/Part3/v105/docs/6.4.4
Enumerator
Mandatory
Optional
ExposesItsArray
OptionalPlaceholder
MandatoryPlaceholder
Definition at line 257 of file common.hpp.
BrowseDirection
enum class opcua::BrowseDirection : int32_t strong
Browse direction.
An enumeration that specifies the direction of references to follow.
See also
UA_BrowseDirection
https://reference.opcfoundation.org/Core/Part4/v105/docs/7.5
Enumerator
Forward
Inverse
Both
Invalid
Definition at line 273 of file common.hpp.
TimestampsToReturn
enum class opcua::TimestampsToReturn : int32_t strong
Timestamps to return.
See also
UA_TimestampsToReturn
https://reference.opcfoundation.org/Core/Part4/v105/docs/7.40
Enumerator
Source
Server
Both
Neither
Invalid
Definition at line 287 of file common.hpp.
MonitoringMode
enum class opcua::MonitoringMode : int32_t strong
Monitoring mode.
See also
UA_MonitoringMode
https://reference.opcfoundation.org/Core/Part4/v105/docs/7.23
Enumerator
Disabled
Sampling
Reporting
Definition at line 302 of file common.hpp.
MessageSecurityMode
enum class opcua::MessageSecurityMode : int32_t strong
Message security mode.
See also
UA_MessageSecurityMode
https://reference.opcfoundation.org/Core/Part4/v105/docs/7.20
Enumerator
Invalid
Will always be rejected.
None
No security applied.
Sign
All messages are signed but not encrypted.
SignAndEncrypt
All messages are signed and encrypted.
Definition at line 315 of file common.hpp.
LogLevel
enum class opcua::LogLevel strong
Log level.
See also
UA_LogLevel
Enumerator
Trace
Debug
Info
Warning
Error
Fatal
Definition at line 14 of file log.hpp.
LogCategory
enum class opcua::LogCategory strong
Log category.
See also
UA_LogCategory
Enumerator
Network
SecureChannel
Session
Server
Client
Userland
SecurityPolicy
Definition at line 27 of file log.hpp.
NodeIdType
enum class opcua::NodeIdType : uint8_t strong
NodeId types.
See also
UA_NodeIdType
Enumerator
Numeric
String
Guid
ByteString
Definition at line 578 of file types.hpp.
VariantPolicy
enum class opcua::VariantPolicy strong
Policies for variant factory methods Variant::fromScalar, Variant::fromArray.
Enumerator
Copy
Store copy of scalar/array inside the variant.
Reference
Store reference to scalar/array inside the variant.
Both scalars and arrays must be mutable native/wrapper types. Arrays must store the elements contiguously in memory.
ReferenceIfPossible
Favor referencing but fall back to copying if necessary.
Definition at line 868 of file types.hpp.
ExtensionObjectEncoding
enum class opcua::ExtensionObjectEncoding strong
Extension object encoding.
See also
UA_ExtensionObjectEncoding
Enumerator
EncodedNoBody
EncodedByteString
EncodedXml
Decoded
DecodedNoDelete
Definition at line 1643 of file types.hpp.
Function Documentation
asWrapper() [1/2]
Client * opcua::asWrapper (UA_Client * client) noexcept
Convert native UA_Client pointer to its wrapper instance.
The native client must be owned by a Client instance.
Referenced by opcua::services::addNodeAsync(), opcua::services::addReferenceAsync(), opcua::services::browseAsync(), opcua::services::browseNextAsync(), opcua::services::callAsync(), opcua::services::createMonitoredItemDataChangeAsync(), opcua::services::createMonitoredItemEventAsync(), opcua::services::detail::MonitoredItemContext::dataChangeCallbackNativeClient(), opcua::services::detail::MonitoredItemContext::dataChangeCallbackNativeServer(), opcua::services::deleteMonitoredItemAsync(), opcua::services::deleteNodeAsync(), opcua::services::deleteReferenceAsync(), opcua::services::detail::MonitoredItemContext::eventCallbackNative(), opcua::ExpandedNodeId::ExpandedNodeId(), opcua::ExpandedNodeId::ExpandedNodeId(), opcua::DiagnosticInfo::getAdditionalInfo(), opcua::ExtensionObject::getEncodedBody(), opcua::ExtensionObject::getEncodedTypeId(), opcua::DiagnosticInfo::getInnerDiagnosticInfo(), opcua::ExpandedNodeId::getNodeId(), opcua::ExpandedNodeId::getNodeId(), opcua::services::detail::getSingleStatus(), opcua::DataValue::getValue(), opcua::DataValue::getValue(), opcua::DataValue::getValue(), opcua::DataValue::getValue(), opcua::services::modifyMonitoredItem(), opcua::services::modifyMonitoredItemAsync(), opcua::services::readAttributeAsync(), opcua::DataType::setBinaryEncodingId(), opcua::services::setMonitoringMode(), opcua::services::setMonitoringModeAsync(), opcua::DataType::setTypeId(), opcua::DataValue::setValue(), opcua::DataValue::setValue(), opcua::services::detail::SubscriptionContext::statusChangeCallbackNative(), opcua::detail::toNative(), opcua::services::translateBrowsePathToNodeIdsAsync(), opcua::services::writeAttributeAsync(), and opcua::Node< Connection >::writeDataType().
operator==() [1/21]
bool opcua::operator== (const Client & lhs, const Client & rhs) inline noexcept
Definition at line 291 of file client.hpp.
operator!=() [1/21]
bool opcua::operator!= (const Client & lhs, const Client & rhs) inline noexcept
Definition at line 295 of file client.hpp.
operator==() [2/21]
bool opcua::operator== (const UA_DataType & lhs, const UA_DataType & rhs) inline noexcept
Definition at line 120 of file datatype.hpp.
operator!=() [2/21]
bool opcua::operator!= (const UA_DataType & lhs, const UA_DataType & rhs) inline noexcept
Definition at line 124 of file datatype.hpp.
operator==() [3/21]
bool opcua::operator== (const UA_DataTypeMember & lhs, const UA_DataTypeMember & rhs) inline noexcept
Definition at line 128 of file datatype.hpp.
operator!=() [3/21]
bool opcua::operator!= (const UA_DataTypeMember & lhs, const UA_DataTypeMember & rhs) inline noexcept
Definition at line 139 of file datatype.hpp.
operator==() [4/21]
bool opcua::operator== (const Event & lhs, const Event & rhs) noexcept
operator!=() [4/21]
bool opcua::operator!= (const Event & lhs, const Event & rhs) noexcept
throwIfBad()
void opcua::throwIfBad (UA_StatusCode code) constexpr
Check the status code and throw a BadStatus exception if the status code is bad.
Definition at line 87 of file exception.hpp.
Referenced by opcua::detail::copy(), opcua::services::createMonitoredItemsDataChangeAsync(), opcua::services::createMonitoredItemsEventAsync(), opcua::services::deleteMonitoredItemsAsync(), opcua::services::deleteSubscriptionsAsync(), opcua::ExtensionObject::fromDecodedCopy(), opcua::services::modifyMonitoredItemsAsync(), opcua::services::modifySubscriptionAsync(), opcua::services::detail::sendRequestAsync(), and opcua::StatusCode::throwIfBad().
operator==() [5/21]
template<typename T > bool opcua::operator== (const MonitoredItem< T > & lhs, const MonitoredItem< T > & rhs) inline noexcept
Definition at line 101 of file monitoreditem.hpp.
operator!=() [5/21]
template<typename T > bool opcua::operator!= (const MonitoredItem< T > & lhs, const MonitoredItem< T > & rhs) inline noexcept
Definition at line 108 of file monitoreditem.hpp.
operator==() [6/21]
template<typename Connection > bool opcua::operator== (const Node< Connection > & lhs, const Node< Connection > & rhs) noexcept
Definition at line 1394 of file node.hpp.
operator!=() [6/21]
template<typename Connection > bool opcua::operator!= (const Node< Connection > & lhs, const Node< Connection > & rhs) noexcept
Definition at line 1399 of file node.hpp.
asWrapper() [2/2]
Server * opcua::asWrapper (UA_Server * server) noexcept
Convert native UA_Server pointer to its wrapper instance.
The native server must be owned by a Server instance.
operator==() [7/21]
bool opcua::operator== (const Server & lhs, const Server & rhs) inline noexcept
Definition at line 276 of file server.hpp.
operator!=() [7/21]
bool opcua::operator!= (const Server & lhs, const Server & rhs) inline noexcept
Definition at line 280 of file server.hpp.
operator==() [8/21]
bool opcua::operator== (const Session & lhs, const Session & rhs) noexcept
operator!=() [8/21]
bool opcua::operator!= (const Session & lhs, const Session & rhs) noexcept
Span() [1/2]
template<typename Container > opcua::Span (Container &) -> Span< typename Container::value_type >
Examples
custom_datatypes/client_custom_datatypes.cpp.
Referenced by opcua::Variant::getArray(), and opcua::Variant::getArray().
Span() [2/2]
template<typename Container > opcua::Span (const Container &) -> Span< const typename Container::value_type >
operator==() [9/21]
template<typename T , typename U , typename = detail::EnableIfEqualityComparable<T, U>> bool opcua::operator== (Span< T > lhs, Span< U > rhs) constexpr
Definition at line 226 of file span.hpp.
operator!=() [9/21]
template<typename T , typename U , typename = detail::EnableIfEqualityComparable<T, U>> bool opcua::operator!= (Span< T > lhs, Span< U > rhs) constexpr
Definition at line 231 of file span.hpp.
operator==() [10/21]
template<typename T > bool opcua::operator== (const Subscription< T > & lhs, const Subscription< T > & rhs) inline noexcept
Definition at line 165 of file subscription.hpp.
operator!=() [10/21]
template<typename T > bool opcua::operator!= (const Subscription< T > & lhs, const Subscription< T > & rhs) inline noexcept
Definition at line 170 of file subscription.hpp.
getDataType()
template<typename T > const UA_DataType & opcua::getDataType () noexcept
Definition at line 46 of file typeregistry.hpp.
Referenced by opcua::ExtensionObject::fromDecoded(), opcua::ExtensionObject::fromDecodedCopy(), opcua::detail::getMemberDataType(), opcua::Variant::isType(), opcua::Variant::setArray(), opcua::Variant::setArrayCopy(), opcua::VariableAttributes::setDataType(), opcua::VariableTypeAttributes::setDataType(), opcua::Variant::setScalar(), opcua::Variant::setScalarCopy(), opcua::detail::toNativeArray(), and opcua::Node< Connection >::writeDataType().
operator==() [11/21]
bool opcua::operator== (const UA_String & lhs, const UA_String & rhs) inline noexcept
Definition at line 269 of file types.hpp.
operator!=() [11/21]
bool opcua::operator!= (const UA_String & lhs, const UA_String & rhs) inline noexcept
Definition at line 273 of file types.hpp.
operator==() [12/21]
bool opcua::operator== (const String & lhs, std::string_view rhs) inline noexcept
Definition at line 277 of file types.hpp.
operator!=() [12/21]
bool opcua::operator!= (const String & lhs, std::string_view rhs) inline noexcept
Definition at line 281 of file types.hpp.
operator==() [13/21]
bool opcua::operator== (std::string_view lhs, const String & rhs) inline noexcept
Definition at line 285 of file types.hpp.
operator!=() [13/21]
bool opcua::operator!= (std::string_view lhs, const String & rhs) inline noexcept
Definition at line 289 of file types.hpp.
operator<<() [1/3]
std::ostream & opcua::operator<< (std::ostream & os, const String & str)
operator==() [14/21]
bool opcua::operator== (const UA_Guid & lhs, const UA_Guid & rhs) inline noexcept
Definition at line 474 of file types.hpp.
operator!=() [14/21]
bool opcua::operator!= (const UA_Guid & lhs, const UA_Guid & rhs) inline noexcept
Definition at line 478 of file types.hpp.
operator<<() [2/3]
std::ostream & opcua::operator<< (std::ostream & os, const Guid & guid)
operator==() [15/21]
bool opcua::operator== (const ByteString & lhs, std::string_view rhs) inline noexcept
Definition at line 522 of file types.hpp.
operator!=() [15/21]
bool opcua::operator!= (const ByteString & lhs, std::string_view rhs) inline noexcept
Definition at line 526 of file types.hpp.
operator==() [16/21]
bool opcua::operator== (std::string_view lhs, const ByteString & rhs) inline noexcept
Definition at line 530 of file types.hpp.
operator!=() [16/21]
bool opcua::operator!= (std::string_view lhs, const ByteString & rhs) inline noexcept
Definition at line 534 of file types.hpp.
operator<<() [3/3]
std::ostream & opcua::operator<< (std::ostream & os, const XmlElement & xmlElement)
operator==() [17/21]
bool opcua::operator== (const UA_NodeId & lhs, const UA_NodeId & rhs) inline noexcept
Definition at line 696 of file types.hpp.
operator!=() [17/21]
bool opcua::operator!= (const UA_NodeId & lhs, const UA_NodeId & rhs) inline noexcept
Definition at line 700 of file types.hpp.
operator<() [1/2]
bool opcua::operator< (const UA_NodeId & lhs, const UA_NodeId & rhs) inline noexcept
Definition at line 704 of file types.hpp.
operator>() [1/2]
bool opcua::operator> (const UA_NodeId & lhs, const UA_NodeId & rhs) inline noexcept
Definition at line 708 of file types.hpp.
operator<=() [1/2]
bool opcua::operator<= (const UA_NodeId & lhs, const UA_NodeId & rhs) inline noexcept
Definition at line 712 of file types.hpp.
operator>=() [1/2]
bool opcua::operator>= (const UA_NodeId & lhs, const UA_NodeId & rhs) inline noexcept
Definition at line 716 of file types.hpp.
operator==() [18/21]
bool opcua::operator== (const UA_ExpandedNodeId & lhs, const UA_ExpandedNodeId & rhs) inline noexcept
Definition at line 770 of file types.hpp.
operator!=() [18/21]
bool opcua::operator!= (const UA_ExpandedNodeId & lhs, const UA_ExpandedNodeId & rhs) inline noexcept
Definition at line 774 of file types.hpp.
operator<() [2/2]
bool opcua::operator< (const UA_ExpandedNodeId & lhs, const UA_ExpandedNodeId & rhs) inline noexcept
Definition at line 778 of file types.hpp.
operator>() [2/2]
bool opcua::operator> (const UA_ExpandedNodeId & lhs, const UA_ExpandedNodeId & rhs) inline noexcept
Definition at line 782 of file types.hpp.
operator<=() [2/2]
bool opcua::operator<= (const UA_ExpandedNodeId & lhs, const UA_ExpandedNodeId & rhs) inline noexcept
Definition at line 786 of file types.hpp.
operator>=() [2/2]
bool opcua::operator>= (const UA_ExpandedNodeId & lhs, const UA_ExpandedNodeId & rhs) inline noexcept
Definition at line 790 of file types.hpp.
operator==() [19/21]
bool opcua::operator== (const UA_QualifiedName & lhs, const UA_QualifiedName & rhs) inline noexcept
Definition at line 818 of file types.hpp.
operator!=() [19/21]
bool opcua::operator!= (const UA_QualifiedName & lhs, const UA_QualifiedName & rhs) inline noexcept
Definition at line 822 of file types.hpp.
operator==() [20/21]
bool opcua::operator== (const UA_LocalizedText & lhs, const UA_LocalizedText & rhs) inline noexcept
Definition at line 855 of file types.hpp.
operator!=() [20/21]
bool opcua::operator!= (const UA_LocalizedText & lhs, const UA_LocalizedText & rhs) inline noexcept
Definition at line 859 of file types.hpp.
operator==() [21/21]
bool opcua::operator== (const NumericRangeDimension & lhs, const NumericRangeDimension & rhs) inline noexcept
Definition at line 1874 of file types.hpp.
operator!=() [21/21]
bool opcua::operator!= (const NumericRangeDimension & lhs, const NumericRangeDimension & rhs) inline noexcept
Definition at line 1880 of file types.hpp.