open62541++: opcua::services Namespace Reference
opcua::services Namespace Reference
Functions
template<typename T >
DataValue readAttribute (T &serverOrClient, const NodeId &id, UA_AttributeId attributeId, UA_TimestampsToReturn timestamps=UA_TIMESTAMPSTORETURN_NEITHER)
Generic function to read node attributes.
template<typename AttributeType , typename T >
auto readAttributeScalar (T &serverOrClient, const NodeId &id, UA_AttributeId attributeId)
Helper function to read scalar node attributes.
template<typename T >
void writeAttribute (T &serverOrClient, const NodeId &id, UA_AttributeId attributeId, const DataValue &value)
Generic function to write node attributes.
template<typename T >
NodeId readNodeId (T &serverOrClient, const NodeId &id)
Read the NodeId attribute of a node.
template<typename T >
NodeClass readNodeClass (T &serverOrClient, const NodeId &id)
Read the NodeClass attribute of a node.
template<typename T >
QualifiedName readBrowseName (T &serverOrClient, const NodeId &id)
Read the BrowseName attribute of a node.
template<typename T >
LocalizedText readDisplayName (T &serverOrClient, const NodeId &id)
Read the DisplayName attribute of a node.
template<typename T >
LocalizedText readDescription (T &serverOrClient, const NodeId &id)
Read the Description attribute of a node.
template<typename T >
uint32_t readWriteMask (T &serverOrClient, const NodeId &id)
Read the WriteMask attribute of a node.
template<typename T >
uint32_t readUserWriteMask (T &serverOrClient, const NodeId &id)
Read the UserWriteMask attribute of a node.
template<typename T >
bool readIsAbstract (T &serverOrClient, const NodeId &id)
Read the IsAbtract attribute of a reference type node.
template<typename T >
bool readSymmetric (T &serverOrClient, const NodeId &id)
Read the Symmetric attribute of a reference type node.
template<typename T >
LocalizedText readInverseName (T &serverOrClient, const NodeId &id)
Read the InverseName attribute of a reference type node.
template<typename T >
void readDataValue (T &serverOrClient, const NodeId &id, DataValue &value)
Read the Value attribute of a variable node as a DataValue object.
template<typename T >
void readValue (T &serverOrClient, const NodeId &id, Variant &value)
Read the Value attribute of a variable node as a Variant object.
template<typename T >
NodeId readDataType (T &serverOrClient, const NodeId &id)
Read the DataType attribute of a variable (type) node as NodeId.
template<typename T >
ValueRank readValueRank (T &serverOrClient, const NodeId &id)
Read the ValueRank attribute of a variable (type) node.
template<typename T >
std::vector< uint32_t > readArrayDimensions (T &serverOrClient, const NodeId &id)
Read the ArrayDimensions attribute of a variable (type) node.
template<typename T >
uint8_t readAccessLevel (T &serverOrClient, const NodeId &id)
Read the AccessLevel attribute of a variable node.
template<typename T >
uint8_t readUserAccessLevel (T &serverOrClient, const NodeId &id)
Read the UserAccessLevel attribute a variable node.
template<typename T >
double readMinimumSamplingInterval (T &serverOrClient, const NodeId &id)
Read the MinimumSamplingInterval attribute of a variable node.
template<typename T >
void writeDisplayName (T &serverOrClient, const NodeId &id, const LocalizedText &name)
Write the DisplayName attribute of a node.
template<typename T >
void writeDescription (T &serverOrClient, const NodeId &id, const LocalizedText &desc)
Write the Description attribute of a node.
template<typename T >
void writeWriteMask (T &serverOrClient, const NodeId &id, uint32_t mask)
Write the WriteMask attribute of a node.
template<typename T >
void writeUserWriteMask (T &serverOrClient, const NodeId &id, uint32_t mask)
Write the UserWriteMask attribute of a node.
template<typename T >
void writeIsAbstract (T &serverOrClient, const NodeId &id, bool isAbstract)
Write the IsAbstract attribute of a reference type node.
template<typename T >
void writeSymmetric (T &serverOrClient, const NodeId &id, bool symmetric)
Write the Symmetric attribute of a reference type node.
template<typename T >
void writeInverseName (T &serverOrClient, const NodeId &id, const LocalizedText &name)
Write the InverseName of a reference type node.
template<typename T >
void writeDataValue (T &serverOrClient, const NodeId &id, const DataValue &value)
Write the Value attribute of a variable node as a DataValue object.
template<typename T >
void writeValue (T &serverOrClient, const NodeId &id, const Variant &value)
Write the Value attribute of a variable node as a Variant object.
template<typename T >
void writeDataType (T &serverOrClient, const NodeId &id, Type type)
Write the DataType attribute of a variable (type) node.
template<typename T >
void writeDataType (T &serverOrClient, const NodeId &id, const NodeId &typeId)
Write the DataType attribute of a variable (type) node by node id.
template<typename T >
void writeValueRank (T &serverOrClient, const NodeId &id, ValueRank valueRank)
Write the ValueRank attribute of a variable (type) node.
template<typename T >
void writeArrayDimensions (T &serverOrClient, const NodeId &id, const std::vector< uint32_t > &dimensions)
Write the ArrayDimensions attribute of variable (type) node.
template<typename T >
void writeAccessLevel (T &serverOrClient, const NodeId &id, uint8_t mask)
Write the AccessLevel attribute of variable node.
template<typename T >
void writeUserAccessLevel (T &serverOrClient, const NodeId &id, uint8_t mask)
Write the UserAccessLevel attribute of variable node.
template<typename T >
void writeMinimumSamplingInterval (T &serverOrClient, const NodeId &id, double milliseconds)
Write the MinimumSamplingInterval attribute of a variable node.
template<typename T >
void addObject (T &serverOrClient, const NodeId &parentId, const NodeId &id, std::string_view browseName, const NodeId &objectType=ObjectTypeId::BaseObjectType, const NodeId &referenceType=ReferenceTypeId::HasComponent)
Add child object.
template<typename T >
void addFolder (T &serverOrClient, const NodeId &parentId, const NodeId &id, std::string_view browseName, const NodeId &referenceType=ReferenceTypeId::HasComponent)
Add child folder.
template<typename T >
void addVariable (T &serverOrClient, const NodeId &parentId, const NodeId &id, std::string_view browseName, const NodeId &variableType=VariableTypeId::BaseDataVariableType, const NodeId &referenceType=ReferenceTypeId::HasComponent)
Add child variable.
template<typename T >
void addProperty (T &serverOrClient, const NodeId &parentId, const NodeId &id, std::string_view browseName)
Add child property.
template<typename T >
void addObjectType (T &serverOrClient, const NodeId &parentId, const NodeId &id, std::string_view browseName, const NodeId &referenceType=ReferenceTypeId::HasSubtype)
Add child object type.
template<typename T >
void addVariableType (T &serverOrClient, const NodeId &parentId, const NodeId &id, std::string_view browseName, const NodeId &variableType=VariableTypeId::BaseDataVariableType, const NodeId &referenceType=ReferenceTypeId::HasSubtype)
Add child variable type.
template<typename T >
void addReference (T &serverOrClient, const NodeId &sourceId, const NodeId &targetId, const NodeId &referenceType, bool forward=true)
Add reference.
template<typename T >
void addModellingRule (T &serverOrClient, const NodeId &id, ModellingRule rule)
Add modelling rule.
template<typename T >
void deleteNode (T &serverOrClient, const NodeId &id, bool deleteReferences=true)
Delete node.
template<typename T >
BrowseResult browse (T &serverOrClient, const BrowseDescription &bd, uint32_t maxReferences=0)
Discover the references of a specified node.
template<typename T >
BrowseResult browseNext (T &serverOrClient, bool releaseContinuationPoint, const ByteString &continuationPoint)
Request the next set of a browse or browseNext response.
template<typename T >
std::vector< ReferenceDescription > browseAll (T &serverOrClient, const BrowseDescription &bd, uint32_t maxReferences=0)
Discover all the references of a specified node (without calling browseNext).
template<typename T >
BrowsePathResult translateBrowsePathToNodeIds (T &serverOrClient, const BrowsePath &browsePath)
Translate a browse path to NodeIds.
template<typename T >
BrowsePathResult browseSimplifiedBrowsePath (T &serverOrClient, const NodeId &origin, const std::vector< QualifiedName > &browsePath)
A simplified version of translateBrowsePathToNodeIds.
template<>
DataValue readAttribute< Server > (Server &server, const NodeId &id, UA_AttributeId attributeId, UA_TimestampsToReturn timestamps)
template<>
DataValue readAttribute< Client > (Client &client, const NodeId &id, UA_AttributeId attributeId, UA_TimestampsToReturn timestamps)
template<>
void writeAttribute< Server > (Server &server, const NodeId &id, UA_AttributeId attributeId, const DataValue &value)
template<>
void writeAttribute< Client > (Client &client, const NodeId &id, UA_AttributeId attributeId, const DataValue &value)
template<>
void addObject< Server > (Server &server, const NodeId &parentId, const NodeId &id, std::string_view browseName, const NodeId &objectType, const NodeId &referenceType)
template<>
void addObject< Client > (Client &client, const NodeId &parentId, const NodeId &id, std::string_view browseName, const NodeId &objectType, const NodeId &referenceType)
template<>
void addVariable< Server > (Server &server, const NodeId &parentId, const NodeId &id, std::string_view browseName, const NodeId &variableType, const NodeId &referenceType)
template<>
void addVariable< Client > (Client &client, const NodeId &parentId, const NodeId &id, std::string_view browseName, const NodeId &variableType, const NodeId &referenceType)
template<>
void addObjectType< Server > (Server &server, const NodeId &parentId, const NodeId &id, std::string_view browseName, const NodeId &referenceType)
template<>
void addObjectType< Client > (Client &client, const NodeId &parentId, const NodeId &id, std::string_view browseName, const NodeId &referenceType)
template<>
void addVariableType< Server > (Server &server, const NodeId &parentId, const NodeId &id, std::string_view browseName, const NodeId &variableType, const NodeId &referenceType)
template<>
void addVariableType< Client > (Client &client, const NodeId &parentId, const NodeId &id, std::string_view browseName, const NodeId &variableType, const NodeId &referenceType)
template<>
void addReference< Server > (Server &server, const NodeId &sourceId, const NodeId &targetId, const NodeId &referenceType, bool forward)
template<>
void addReference< Client > (Client &client, const NodeId &sourceId, const NodeId &targetId, const NodeId &referenceType, bool forward)
template<>
void deleteNode< Server > (Server &server, const NodeId &id, bool deleteReferences)
template<>
void deleteNode< Client > (Client &client, const NodeId &id, bool deleteReferences)
template<>
BrowseResult browse< Server > (Server &server, const BrowseDescription &bd, uint32_t maxReferences)
template<>
BrowseResult browse< Client > (Client &client, const BrowseDescription &bd, uint32_t maxReferences)
template<>
BrowseResult browseNext< Server > (Server &server, bool releaseContinuationPoint, const ByteString &continuationPoint)
template<>
BrowseResult browseNext< Client > (Client &client, bool releaseContinuationPoint, const ByteString &continuationPoint)
template<>
BrowsePathResult translateBrowsePathToNodeIds< Server > (Server &server, const BrowsePath &browsePath)
template<>
BrowsePathResult translateBrowsePathToNodeIds< Client > (Client &client, const BrowsePath &browsePath)
template std::vector< ReferenceDescription > browseAll< Server > (Server &, const BrowseDescription &, uint32_t)
template std::vector< ReferenceDescription > browseAll< Client > (Client &, const BrowseDescription &, uint32_t)
template BrowsePathResult browseSimplifiedBrowsePath< Server > (Server &, const NodeId &, const std::vector< QualifiedName > &)
template BrowsePathResult browseSimplifiedBrowsePath< Client > (Client &, const NodeId &, const std::vector< QualifiedName > &)
Function Documentation
addObject< Client >()
template<> void opcua::services::addObject< Client > (Client & client, const NodeId & parentId, const NodeId & id, std::string_view browseName, const NodeId & objectType, const NodeId & referenceType)
Definition at line 36 of file NodeManagement.cpp.
References opcua::Client::handle(), opcua::detail::throwOnBadStatus(), and UA_ObjectAttributes_default.
addObject< Server >()
template<> void opcua::services::addObject< Server > (Server & server, const NodeId & parentId, const NodeId & id, std::string_view browseName, const NodeId & objectType, const NodeId & referenceType)
Definition at line 13 of file NodeManagement.cpp.
References opcua::Server::handle(), opcua::detail::throwOnBadStatus(), and UA_ObjectAttributes_default.
addObjectType< Client >()
template<> void opcua::services::addObjectType< Client > (Client & client, const NodeId & parentId, const NodeId & id, std::string_view browseName, const NodeId & referenceType)
Definition at line 124 of file NodeManagement.cpp.
References opcua::Client::handle(), opcua::detail::throwOnBadStatus(), and UA_ObjectTypeAttributes_default.
addObjectType< Server >()
template<> void opcua::services::addObjectType< Server > (Server & server, const NodeId & parentId, const NodeId & id, std::string_view browseName, const NodeId & referenceType)
Definition at line 103 of file NodeManagement.cpp.
References opcua::Server::handle(), opcua::detail::throwOnBadStatus(), and UA_ObjectTypeAttributes_default.
addReference< Client >()
template<> void opcua::services::addReference< Client > (Client & client, const NodeId & sourceId, const NodeId & targetId, const NodeId & referenceType, bool forward)
Definition at line 207 of file NodeManagement.cpp.
References opcua::Client::handle(), opcua::detail::throwOnBadStatus(), UA_Client_addReference(), UA_NODECLASS_UNSPECIFIED, and UA_STRING_NULL.
addReference< Server >()
template<> void opcua::services::addReference< Server > (Server & server, const NodeId & sourceId, const NodeId & targetId, const NodeId & referenceType, bool forward)
Definition at line 189 of file NodeManagement.cpp.
References opcua::Server::handle(), opcua::detail::throwOnBadStatus(), and UA_Server_addReference().
addVariable< Client >()
template<> void opcua::services::addVariable< Client > (Client & client, const NodeId & parentId, const NodeId & id, std::string_view browseName, const NodeId & variableType, const NodeId & referenceType)
Definition at line 81 of file NodeManagement.cpp.
References opcua::Client::handle(), opcua::detail::throwOnBadStatus(), and UA_VariableAttributes_default.
addVariable< Server >()
template<> void opcua::services::addVariable< Server > (Server & server, const NodeId & parentId, const NodeId & id, std::string_view browseName, const NodeId & variableType, const NodeId & referenceType)
Definition at line 58 of file NodeManagement.cpp.
References opcua::Server::handle(), opcua::detail::throwOnBadStatus(), and UA_VariableAttributes_default.
addVariableType< Client >()
template<> void opcua::services::addVariableType< Client > (Client & client, const NodeId & parentId, const NodeId & id, std::string_view browseName, const NodeId & variableType, const NodeId & referenceType)
Definition at line 167 of file NodeManagement.cpp.
References opcua::Client::handle(), opcua::detail::throwOnBadStatus(), and UA_VariableTypeAttributes_default.
addVariableType< Server >()
template<> void opcua::services::addVariableType< Server > (Server & server, const NodeId & parentId, const NodeId & id, std::string_view browseName, const NodeId & variableType, const NodeId & referenceType)
Definition at line 144 of file NodeManagement.cpp.
References opcua::Server::handle(), opcua::detail::throwOnBadStatus(), and UA_VariableTypeAttributes_default.
browse< Client >()
template<> BrowseResult opcua::services::browse< Client > (Client & client, const BrowseDescription & bd, uint32_t maxReferences)
Definition at line 22 of file View.cpp.
References opcua::Client::handle(), opcua::TypeWrapper< T, typeIndex >::handle(), UA_BrowseRequest::requestedMaxReferencesPerNode, opcua::TypeWrapper< T, typeIndex >::swap(), opcua::detail::throwOnBadStatus(), and UA_STATUSCODE_BADUNEXPECTEDERROR.
browse< Server >()
template<> BrowseResult opcua::services::browse< Server > (Server & server, const BrowseDescription & bd, uint32_t maxReferences)
Definition at line 15 of file View.cpp.
References opcua::Server::handle(), opcua::TypeWrapper< T, typeIndex >::handle(), opcua::detail::throwOnBadStatus(), and UA_Server_browse().
browseAll< Client >()
template std::vector<ReferenceDescription> opcua::services::browseAll< Client > (Client & , const BrowseDescription & , uint32_t)
browseAll< Server >()
template std::vector<ReferenceDescription> opcua::services::browseAll< Server > (Server & , const BrowseDescription & , uint32_t)
browseNext< Client >()
template<> BrowseResult opcua::services::browseNext< Client > (Client & client, bool releaseContinuationPoint, const ByteString & continuationPoint)
Definition at line 53 of file View.cpp.
References opcua::Client::handle(), opcua::TypeWrapper< T, typeIndex >::handle(), UA_BrowseNextRequest::releaseContinuationPoints, opcua::TypeWrapper< T, typeIndex >::swap(), opcua::detail::throwOnBadStatus(), and UA_STATUSCODE_BADUNEXPECTEDERROR.
browseNext< Server >()
template<> BrowseResult opcua::services::browseNext< Server > (Server & server, bool releaseContinuationPoint, const ByteString & continuationPoint)
Definition at line 42 of file View.cpp.
References opcua::Server::handle(), opcua::TypeWrapper< T, typeIndex >::handle(), opcua::detail::throwOnBadStatus(), and UA_Server_browseNext().
browseSimplifiedBrowsePath< Client >()
template BrowsePathResult opcua::services::browseSimplifiedBrowsePath< Client > (Client & , const NodeId & , const std::vector< QualifiedName > &)
browseSimplifiedBrowsePath< Server >()
template BrowsePathResult opcua::services::browseSimplifiedBrowsePath< Server > (Server & , const NodeId & , const std::vector< QualifiedName > &)
deleteNode< Client >()
template<> void opcua::services::deleteNode< Client > (Client & client, const NodeId & id, bool deleteReferences)
Definition at line 233 of file NodeManagement.cpp.
References opcua::Client::handle(), opcua::detail::throwOnBadStatus(), and UA_Client_deleteNode().
deleteNode< Server >()
template<> void opcua::services::deleteNode< Server > (Server & server, const NodeId & id, bool deleteReferences)
Definition at line 227 of file NodeManagement.cpp.
References opcua::Server::handle(), opcua::detail::throwOnBadStatus(), and UA_Server_deleteNode().
readAttribute< Client >()
template<> DataValue opcua::services::readAttribute< Client > (Client & client, const NodeId & id, UA_AttributeId attributeId, UA_TimestampsToReturn timestamps)
Definition at line 27 of file Attribute.cpp.
References opcua::Client::handle(), UA_ReadValueId::nodeId, opcua::ReadResponse, opcua::TypeWrapper< T, typeIndex >::swap(), opcua::detail::throwOnBadStatus(), UA_ReadRequest::timestampsToReturn, and UA_STATUSCODE_BADUNEXPECTEDERROR.
readAttribute< Server >()
template<> DataValue opcua::services::readAttribute< Server > (Server & server, const NodeId & id, UA_AttributeId attributeId, UA_TimestampsToReturn timestamps)
Definition at line 12 of file Attribute.cpp.
References opcua::Server::handle(), UA_ReadValueId::nodeId, opcua::detail::throwOnBadStatus(), and UA_Server_read().
readAttributeScalar()
template<typename AttributeType , typename T > auto opcua::services::readAttributeScalar (T & serverOrClient, const NodeId & id, UA_AttributeId attributeId) inline
Helper function to read scalar node attributes.
Definition at line 59 of file Attribute.h.
References readAttribute().
translateBrowsePathToNodeIds< Client >()
template<> BrowsePathResult opcua::services::translateBrowsePathToNodeIds< Client > (Client & client, const BrowsePath & browsePath)
Definition at line 108 of file View.cpp.
References UA_TranslateBrowsePathsToNodeIdsRequest::browsePathsSize, opcua::Client::handle(), opcua::TypeWrapper< T, typeIndex >::handle(), opcua::TypeWrapper< T, typeIndex >::swap(), opcua::detail::throwOnBadStatus(), UA_STATUSCODE_BADUNEXPECTEDERROR, and UA_TYPES_TRANSLATEBROWSEPATHSTONODEIDSRESPONSE.
translateBrowsePathToNodeIds< Server >()
template<> BrowsePathResult opcua::services::translateBrowsePathToNodeIds< Server > (Server & server, const BrowsePath & browsePath)
Definition at line 97 of file View.cpp.
References opcua::Server::handle(), opcua::TypeWrapper< T, typeIndex >::handle(), opcua::detail::throwOnBadStatus(), and UA_Server_translateBrowsePathToNodeIds().
writeAttribute< Client >()
template<> void opcua::services::writeAttribute< Client > (Client & client, const NodeId & id, UA_AttributeId attributeId, const DataValue & value)
Definition at line 74 of file Attribute.cpp.
References opcua::Client::handle(), opcua::TypeWrapper< T, typeIndex >::handle(), UA_WriteValue::nodeId, UA_WriteRequest::nodesToWrite, opcua::detail::throwOnBadStatus(), UA_STATUSCODE_BADUNEXPECTEDERROR, UA_DataValue::value, and opcua::WriteResponse.
writeAttribute< Server >()
template<> void opcua::services::writeAttribute< Server > (Server & server, const NodeId & id, UA_AttributeId attributeId, const DataValue & value)
Definition at line 60 of file Attribute.cpp.
References opcua::Server::handle(), opcua::TypeWrapper< T, typeIndex >::handle(), UA_WriteValue::nodeId, opcua::detail::throwOnBadStatus(), UA_Server_write(), and UA_DataValue::value.