open62541pp: opcua::services::detail Namespace Reference
opcua::services::detail Namespace Reference
Services » Attribute service set | Services » MonitoredItem service set » CreateMonitoredItems service | Services » Subscription service set » CreateSubscription service
Classes
struct AsyncServiceAdapter
struct AttributeHandler
struct AttributeHandler< AttributeId::AccessLevel >
struct AttributeHandler< AttributeId::ArrayDimensions >
struct AttributeHandler< AttributeId::BrowseName >
struct AttributeHandler< AttributeId::ContainsNoLoops >
struct AttributeHandler< AttributeId::DataType >
struct AttributeHandler< AttributeId::DataTypeDefinition >
struct AttributeHandler< AttributeId::Description >
struct AttributeHandler< AttributeId::DisplayName >
struct AttributeHandler< AttributeId::EventNotifier >
struct AttributeHandler< AttributeId::Executable >
struct AttributeHandler< AttributeId::Historizing >
struct AttributeHandler< AttributeId::InverseName >
struct AttributeHandler< AttributeId::IsAbstract >
struct AttributeHandler< AttributeId::MinimumSamplingInterval >
struct AttributeHandler< AttributeId::NodeClass >
struct AttributeHandler< AttributeId::NodeId >
struct AttributeHandler< AttributeId::Symmetric >
struct AttributeHandler< AttributeId::UserAccessLevel >
struct AttributeHandler< AttributeId::UserExecutable >
struct AttributeHandler< AttributeId::UserWriteMask >
struct AttributeHandler< AttributeId::Value >
struct AttributeHandler< AttributeId::ValueRank >
struct AttributeHandler< AttributeId::WriteMask >
struct AttributeHandlerScalar
struct AttributeHandlerScalar< Bitmask< T > >
struct AttributeHandlerScalar< T, std::enable_if_t< std::is_enum_v< T > > >
struct AttributeHandlerVariant
struct CallbackAdapter
struct HookToken
struct MonitoredItemContext
struct SubscriptionContext
struct TransformToken
struct Wrap
Functions
template<AttributeId Attribute, typename T >
auto readAttributeImpl (T &connection, const NodeId &id) noexcept
template<AttributeId Attribute, typename CompletionToken >
auto readAttributeAsyncImpl (Client &connection, const NodeId &id, CompletionToken &&token)
template<AttributeId Attribute, typename T , typename U >
StatusCode writeAttributeImpl (T &connection, const NodeId &id, U &&value) noexcept
template<AttributeId Attribute, typename T , typename U , typename CompletionToken >
auto writeAttributeAsyncImpl (T &connection, const NodeId &id, U &&value, CompletionToken &&token)
template<typename HookFunction , typename CompletionToken >
HookToken (HookFunction &&, CompletionToken &&) -> HookToken< HookFunction, CompletionToken >
template<typename CompletionHandler , typename Transform >
auto asyncTransform (CompletionHandler &&handler, Transform &&transform)
template<typename TransformFunction , typename CompletionToken >
TransformToken (TransformFunction &&, CompletionToken &&) -> TransformToken< TransformFunction, CompletionToken >
Result< Variant > getVariant (DataValue &&dv) noexcept
template<typename Request , typename Response , typename CompletionToken >
auto sendRequestAsync (Client &client, const Request &request, CompletionToken &&token)
template<typename Request , typename Response >
Response sendRequest (Client &client, const Request &request) noexcept
template<typename T >
auto * getPointer (T &value) noexcept
template<typename T >
auto * getPointer (Span< T > array) noexcept
template<typename T >
auto * getNativePointer (T &wrapper) noexcept
template<typename T >
auto * getNativePointer (Span< T > array) noexcept
template<typename T >
ExtensionObject wrapNodeAttributes (const T &attributes) noexcept
UA_AddNodesItem createAddNodesItem (const NodeId &parentId, const NodeId &referenceType, const NodeId &id, std::string_view browseName, NodeClass nodeClass, const ExtensionObject &nodeAttributes, const NodeId &typeDefinition) noexcept
UA_AddNodesRequest createAddNodesRequest (UA_AddNodesItem &item) noexcept
UA_AddReferencesItem createAddReferencesItem (const NodeId &sourceId, const NodeId &referenceType, bool forward, const NodeId &targetId) noexcept
UA_AddReferencesRequest createAddReferencesRequest (UA_AddReferencesItem &item) noexcept
UA_DeleteNodesItem createDeleteNodesItem (const NodeId &id, bool deleteReferences) noexcept
UA_DeleteNodesRequest createDeleteNodesRequest (UA_DeleteNodesItem &item) noexcept
UA_DeleteReferencesItem createDeleteReferencesItem (const NodeId &sourceId, const NodeId &referenceType, bool isForward, const NodeId &targetId, bool deleteBidirectional) noexcept
UA_DeleteReferencesRequest createDeleteReferencesRequest (UA_DeleteReferencesItem &item) noexcept
UA_ReadValueId createReadValueId (const NodeId &id, AttributeId attributeId) noexcept
UA_ReadRequest createReadRequest (TimestampsToReturn timestamps, UA_ReadValueId &item) noexcept
UA_ReadRequest createReadRequest (TimestampsToReturn timestamps, Span< const ReadValueId > nodesToRead) noexcept
UA_WriteValue createWriteValue (const NodeId &id, AttributeId attributeId, const DataValue &value) noexcept
UA_WriteRequest createWriteRequest (UA_WriteValue &item) noexcept
UA_WriteRequest createWriteRequest (Span< const WriteValue > nodesToWrite) noexcept
UA_CallMethodRequest createCallMethodRequest (const NodeId &objectId, const NodeId &methodId, Span< const Variant > inputArguments) noexcept
UA_CallRequest createCallRequest (UA_CallMethodRequest &item) noexcept
UA_BrowseRequest createBrowseRequest (const BrowseDescription &bd, uint32_t maxReferences) noexcept
UA_BrowseNextRequest createBrowseNextRequest (bool releaseContinuationPoint, const ByteString &continuationPoint) noexcept
UA_TranslateBrowsePathsToNodeIdsRequest createTranslateBrowsePathsToNodeIdsRequest (const BrowsePath &browsePath) noexcept
BrowsePath createBrowsePath (const NodeId &origin, Span< const QualifiedName > browsePath)
template<typename SubscriptionParameters >
UA_CreateSubscriptionRequest createCreateSubscriptionRequest (const SubscriptionParameters &parameters, bool publishingEnabled) noexcept
template<typename SubscriptionParameters >
UA_ModifySubscriptionRequest createModifySubscriptionRequest (uint32_t subscriptionId, const SubscriptionParameters &parameters) noexcept
UA_SetPublishingModeRequest createSetPublishingModeRequest (bool publishing, Span< const uint32_t > subscriptionIds) noexcept
UA_DeleteSubscriptionsRequest createDeleteSubscriptionsRequest (uint32_t &subscriptionId) noexcept
template<typename MonitoringParameters >
void copyMonitoringParametersToNative (const MonitoringParameters &parameters, UA_MonitoringParameters &native) noexcept
template<typename MonitoringParameters >
UA_MonitoredItemCreateRequest createMonitoredItemCreateRequest (const ReadValueId &itemToMonitor, MonitoringMode monitoringMode, MonitoringParameters &parameters) noexcept
UA_CreateMonitoredItemsRequest createCreateMonitoredItemsRequest (uint32_t subscriptionId, TimestampsToReturn timestampsToReturn, Span< const UA_MonitoredItemCreateRequest > itemsToCreate) noexcept
template<typename MonitoringParameters >
UA_MonitoredItemModifyRequest createMonitoredItemModifyRequest (uint32_t monitoredItemId, MonitoringParameters &parameters) noexcept
template<typename MonitoringParameters >
UA_ModifyMonitoredItemsRequest createModifyMonitoredItemsRequest (uint32_t subscriptionId, MonitoringParameters &parameters, UA_MonitoredItemModifyRequest &item) noexcept
UA_SetMonitoringModeRequest createSetMonitoringModeRequest (uint32_t subscriptionId, Span< const uint32_t > monitoredItemIds, MonitoringMode monitoringMode) noexcept
UA_SetTriggeringRequest createSetTriggeringRequest (uint32_t subscriptionId, uint32_t triggeringItemId, Span< const uint32_t > linksToAdd, Span< const uint32_t > linksToRemove) noexcept
UA_DeleteMonitoredItemsRequest createDeleteMonitoredItemsRequest (uint32_t subscriptionId, Span< const uint32_t > monitoredItemIds) noexcept
template<typename Response >
const UA_ResponseHeader & getResponseHeader (const Response &response) noexcept
template<typename Response >
StatusCode getServiceResult (const Response &response) noexcept
template<typename Response >
auto getSingleResultRef (Response &response) noexcept
template<typename Response >
StatusCode getSingleStatus (const Response &response) noexcept
template<typename WrapperType , typename Response >
Result< WrapperType > wrapSingleResult (Response &response) noexcept
template<typename WrapperType , typename Response >
WrapperType wrapSingleResultWithStatus (Response &response) noexcept
Result< NodeId > getAddedNodeId (UA_AddNodesResult &result) noexcept
std::vector< std::unique_ptr< MonitoredItemContext > > createMonitoredItemContexts (Client &connection, const CreateMonitoredItemsRequest &request, DataChangeNotificationCallback dataChangeCallback, EventNotificationCallback eventCallback, DeleteMonitoredItemCallback deleteCallback)
void convertMonitoredItemContexts (Span< const std::unique_ptr< MonitoredItemContext > > contexts, Span< MonitoredItemContext * > contextsPtr, Span< UA_Client_DataChangeNotificationCallback > dataChangeCallbacksNative, Span< UA_Client_EventNotificationCallback > eventCallbacksNative, Span< UA_Client_DeleteMonitoredItemCallback > deleteCallbacksNative) noexcept
void storeMonitoredItemContexts (Client &connection, uint32_t subscriptionId, const CreateMonitoredItemsResponse &response, Span< std::unique_ptr< MonitoredItemContext > > contexts)
std::unique_ptr< SubscriptionContext > createSubscriptionContext (Client &connection, StatusChangeNotificationCallback &&statusChangeCallback, DeleteSubscriptionCallback &&deleteCallback)
void storeSubscriptionContext (Client &connection, uint32_t subscriptionId, std::unique_ptr< SubscriptionContext > &&context)
Function Documentation
readAttributeImpl()
template<AttributeId Attribute, typename T > auto opcua::services::detail::readAttributeImpl (T & connection, const NodeId & id) noexcept
Definition at line 217 of file attribute.hpp.
Referenced by opcua::services::readAccessLevel(), opcua::services::readArrayDimensions(), opcua::services::readBrowseName(), opcua::services::readContainsNoLoops(), opcua::services::readDataType(), opcua::services::readDataTypeDefinition(), opcua::services::readDescription(), opcua::services::readDisplayName(), opcua::services::readEventNotifier(), opcua::services::readExecutable(), opcua::services::readHistorizing(), opcua::services::readInverseName(), opcua::services::readIsAbstract(), opcua::services::readMinimumSamplingInterval(), opcua::services::readNodeClass(), opcua::services::readNodeId(), opcua::services::readSymmetric(), opcua::services::readUserAccessLevel(), opcua::services::readUserExecutable(), opcua::services::readUserWriteMask(), opcua::services::readValue(), opcua::services::readValueRank(), and opcua::services::readWriteMask().
readAttributeAsyncImpl()
template<AttributeId Attribute, typename CompletionToken > auto opcua::services::detail::readAttributeAsyncImpl (Client & connection, const NodeId & id, CompletionToken && token)
Definition at line 224 of file attribute.hpp.
Referenced by opcua::services::readAccessLevelAsync(), opcua::services::readArrayDimensionsAsync(), opcua::services::readBrowseNameAsync(), opcua::services::readContainsNoLoopsAsync(), opcua::services::readDataTypeAsync(), opcua::services::readDataTypeDefinitionAsync(), opcua::services::readDescriptionAsync(), opcua::services::readDisplayNameAsync(), opcua::services::readEventNotifierAsync(), opcua::services::readExecutableAsync(), opcua::services::readHistorizingAsync(), opcua::services::readInverseNameAsync(), opcua::services::readIsAbstractAsync(), opcua::services::readMinimumSamplingIntervalAsync(), opcua::services::readNodeClassAsync(), opcua::services::readNodeIdAsync(), opcua::services::readSymmetricAsync(), opcua::services::readUserAccessLevelAsync(), opcua::services::readUserExecutableAsync(), opcua::services::readUserWriteMaskAsync(), opcua::services::readValueAsync(), opcua::services::readValueRankAsync(), and opcua::services::readWriteMaskAsync().
writeAttributeImpl()
template<AttributeId Attribute, typename T , typename U > StatusCode opcua::services::detail::writeAttributeImpl (T & connection, const NodeId & id, U && value) noexcept
Definition at line 241 of file attribute.hpp.
Referenced by opcua::services::writeAccessLevel(), opcua::services::writeArrayDimensions(), opcua::services::writeBrowseName(), opcua::services::writeContainsNoLoops(), opcua::services::writeDataType(), opcua::services::writeDescription(), opcua::services::writeDisplayName(), opcua::services::writeEventNotifier(), opcua::services::writeExecutable(), opcua::services::writeHistorizing(), opcua::services::writeInverseName(), opcua::services::writeIsAbstract(), opcua::services::writeMinimumSamplingInterval(), opcua::services::writeSymmetric(), opcua::services::writeUserAccessLevel(), opcua::services::writeUserExecutable(), opcua::services::writeUserWriteMask(), opcua::services::writeValue(), opcua::services::writeValueRank(), and opcua::services::writeWriteMask().
writeAttributeAsyncImpl()
template<AttributeId Attribute, typename T , typename U , typename CompletionToken > auto opcua::services::detail::writeAttributeAsyncImpl (T & connection, const NodeId & id, U && value, CompletionToken && token)
Definition at line 247 of file attribute.hpp.
Referenced by opcua::services::writeAccessLevelAsync(), opcua::services::writeArrayDimensionsAsync(), opcua::services::writeBrowseNameAsync(), opcua::services::writeContainsNoLoopsAsync(), opcua::services::writeDataTypeAsync(), opcua::services::writeDescriptionAsync(), opcua::services::writeDisplayNameAsync(), opcua::services::writeEventNotifierAsync(), opcua::services::writeExecutableAsync(), opcua::services::writeHistorizingAsync(), opcua::services::writeInverseNameAsync(), opcua::services::writeIsAbstractAsync(), opcua::services::writeMinimumSamplingIntervalAsync(), opcua::services::writeSymmetricAsync(), opcua::services::writeUserAccessLevelAsync(), opcua::services::writeUserExecutableAsync(), opcua::services::writeUserWriteMaskAsync(), opcua::services::writeValueAsync(), opcua::services::writeValueRankAsync(), and opcua::services::writeWriteMaskAsync().
HookToken()
template<typename HookFunction , typename CompletionToken > opcua::services::detail::HookToken (HookFunction && , CompletionToken &&) -> HookToken< HookFunction, CompletionToken >
asyncTransform()
template<typename CompletionHandler , typename Transform > auto opcua::services::detail::asyncTransform (CompletionHandler && handler, Transform && transform)
Definition at line 12 of file async_transform.hpp.
Referenced by opcua::AsyncResult< services::detail::TransformToken< TransformFunction, CompletionToken >, T >::initiate().
TransformToken()
template<typename TransformFunction , typename CompletionToken > opcua::services::detail::TransformToken (TransformFunction && , CompletionToken &&) -> TransformToken< TransformFunction, CompletionToken >
getVariant()
Result< Variant > opcua::services::detail::getVariant (DataValue && dv) inline noexcept
Definition at line 16 of file attribute_handler.hpp.
Referenced by opcua::services::detail::AttributeHandler< AttributeId::ArrayDimensions >::fromDataValue(), opcua::services::detail::AttributeHandler< AttributeId::NodeClass >::fromDataValue(), opcua::services::detail::AttributeHandlerScalar< T, Enable >::fromDataValue(), and opcua::services::detail::AttributeHandlerVariant::fromDataValue().
sendRequestAsync()
template<typename Request , typename Response , typename CompletionToken > auto opcua::services::detail::sendRequestAsync (Client & client, const Request & request, CompletionToken && token)
Async client service requests.
Definition at line 101 of file client_service.hpp.
Referenced by opcua::services::addNodesAsync(), opcua::services::addReferencesAsync(), opcua::services::browseAsync(), opcua::services::browseNextAsync(), opcua::services::callAsync(), opcua::services::deleteNodesAsync(), opcua::services::deleteReferencesAsync(), opcua::services::readAsync(), opcua::services::registerNodesAsync(), sendRequestAsync(), opcua::services::setMonitoringModeAsync(), opcua::services::setTriggeringAsync(), opcua::services::translateBrowsePathsToNodeIdsAsync(), opcua::services::unregisterNodesAsync(), and opcua::services::writeAsync().
sendRequest()
template<typename Request , typename Response > Response opcua::services::detail::sendRequest (Client & client, const Request & request) noexcept
Sync client service requests.
Definition at line 121 of file client_service.hpp.
Referenced by sendRequest().
getPointer() [1/2]
template<typename T > auto * opcua::services::detail::getPointer (T & value) noexcept
Definition at line 18 of file request_handling.hpp.
Referenced by createCreateMonitoredItemsRequest(), createDeleteMonitoredItemsRequest(), createSetMonitoringModeRequest(), createSetPublishingModeRequest(), createSetTriggeringRequest(), getNativePointer(), and getNativePointer().
getPointer() [2/2]
template<typename T > auto * opcua::services::detail::getPointer (Span< T > array) noexcept
Definition at line 24 of file request_handling.hpp.
getNativePointer() [1/2]
template<typename T > auto * opcua::services::detail::getNativePointer (T & wrapper) noexcept
Definition at line 30 of file request_handling.hpp.
Referenced by createBrowseNextRequest(), createBrowseRequest(), createCallMethodRequest(), createReadRequest(), createTranslateBrowsePathsToNodeIdsRequest(), and createWriteRequest().
getNativePointer() [2/2]
template<typename T > auto * opcua::services::detail::getNativePointer (Span< T > array) noexcept
Definition at line 35 of file request_handling.hpp.
wrapNodeAttributes()
template<typename T > ExtensionObject opcua::services::detail::wrapNodeAttributes (const T & attributes) noexcept
Definition at line 40 of file request_handling.hpp.
Referenced by opcua::services::addDataType(), opcua::services::addDataTypeAsync(), opcua::services::addMethodAsync(), opcua::services::addObject(), opcua::services::addObjectAsync(), opcua::services::addObjectType(), opcua::services::addObjectTypeAsync(), opcua::services::addReferenceType(), opcua::services::addReferenceTypeAsync(), opcua::services::addVariable(), opcua::services::addVariableAsync(), opcua::services::addVariableType(), opcua::services::addVariableTypeAsync(), opcua::services::addView(), and opcua::services::addViewAsync().
createAddNodesItem()
UA_AddNodesItem opcua::services::detail::createAddNodesItem (const NodeId & parentId, const NodeId & referenceType, const NodeId & id, std::string_view browseName, NodeClass nodeClass, const ExtensionObject & nodeAttributes, const NodeId & typeDefinition) inline noexcept
Definition at line 45 of file request_handling.hpp.
Referenced by opcua::services::addNodeAsync().
createAddNodesRequest()
UA_AddNodesRequest opcua::services::detail::createAddNodesRequest (UA_AddNodesItem & item) inline noexcept
Definition at line 66 of file request_handling.hpp.
Referenced by opcua::services::addNodeAsync().
createAddReferencesItem()
UA_AddReferencesItem opcua::services::detail::createAddReferencesItem (const NodeId & sourceId, const NodeId & referenceType, bool forward, const NodeId & targetId) inline noexcept
Definition at line 73 of file request_handling.hpp.
Referenced by opcua::services::addReferenceAsync().
createAddReferencesRequest()
UA_AddReferencesRequest opcua::services::detail::createAddReferencesRequest (UA_AddReferencesItem & item) inline noexcept
Definition at line 84 of file request_handling.hpp.
Referenced by opcua::services::addReferenceAsync().
createDeleteNodesItem()
UA_DeleteNodesItem opcua::services::detail::createDeleteNodesItem (const NodeId & id, bool deleteReferences) inline noexcept
Definition at line 91 of file request_handling.hpp.
Referenced by opcua::services::deleteNodeAsync().
createDeleteNodesRequest()
UA_DeleteNodesRequest opcua::services::detail::createDeleteNodesRequest (UA_DeleteNodesItem & item) inline noexcept
Definition at line 98 of file request_handling.hpp.
Referenced by opcua::services::deleteNodeAsync().
createDeleteReferencesItem()
UA_DeleteReferencesItem opcua::services::detail::createDeleteReferencesItem (const NodeId & sourceId, const NodeId & referenceType, bool isForward, const NodeId & targetId, bool deleteBidirectional) inline noexcept
Definition at line 105 of file request_handling.hpp.
Referenced by opcua::services::deleteReferenceAsync().
createDeleteReferencesRequest()
UA_DeleteReferencesRequest opcua::services::detail::createDeleteReferencesRequest (UA_DeleteReferencesItem & item) inline noexcept
Definition at line 121 of file request_handling.hpp.
Referenced by opcua::services::deleteReferenceAsync().
createReadValueId()
UA_ReadValueId opcua::services::detail::createReadValueId (const NodeId & id, AttributeId attributeId) inline noexcept
Definition at line 129 of file request_handling.hpp.
Referenced by opcua::services::readAttributeAsync().
createReadRequest() [1/2]
UA_ReadRequest opcua::services::detail::createReadRequest (TimestampsToReturn timestamps, UA_ReadValueId & item) inline noexcept
Definition at line 136 of file request_handling.hpp.
Referenced by opcua::services::read(), opcua::services::readAsync(), and opcua::services::readAttributeAsync().
createReadRequest() [2/2]
UA_ReadRequest opcua::services::detail::createReadRequest (TimestampsToReturn timestamps, Span< const ReadValueId > nodesToRead) inline noexcept
Definition at line 146 of file request_handling.hpp.
createWriteValue()
UA_WriteValue opcua::services::detail::createWriteValue (const NodeId & id, AttributeId attributeId, const DataValue & value) inline noexcept
Definition at line 156 of file request_handling.hpp.
Referenced by opcua::services::writeAttributeAsync().
createWriteRequest() [1/2]
UA_WriteRequest opcua::services::detail::createWriteRequest (UA_WriteValue & item) inline noexcept
Definition at line 167 of file request_handling.hpp.
Referenced by opcua::services::write(), opcua::services::writeAsync(), and opcua::services::writeAttributeAsync().
createWriteRequest() [2/2]
UA_WriteRequest opcua::services::detail::createWriteRequest (Span< const WriteValue > nodesToWrite) inline noexcept
Definition at line 174 of file request_handling.hpp.
createCallMethodRequest()
UA_CallMethodRequest opcua::services::detail::createCallMethodRequest (const NodeId & objectId, const NodeId & methodId, Span< const Variant > inputArguments) inline noexcept
Definition at line 183 of file request_handling.hpp.
Referenced by opcua::services::callAsync().
createCallRequest()
UA_CallRequest opcua::services::detail::createCallRequest (UA_CallMethodRequest & item) inline noexcept
Definition at line 194 of file request_handling.hpp.
Referenced by opcua::services::callAsync().
createBrowseRequest()
UA_BrowseRequest opcua::services::detail::createBrowseRequest (const BrowseDescription & bd, uint32_t maxReferences) inline noexcept
Definition at line 203 of file request_handling.hpp.
Referenced by opcua::services::browseAsync().
createBrowseNextRequest()
UA_BrowseNextRequest opcua::services::detail::createBrowseNextRequest (bool releaseContinuationPoint, const ByteString & continuationPoint) inline noexcept
Definition at line 213 of file request_handling.hpp.
Referenced by opcua::services::browseNextAsync().
createTranslateBrowsePathsToNodeIdsRequest()
UA_TranslateBrowsePathsToNodeIdsRequest opcua::services::detail::createTranslateBrowsePathsToNodeIdsRequest (const BrowsePath & browsePath) inline noexcept
Definition at line 223 of file request_handling.hpp.
Referenced by opcua::services::translateBrowsePathToNodeIdsAsync().
createBrowsePath()
BrowsePath opcua::services::detail::createBrowsePath (const NodeId & origin, Span< const QualifiedName > browsePath) inline
Definition at line 232 of file request_handling.hpp.
Referenced by opcua::services::browseSimplifiedBrowsePath(), and opcua::services::browseSimplifiedBrowsePathAsync().
createCreateSubscriptionRequest()
template<typename SubscriptionParameters > UA_CreateSubscriptionRequest opcua::services::detail::createCreateSubscriptionRequest (const SubscriptionParameters & parameters, bool publishingEnabled) noexcept
Definition at line 248 of file request_handling.hpp.
createModifySubscriptionRequest()
template<typename SubscriptionParameters > UA_ModifySubscriptionRequest opcua::services::detail::createModifySubscriptionRequest (uint32_t subscriptionId, const SubscriptionParameters & parameters) noexcept
Definition at line 262 of file request_handling.hpp.
createSetPublishingModeRequest()
UA_SetPublishingModeRequest opcua::services::detail::createSetPublishingModeRequest (bool publishing, Span< const uint32_t > subscriptionIds) inline noexcept
Definition at line 275 of file request_handling.hpp.
createDeleteSubscriptionsRequest()
UA_DeleteSubscriptionsRequest opcua::services::detail::createDeleteSubscriptionsRequest (uint32_t & subscriptionId) inline noexcept
Definition at line 285 of file request_handling.hpp.
copyMonitoringParametersToNative()
template<typename MonitoringParameters > void opcua::services::detail::copyMonitoringParametersToNative (const MonitoringParameters & parameters, UA_MonitoringParameters & native) inline noexcept
Definition at line 294 of file request_handling.hpp.
Referenced by createMonitoredItemCreateRequest(), and createMonitoredItemModifyRequest().
createMonitoredItemCreateRequest()
template<typename MonitoringParameters > UA_MonitoredItemCreateRequest opcua::services::detail::createMonitoredItemCreateRequest (const ReadValueId & itemToMonitor, MonitoringMode monitoringMode, MonitoringParameters & parameters) noexcept
Definition at line 304 of file request_handling.hpp.
createCreateMonitoredItemsRequest()
UA_CreateMonitoredItemsRequest opcua::services::detail::createCreateMonitoredItemsRequest (uint32_t subscriptionId, TimestampsToReturn timestampsToReturn, Span< const UA_MonitoredItemCreateRequest > itemsToCreate) inline noexcept
Definition at line 316 of file request_handling.hpp.
createMonitoredItemModifyRequest()
template<typename MonitoringParameters > UA_MonitoredItemModifyRequest opcua::services::detail::createMonitoredItemModifyRequest (uint32_t monitoredItemId, MonitoringParameters & parameters) noexcept
Definition at line 330 of file request_handling.hpp.
Referenced by opcua::services::modifyMonitoredItem().
createModifyMonitoredItemsRequest()
template<typename MonitoringParameters > UA_ModifyMonitoredItemsRequest opcua::services::detail::createModifyMonitoredItemsRequest (uint32_t subscriptionId, MonitoringParameters & parameters, UA_MonitoredItemModifyRequest & item) noexcept
Definition at line 340 of file request_handling.hpp.
Referenced by opcua::services::modifyMonitoredItem().
createSetMonitoringModeRequest()
UA_SetMonitoringModeRequest opcua::services::detail::createSetMonitoringModeRequest (uint32_t subscriptionId, Span< const uint32_t > monitoredItemIds, MonitoringMode monitoringMode) inline noexcept
Definition at line 351 of file request_handling.hpp.
Referenced by opcua::services::setMonitoringMode(), and opcua::services::setMonitoringModeAsync().
createSetTriggeringRequest()
UA_SetTriggeringRequest opcua::services::detail::createSetTriggeringRequest (uint32_t subscriptionId, uint32_t triggeringItemId, Span< const uint32_t > linksToAdd, Span< const uint32_t > linksToRemove) inline noexcept
Definition at line 362 of file request_handling.hpp.
createDeleteMonitoredItemsRequest()
UA_DeleteMonitoredItemsRequest opcua::services::detail::createDeleteMonitoredItemsRequest (uint32_t subscriptionId, Span< const uint32_t > monitoredItemIds) inline noexcept
Definition at line 378 of file request_handling.hpp.
getResponseHeader()
template<typename Response > const UA_ResponseHeader & opcua::services::detail::getResponseHeader (const Response & response) noexcept
Definition at line 35 of file response_handling.hpp.
Referenced by getServiceResult().
getServiceResult()
template<typename Response > StatusCode opcua::services::detail::getServiceResult (const Response & response) noexcept
Definition at line 44 of file response_handling.hpp.
Referenced by getSingleResultRef().
getSingleResultRef()
template<typename Response > auto opcua::services::detail::getSingleResultRef (Response & response) noexcept
Definition at line 49 of file response_handling.hpp.
Referenced by opcua::services::addNodeAsync(), getSingleStatus(), and wrapSingleResult().
getSingleStatus()
template<typename Response > StatusCode opcua::services::detail::getSingleStatus (const Response & response) noexcept
Definition at line 68 of file response_handling.hpp.
Referenced by opcua::services::addReferenceAsync(), opcua::services::deleteNodeAsync(), opcua::services::deleteReferenceAsync(), opcua::services::setMonitoringMode(), opcua::services::setMonitoringModeAsync(), and opcua::services::writeAttributeAsync().
wrapSingleResult()
template<typename WrapperType , typename Response > Result< WrapperType > opcua::services::detail::wrapSingleResult (Response & response) noexcept
Definition at line 74 of file response_handling.hpp.
Referenced by opcua::services::readAttributeAsync(), and wrapSingleResultWithStatus().
wrapSingleResultWithStatus()
template<typename WrapperType , typename Response > WrapperType opcua::services::detail::wrapSingleResultWithStatus (Response & response) noexcept
Definition at line 80 of file response_handling.hpp.
Referenced by opcua::services::browseAsync(), opcua::services::browseNextAsync(), opcua::services::callAsync(), opcua::services::modifyMonitoredItem(), and opcua::services::translateBrowsePathToNodeIdsAsync().
getAddedNodeId()
Result< NodeId > opcua::services::detail::getAddedNodeId (UA_AddNodesResult & result) inline noexcept
Definition at line 88 of file response_handling.hpp.
Referenced by opcua::services::addNodeAsync().
createMonitoredItemContexts()
std::vector< std::unique_ptr< MonitoredItemContext > > opcua::services::detail::createMonitoredItemContexts (Client & connection, const CreateMonitoredItemsRequest & request, DataChangeNotificationCallback dataChangeCallback, EventNotificationCallback eventCallback, DeleteMonitoredItemCallback deleteCallback)
convertMonitoredItemContexts()
void opcua::services::detail::convertMonitoredItemContexts (Span< const std::unique_ptr< MonitoredItemContext > > contexts, Span< MonitoredItemContext * > contextsPtr, Span< UA_Client_DataChangeNotificationCallback > dataChangeCallbacksNative, Span< UA_Client_EventNotificationCallback > eventCallbacksNative, Span< UA_Client_DeleteMonitoredItemCallback > deleteCallbacksNative) noexcept
storeMonitoredItemContexts()
void opcua::services::detail::storeMonitoredItemContexts (Client & connection, uint32_t subscriptionId, const CreateMonitoredItemsResponse & response, Span< std::unique_ptr< MonitoredItemContext > > contexts)
createSubscriptionContext()
std::unique_ptr< SubscriptionContext > opcua::services::detail::createSubscriptionContext (Client & connection, StatusChangeNotificationCallback && statusChangeCallback, DeleteSubscriptionCallback && deleteCallback)
Referenced by opcua::services::createSubscription().
storeSubscriptionContext()
void opcua::services::detail::storeSubscriptionContext (Client & connection, uint32_t subscriptionId, std::unique_ptr< SubscriptionContext > && context)