open62541pp: opcua::detail::WrapperConversion< WrapperType > Struct Template Reference
opcua::detail::WrapperConversion< WrapperType > Struct Template Reference
#include <wrapper.hpp>
Detailed Description
template<typename WrapperType>
struct opcua::detail::WrapperConversion< WrapperType >
Definition at line 112 of file wrapper.hpp.
Public Types
using NativeType = typename WrapperType::NativeType
Static Public Member Functions
static constexpr WrapperType * asWrapper (NativeType *native) noexcept
static constexpr const WrapperType * asWrapper (const NativeType *native) noexcept
static constexpr WrapperType & asWrapper (NativeType &native) noexcept
static constexpr const WrapperType & asWrapper (const NativeType &native) noexcept
static constexpr NativeType * asNative (WrapperType *wrapper) noexcept
static constexpr const NativeType * asNative (const WrapperType *wrapper) noexcept
static constexpr NativeType & asNative (WrapperType &wrapper) noexcept
static constexpr const NativeType & asNative (const WrapperType &wrapper) noexcept
Member Typedef Documentation
NativeType
template<typename WrapperType > using opcua::detail::WrapperConversion< WrapperType >::NativeType = typename WrapperType::NativeType
Definition at line 116 of file wrapper.hpp.
Member Function Documentation
asWrapper() [1/4]
template<typename WrapperType > static constexpr WrapperType * opcua::detail::WrapperConversion< WrapperType >::asWrapper (NativeType * native) inline static constexpr noexcept
Definition at line 119 of file wrapper.hpp.
Referenced by opcua::asWrapper(), opcua::asWrapper(), opcua::asWrapper(), opcua::asWrapper(), opcua::detail::WrapperConversion< WrapperType >::asWrapper(), and opcua::detail::WrapperConversion< WrapperType >::asWrapper().
asWrapper() [2/4]
template<typename WrapperType > static constexpr const WrapperType * opcua::detail::WrapperConversion< WrapperType >::asWrapper (const NativeType * native) inline static constexpr noexcept
Definition at line 123 of file wrapper.hpp.
asWrapper() [3/4]
template<typename WrapperType > static constexpr WrapperType & opcua::detail::WrapperConversion< WrapperType >::asWrapper (NativeType & native) inline static constexpr noexcept
Definition at line 127 of file wrapper.hpp.
asWrapper() [4/4]
template<typename WrapperType > static constexpr const WrapperType & opcua::detail::WrapperConversion< WrapperType >::asWrapper (const NativeType & native) inline static constexpr noexcept
Definition at line 131 of file wrapper.hpp.
asNative() [1/4]
template<typename WrapperType > static constexpr NativeType * opcua::detail::WrapperConversion< WrapperType >::asNative (WrapperType * wrapper) inline static constexpr noexcept
Definition at line 135 of file wrapper.hpp.
Referenced by opcua::asNative(), opcua::asNative(), opcua::asNative(), opcua::asNative(), opcua::detail::WrapperConversion< WrapperType >::asNative(), and opcua::detail::WrapperConversion< WrapperType >::asNative().
asNative() [2/4]
template<typename WrapperType > static constexpr const NativeType * opcua::detail::WrapperConversion< WrapperType >::asNative (const WrapperType * wrapper) inline static constexpr noexcept
Definition at line 139 of file wrapper.hpp.
asNative() [3/4]
template<typename WrapperType > static constexpr NativeType & opcua::detail::WrapperConversion< WrapperType >::asNative (WrapperType & wrapper) inline static constexpr noexcept
Definition at line 143 of file wrapper.hpp.
asNative() [4/4]
template<typename WrapperType > static constexpr const NativeType & opcua::detail::WrapperConversion< WrapperType >::asNative (const WrapperType & wrapper) inline static constexpr noexcept
Definition at line 147 of file wrapper.hpp.