open62541++: opcua::TypeIndexList< typeIndexes > Struct Template Reference
opcua::TypeIndexList< typeIndexes > Struct Template Reference
#include <TypeConverter.h>
Public Types
using TypeIndexes = std::integer_sequence< TypeIndex, typeIndexes... >
Static Public Member Functions
static constexpr size_t size ()
static constexpr bool contains (TypeIndex typeIndex)
static constexpr bool contains (Type type)
static constexpr auto toArray ()
Detailed Description
template<TypeIndex... typeIndexes>
struct opcua::TypeIndexList< typeIndexes >
Definition at line 22 of file TypeConverter.h.
Member Typedef Documentation
TypeIndexes
template<TypeIndex... typeIndexes> using opcua::TypeIndexList< typeIndexes >::TypeIndexes = std::integer_sequence<TypeIndex, typeIndexes...>
Definition at line 23 of file TypeConverter.h.
Member Function Documentation
size()
template<TypeIndex... typeIndexes> static constexpr size_t opcua::TypeIndexList< typeIndexes >::size () inline static constexpr
Definition at line 25 of file TypeConverter.h.
Referenced by opcua::detail::guessDataType().
contains() [1/2]
template<TypeIndex... typeIndexes> static constexpr bool opcua::TypeIndexList< typeIndexes >::contains (TypeIndex typeIndex) inline static constexpr
Definition at line 29 of file TypeConverter.h.
Referenced by opcua::TypeIndexList< typeIndexes >::contains().
contains() [2/2]
template<TypeIndex... typeIndexes> static constexpr bool opcua::TypeIndexList< typeIndexes >::contains (Type type) inline static constexpr
Definition at line 33 of file TypeConverter.h.
toArray()
template<TypeIndex... typeIndexes> static constexpr auto opcua::TypeIndexList< typeIndexes >::toArray () inline static constexpr
Definition at line 37 of file TypeConverter.h.
Referenced by opcua::detail::TypeConverterNative< T, typeIndexes >::fromNative(), opcua::detail::guessDataType(), and opcua::detail::isValidTypeCombination().