open62541++: opcua::TypeConverter< std::chrono::time_point< Clock, Duration > > Struct Template Reference
opcua::TypeConverter< std::chrono::time_point< Clock, Duration > > Struct Template Reference
#include <TypeConverter.h>
Public Types
using ValueType = std::chrono::time_point< Clock, Duration >
using NativeType = UA_DateTime
using ValidTypes = TypeIndexList< UA_TYPES_DATETIME >
Static Public Member Functions
static void fromNative (const NativeType &src, ValueType &dst)
static void toNative (const ValueType &src, NativeType &dst)
Detailed Description
template<typename Clock, typename Duration>
struct opcua::TypeConverter< std::chrono::time_point< Clock, Duration > >
Definition at line 396 of file TypeConverter.h.
Member Typedef Documentation
NativeType
template<typename Clock , typename Duration > using opcua::TypeConverter< std::chrono::time_point< Clock, Duration > >::NativeType = UA_DateTime
Definition at line 398 of file TypeConverter.h.
ValidTypes
template<typename Clock , typename Duration > using opcua::TypeConverter< std::chrono::time_point< Clock, Duration > >::ValidTypes = TypeIndexList<UA_TYPES_DATETIME>
Definition at line 399 of file TypeConverter.h.
ValueType
template<typename Clock , typename Duration > using opcua::TypeConverter< std::chrono::time_point< Clock, Duration > >::ValueType = std::chrono::time_point<Clock, Duration>
Definition at line 397 of file TypeConverter.h.
Member Function Documentation
fromNative()
template<typename Clock , typename Duration > static void opcua::TypeConverter< std::chrono::time_point< Clock, Duration > >::fromNative (const NativeType & src, ValueType & dst) inline static
Definition at line 401 of file TypeConverter.h.
References opcua::Duration, and opcua::DateTime::toTimePoint().
toNative()
template<typename Clock , typename Duration > static void opcua::TypeConverter< std::chrono::time_point< Clock, Duration > >::toNative (const ValueType & src, NativeType & dst) inline static
Definition at line 405 of file TypeConverter.h.
References opcua::DateTime::fromTimePoint(), and opcua::DateTime::get().