open62541pp: opcua::services::detail::AsyncServiceAdapter< Response > Struct Template Reference
opcua::services::detail::AsyncServiceAdapter< Response > Struct Template Reference
#include <client_service.hpp>
Detailed Description
template<typename Response>
struct opcua::services::detail::AsyncServiceAdapter< Response >
Adapter to initiate open62541 async client operations with completion tokens.
Definition at line 22 of file client_service.hpp.
Classes
struct CallbackAndContext
Public Types
using ExceptionCatcher = opcua::detail::ExceptionCatcher
Static Public Member Functions
template<typename CompletionHandler >
static auto createCallbackAndContext (ExceptionCatcher &exceptionCatcher, CompletionHandler &&handler)
template<typename Initiation , typename CompletionToken >
static auto initiate (Client &client, Initiation &&initiation, CompletionToken &&token)
Member Typedef Documentation
ExceptionCatcher
template<typename Response > using opcua::services::detail::AsyncServiceAdapter< Response >::ExceptionCatcher = opcua::detail::ExceptionCatcher
Definition at line 23 of file client_service.hpp.
Member Function Documentation
createCallbackAndContext()
template<typename Response > template<typename CompletionHandler > static auto opcua::services::detail::AsyncServiceAdapter< Response >::createCallbackAndContext (ExceptionCatcher & exceptionCatcher, CompletionHandler && handler) inline static
Definition at line 32 of file client_service.hpp.
initiate()
template<typename Response > template<typename Initiation , typename CompletionToken > static auto opcua::services::detail::AsyncServiceAdapter< Response >::initiate (Client & client, Initiation && initiation, CompletionToken && token) inline static
Initiate open62541 async client operation with user-defined completion token.
Parameters
client Instance of type Client
initiation Callable to initiate the async operation. Following signature is expected: void(UA_ClientAsyncServiceCallback callback, void* userdata)
token Completion token
Definition at line 71 of file client_service.hpp.
Referenced by opcua::services::createMonitoredItemsDataChangeAsync(), opcua::services::createMonitoredItemsEventAsync(), opcua::services::createSubscriptionAsync(), opcua::services::deleteMonitoredItemsAsync(), and opcua::services::modifyMonitoredItemsAsync().