open62541++: opcua::TypeList< T > Struct Template Reference
opcua::TypeList< T > Struct Template Reference
#include <TypeConverter.h>
Public Types
using Types = std::integer_sequence< Type, T... >
Static Public Member Functions
static constexpr size_t size ()
static constexpr bool contains (Type type)
static constexpr auto toArray ()
Detailed Description
template<Type... T>
struct opcua::TypeList< T >
Definition at line 20 of file TypeConverter.h.
Member Typedef Documentation
Types
template<Type... T> using opcua::TypeList< T >::Types = std::integer_sequence<Type, T...>
Definition at line 21 of file TypeConverter.h.
Member Function Documentation
contains()
template<Type... T> static constexpr bool opcua::TypeList< T >::contains (Type type) inline static constexpr
Definition at line 27 of file TypeConverter.h.
Referenced by opcua::detail::isValidTypeCombination().
size()
template<Type... T> static constexpr size_t opcua::TypeList< T >::size () inline static constexpr
Definition at line 23 of file TypeConverter.h.
toArray()
template<Type... T> static constexpr auto opcua::TypeList< T >::toArray () inline static constexpr
Definition at line 31 of file TypeConverter.h.
Referenced by opcua::detail::TypeConverterNative< UA_String, Type::String, Type::ByteString, Type::XmlElement >::fromNative(), and opcua::detail::guessType().