open62541pp: opcua::services::detail::CallbackAdapter Struct Reference
opcua::services::detail::CallbackAdapter Struct Reference
#include <callbackadapter.hpp>
Detailed Description
Helper class to map open62541 / C-style callbacks to std::function objects.
The the concrete adapter should:
store the std::function objects
implement static methods of the native open62541 callbacks
pass the pointer to itself as the callback context
Definition at line 16 of file callbackadapter.hpp.
Public Member Functions
template<typename F , typename... Args>
void invoke (F &&callback, Args &&... args) const noexcept
Public Attributes
opcua::detail::ExceptionCatcher * catcher = nullptr
Member Function Documentation
invoke()
template<typename F , typename... Args> void opcua::services::detail::CallbackAdapter::invoke (F && callback, Args &&... args) const inline noexcept
Definition at line 21 of file callbackadapter.hpp.
Referenced by opcua::services::detail::MonitoredItemContext::dataChangeCallbackNativeClient(), opcua::services::detail::MonitoredItemContext::dataChangeCallbackNativeServer(), opcua::services::detail::MonitoredItemContext::deleteCallbackNative(), opcua::services::detail::SubscriptionContext::deleteCallbackNative(), opcua::services::detail::MonitoredItemContext::eventCallbackNative(), and opcua::services::detail::SubscriptionContext::statusChangeCallbackNative().
Member Data Documentation
catcher
opcua::detail::ExceptionCatcher* opcua::services::detail::CallbackAdapter::catcher = nullptr
Definition at line 18 of file callbackadapter.hpp.
Referenced by invoke().