open62541++: opcua::TypeConverter< T, Enable > Struct Template Reference
opcua::TypeConverter< T, Enable > Struct Template Reference
#include <TypeConverter.h>
Public Types
using ValueType = T
using NativeType = std::nullptr_t
using ValidTypes = TypeIndexList<>
Static Public Member Functions
static void fromNative (const NativeType &src, ValueType &dst)
static void toNative (const ValueType &src, NativeType &dst)
Detailed Description
template<typename T, typename Enable = void>
struct opcua::TypeConverter< T, Enable >
Type conversion from and to native UA_* types.
Template specializations can be added for conversions of arbitrary types.
Definition at line 47 of file TypeConverter.h.
Member Typedef Documentation
ValueType
template<typename T , typename Enable = void> using opcua::TypeConverter< T, Enable >::ValueType = T
Examples
typeconversion.cpp.
Definition at line 50 of file TypeConverter.h.
NativeType
template<typename T , typename Enable = void> using opcua::TypeConverter< T, Enable >::NativeType = std::nullptr_t
Examples
typeconversion.cpp.
Definition at line 51 of file TypeConverter.h.
ValidTypes
template<typename T , typename Enable = void> using opcua::TypeConverter< T, Enable >::ValidTypes = TypeIndexList<>
Examples
typeconversion.cpp.
Definition at line 52 of file TypeConverter.h.
Member Function Documentation
fromNative()
template<typename T , typename Enable = void> static void opcua::TypeConverter< T, Enable >::fromNative (const NativeType & src, ValueType & dst) static
Examples
typeconversion.cpp.
Referenced by opcua::detail::fromNative(), and opcua::detail::fromNativeArray().
toNative()
template<typename T , typename Enable = void> static void opcua::TypeConverter< T, Enable >::toNative (const ValueType & src, NativeType & dst) static
Examples
typeconversion.cpp.
Referenced by opcua::TypeConverter< const char * >::toNative(), opcua::TypeConverter< std::string >::toNative(), opcua::TypeConverter< char[N]>::toNative(), opcua::detail::toNativeAlloc(), and opcua::detail::toNativeArrayAlloc().