open62541++: opcua::TypeConverter< std::string > Struct Reference
opcua::TypeConverter< std::string > Struct Reference
#include <TypeConverter.h>
Public Types
using ValueType = std::string
using NativeType = UA_String
using ValidTypes = TypeList< Type::String, Type::ByteString, Type::XmlElement >
Static Public Member Functions
static void fromNative (const NativeType &src, ValueType &dst)
static void toNative (const ValueType &src, NativeType &dst)
Detailed Description
Definition at line 293 of file TypeConverter.h.
Member Typedef Documentation
NativeType
using opcua::TypeConverter< std::string >::NativeType = UA_String
Definition at line 295 of file TypeConverter.h.
ValidTypes
using opcua::TypeConverter< std::string >::ValidTypes = TypeList<Type::String, Type::ByteString, Type::XmlElement>
Definition at line 296 of file TypeConverter.h.
ValueType
using opcua::TypeConverter< std::string >::ValueType = std::string
Definition at line 294 of file TypeConverter.h.
Member Function Documentation
fromNative()
static void opcua::TypeConverter< std::string >::fromNative (const NativeType & src, ValueType & dst) inline static
Definition at line 298 of file TypeConverter.h.
References opcua::detail::toString().
toNative()
static void opcua::TypeConverter< std::string >::toNative (const ValueType & src, NativeType & dst) inline static
Definition at line 302 of file TypeConverter.h.
References opcua::detail::allocUaString(), and UA_clear().