open62541: /home/runner/work/open62541pp/open62541pp/build/doc/open62541/deps/mqtt-c/examples/templates/mbedtls_sockets.h File Reference
mbedtls_sockets.h File Reference
#include <inttypes.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <mbedtls/error.h>
#include <mbedtls/entropy.h>
#include <mbedtls/ctr_drbg.h>
#include <mbedtls/net_sockets.h>
#include <mbedtls/ssl.h>
Data Structures
struct mbedtls_context
Macros
#define MBEDTLS_NET_POLL_READ 1
compat for older mbedtls
#define MBEDTLS_NET_POLL_WRITE 1
Functions
int mbedtls_net_poll (mbedtls_net_context *ctx, uint32_t rw, uint32_t timeout)
void failed (const char *fn, int rv)
void cert_verify_failed (uint32_t rv)
void open_nb_socket (struct mbedtls_context *ctx, const char *hostname, const char *port, const char *ca_file)
Macro Definition Documentation
MBEDTLS_NET_POLL_READ
#define MBEDTLS_NET_POLL_READ 1
compat for older mbedtls
Definition at line 17 of file mbedtls_sockets.h.
MBEDTLS_NET_POLL_WRITE
#define MBEDTLS_NET_POLL_WRITE 1
Definition at line 18 of file mbedtls_sockets.h.
Function Documentation
cert_verify_failed()
void cert_verify_failed (uint32_t rv)
Definition at line 53 of file mbedtls_sockets.h.
Referenced by open_nb_socket().
failed()
void failed (const char * fn, int rv)
Definition at line 46 of file mbedtls_sockets.h.
Referenced by open_nb_socket().
mbedtls_net_poll()
int mbedtls_net_poll (mbedtls_net_context * ctx, uint32_t rw, uint32_t timeout)
Definition at line 21 of file mbedtls_sockets.h.
Referenced by open_nb_socket().
open_nb_socket()
void open_nb_socket (struct mbedtls_context * ctx, const char * hostname, const char * port, const char * ca_file)
Definition at line 63 of file mbedtls_sockets.h.
References mbedtls_context::ca_crt, cert_verify_failed(), mbedtls_context::ctr_drbg, mbedtls_context::entropy, failed(), mbedtls_net_poll(), MBEDTLS_NET_POLL_READ, MBEDTLS_NET_POLL_WRITE, mbedtls_context::net_ctx, mbedtls_context::ssl_conf, and mbedtls_context::ssl_ctx.