name: Codegen

on:
  push:
    branches: [master]
  pull_request:

jobs:
  codegen:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        script:
          - tools/gen_attribute_highlevel.py
          - tools/gen_nodeids.py
          - tools/gen_typeregistry_native.py
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Run codegen script
        run: python ${{ matrix.script }}
      - name: Check diff
        run: git diff --exit-code
